### ISSUE TITLE
Add Walnut Creek, CA

### ISSUE THREAD

**Issue by vsachtjen** [defund12/defund12.org#1002]
To: justin@justinwedel.com, kwilk@walnut-creek.org, cindy@cindysilva.org, francois@walnut-creek.org, mayor@walnut-creek.org

Subject: [Unique Subject Line!]

Dear Mayor Haskew and City Council Members,

My name is [YOUR NAME] and I am a Walnut Creek resident writing to urge you to defund the Walnut Creek Police Department.

WCPD takes up 30% ($52.1M) of the city’s general fund, and that percentage has risen for the last two decades, taking away desperately needed resources from essential city programs and services. The entire budget for Community & Economic Development only accounts for 8% ($14.9M) of the city's budget. The investment in policing has not made us safer – WCPD remains an embarrassment to the city and a lethal threat to Walnut Creek's Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With Walnut Creek's current finances in dire jeopardy, it is clear that we must defund the police.

As Walnut Creek residents, we therefore demand that you take immediate action to ensure the following:
Reduce WCPD’s allocation from the General Fund by 50% (roughly $26M)
Disallow unauthorised overtime by WCPD
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Walnut Creek can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund and Abolish WCPD.

Thank you,

[YOUR NAME]

**Comment by swallan** [comment]
Hi @vsachtjen ! Thanks for your interest in adding Walnut Creek to the site. Can you provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by tapp14** [comment]
I have pulled out some key pages from the Walnut Creek city budget, PDF attached... a whopping 30% is spent on police! This is shocking because it seems like a tame crime-less suburb. https://www.dropbox.com/s/8y8zkc38lw35v9q/Screenshot%202020-06-09%2013.42.04.png?dl=0

Thanks! 
[WC_budget.pdf](https://github.com/defund12/defund12.org/files/4754880/WC_budget.pdf)
![Screenshot 2020-06-09 14 12 47](https://user-images.githubusercontent.com/66699804/84200396-91052200-aa5b-11ea-803d-4b2b533e2052.png)

**Comment by vsachtjen** [comment]
> Hi @vsachtjen ! Thanks for your interest in adding Walnut Creek to the site. Can you provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?
> 
> Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.
> 
> Thank you!

Hi, I have added additional information from the city's budget!

**Comment by serifluous** [comment]
**Suggested edits in bold** (reword "crime" phrasing)

To: justin@justinwedel.com, kwilk@walnut-creek.org, cindy@cindysilva.org, francois@walnut-creek.org, mayor@walnut-creek.org

Subject: [Unique Subject Line!]

Dear Mayor Haskew and City Council Members,

My name is [YOUR NAME] and I am a Walnut Creek resident writing to urge you to defund the Walnut Creek Police Department.

WCPD takes up 30% ($52.1M) of the city’s general fund, and that percentage has risen for the last two decades, taking away desperately needed resources from essential city programs and services. The entire budget for Community & Economic Development only accounts for 8% ($14.9M) of the city's budget. The investment in policing has not made us safer – WCPD remains an embarrassment to the city and a lethal threat to Walnut Creek's Black and Brown communities, while increased police spending shows no correlation to **increasing public safety** over the past 20 years. With Walnut Creek's current finances in dire jeopardy, it is clear that we must defund the police.

As Walnut Creek residents, we therefore demand that you take immediate action to ensure the following:
- Reduce WCPD’s allocation from the General Fund by 50% (roughly $26M)
- Disallow unauthorised overtime by WCPD
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
- Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Walnut Creek can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund and Abolish WCPD.

Thank you,

[YOUR NAME]

**Comment by rpalakkal** [comment]
adding this one!
