### ISSUE TITLE
Defund the Poughkeepsie Police Department (Add Poughkeepsie, New York / Dutchess County, New York)

### ISSUE THREAD

**Issue by DerilusP1** [defund12/defund12.org#1003]
**To:** CountyExec@DutchessNY.gov
CountyLegislature@DutchessNY.gov
BKendall@DutchessNY.gov
Comptroller@DutchessNY.gov
DistrictAttorney@dutchessny.gov
jbaisley@townofpoughkeepsie-ny.gov
jrenihan@townofpoughkeepsie-ny.gov
bill.carlos@aol.com
jlopez@townofpoughkeepsie-ny.gov
Michaelcifone@aol.com
mwoolever@townofpoughkeepsie-ny.gov
ashershin@yahoo.com
fsalvatore@townofpoughkeepsie-ny.gov
____________________________________________

**Subject: Defunding of the PK Police Department**

**Message**

To Poughkeepsie Town Officials:

My name is [Insert Name] and I am a resident of [Neighborhood/City]. 

Given the historic, social, and political origins of [police and policing](https://gen.medium.com/slavery-and-the-origins-of-the-american-police-state-ec318f5ff05b), in conjunction with the recent nationwide protests reflecting the antiBlack deaths of [George Floyd](https://www.refinery29.com/en-us/2020/05/9838535/george-floyd-killed-by-minneapolis-police-knee-video), [Breonna Taylor](https://zora.medium.com/where-is-the-outrage-for-breonna-taylor-f2f7ed762e79), and [Tony McDade](https://www.refinery29.com/en-us/2020/05/9844546/tony-mcdade-police-killed-tallahassee-black-transgender-man) I am contacting you because I am demanding you to redirect money away from the Poughkeepsie Police Department and prioritize collective services that will help improve the socio-economic conditions of Poughkeepsie's **_predominately Black_** communities. I yearn to know what you will do to protect Black lives and prevent further instances of police-state-sanctioned violence. I am calling to urge you to condemn police brutality, racial profiling, and the use of excessive force by police on oppressed communities. 

Sincerely,
[Insert Name]

**Comment by sarainoa** [comment]
Dear Poughkeepsie town officials,

My name is Sara Inoa. I am a person of color and have lived in Poughkeepsie for fourteen years. I am a recent graduate of Vassar college (sociology and  English), an artist, and the mother of a beautiful four year old child that I want to bring up in a world that has chosen to learn how to care for and love one another. The way we currently exist while complex and at times joyful has never seized disregarding, exploiting, disenfranchising, and enslaving (imprisoning) black people and it is time reckon with our past and learn what a world that acknowledges the humanness of all who live on it looks like.

Given the historic, social, and political origins of police and policing, in conjunction with the recent nationwide protests reflecting the antiBlack deaths of George Floyd, Breonna Taylor, and Tony McDade I am contacting you because I am asking you to redirect money away from the Poughkeepsie Police Department and prioritize collective services that will help improve the socio-economic conditions of our predominately Black communities. We want to know what you will do to protect Black lives and prevent further instances of police-state-sanctioned violence. I am calling to urge you to condemn police brutality, racial profiling, and the use of excessive force by police on marginalized communities.

Yours,

Sara Inoa

**Comment by skullface** [comment]
Hi @DerilusP1 and @sarainoa! These are beautiful messages and I’d love for your elected officials to receive them. The purpose of this open request is to create a template for other folks to use at defund12.org/poughkeepsie-ny. Once you have written the template, our content team will review it and our developers will add it to the site.

**_Please rewrite this message so anyone can insert their name and contact info and send it._** Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). 

(I hope you email what you’ve written directly to your town officials as well!)

Thank you for your participation~

**Comment by sarainoa** [comment]
Oh this makes sense !! Thanks for letting me know !

**Comment by DerilusP1** [comment]
> Hi @DerilusP1 and @sarainoa! These are beautiful messages and I’d love for your elected officials to receive them. The purpose of this open request is to create a template for other folks to use at defund12.org/poughkeepsie-ny. Once you have written the template, our content team will review it and our developers will add it to the site.
> 
> **_Please rewrite this message so anyone can insert their name and contact info and send it._** Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md).
> 
> (I hope you email what you’ve written directly to your town officials as well!)
> 
> Thank you for your participation~

Ok, thank you!
