### ISSUE TITLE
Miami-Dade County

### ISSUE THREAD

**Issue by d4nc3r5ky** [defund12/defund12.org#1036]
Below are the addresses of the County Commissioners and the Mayor. I believe they are all the relevant officials to contact regarding the budget, but if anyone thinks others should be added, go ahead! 

Sources: https://www.miamidade.gov/commission/ & https://www.miamidade.gov/global/government/mayor/home.page

**Email Addresses**
District 1 Commissioner Barbara J. Jordan: bjordan@miamidade.gov
District 2 Commissioner Jean Monestime: district2@miamidade.gov
District 3 Chairwoman Audrey M. Edmonson: district3@miamidade.gov
District 4 Commissioner Sally A. Heyman: district4@miamidade.gov
District 5 Commissioner Eileen Higgins: district5@miamidade.gov
District 6 Vice Chairwoman Rebeca Sosa: district6@miamidade.gov
District 7 Commissioner Xavier L. Suarez: District7@miamidade.gov
District 8 Commissioner Daniella Levine Cava: District8@miamidade.gov
District 9 Commissioner Dennis C. Moss: DennisMoss@miamidade.gov
District 10 Commissioner Javier D. Souto: district10@miamidade.gov
District 11 Commissioner Joe A. Martinez: district11@miamidade.gov
District 12 Commissioner Jose "Pepe" Diaz: district12@miamidade.gov
District 13 Commissioner Esteban L. Bovo, Jr.: district13@miamidade.gov
Miami-Dade County Mayor: mayor@miamidade.gov

Will be back to work on the draft; just wanted to get the ball rolling!

**Comment by skullface** [comment]
Thanks @d4nc3r5ky! Closing this issue until you reply with the email message content, then we’ll re-open it for review!

**Comment by d4nc3r5ky** [comment]
I'm collecting data specific for Miami-Dade County in [this google doc](https://docs.google.com/document/d/1lrP7W_KEhRVBFregQ-un3qgUgWTefH4MO24pmC5ThaI/edit?usp=sharing) in case anyone wants to hop on and collaborate.

**Comment by d4nc3r5ky** [comment]
I would really love for someone else to take a look at this and give their input before it is put up. Is it too bold in parts? Should it be condensed, more specific in places? etc.

**Message**

My name is [NAME], I am a resident of Miami-Dade County. I am writing to demand that the Mayor and Board of County Commissioners adopt a county budget that prioritizes community well-being, and redirects funding away from the police. I will not be content with “reform;” I am demanding that real change be made to the way this city allocates its resources.

For the current fiscal year, Miami-Dade County allocated $759,072,000 for police, including a $68,404,000 increase (9.9%) on the previous year. I demand that the 2020-2021 fiscal year be truly a new year, in which the elected officials of Miami-Dade County meaningfully defund the Miami-Dade Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. 

Let us be clear: we do not demand “better police”—history has shown that police “reform” is not enough. It is wrong to understand the police as a broken institution in need of fixing; it is a bad institution that works, not for but against those with whom it most comes in contact. History affords us examples of similar racist systems; we do not look back on Jim Crow and slavery as flawed but as unjust, intolerably immoral—not needing to be modified but rather abolished so as to make way for better, more just systems.

We must imagine how the needs of the community that the police purport to meet can be better met through a framework of care rather than a racialized framework of criminalization and punishment. For that reason we demand that the County begin on a path to invest in the nonviolent institutions, services, spaces, and functions of community that are better equipped to promote the safety and wellbeing of its residents. This will mean strengthening and expanding existing programs and departments, as well as working with the community to break new ground.

What we need are more social services, more jobs, more educational opportunities, more affordable housing, more arts programs, more community centers, more substance abuse treatment services, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

It is your duty to represent your constituents. I urge you to revise the budget for the 2020-2021 fiscal year, and to fund care, not cops. Can I count on you to pass a budget that puts a focus on social service programs and the wellbeing of the community? Public opinion is with me.

Thank you, 
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Reviewing now!

**Comment by mahrer** [comment]
This looks great. Minor edits below:

---

Email Addresses
District 1 Commissioner Barbara J. Jordan: bjordan@miamidade.gov
District 2 Commissioner Jean Monestime: district2@miamidade.gov
District 3 Chairwoman Audrey M. Edmonson: district3@miamidade.gov
District 4 Commissioner Sally A. Heyman: district4@miamidade.gov
District 5 Commissioner Eileen Higgins: district5@miamidade.gov
District 6 Vice Chairwoman Rebeca Sosa: district6@miamidade.gov
District 7 Commissioner Xavier L. Suarez: District7@miamidade.gov
District 8 Commissioner Daniella Levine Cava: District8@miamidade.gov
District 9 Commissioner Dennis C. Moss: DennisMoss@miamidade.gov
District 10 Commissioner Javier D. Souto: district10@miamidade.gov
District 11 Commissioner Joe A. Martinez: district11@miamidade.gov
District 12 Commissioner Jose "Pepe" Diaz: district12@miamidade.gov
District 13 Commissioner Esteban L. Bovo, Jr.: district13@miamidade.gov
Miami-Dade County Mayor: mayor@miamidade.gov

Message:

Dear Mayor and Commissioners of Miami-Dade County,

My name is [NAME], I am a resident of Miami-Dade County. I am writing to demand that the Mayor and Board of County Commissioners adopt a budget that prioritizes community well-being, and redirects funding away from the police. I will not be content with “reform.” I am demanding that real change be made to the way this city allocates its resources. In recent weeks, your constituents have taken to the streets to join a national, and now global, outcry against systemic racism. A systemic problem requires systemic solutions.

For the current fiscal year, Miami-Dade County allocated $759,072,000 for police, including a $68,404,000 increase (9.9%) on the previous year's police operating budget and a staggering 35% of the General Fund. I demand that this be the year when the elected officials of Miami-Dade County begin to meaningfully defund the Miami-Dade Police Department and reallocate those funds to areas proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, educational opportunities, arts programs, resilience and sustainability measures, and more. I demand a budget that reflects the actual needs of Miami-Dade County residents.

It is time we imagine how the needs of the community that the police purport to meet can be better met through a framework of care rather than a racialized framework of criminalization and punishment. For that reason we demand that the County begin on a path to invest in the nonviolent institutions, services, spaces, and functions of community that are better equipped to promote the safety and wellbeing of its residents. This will mean strengthening and expanding existing programs and departments, as well as working with, listening to, and learning from the community to break new ground. This is a long transition process but change starts with reallocating this funding!

It is your duty to represent your constituents. I urge you to revise the budget for the 2020-2021 fiscal year, and to fund care, not cops. Can I count on you to pass a budget that puts a focus on social service programs and the wellbeing of the community? Public opinion is with me.

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
