### ISSUE TITLE
Defund Detroit Police Department 

### ISSUE THREAD

**Issue by emgarava** [defund12/defund12.org#1037]
email addresses: 
emailmayorduggan@detroitmi.gov, naglickj@detroitmi.gov, Bjones_mb@detroitmi.gov, councilmembersheffield@detroitmi.gov, councilmemberayers@detroitmi.gov, councilmembertate@detroitmi.gov, councilmemberMcCalister@detroitmi.gov, BensonS@detroitmi.gov, councilmanSpivey@detroitmi.gov, councilmemberraquel@detroitmi.gov, LelandG@detroitmi.gov 
--
Subject: ACTION REQUIRED | FY2021 Budget
Email: 
Hi Mayor Duggan, CFO, and City Council, 

My name is [NAME] and I live in [NEIGHBORHOOD]. I am sending this message as my formal request to reallocate some of the roughly $330 million DPD budget to alternate public programs and resources.

As you know, the Detroit Police have been murdered a number of black people — Aiyana Jones, Malice Green, Carl Cooper, Aubrey Pollard and Fred Temple...the list goes on. As you know, the police exist in the union states because they were used as a violent force to suppress poor Americans and maintain the power of what we now call the one percent. As you know, this is a department fresh off the heels of a massive recovery, both from their all-time low headcount in 2015 and the COVID19 pandemic. The DPD is due for restructuring. 

I cannot grapple with the fact that the DPD has tanks and riot gear at the ready while Detroit Public School students attend class in dilapidated buildings with books older than them and teachers scraping their wallets for classroom supplies. 

I can't condone $330 million budgeted in FY2020 while 300,000 Detroiters are without water and the department that has the power to turn it back on is funded with only $70k. 

I am not asking that you take police off of the streets. I ask that you relive young black boys and girls of the trauma of watching a man get murdered by an officer on Instagram over, and over, and over, and over, and over again, and seeing an armed officer at their school the next day. 

Detroit needs you to trim the fat on the DPD. Demilitarize the force, require that if you're an officer your zip code is a part of the city, require that police intervene when they witness police on civilian violence, end their union funding, ban shooting at moving vehicles, and require comprehensive reporting. 

We the people will not stop demonstrating until our demands are met. We're out here to see how much of that $330 million we can spend. 

Best, 

[NAME]

**Comment by emgarava** [comment]
REVISION: 4th paragraph, "only $70k" should be "less than half that amount"

**Comment by serifluous** [comment]
Hi @emgarava ! Thanks for the submission.

A few suggested edits in bold below:
- Based on our [style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md), our core message is defunding the police and not reforming the police. I've removed the reform demands in the 2nd, 5th, and 6th paragraphs. If this is ok @emgarava , let me know, and I'll approve the email template.
- Update to 4th paragraph made based on comment above
- Budget number and year updated based on adopted FY2021 budget here, pA44: https://detroitmi.gov/sites/detroitmi.localhost/files/2020-06/1%20-%20FY%202021-24%20Four-Year%20Financial%20Plan%20-%20Section%20A%20Overview%20-%20Adopted_1.pdf

Email
--

email addresses:
emailmayorduggan@detroitmi.gov, naglickj@detroitmi.gov, Bjones_mb@detroitmi.gov, councilmembersheffield@detroitmi.gov, councilmemberayers@detroitmi.gov, councilmembertate@detroitmi.gov, councilmemberMcCalister@detroitmi.gov, BensonS@detroitmi.gov, councilmanSpivey@detroitmi.gov, councilmemberraquel@detroitmi.gov, LelandG@detroitmi.gov

Email:
Hi Mayor Duggan, CFO, and City Council,

My name is [NAME] and I live in [NEIGHBORHOOD]. I am sending this message as my formal request to reallocate some of the roughly $330 million DPD budget to alternate public programs and resources.

As you know, the Detroit Police have been murdered a number of black people — Aiyana Jones, Malice Green, Carl Cooper, Aubrey Pollard and Fred Temple...the list goes on. As you know, the police exist in the union states because they were used as a violent force to suppress poor Americans and maintain the power of what we now call the one percent. As you know, this is a department fresh off the heels of a massive recovery, both from their all-time low headcount in 2015 and the COVID19 pandemic. The DPD is due for **defunding**.

I cannot grapple with the fact that the DPD has tanks and riot gear at the ready while Detroit Public School students attend class in dilapidated buildings with books older than them and teachers scraping their wallets for classroom supplies.

I can't condone **$328.7** million budgeted in **FY2021** while 300,000 Detroiters are without water and the department that has the power to turn it back on is funded with **less than half that amount**.

**I ask that you relive young black boys and girls of the trauma of watching a man get murdered by an officer on Instagram over, and over, and over, and over, and over again, and seeing an armed officer at their school the next day. Detroit needs you to trim the fat on the DPD.**

We the people will not stop demonstrating until our demands are met. We're out here to see how much of that $330 million we can spend on **alternate public programs and resources**.

Best,
[NAME]

**Comment by mahrer** [comment]
Hi @emgarava and @serifluous, it looks like we already have a template for Detroit here:
https://defund12.org/detroit 

If you'd like to make changes to the existing template, feel free to open a new issue with the label content-change-request.
