### ISSUE TITLE
Open Letter to Mayor and Aldermen Evanston, IL

### ISSUE THREAD

**Issue by daisycha** [defund12/defund12.org#1039]
To: shagerty@cityofevanston.org , jfiske@cityofevanston.org , pbraithwaite@cityofevanston.org , mwynne@cityofevanston.org , dwilson@cityofevanston.org , tsuffredin@cityofevanston.org , rsimmons@cityofevanston.org , erevelle@cityofevanston.org , arainey@cityofevanston.org , cfleming@cityofevanston.org ,  estorlie@cityofevanston.org 

Hello,

My name is [INSERT NAME] and I am a resident of Evanston's [INSERT WARD NUMBER] ward. I am extremely concerned with our City's budget for the Evanston Police Department (EPD) at the expense of critical youth, education, and health services. This fiscal year's budget of $56,000,000 for the police is alarming especially when the EPD has brutalized Evanston’s Black and Brown communities at the expense of funding educational, financial, environmental, and health-based initiatives to fix our city’s apparent and gaping racial disparities across the board. 

I am therefore writing to demand that the City Council vote to reapportion funds allocated to the EPD to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is morally reprehensible to dedicate 34% of the City’s general fund towards policing while hundreds of citizens are homeless and many more lack access to essential services, including food, housing, and necessary mental health resources. Moreover, the 5th ward hasn't had a public K-12 school since desegregation which could be a great starting point for a place to reallocate funds. 

I also urge the City Council to enact legislation that holds police accountable and overturn policies that allow police to engage in unlawful behavior with impunity. The newly established Citizen Police Review Commission isn't enough. The police were created to control Black/Brown bodies; it's impossible to reform an inherently racist system. Read the "8 To Abolition," campaign and see how other cities are already defunding their police forces in support of funding community safety, health, and other needs.

Reform is impossible, and we demand you reckon with the EPD's force by firing officers who have traumatized thousands of members of our community. Hold the officers accountable who were involved in the racist and unjust arrests of Iain Bady, Trent Hunt, and Lawrence Crosby to name a few. Black Lives can't matter until we defund the police. 

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents, especially Black ones, and take immediate action to address their concerns. 

Thank you, 
[NAME]
[ADDRESS]
[EMAIL]
[PHONE NUMBER] 

https://www.8toabolition.com/

**Comment by swallan** [comment]
shagerty@cityofevanston.org , jfiske@cityofevanston.org , pbraithwaite@cityofevanston.org , mwynne@cityofevanston.org , dwilson@cityofevanston.org , tsuffredin@cityofevanston.org , rsimmons@cityofevanston.org , erevelle@cityofevanston.org , arainey@cityofevanston.org , cfleming@cityofevanston.org

Hello,
My name is [INSERT NAME] and I am a resident of Evanston's [INSERT WARD NUMBER] ward. I am extremely concerned with our City's budget for the Evanston Police Department (EPD) at the expense of critical youth, education, and health services. This fiscal year's budget of $56,000,000 for the police is alarming especially when the EPD has continually brutalized the Black and Brown communities at the expense of funding educational, financial, environmental, and health-based initiatives to fix our cities apparent and gaping racial disparities across the board.

I am therefore writing to demand that the City Council vote to reapportion funds allocated to the EPD to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is morally reprehensible to dedicate 34% of the City’s general fund towards policing while hundreds of citizens are homeless and many more lack access to essential services, including food, housing, and necessary mental health resources. Moreover, the 5th ward hasn't had a public K-12 school since desegregation which could be a great starting point for a place to reallocate funds.

I also urge the City Council to enact legislation that holds police accountable and overturn policies that allow police to engage in unlawful behavior with impunity. The newly established Citizen Police Review Commission isn't enough. The police were created to control Black/Brown bodies; it's impossible to reform an inherently racist system. Read the "8 To Abolition," campaign and see how other cities are already defunding their police forces in support of funding community safety, health, and other needs.

Reform is impossible, and we demand you reckon with the EPD's force by firing officers who have traumatized thousands of members of our community. Hold the officers who were involved in the racist and unjust arrests of Iain Bady, Trent Hunt, and Lawrence Crosby to name a few. Black Lives can't matter until we defund the police.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents, especially Black ones, and take immediate action to address their concerns.

Thank you,
[NAME]
[ADDRESS]
[EMAIL]
[PHONE NUMBER]

**Comment by mahrer** [comment]
@swallan I assume you were finished editing this?

**Comment by swallan** [comment]
@mahrer I believe I made some edits, though it was long enough ago that I do not remember.. I think it is probably good enough.

**Comment by ctneal91** [comment]
on it now

**Comment by daisycha** [comment]
Hey all, I just added a new email to the original request I posted and was wondering if you could add it to the one you publish as well. Love the work you're doing, thanks.
