### ISSUE TITLE
new city--Monterey, CA

### ISSUE THREAD

**Issue by donkadoodle** [defund12/defund12.org#1040]
roberson@monterey.org, albert@monterey.org, haffa@monterey.org, smith@monterey.org, twilliamson@monterey.org

To Mayor Roberson and Monterey City Council Members,

My name is [YOUR NAME], and I am a Monterey community member. Since the violent murder of George Floyd, our nation has been forced to take an honest look at how Black and Brown people are treated in America. As a result we have seen protests in all 50 states calling for rapid and meaningful change, especially regarding racist institutions like policing. Simultaneously, cities across the country are facing budget deficits due to Covid-19 and Monterey is no exception. 

As protests continued, Monterey released a budget proposal asking its tax-payers to accept a 60% reduction in recreation, library and museum spending as well as over 40 layoffs, but proposed only an 8% reduction of the police department. In the name of real public safety, I cannot accept this! On June 7, 2020 the Minneapolis City Council voted to defund and dismantle their city's police and pledged to invest in new models of public safety and I ask that Monterey City Council adopt this agenda as well.

Last year, expenditures for MPD totaled over $17million, more than the expenditures for community services such as museums, parks and libraries combined. Though our city continues to spend extraordinary amounts on policing, residents still struggle with issues of public safety, houselessness, accessibility to mental health services, food equity and accessibility as well as general affordability in Monterey. By defunding police and reallocating those dollars to community services, you can make incredible systemic change to enrich the lives of all your constituents and uplift our most vulnerable populations. Real public safety addresses root causes, not just the symptoms; eliminating the desperation that places individuals in a position to commit criminalized acts in the first place. Additionally, many major events along our beautiful peninsula--which historically call for more police presence--have been canceled this year due to the pandemic. Though this means a decrease in city revenue through the TOT, it also means less tourism and crowds, a decrease in traffic and therefore a significantly lower demand on and for the police.

I call on you to defund the Monterey Police Department and use those extraordinary assets to offer more social services and boost the budgets for schools, recreation, libraries and the arts, which fundamentally enhance the health and wellness of all our community members. Defunding MPD will make space for new systems and more nuanced emergency-response approaches. Our citizens deserve this!

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by stephbwills** [comment]
Reviewing this one shortly.

**Comment by stephbwills** [comment]
@donkadoodle - this is great! I'm checking numbers based on [this video](https://www.youtube.com/watch?v=8OxU29D6oNQ&feature=youtu.be) and the [19-21 budget](https://monterey.org/Portals/0/Reports/Finance/Budget/BudgetBookFINALwLinks.pdf)—let me know if there is anything else I should be looking at.

One thing: 
- Where is the 17 mil toward the police coming from? I'm actually getting 18.4 (80.2*.23)

![image](https://user-images.githubusercontent.com/7321362/84426452-22999e80-abd8-11ea-8fe3-80c4c65a8175.png)

**Comment by mahrer** [comment]
@stephbwills I edited the message slightly to reflect your cited data. Did you see any other numbers that were off when you were fact checking? If not I think this one is ready for a pr.

---

roberson@monterey.org, albert@monterey.org, haffa@monterey.org, smith@monterey.org, twilliamson@monterey.org

To Mayor Roberson and Monterey City Council Members,

My name is [YOUR NAME], and I am a Monterey community member. Since the violent murder of George Floyd, our nation has been forced to take an honest look at how Black and Brown people are treated in America. As a result we have seen protests in all 50 states calling for rapid and meaningful change, especially regarding racist institutions like policing. Simultaneously, cities across the country are facing budget deficits due to Covid-19 and Monterey is no exception.

As protests continued, Monterey released a budget proposal asking its tax-payers to accept a 60% reduction in recreation, library and museum spending as well as over 40 layoffs, but proposed only an 8% reduction of the police department. In the name of real public safety, I cannot accept this! On June 7, 2020 the Minneapolis City Council voted to defund and dismantle their city's police and pledged to invest in new models of public safety and I ask that Monterey City Council adopt this agenda as well.

According to the 2019-2021 Biennium Adopted Budget, expenditures for MPD totaled over $18 million, more than the expenditures for community services such as museums, parks and libraries combined. Though our city continues to spend extraordinary amounts on policing, residents still struggle with issues of public safety, houselessness, accessibility to mental health services, food equity and accessibility as well as general affordability in Monterey. By defunding police and reallocating those dollars to community services, you can make incredible systemic change to enrich the lives of all your constituents and uplift our most vulnerable populations. Real public safety addresses root causes, not just the symptoms; eliminating the desperation that places individuals in a position to commit criminalized acts in the first place. Additionally, many major events along our beautiful peninsula--which historically call for more police presence--have been canceled this year due to the pandemic. Though this means a decrease in city revenue through the TOT, it also means less tourism and crowds, a decrease in traffic and therefore a significantly lower demand on and for the police.

I call on you to defund the Monterey Police Department and use those extraordinary assets to offer more social services and boost the budgets for schools, recreation, libraries and the arts, which fundamentally enhance the health and wellness of all our community members. Defunding MPD will make space for new systems and more nuanced emergency-response approaches. Our citizens deserve this!

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by stephbwills** [comment]
That's it @mahrer! Everything lgtm

**Comment by stephbwills** [comment]
@mahrer sorry there was one more thing, actually. I couldn't find the source for 40 layoffs in the presentation or budget but may have missed it.

**Comment by donkadoodle** [comment]
I am having trouble replying. The 40 plus layoffs come from monterey's most
recent budget cuts proposal to be voted on in the coming week.
the $17 million is what i found in expenditures for police on page 50 of
file CAFR19.pdf which i am unable to attach to this email due to size but
is available on city of monterey's financials page. i may be incorrect
about the $17 because i dont fully know how to read but that;s what it
looked like.
-donka

**Comment by donkadoodle** [comment]
correction: document where i got info is called CAFR2019.pdf

**Comment by donkadoodle** [comment]
![image](https://user-images.githubusercontent.com/66656984/84449885-85ecf600-ac03-11ea-94db-f22fdbf3aaf6.png)

**Comment by mahrer** [comment]
Thanks for providing your sources, @donkadoodle. I'm gonna say it's ready to go. Copy and pasting again so that the dev team can easily find it:

---

SEND TO: roberson@monterey.org, albert@monterey.org, haffa@monterey.org, smith@monterey.org, twilliamson@monterey.org

To Mayor Roberson and Monterey City Council Members,

My name is [YOUR NAME], and I am a Monterey community member. Since the violent murder of George Floyd, our nation has been forced to take an honest look at how Black and Brown people are treated in America. As a result we have seen protests in all 50 states calling for rapid and meaningful change, especially regarding racist institutions like policing. Simultaneously, cities across the country are facing budget deficits due to Covid-19 and Monterey is no exception.

As protests continued, Monterey released a budget proposal asking its tax-payers to accept a 60% reduction in recreation, library and museum spending as well as over 40 layoffs, but proposed only an 8% reduction of the police department. In the name of real public safety, I cannot accept this! On June 7, 2020 the Minneapolis City Council voted to defund and dismantle their city's police and pledged to invest in new models of public safety and I ask that Monterey City Council adopt this agenda as well.

According to the 2019-2021 Biennium Adopted Budget, expenditures for MPD totaled over $18 million, more than the expenditures for community services such as museums, parks and libraries combined. Though our city continues to spend extraordinary amounts on policing, residents still struggle with issues of public safety, houselessness, accessibility to mental health services, food equity and accessibility as well as general affordability in Monterey. By defunding police and reallocating those dollars to community services, you can make incredible systemic change to enrich the lives of all your constituents and uplift our most vulnerable populations. Real public safety addresses root causes, not just the symptoms; eliminating the desperation that places individuals in a position to commit criminalized acts in the first place. Additionally, many major events along our beautiful peninsula--which historically call for more police presence--have been canceled this year due to the pandemic. Though this means a decrease in city revenue through the TOT, it also means less tourism and crowds, a decrease in traffic and therefore a significantly lower demand on and for the police.

I call on you to defund the Monterey Police Department and use those extraordinary assets to offer more social services and boost the budgets for schools, recreation, libraries and the arts, which fundamentally enhance the health and wellness of all our community members. Defunding MPD will make space for new systems and more nuanced emergency-response approaches. Our citizens deserve this!

Sincerely,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it

**Comment by donkadoodle** [comment]
is it possible to add one more email address? the city clerk:
gawf@monterey.org

**Comment by todd-m** [comment]
sure, added
