### ISSUE TITLE
Add Richland, WA

### ISSUE THREAD

**Issue by JDot104** [defund12/defund12.org#1051]
Letter To:
rlukson@ci.richland.wa.us, BThompson@CI.RICHLAND.WA.US, skent@CI.RICHLAND.WA.US, banderson@CI.RICHLAND.WA.US, plemley@ci.richland.wa.us, tchristensen@CI.RICHLAND.WA.US, malvarez@CI.RICHLAND.WA.US

Subject: 
Public Safety Concern

Message:
Dear Richland City Leadership,

My name is [YOUR NAME] and I am a resident of Richland. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. I will no longer accept empty gestures and suggestions of “reform.” I am demanding that my voice be heard now, and that real change be made to the way this city allocates its resources.

Rather than prioritize the quality of life for all of Richland with a proportional budget, Richland chooses to prioritize RPD. In the 2019-2020 budget, the RPD was allocated a budget of $14,651,400 accounting for 24% of Richland’s total budget. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

According to the Tri-City Herald, 223 Tri-Citians were homeless as of 2017, however the pandemic’s severe economic consequences has likely caused this number to increase. Support for communities in need is necessary now, more than ever. But instead, Richland has chosen to prioritize RPD over funding services for the homeless many of whom are facing mental health problems and drug addiction.

I demand the City Council defund RPD. Instead, I demand we redirect police funding to improving mental health response teams, homeless shelters, and funding drug addiction treatment centers. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Richland residents. I demand a budget that supports community well-being, rather than empowers the police forces that tear them apart.

I am urging you to completely revise the Richland budget for the 2020-2021 fiscal year. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by JDot104** [comment]
[Richlandtaxes.pdf](https://github.com/defund12/defund12.org/files/4761926/Richlandtaxes.pdf)
[RichlandExpenditures.pdf](https://github.com/defund12/defund12.org/files/4761933/RichlandExpenditures.pdf)
Sources^

**Comment by stephbwills** [comment]
Thanks for opening @JDot104! I'll be reviewing this shortly.

**Comment by stephbwills** [comment]
@JDot104 would you mind sharing your source for the 223 Tri-citians? I'm seeing 222 here: https://www.tri-cityherald.com/news/politics-government/article238310503.html but not sure if you've used a more recent article.

**Comment by JDot104** [comment]
this is the link to the source I used: https://www.tri-cityherald.com/news/local/article195799699.html
thanks so much!

**Comment by stephbwills** [comment]
Thanks! Mind reading over my edits? I used the [Defund12 style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md) to inform my decisions:  
- changed up the second paragraph and worked it in elsewhere break up some common language we've seen among emails... this will help 'em feel a little less like robo emails to the city leaders receiving them
- edited language around homeless community to recent numbers (please double check this one for me! We can use the 2018 article if it makes more sense) 
- made minor grammatical changes
- shortened it up where I could without changing your voice

---

to: rlukson@ci.richland.wa.us, bthompson@ci.richland.wa.us, skent@ci.richland.wa.us, banderson@ci.richland.wa.us, plemley@ci.richland.wa.us, tchristensen@ci.richland.wa.us, malvarez@ci.richland.wa.us

Subject:
Public Safety Concern

Message:
Dear Richland City Leadership,

My name is [YOUR NAME], and I am a resident of Richland. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police. 

Rather than prioritize the quality of life for all of Richland with a proportional budget, Richland chooses to prioritize RPD. In the 2019-2020 budget, the RPD was allocated $14.6 million, accounting for 24% of Richland’s total estimated expenditures. We must spend this money in ways that are proven to improve community safety and wellness.

According to the Tri-City Herald, [222 Tri-Citians were homeless as of 2019](https://www.tri-cityherald.com/news/politics-government/article238310503.html), a number that may increase with the pandemic’s severe economic consequences. Support for communities in need is necessary now, more than ever. But instead, Richland has chosen to prioritize RPD over funding services for the homeless, many of whom are facing addiction and mental health conditions.

Amid widespread upheaval over the systemic violence of policing, I will no longer accept empty gestures and suggestions of “reform.” I join the calls of those across the country to defund the police. And I urge the Richland City Council to redirect police budgets to fund drug addiction treatment centers and improve mental health response teams and homeless shelters. I demand that you create a budget that adequately and effectively meets the needs of at-risk Richland residents. I demand that you support community well-being, rather than empowering the police forces that tear us apart.

I urge you to completely revise the Richland budget for the 2020-2021 fiscal year. You need to adopt a budget for the people. Public opinion is with me.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by JDot104** [comment]
Thank you! Yes, its fine with me!

**Comment by stephbwills** [comment]
great—@mahrer I can't update the label, but if you're you're able to get to it, I think this email's ready for a pr.
