### ISSUE TITLE
ADD San Mateo County, CA

### ISSUE THREAD

**Issue by ricee1213** [defund12/defund12.org#1053]
To: dpine@smcgov.org, cgroom@smcgov.org, DHorsley@smcgov.org, CHunter@smcgov.org, wslocum@smcgov.org, mdragun@smcgov.org, dcanepa@smcgov.org, tbayudan@smcgov.org
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!) 🔗

County Supervisors Pine, Groom, Horsley, Slocum, and Canepa,

My name is [YOUR NAME], and I am a resident of [CITY] in San Mateo County. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this county allocates its resources.

In the county's recommended FY 2020-21 operating budget, $280M is allocated to the Sheriff's Office, up from $276M+ in the FY 2019-20 budget. This is despite a projected $65-100M deficit in the proposed budget from COVID19. There is not just a need for police and sheriff reform, but police defunding and abolition: the entire structure of the sheriff and police force is inherently corrupt and ineffective.

The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

I demand that the County Supervisors begin meaningfully defunding the San Mateo County Sheriff's Office and reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of San Mateo County residents.  Propose and vote to expand on its current efforts in healthcare, affordable housing, and restorative justice. It is your duty to represent your constituents. I am urging you to revise the San Mateo County budget for the next fiscal year. 

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ellahenn** [comment]
More email addresses (including county councilmembers/deputies) that could be added: 
bsilverfarb@smcgov.org
akeighran@smcgov.org
mrichardson@smcgov.org
jbeiers@smcgov.org
ccunningham@smcgov.org
jnibbelin@smcgov.org
pokada@smcgov.org
dsilberman@smcgov.org
hhardy@smcgov.org
rmarcher@smcgov.org
aarmsby@smcgov.org
jholiber@smcgov.org
dvalim@smcgov.org
mandrikopoulos@smcgov.org
cbaumgartner@smcgov.org
gbeltramo@smcgov.org
jcharles@smcgov.org
lcho@smcgov.org
pcruz@smcgov.org
adonahue@smcgov.org
jellard@smcgov.org
aely@smcgov.org
tfox@smcgov.org
theumann@smcgov.org
jskraske@smcgov.org
bkulich@smcgov.org
imandelbaum@smcgov.org
kmarlow@smcgov.org
dmccloskey@smcgov.org
rpadilla@smcgov.org
kpaszek@smcgov.org
krosenthal@smcgov.org
psheng@smcgov.org
msheth@smcgov.org
bwong@smcgov.org

**Comment by ricee1213** [comment]
thanks @ellahenn!! :)

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

To: 
dpine@smcgov.org, cgroom@smcgov.org, DHorsley@smcgov.org, CHunter@smcgov.org, wslocum@smcgov.org, mdragun@smcgov.org, dcanepa@smcgov.org, tbayudan@smcgov.org
bsilverfarb@smcgov.org
akeighran@smcgov.org
mrichardson@smcgov.org
jbeiers@smcgov.org
ccunningham@smcgov.org
jnibbelin@smcgov.org
pokada@smcgov.org
dsilberman@smcgov.org
hhardy@smcgov.org
rmarcher@smcgov.org
aarmsby@smcgov.org
jholiber@smcgov.org
dvalim@smcgov.org
mandrikopoulos@smcgov.org
cbaumgartner@smcgov.org
gbeltramo@smcgov.org
jcharles@smcgov.org
lcho@smcgov.org
pcruz@smcgov.org
adonahue@smcgov.org
jellard@smcgov.org
aely@smcgov.org
tfox@smcgov.org
theumann@smcgov.org
jskraske@smcgov.org
bkulich@smcgov.org
imandelbaum@smcgov.org
kmarlow@smcgov.org
dmccloskey@smcgov.org
rpadilla@smcgov.org
kpaszek@smcgov.org
krosenthal@smcgov.org
psheng@smcgov.org
msheth@smcgov.org
bwong@smcgov.org

Message:

County Supervisors Pine, Groom, Horsley, Slocum, and Canepa,

My name is [YOUR NAME], and I am a resident of [CITY] in San Mateo County. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this county allocates its resources.

In the county's recommended FY 2020-21 operating budget, $280M is allocated to the Sheriff's Office, up from $276M+ in the FY 2019-20 budget. This is despite a projected $65-100M deficit in the proposed budget from COVID-19. There is not just a need for police reform, but police defunding and abolition. The entire structure of the sheriff and police force is inherently corrupt and ineffective.

The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

I demand that the County Supervisors begin meaningfully defunding the San Mateo County Sheriff's Office and reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of San Mateo County residents.  Propose and vote to expand on its current efforts in healthcare, affordable housing, and restorative justice. It is your duty to represent your constituents. I am urging you to revise the San Mateo County budget for the next fiscal year. 

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
