### ISSUE TITLE
Wilmington, NC - letter to Mayor and City Council Members

### ISSUE THREAD

**Issue by daliadalili** [defund12/defund12.org#1064]
bill.saffo@wilmingtonnc.gov, council@wilmingtonnc.gov, margaret.haynes@wilmingtonnc.gov, neil.anderson@wilmingtonnc.gov, clifford.barnett@wilmingtonnc.gov, council@wilmingtonnc.gov, charlie.rivenbark@wilmingtonnc.gov, kevin.spears@wilmingtonnc.gov

Subject: Defunding the Wilmington Police Department

Message:
Dear Mayor Saffo and Wilmington City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Wilmington City Police department and invest them into social services that would directly improve the well-being of Wilmington citizens.

The budget for 2019 was $35,097,295, and the recommended budget for 2020 is $36,546,488. This is a 13% increase from 2019 to 2020 and an almost 20% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the city of Wilmington’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Wilmington City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by aurendisson** [comment]
Editing notes: I removed a duplicate email address, tightened up some small areas of copy, and reworded the first sentence to emphasize the demand for defunding. Department budget figures confirmed here: https://www.wilmingtonnc.gov/home/showdocument?id=10786 

bill.saffo@wilmingtonnc.gov, council@wilmingtonnc.gov, margaret.haynes@wilmingtonnc.gov, neil.anderson@wilmingtonnc.gov, clifford.barnett@wilmingtonnc.gov, charlie.rivenbark@wilmingtonnc.gov, kevin.spears@wilmingtonnc.gov

Subject: Defunding the Wilmington Police Department

Message:
Dear Mayor Saffo and Wilmington City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you defund the Wilmington Police Department and reallocate funds to invest in social services that would directly improve the well-being of Wilmington citizens.

The 2019 police budget was $35,097,295, and the recommended budget for 2020 is $36,546,488. This is a 13% increase from 2019 to 2020 and an almost 20% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, health care, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement has been. I demand that more aggressive financial support be directed to those areas.

I am demanding long-term, sustainable change. I am demanding that the city of Wilmington’s budget be better spent on quality of life for all, particularly for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Wilmington City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now

**Comment by littleseeds** [comment]
@daliadalili -- if my math is right, it looks like the 13% figure came from the Adopted Budget ($32,302,549) vs. Adjusted Budget ($35,097,295) for 2019. I'm going to go ahead and change the 2019 budget number to $32,302,549 to be consistent with the 13% figure (change from Adjusted Budget is 4%), but let me know if you object. Thanks!
