### ISSUE TITLE
Please add Brick, NJ 

### ISSUE THREAD

**Issue by lfichera** [defund12/defund12.org#111]

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by cstrouse** [comment]
- Councilwoman Heather deJong, councilwomandejong@gmail.com
- Councilman Arthur Halloran, councilmanhalloran@gmail.com
- Council President Andrea Zapcic, azapcic@twp.brick.nj.us
- Councilman Paul Mummolo, councilmanmummolo@gmail.com
- Council Vice President Lisa Crate, councilwomancrate@gmail.com
- Councilwoman Marianna Pontoriero, councilwomanpontoriero@gmail.com

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
