### ISSUE TITLE
Lancaster, PA

### ISSUE THREAD

**Issue by madijanz** [defund12/defund12.org#1119]

**Comment by madijanz** [comment]
Emails: 
City Council Members: 
ismithwadeel@cityoflancasterpa.com
jarroyo@cityoflancasterpa.com
abakay@cityoflancasterpa.com
fcraig@cityoflancasterpa.com
jdiaz@cityoflancasterpa.com
xgarciamolina@cityoflancasterpa.com
psoto@cityoflancasterpa.com

Chief of Staff: jeking@cityoflancasterpa.com
Mayor: bburkholder@cityoflancasterpa.com

**Comment by swallan** [comment]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by madijanz** [comment]
Just finishing up edits now, will comment the template and subject line within the hour

**Comment by swallan** [comment]
@madijanz Great!

**Comment by averymcguirt** [comment]
Few edits to make the final section read more clearly. 

Dear Mayor Sorace and City Council Members,

My name is [YOUR NAME] from [YOUR NEIGHBORHOOD]. I am writing to urge you to commit to an ethical and equitable reallocation of the Lancaster City expense budget, away from the Lancaster City Bureau of Police and towards social services. The people of the city you govern have been showing up in the streets expressing their rage, grief and discontent because the measures already in place are not working.

As you know, our city and our police department have settled 8 lawsuits over claims of wrongdoing since 2015, including 5 for the use of excessive force. These settlements are paid for by us, Lancaster’s taxpayers. In addition, the lack of transparency and accountability from the police department has made it impossible to quantify any other misconduct that takes place. I will no longer accept empty gestures and suggestions of “reform” like those referenced in the “City of Lancaster Commitments to Racial Equity.”

In March of this year you told Keystone Edge, and I quote, “If I could snap my fingers and eliminate poverty, I would do it.” As a city resident, I would like to see a People’s budget that reflects this goal by prioritizing community wellbeing and redirects funding away from the police so that Lancaster can be a place of justice and safety for all people.

It is absolutely absurd that the adopted 2020 police budget is $26,846,397 which is larger than the allocations to the fire department, department of Community Planning & Economic Development and the department of Public Works combined. The police get 42.8% of our City’s budget of which 12 million is solely for police salaries. As a Lancaster City Resident, I demand you reallocate at least 20% of the Police budget to local social services. Places in the budget that deserve more funding, and will help you uphold your goal of working on poverty solutions, are:

-Homelessness Services: The city needs to have a robust program for housing vulnerable peoples and providing mobility into jobs and access to social services. Currently the budget lists this under Community Development Division, which received only 4.79 million in 2020.

-Low Income Housing: Similarly to homelessness services, the city needs a robust program for its residents. There is currently no mention of low-income housing support in the General Fund budget

-A team of social workers that reflect the city’s demographics trained to de-escalate and respond to emergency and non-emergency community needs

-Economic Development for and by Black and other City Residents of Color: Invest in and prioritize Black and other POC who are city residents for all grant and loan programs, specifically the existing enterprise loan program

Your action is imperative in this moment and I look forward to seeing you adopt a People's budget.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
