### ISSUE TITLE
Santa Clara, CA (City)

### ISSUE THREAD

**Issue by aed1993** [defund12/defund12.org#1138]
MayorAndCouncil@santaclaraca.gov; lgillmor@santaclaraca.gov (Mayor); kwatanabe@santaclaraca.gov (District 1); rchahal@santaclaraca.gov (District 2); khardy@santaclaraca.gov (District 3); toneill@santaclaraca.gov (District 4); ddavis@santaclaraca.gov (Distrct 6)

To Mayor Lisa Gilmore, Santa Clara City Council Members, and the Santa Clara City Manager,

My name is [YOUR NAME], and I am a resident of Santa Clara. These past weeks, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul of our approach to criminal justice in America. I ask that our voices be heard, and that real change be made to the way this city allocates its resources. The Bay Area has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2020-2021 is under review as these protests continue. SCPD is a poor use of our resources.

The fact that SCPD encompasses over 77 million dollars of the city’s general operating fund in the proposed 2020/2021 budget is deeply concerning. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

We could be spending the money we currently spend on policing on resources that better serve the community, like affordable housing, public education, mental health resources, and improving the library system, just to name a few. Amidst a pandemic in which everyone has been affected monetarily, the police system should be the first to be defunded. There are other far more important initiatives that need our money.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Santa Clara residents during this trying and uncertain time, when livelihoods are on the line. I ask you to meaningfully reallocate funds towards social programs and resources that support housing, education, and other critical community needs. I urge you to pass a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincereley,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by aurendisson** [comment]
The edited version below. I corrected the spelling of the mayor's name, reworded the portion about "We could be spending," corrected a slash that should have been a hyphen, removed some commas, and corrected a couple of small typos. 


MayorAndCouncil@santaclaraca.gov; lgillmor@santaclaraca.gov (Mayor); kwatanabe@santaclaraca.gov (District 1); rchahal@santaclaraca.gov (District 2); khardy@santaclaraca.gov (District 3); toneill@santaclaraca.gov (District 4); ddavis@santaclaraca.gov (District 6)

To Mayor Lisa Gillmor, Santa Clara City Council Members, and the Santa Clara City Manager,

My name is [YOUR NAME], and I am a resident of Santa Clara. These past weeks, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul of our approach to criminal justice in America. I ask that our voices be heard and that real change be made to the way this city allocates its resources. The Bay Area has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2020-2021 is under review as these protests continue. SCPD is a poor use of our resources.

The fact that SCPD encompasses over $77 million of the city’s general operating fund in the proposed 2020-2021 budget is deeply concerning. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

We could be spending our current policing budget on resources that better serve the community, such as affordable housing, public education, mental health resources, and improving the library system, just to name a few. Amidst a pandemic in which everyone has been affected monetarily, the police system should be the first to be defunded. There are other far more important initiatives that need our money.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Santa Clara residents during this trying and uncertain time when livelihoods are on the line. I ask you to meaningfully reallocate funds towards social programs and resources that support housing, education, and other critical community needs. I urge you to pass a budget that supports community well-being, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by aurendisson** [comment]
@ready-for-pr

**Comment by dionlarson** [comment]
Budget verified, page 66 [here](https://www.santaclaraca.gov/home/showdocument?id=64781).

**Comment by todd-m** [comment]
on it
