### ISSUE TITLE
Please add Albuquerque, New Mexico

### ISSUE THREAD

**Issue by anniedorazio** [defund12/defund12.org#114]
*A subject message: Please add Albuquerque, New Mexico to defund12.org
*I only have contact list info: 
www.heinrich.senate.gov/contact 
www.tomudall.senate.gov/?p=contact
https://haaland.house.gov/contact/email-me

* This is a link to the current city budget: http://documents.cabq.gov/budget/fy-20-approved-budget.pdf 

Thank you!!

**Comment by teddywilson** [comment]
Hey, in order to proceed we will need a bit more information. The subject should be a subject to the email we will send out. We will also need a typed up email similar to the ones we currently have on the site. Please reassign back to me once this is complete.

**Comment by anniedorazio** [comment]
Will do. Thank you!

**Comment by cstrouse** [comment]
- Councilor Lan Sena, District 1, lansena@cabq.gov
- Councilor Isaac Benton, District 2, ibenton@cabq.gov
- Diane Dolan, District 2, Policy Analyst, ddolan@cabq.gov
- Councilor Klarissa J. Peña, District 3, kpena@cabq.gov
- Policy Analyst Nancy Montaño, District 3, nancymontano@cabq.gov
- Councilor Brook Bassan, District 4, bbassan@cabq.gov
- Councilor Cynthia Borrego, District 5, cynthiaborrego@cabq.gov
- Policy Analyst Susan Vigil, District 5, susanvigil@cabq.gov
- Councilor Pat Davis, District 6, patdavis@cabq.gov
- Policy Analyst Sean Foran, District 6, seanforan@cabq.gov
- Councilor Diane Gibson, District 7, dgibson@cabq.gov
- Policy Analyst Abigail Stiles, District 7, astiles@cabq.gov
- Councilor Trudy Jones, District 8, trudyjones@cabq.gov
- Policy Analyst Aziza Chavez, District 8, azizachavez@cabq.gov
- Councilor Don Harris, District 9, dharris@cabq.gov
- Policy Analyst Laura Rummler, District 9, lrummler@cabq.gov

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
