### ISSUE TITLE
Washington County, OR.- Letter to Comissioners

### ISSUE THREAD

**Issue by justicemeow** [defund12/defund12.org#1141]
TO: cao@co.washington.or.us, kathryn_harrington@co.washington.or.us, info@kathrynforourcounty.com, dick_schouten@co.washington.or.us, supportschouten@gmail.com, royr@rascpas.com, roy_rogers@co.washington.or.us, pamelatreece@mac.com, pam_treece@co.washington.or.us, jerry@willey.biz, jerry_willey@co.washington.or.us, finance_budget@co.washington.or.us

Dear Washington County Commissioners,

My name is [YOUR NAME] and I am a resident of [YOUR WARD]. I am writing to demand that the County Commissioners adopts a budget that prioritizes community well-being and redirects funding away from the Washington County Sheriffs Office.

Many Oregonians may be tempted to think the unique nature of such a vast, yet sparsely-populated state minimizes the likelihood of police brutality in our city communities. However, as reported by The Oregonian/OregonLive's investigation project : “State regulators took no action to sideline dozens of officers fired for chronically inept police work or worse. The department let fired officers remain eligible to work even after they accumulated records of brutality, recklessness, shoddy investigations and anger management problems.” Oregon police forces, including the Washington County Sheriffs Office, operate within a culture of impunity, and as the members of the communities they are supposed to be protecting, we can’t even begin to grasp the scope of their violence.

We are in the midst of widespread upheaval over the systemic violence of policing. Empty gestures and suggestions of “reform” are inadequate and unacceptable. I am demanding that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. I am demanding that the Washington County Commissioners defund Washington County Sheriff’s Office. I join the calls of those across the country to defund the police. I am demanding a budget that adequately and effectively meets the needs of at-risk Washington County residents during this trying and uncertain time, when livelihoods are on the line. I am demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart.

As commissioners, the budget proposal is in your hands. It is your duty to represent your constituents justly. I am urging you to completely revise the budget for the July 1, 2020 to June 30, 2021 fiscal year. Currently the Washington County’s proposed $1.4 billion total budget is ready to give $214,594,431 to Public Safety & Justice Division, Which is a 16% increase from last year’s budget. We urge you to fund the social programs proven to be more effective than policing at promoting community safety and equity. Have the courage to be a leader of the change this city, state, and country desperately needs.

EXAMPLES OF RACISM & MISCONDUCT BY WCSO OFFICERS (that were made public):

https://www.youtube.com/watch?v=kV4qFW869wo 

https://www.oregonlive.com/crime/2020/06/washington-county-reopens-misconduct-case-against-sheriffs-deputy-after-racist-email-surfaces.html 

https://www.kptv.com/news/sheriff-washington-co-deputy-accused-of-concerning-use-of-force-in-2018-using-racial-epithets/article_0a5cbe18-a78e-11ea-a04c-2f3a89bf855c.html 

THE OREGON DEPARTMENT OF PUBLIC SAFETY STANDARDS LACKING OVERSIGHT:

Evidence that The Oregon Department of Public Safety Standards allowing police misconduct  :

https://projects.oregonlive.com/police/state-oversight/ 

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by justicemeow** [comment]
just FYI this county is having their budgeting meeting on june 16th.. if we could get this put up asap that would be most appreciated. thank you for your time and effort and doing this and no hard feelings if it cant get posted by then.

**Comment by mahrer** [comment]
Good to know @justicemeow! I'll review this now and try to expedite the pull request.

**Comment by mahrer** [comment]
Some minor edits:

---

TO: cao@co.washington.or.us, kathryn_harrington@co.washington.or.us, info@kathrynforourcounty.com, dick_schouten@co.washington.or.us, supportschouten@gmail.com, royr@rascpas.com, roy_rogers@co.washington.or.us, pamelatreece@mac.com, pam_treece@co.washington.or.us, jerry@willey.biz, jerry_willey@co.washington.or.us, finance_budget@co.washington.or.us

Dear Washington County Commissioners,

My name is [YOUR NAME] and I am a resident of [YOUR WARD]. I am writing to demand that the County Commissioners adopts a budget that prioritizes community well-being and redirects funding away from the Washington County Sheriffs Office.

Many Oregonians may be tempted to think the unique nature of such a vast, yet sparsely-populated state minimizes the likelihood of police brutality in our city communities. However, as reported by The Oregonian/OregonLive's investigation project, “State regulators took no action to sideline dozens of officers fired for chronically inept police work or worse. The department let fired officers remain eligible to work even after they accumulated records of brutality, recklessness, shoddy investigations and anger management problems.” Oregon police forces, including the Washington County Sheriffs Office, operate within a culture of impunity, and as the members of the communities they are supposed to be protecting, we can’t even begin to grasp the scope of their violence.

We are in the midst of widespread upheaval over the systemic violence of policing. Empty gestures and suggestions of “reform” are inadequate and unacceptable. I am demanding that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. I am demanding that the Washington County Commissioners defund Washington County Sheriff’s Office. I join the calls of those across the country to defund the police. I am demanding a budget that adequately and effectively meets the needs of at-risk Washington County residents during this trying and uncertain time, when livelihoods are on the line. I am demanding a budget that supports community well-being, rather than empowering the police forces that tear them apart.

As commissioners, the budget proposal is in your hands. It is your duty to represent your constituents justly. I am urging you to completely revise the budget for the July 1, 2020 to June 30, 2021 fiscal year. Currently the Washington County’s proposed $1.4 billion total budget is ready to give $214,594,431 to Public Safety & Justice Division, which is a 16% increase from last year’s budget. We urge you to fund the social programs proven to be more effective than policing at promoting community safety and equity. Have the courage to be a leader of the change this city, state, and country desperately needs.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

EXAMPLES OF RACISM & MISCONDUCT BY WCSO OFFICERS (that were made public):
https://www.youtube.com/watch?v=kV4qFW869wo

https://www.oregonlive.com/crime/2020/06/washington-county-reopens-misconduct-case-against-sheriffs-deputy-after-racist-email-surfaces.html

https://www.kptv.com/news/sheriff-washington-co-deputy-accused-of-concerning-use-of-force-in-2018-using-racial-epithets/article_0a5cbe18-a78e-11ea-a04c-2f3a89bf855c.html

Evidence that The Oregon Department of Public Safety Standards allowing police misconduct:
https://projects.oregonlive.com/police/state-oversight/

**Comment by justicemeow** [comment]
thank you !!!!!

**Comment by rpalakkal** [comment]
adding right now!
