### ISSUE TITLE
Add Davenport, IA

### ISSUE THREAD

**Issue by tiamia08** [defund12/defund12.org#1142]
Email for mayor: mike.matson@davenportiowa.com
patrick.peacock@davenportiowa.com

The city of Davenport's total general fund budget for FY21 is $49,435,595 with 38% of that being for police.  Only 1% ($344,703) of the budget is allocated for the Civil Rights Department and 1.3% ($642,246) towards Community & Economic Development. This is higher than Cedar Rapids, Iowa City and West Des Moines, but slightly less than Des Moines at 39%.  These other cities also allocate more money to neighborhood development, Iowa City 13%, West Des Moines 3%, and Des Moines 4%.  Davenport allocates a huge amount of money for police services, 89% of that money going to employees.  The police budget needs to be reduced to allow for additional funding for the Civil Rights Department and Community & Economic Development.  To allow for these services for mental health, substance abuse, homelessness, youth diversion, and having police out of the schools can be implemented and the police will not have to perform them as the primary provider.

**Comment by Rtrott** [comment]
Reviewing now

**Comment by aurendisson** [comment]
This email needs work on its structure to align with our template, and we should add more elected officials/councilmembers to the list of emails.

**Comment by dav5th** [comment]
The rest of city council;

rick.dunn@davenportiowa.com
matt.dohrmann@davenportiowa.com
maria.dickmann@davenportiowa.com
marion.meginnis@davenportiowa.com
raymond.ambrose@davenportiowa.com
ben.jobgen@davenportiowa.com
judith.lee@davenportiowa.com
kyle.gripp@davenportiowa.com
jj.condon@davenportiowa.com

**Comment by wendywx** [comment]
edits in bold:

------------------------------------------------

To: 
mike.matson@davenportiowa.com
patrick.peacock@davenportiowa.com
rick.dunn@davenportiowa.com
matt.dohrmann@davenportiowa.com
maria.dickmann@davenportiowa.com
marion.meginnis@davenportiowa.com
raymond.ambrose@davenportiowa.com
ben.jobgen@davenportiowa.com
judith.lee@davenportiowa.com
kyle.gripp@davenportiowa.com
jj.condon@davenportiowa.com

Body:

**To Mayor Matson and City Councilmembers**,

**My name is [YOUR NAME] and I am a resident of Davenport.** **I am writing to urge that the city divest from the systems of incarceration and policing, and instead invest in life affirming, sustainable, and self-determined community resources.**

The city of Davenport's total general fund **operating** budget for FY21 is $49,435,595 with 38**.9**% of that being for **the** police **department**. **Even more alarming, less than** 1% ($344,703) of **this** budget is allocated for the Civil Rights Department and 1.3% ($642,246) towards Community & Economic Development **[1]**. **The percentage of the Davenport general fund expenditures allocated towards the Davenport Police Department is** higher than Cedar Rapids **[2]**, Iowa City **[3],** and West Des Moines **[4]** **have allocated towards their respective police departments for FY21**. These other cities also allocate more money to neighborhood/community development**:** Iowa City **8.5**% **[3]**, West Des Moines **2.14**% [4], and Des Moines **5**% [5], **though these are still far from ideal**. 

**I urge the City Council to reduce the Davenport Police Department** budget to allow for additional funding for the Civil Rights and Community & Economic Development **Departments**, **as well as more effective social programs and services for mental health, substance abuse, homelessness, and youth diversion. Resources should be allocated to EMTs, social workers, and other social service providers to respond to the majority of current police business, including health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. Please do the right thing. Prioritize the health, safety and well-being of Davenport residents.**

**Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Sources:
[1] Davenport FY 2021 Operating & Capital Improvement Budget - https://cityofdavenportiowa.com/UserFiles/Servers/Server_6481372/File/Departments/Finance/Budget/FY%202021%20Budget%20Book.pdf
[2] Cedar Rapids Fiscal Year 2021 Budget Book 1 - https://cms.revize.com/revize/cedarrapids/document_center/Finance/Budget/FY%202021%20Budget%20-%20GFOA%20Version%20-%20Book%201.pdf
[3] Iowa City FY2021 Proposed Budget - https://www8.iowa-city.org/WebLink/0/edoc/1927679/FY2021%20Proposed%20Budget.pdf
[4] West Des Moines FY 2020-2021 General Fund Budget - https://www.wdm.iowa.gov/home/showdocument?id=31317
[5] Des Moines FY 2021 Recommended Operating Budget - https://www.dsm.city/document_center/Finance/Operating%20Budget/2021/FY2021%20Recommended%20Operating%20Budget%20-%20for%20Web.pdf?pdf=FY2021%20Recommended%20Operating%20Budget&t=1592190908856**

-------------------------------------------------

Hi @tiamia08 @dav5th - thank you for your interest in adding Davenport!

I removed the statistic with "89% of that money going to employees" because it didn't appear to serve a purpose (ex. a demand for number of employees to be reduced).

"and having police out of the schools can be implemented and the police will not have to perform them as the primary provider." - I also wasn't able to find sources on Davenport school's relationships with the police department, so removed this part. If you provide a source later on then please open a content change request in the future. I replaced this sentence with a general call to replace police with social workers and violence interrupters.

I updated the statistics as per the sources listed above, and added a salutation, opening introduction, and closing as per the [email style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md).

Marking this as ready for PR.
