### ISSUE TITLE
Add: Rochester, NY

### ISSUE THREAD

**Issue by BigOlBrett** [defund12/defund12.org#1150]
info@cityofrochester.gov, loretta.scott@cityofrocheter.gov, Council@cityofrochester.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Mayor Lovely Warren and Rochester City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect additional money away from the Rochester PD in the 2021 budget and instead to prioritize services that help strengthen our communities.

I commend you on the near 4% decrease for policing in the 2020-21 proposed budget. However, the recent murders by police of George Floyd and Breonna Taylor leave no choice but to demand more from our City.

You are well aware that Rochester now ranks 3rd in overall poverty among the nation's 75 largest metropolitan areas. I'm sure you are also aware that crime is not random. Crime occurs when someone is unable to meet their basic needs through other means. Fighting crime in Rochester begins and ends with fighting poverty and empowering our neighbors. 

I want a budget that reflects our community’s priorities and needs. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. These services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by BigOlBrett** [comment]
info@cityofrochester.gov, loretta.scott@cityofrocheter.gov, Council@cityofrochester.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Mayor Lovely Warren and Rochester City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect additional money away from the Rochester PD in the 2021 budget and instead to prioritize services that help strengthen our communities.

You are well aware that Rochester now ranks 3rd in overall poverty among the nation's 75 largest metropolitan areas. I'm sure you are also aware that crime is not random. Crime occurs when someone is unable to meet their basic needs through other means. Fighting crime in Rochester begins and ends with fighting poverty and empowering our neighbors.

I want a budget that reflects our community’s priorities and needs. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. These services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by Rtrott** [comment]
reviewing now

**Comment by Rtrott** [comment]
info@cityofrochester.gov, loretta.scott@cityofrocheter.gov, Council@cityofrochester.gov,
Malik.Evans@cityofrochester.gov, Mitch.Gruber@cityofrochester.gov, Willie.Lightfoot@cityofrochester.gov
biography, Jacklyn.Ortiz@cityofrochester.gov
biography,

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Mayor Lovely Warren and Rochester City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to divert money away from the Rochester PD in the 2021 budget and instead to prioritize services that help strengthen our communities.

Rochester now ranks 3rd in overall poverty among the nation's 75 largest metropolitan areas, yet the proposed budget for the fiscal year 2020/21 includes 95,866,000 for the Rochester PD, making up over 18% of the proposed Budget, whereas funds towards children, youth, family programs and neighborhood support makes up just 9% combined. I'm sure you are aware that crime is not random. Crime occurs when someone is unable to meet their basic needs through other means. Promoting safety in Rochester begins and ends with fighting poverty and empowering our neighbors.

I want a budget that reflects our community’s priorities and needs. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. These services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it

**Comment by todd-m** [comment]
JK, we already have a letter for Rochester; relevant issues are #1171, #1056, #901, #814, #784, #580, #279. Rochester is in demand! Marking as duplicate -- this should probably be closed unless someone wants a specific edit included in the template that's live.
