### ISSUE TITLE
Cupertino - Letter to Mayor and City Council

### ISSUE THREAD

**Issue by sagareejain** [defund12/defund12.org#1182]
To: sscharf@cupertino.org, rsinks@cupertino.org, liangchao@cupertino.org, jwilley@cupertino.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

To Mayor Scharf and Cupertino City Council Members, 

My name is [YOUR NAME], and I am a resident of Cupertino. Over the last few weeks, I’ve seen an outpouring of rage and grief over an occurrence common in the United States: the police killing of an unarmed Black person. George Floyd, Breonna Taylor, Tony McDade, Ahmaud Arbery. I say their names to honor the lives lost to police violence. I demand that the city of Cupertino respond to this moment, not just with rhetoric, but with change that addresses the systems that encourage anti-Black racism in small towns all over the United States.

Currently, Cupertino spends 14 million on law enforcement each year, and in 2014, the Mercury News reported that 9 million of that goes directly to contracting with Santa Clara County Office of the Sheriff. In doing so, Cupertino is supporting a system of discrimination and brutality against Black people.

County sheriffs and the criminal “justice” system disproportionately police and incarcerate Black people in Santa Clara. In 2017, the Santa Clara County District Attorney reported that while Black residents make up only 2% of the county, a statistic that already points to deep patterns of segregation, Black residents make up 12% of felony defendants and “a disproportionately high number of Black and Hispanic defendants were sentenced to prison as compared to their representation in the community.”

Cupertino spends 9 million dollars contracting with Santa Clara County Police despite the over policing of Black communities, despite the crisis in affordable housing in the South Bay, despite the fact that Cupertino has no homeless shelters. The average Cupertino resident pays $348 a year for Law Enforcement, $139 for Parks and Recreation, $12 for affordable housing, and $2 for support for unhoused people. As a city, I ask that Cupertino answer the call from the Movement for Black Lives and other Black organizations to defund the police and invest instead in community based organizations that truly promote public safety, health, harm reduction, and de-escalation. I ask that: 

Cupertino pledges to defund the police in the upcoming 2024-2025 contract with the Santa Clara Office of the Sheriff.
Cupertino immediately defunds the 48,000 annual subsidy of School Resource Officers in FUHSD and CUSD schools. 
Cupertino instead funds affordable housing, support for unhoused people, and youth mental health. 

I was heartened to see Cupertino pass a resolution on June 5, 2020 affirming that Black Lives Matter. In order to, as the resolution states, “oppose any attempts to undermine the safety, security, and rights of members of our community,” it is essential that Cupertino moves to defund the police and reroute that funding to truly support Black people and communities of color. 

Best,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by swallan** [comment]
To: sscharf@cupertino.org, rsinks@cupertino.org, liangchao@cupertino.org, jwilley@cupertino.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

To Mayor Scharf and Cupertino City Council Members,

My name is [YOUR NAME], and I am a resident of Cupertino. Over the last few weeks, I’ve seen an outpouring of rage and grief over an occurrence common in the United States: the police killing of an unarmed Black person. George Floyd, Breonna Taylor, Tony McDade, Ahmaud Arbery. I say their names to honor the lives lost to police violence. I demand that the city of Cupertino respond to this moment, not just with rhetoric, but with change that addresses the systems that encourage anti-Black racism in small towns all over the United States.

Currently, Cupertino spends 14 million on law enforcement each year, and in 2014, the Mercury News reported that 9 million of that goes directly to contracting with Santa Clara County Office of the Sheriff. In doing so, Cupertino is supporting a system of discrimination and brutality against Black people.

County sheriffs and the criminal “justice” system disproportionately police and incarcerate Black people in Santa Clara. In 2017, the Santa Clara County District Attorney reported that while Black residents make up only 2% of the county, a statistic that already points to deep patterns of segregation, Black residents make up 12% of felony defendants and “a disproportionately high number of Black and Hispanic defendants were sentenced to prison as compared to their representation in the community.”

Cupertino spends 9 million dollars contracting with Santa Clara County Sheriff despite the over policing of Black communities, despite the crisis in affordable housing in the South Bay, despite the fact that Cupertino has no homeless shelters. The average Cupertino resident pays $348 a year for Law Enforcement, $139 for Parks and Recreation, $12 for affordable housing, and $2 for support for unhoused people. As a city, I ask that Cupertino answer the call from the Movement for Black Lives and other Black organizations to defund the police and invest instead in community based organizations that truly promote public safety, health, harm reduction, and de-escalation. I ask that:

1. Cupertino pledges to defund the police in the upcoming 2024-2025 contract with the Santa Clara Office of the Sheriff.
2. Cupertino immediately defunds the 48,000 annual subsidy of School Resource Officers in FUHSD and CUSD schools.
3. Cupertino instead funds affordable housing, support for unhoused people, and youth mental health.

I was heartened to see Cupertino pass a resolution on June 5, 2020 affirming that Black Lives Matter. In order to, as the resolution states, “oppose any attempts to undermine the safety, security, and rights of members of our community,” it is essential that Cupertino moves to defund the police and reroute that funding to truly support Black people and communities of color.

Best,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
