### ISSUE TITLE
PLEASE ADD: Artesia, CA 90701

### ISSUE THREAD

**Issue by artrattheatre** [defund12/defund12.org#1203]
Emails:

tlima@cityofartesia.us
mcanales@cityofartesia.us
ataj@cityofartesia.us
ataj@cityofartesia.us
rtrevino@cityofartesia.us
mramoso@cityofartesia.us
jalderete@cityofartesia.us
wrawlings@cityofartesia.us

Email Template:

Hello, my name is [NAME], a resident of Artesia, CA. 
Many of your terms expire this year, December 2020, or will be up for re-election soon thereafter.
Time for election is near and the time for action is Now.
Myself and my neighbors can only re-elect those who stand for what we stand for.

During the rest of your term, I urge you to take a stand for the national movement led by Black Lives Matters and commit to divesting from our dependency on law enforcement.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the LAPD’s well documented history of murdering Black people. As a part of greater LA county, now is a critical time to assert our city's commitment to justice.

Currently, Artesia is still budgeting nearly half of Artesia's budget to Law Enforcement.
Compared to 41% committed to Law Enforcement, Parks & Recs only received 9%. 
Maintenance and public works even less at 7%.
At that, building and safety in our city is EVEN less than that! 3%
Community promotions coming in most meager at 2%.

As your constituent, I urge you to:
1) Decrease Law Enforcement so that our COMMUNITY INVESTMENTS greatly and significantly outweigh our law enforcement investment.
2) issue a statement in support of Defending Black lives.
3) issue a statement committed to divesting in law enforcement, and INVESTING into our community.

More money into our community means less need for policing.
The public opinion is with me.

Thank you.

Your constituent,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

* * 

SOURCES: 
https://www.cityofartesia.us/documentcenter/view/2598
LAPD email template (defund12.org)
https://www.cityofartesia.us/Directory.aspx

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Emails:
tlima@cityofartesia.us
mcanales@cityofartesia.us
ataj@cityofartesia.us
ataj@cityofartesia.us
rtrevino@cityofartesia.us
mramoso@cityofartesia.us
jalderete@cityofartesia.us
wrawlings@cityofartesia.us

Message:

Dear elected officials of Artesia,

My name is [NAME], a resident of Artesia, CA.

Many of your terms expire this year, December 2020, or will be up for re-election soon thereafter. The time for election is near, and the time for action is now. Myself and my neighbors can only re-elect those who stand for what we stand for. During the rest of your term, I urge you to take a stand for the national movement led by Black Lives Matter and commit to divesting from our dependency on law enforcement. 

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the LAPD’s well documented history of murdering Black people. As a part of greater LA county, now is a critical time to assert our city's commitment to justice.

Currently, nearly half of Artesia's budget is allocated to Law Enforcement (41%). In comparison, 
Parks & Rec receives 9%, Maintenance and Public Works receives 7%, Building and Safety receives 3%, and Community Promotions comes in most meager at 2%.

As your constituent, I urge you to:
- Decrease Law Enforcement so that our community investments significantly outweigh our law enforcement investment.
- Issue a statement in support of Defending Black lives.
- Issue a statement committed to divesting in law enforcement and investing into our community.

The public opinion is with me.
Thank you.

Your constituent,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on this
