### ISSUE TITLE
Boulder, CO budgetary numbers

### ISSUE THREAD

**Issue by sneakmeg** [defund12/defund12.org#1245]
I am writing to the Boulder, CO City Council to call for defunding the police. However, I noticed in the letter draft that it said the budget for Housing and Human Services was set at $21,655,671 for 2020, but according to https://www-static.bouldercolorado.gov/docs/2020_Approved_Budget_ONLINE_Optimized-1-201911141310.pdf?_ga=2.79351186.760377889.1591577574-1753649526.1591577574, on page 220, this should actually be $9,145,957 (unless I'm mistaken?). Just wanted to make sure these numbers were accurate. Thanks!

**Comment by swallan** [comment]
Thanks for letting us know, someone will take a deeper look soon.

**Comment by Rtrott** [comment]
Hi @sneakmeg, so the figure of $21,655,671 is from what I can see correct. If you look at the page 101 of the document, that's the figure that is included in the overall budget. The figure on page 220, is citing the 'general budget', rather than the overall budget. The general budget is made up of mostly tax payer money, whereas the entire budget  also includes money from federal grants and different streams of income that the city has.
