### ISSUE TITLE
Somerville, MA - Letter to Mayor

### ISSUE THREAD

**Issue by viggyram** [defund12/defund12.org#1252]
To: JCurtatone@somervillema.gov

Subject: [PERSONALIZE SUBJECT]

Message: 

Dear Mayor Curtatone,

My name is [INSERT YOUR NAME] and I am a resident of [YOUR WARD (find out here!)] in Somerville, MA. I am writing to demand that you take specific measures to reduce funding for police in the city of Somerville. **The Mayor has a responsibility to communities of color in Somerville to take immediate steps to decrease funding to the police and systems of criminalization in place while reinvesting those funds into Black and brown communities most directly impacted by police violence and disinvestment.**

Our city faces dire crises during the COVID-19 epidemic that can’t be solved by policing. Thousands of us have lost wages and face food-insecurity due to the economic crisis that is unfolding in this community. We face the risk of forced removal as soon as the eviction ban is lifted and recognize that these conditions only exacerbate the long-standing inequalities in Somerville that have displaced communities of color from this area. For far too long the status quo has forced essential educators to live on starvation wages while overwhelming community demands to right this glaring injustice are ignored. Meanwhile, our Police Department hoards hundreds of thousands of dollars seized from citizens unconvicted of any crime and the City rewards police officers with six-figure salaries. This is unconscionable. Somerville police officers don’t just brutalize Somerville residents, but also attack peaceful protestors in other cities through expensive interdepartmental mutual aid agreements. Somerville’s failings include reliance on lethally armed police to solve community problems and funding our police force at the expense of programs that strengthen our community and reduce crime.

[INSERT PERSONAL EXPERIENCE WITH POLICE VIOLENCE/RACISM IN SOMERVILLE]

**To fix these failings, we must reallocate millions of dollars from the $17,000,000 Police Department budget, remove officers from Somerville schools, and disarm the police. Our needs must be addressed by the provision of care and not the threat of violence.** We must reinvest into public goods like education, public health, jobs, and safe housing. Most importantly, decisions around funding and reinvestment must be done in collaboration with Black and brown community members who are most impacted by the harms of police violence and disinvestment. 

While the City of Somerville’s adoption of all of the #8CantWait police reform policies is a first step, it cannot be where we stop. We must significantly defund the Somerville police department by cutting bloated salaries, expensive overtime, and militarized budgets to reinvest in our communities. It’s time to stop investing in criminalization and surveillance, and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing grants, healthcare, youth jobs and services, POC-owned businesses, community centers, trauma-informed first responders, POC-led organizations and projects.

Thank you,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by viggyram** [comment]
Hey all! I'm sure you're swamped. I just wanted to bump this. Our city council hearings are coming up and it would be great to add some pressure on the Mayor and coincillors

**Comment by Rtrott** [comment]
I'll get on reviewing it so it can get to the next stage ASAP!

**Comment by Rtrott** [comment]
The second edited one looks all good to me!

**Comment by viggyram** [comment]
This is awesome! Thank you so much. What's the next step on our end?

**Comment by viggyram** [comment]
Sorry, just bumping this again!

**Comment by wendywx** [comment]
Edits in bold:

--------------------------------------------------

To: JCurtatone@somervillema.gov, citycouncil@somervillema.gov, cityclerk@somervillema.gov

Message:

Dear Mayor Curtatone and Somerville City Council members,

My name is **[YOUR NAME]** and I am a resident of [YOUR WARD (find out [here](https://www.arcgis.com/apps/View/index.html?appid=dbac8d9176e44c0a8e2a214dce256e28)!)] in Somerville, MA. I am writing to demand that you take specific measures to reduce funding for police in the city of Somerville. The Mayor and the members of the city council have a responsibility to communities of color in Somerville to take immediate steps to decrease funding to the police**,** while reinvesting those funds into Black, **B**rown**, and Indigenous** communities most directly impacted by police violence and disinvestment.

Our city faces dire crises during the COVID-19 epidemic that can’t be solved by policing. Thousands of **community members** have lost wages and face food-insecurity due to the economic crisis that is unfolding in this community. **Some** face the risk of forced removal as soon as the eviction ban is lifted and **I** recognize that these conditions only exacerbate the long-standing inequalities in Somerville that have displaced communities of color from this area. For far too long the status quo has forced essential educators to live on starvation wages while overwhelming community demands to right this glaring injustice are ignored. Meanwhile, our Police Department hoards hundreds of thousands of dollars seized from citizens unconvicted of any crime and the City rewards police officers with six-figure salaries. This is unconscionable. Somerville police officers don’t just brutalize Somerville residents, but also attack peaceful protestors in other cities through expensive interdepartmental mutual aid agreements. Somerville’s failings include reliance on lethally armed police to solve community problems and funding our police force at the expense of programs that strengthen our community and reduce crime.

[INSERT PERSONAL EXPERIENCE WITH POLICE VIOLENCE/RACISM IN SOMERVILLE]

**Accordingly, it has come to my attention that the budget for 2021 will be presented to the City Council on June 19.** **The previous FY 2020 budget allocated $17,044,021 to Somerville PD, more than the budgets of Health and Human Services, Culture & Recreation, Medicare, and all the OSPCD Divisions combined.** To fix these failings, **I demand the City to** reallocate millions of dollars from the Police Department FY 2021 budget, remove officers from Somerville schools, and disarm the police. Our needs must be addressed by the provision of care and not the threat of violence. We must reinvest into **social programs and resources** like education, public health, jobs, and safe housing. Most importantly, decisions around funding and reinvestment must be done in collaboration with Black, **B**rown**, and Indigenous** community members who are most impacted by the harms of police violence and disinvestment.

We must significantly defund the Somerville police department by cutting bloated salaries, expensive overtime, and militarized budgets to reinvest in our communities. It’s time to stop investing in criminalization and surveillance, and fund what Black, **B**rown**, and Indigenous** communities need to be safe and healthy: COVID19 relief, housing grants, healthcare, youth jobs and services, POC-owned businesses, community centers, trauma-informed first responders, POC-led organizations and projects.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

------------------------------

Hi @viggyram - Made a few additions, namely added some statistics from the 2020 budget because according to https://somerville.wickedlocal.com/news/20200611/somerville-city-council-laments-delayed-budget-process-reviews-new-online-budget-portal the FY 2021 budget for Somerville won't be presented to the Somerville council until June 19. I also removed the sentence with hashtags and campaign, all of these changes made as per the [email guidelines](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md). If you are okay with these edits then I will mark this issue to be ready to be added to the website.

**Comment by viggyram** [comment]
Hi @wendywx, these edits look good. Thank you!
