### ISSUE TITLE
Lakeland-Letter to Mayor and City Commission

### ISSUE THREAD

**Issue by bluegirl20** [defund12/defund12.org#1271]
To: william.muntz@lakelandgov.net;citycommission@lakelandgov.net
 
Subject: [Type Subject here]

Dear Mayor Bill Muntz & Lakeland City Commission,
My name is [Name]. I live in [area, neighborhood]. Today I am writing to you to demand that the mayor and the city council adopt a smaller budget for the police department that lends more towards community programs and outreach to keep our community safe. Programs such as housing, education, jobs and healthcare.
The recommended police department budget for 2020 according to the publicly released budget expense report came in at over $45,032,613. This is an astronomical number alone and as well when compared to the budgets of other departments (24%).This budget should have been reallocated and reinvested in the community rather than the militarized police force we have seen clashing with peaceful protestors.
I demand that the City Council begin meaningfully defunding the Lakeland Police Department and reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Lakeland residents.
I call on City Council as well as the mayor to slash this budget, invest in the citizens of Lakeland, and set an example for Polk County, Florida, and for the nation as a whole. With these initiatives, we can lead the nation in a new way that’s been previously unimagined.
Can I count on you to reallocate and reinvest these funds? If not, you can count on me to make sure you are voted out.

Sincerely,
[Name]
[Address]
[email]
[Phone]

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

To: william.muntz@lakelandgov.net;citycommission@lakelandgov.net

Message:

Dear Mayor Bill Muntz & Lakeland City Commission,

My name is [YOUR NAME]. I live in [AREA, NEIGHBORHOOD]. Today I am writing to you to demand that the Mayor and the City Council adopt a defund the police department and reallocate those funds into community programs that keep our community safe, such as affordable housing, education, jobs and healthcare.

According to the publicly released budget expense report, the recommended police department spending for 2020 came in at over $45,032,613. This is an astronomical number both alone and when compared to the budgets of other departments (24%). This budget should be reallocated and reinvested in the community rather than the militarized police force we have seen clashing with peaceful protestors.

I demand that the City Council begin meaningfully defunding the Lakeland Police Department and reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Lakeland residents.

I call on City Council as well as the mayor to invest in the citizens of Lakeland and set an example for Polk County, Florida, and for the nation as a whole. With these initiatives, we can lead the nation in a new way that’s been previously unimagined.

Can I count on you to reallocate and reinvest these funds? If not, you can count on me to make sure you are voted out.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
i gotcha Lakeland
