### ISSUE TITLE
Letter to council of Newark California 

### ISSUE THREAD

**Issue by nwk2120** [defund12/defund12.org#1293]
[defund nwk pd.docx](https://github.com/defund12/defund12.org/files/4759431/defund.nwk.pd.docx)
[defund nwk pd.docx](https://github.com/defund12/defund12.org/files/4759433/defund.nwk.pd.docx)

**Comment by todd-m** [comment]
Thanks for the citations, @skullface! @nwk2120, I made some edits for length, but I think your core points are still represented. If you think I missed anything, just respond on this issue.

Dear Councilmembers,

My name is [YOUR NAME] and I am a [RESIDENT &/or EMPLOYEE] of Newark, California. I am writing to urge you to reconsider the unjust allocation of public funds to the police department over social programs and resources that support critical community needs. Research across various communities in the U.S. has shown that policing does not improve the safety and well-being of residents. For example, one recent study in New York City found that living in a neighborhood with heavy policing may affect one’s mental health [1]. Another found that when police officers went on strike, crime did not increase [2]. Communities do not thrive when they have the most police officers or the most spending on their police department, but rather when their residents have sufficient resources and support.

Reading the city budget for FY 19-20 and proposed FY 20-21, I am appalled that 42% of the budget goes to police expenditures: $23.4M of the city's $55.7M budget. Meanwhile, only .3% or $193,000 goes to the Newark Library, $603,600 to Licensed Child Care, $520,700 to Senior Activities, $247,000 to Paratransit Services, $834,700 to Street Repairs and $2M to Park & Landscape Maintenance, with just $1.2M earmarked for General Recreation. Additionally, according to the 2019 CARF report, only $5.8M went to Community Development and just $965,329 was used for Recreation and Community Services. No money is invested in Art for Public Places.

Meanwhile, $180,000 is set aside for three patrol vehicles, $30,000 for bulletproof vests and $13,000 for SWAT rifles. Clearly, disproportionate sums of money are being allocated to policing, sending the message that our community is viewed as a "dangerous neighborhood" by our elected officials.

The educational needs of Newark's nearly 6,000 public school students must be prioritized over policing. Funds that could go to Newark schools are instead being allocated to truancy and delinquency programs. School Resource Officers should be completely removed from the budget with those funds allocated to non-police staff, such as school counselors or therapists, to address students’ most pressing needs.

Many residents have experienced firsthand the rapid increase in Newark's cost of living, with skyrocketing prices in rental housing and home ownership. Yet within the budget objectives, there is no mention of affordable housing for residents at risk of displacement. Decreasing police department expenditures would allow for the creation of more affordable housing. 

I demand a budget that adequately and effectively meets the needs of at-risk Newark residents during this trying and uncertain time when livelihoods are on the line. I demand a budget that supports our community’s well-being, rather than one that disparately empowers police.

It is your duty to represent your constituents. I am urging you to meaningfully revise the Newark city budget for 2020-2021 fiscal year and for all future budgets.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] Sewell, Abigail A., Kevin A. Jefferson, and Hedwig Lee. 2016. “Living under Surveillance: Gender, Psychological Distress, and Stop-Question-and-Frisk Policing in New York City.” Social Science & Medicine 159:1–13.
[2] Sullivan, Christopher M., and Zachary P. O’Keeffe. 2017. “Evidence That Curtailing Proactive Policing Can Reduce Major Crime.” Nature Human Behaviour 1(10):730–37.
