### ISSUE TITLE
Syracuse, NY - Letter to Mayor and City Council Members

### ISSUE THREAD

**Issue by cusechange** [defund12/defund12.org#1294]
Letter to Syracuse Mayor and Council Members 

Subject: [***INSERT UNIQUE SUBJECT LINE***]

**IMPORTANT**: [Don’t forget to replace the [x]’s with your information]

**TEMPLATE** -

To the Syracuse Common Council and to Mayor Ben Walsh, 

Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Syracuse Police Department. 

According to a 2018 U.S. Census Bureau Report, the city of Syracuse was identified as having one of the highest poverty rates in the nation (**31.8%**). It is **necessary** to emphasize that those residents living in poverty are disproportionately Black.

In order to improve communal safety; we **must** publicly recognize that poverty, race, and crime are intersectional systemic issues that disproportionately affect Black Americans. Research shows that a living wage, access to health services, social programs, affordable housing, as well as employment and educational opportunities are more **effective** and cost-efficient at promoting public safety than policing and imprisonment.

Yet, despite our staggeringly high poverty rate, and the known racial disparities regarding poverty, the City of Syracuse’s Budget continues to fund its’ Police Department at an **increased** rate which amounts to more than all of these effective community-enriching departments **combined**. 

For example, the Syracuse Police Budget proposed for 2021 is set to be increased to an approximate **$49,416,893**. Meanwhile, Departments with the ability to directly promote communal safety are **underfunded**. I request you to consider that instead of inflated funding for the Police, this money from our proposed 2021 budget should be used more effectively through **increased** funding for:

- **“Department of Neighborhood Business Development”**, which works to ensure safe and affordable housing for the community. This department received a **decrease** in proposed funding for 2021 from **$539,992** to **$488,192**.

- **“Syracuse Opportunity Works”**, which places Syracuse youth into employment-based opportunities prompting the development of basic work and interpersonal skills. This Department only received **$61,873** in proposed funding for the 2021 budget. 

- **“Division of Minority Affairs”**, which helps promote women and minority businesses in our community. This department only received **$90,582** in proposed funding.

- **“Division of Recreation and Youth Programs”**, responsible for all public programs in the City of Syracuse which includes physical, social, cultural, and creative programs for all ages. This department only received **$3,979,706** in proposed funding.

The funding for these departments combined comprises approximately **$4,620,353**, making up only **1.8%** of proposed 2021 budget spending, compared with the **19%** of budget spending allotted to the Syracuse Police Department. Not only is this spending gap an **irresponsible** and **ineffective** use of constituent’s tax dollars, but it is also **counterintuitive** to the goal of promoting public safety in our community. Public safety measures implemented by police departments often escalate violence and are racially discriminatory towards non-white community members, specifically Black residents. 

The City of Syracuse has already identified at least **8 million dollars** in savings by cutting police overtime; I ask that you please consider other funding inefficiencies that exist within the police department. This funding could then be redistributed to departments who are **effective** in enacting meaningful change in our community. 

Furthermore, I demand an intentional redistribution of police department funds towards providing our community members with better access to affordable housing, neighborhood development, social programs, as well as employment and educational opportunities. **Only** when you implement this **priority shift** in funding will you ensure, as **elected** representatives of our community, that you are **truthfully** moving towards building a safer and healthier community for **all**. 

Thank you for your courtesies, 
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Syracuse Legislative Emails:
mayor@syrgov.net
ContactEX@ongov.net
hhudson@syrgov.net
kbey@syrgov.net
Mgreene@syrgov.net
TRudd@syrgov.net
rpaniagua@syrgov.net
jcarni@syrgov.net
phogan@syrgov.net
cmajok@syrgov.ne
LAllen@syrgov.net
Jdriscoll@syrgov.net
bfmay6@yahoo.com
kevinholmquist@reagan.com
jjrowley@aol.com
lmcbrid1@twcny.rr.com
tburtis@hotmail.com
davidknapp@ongov.net
dknappmb@aol.com
tassone@twcny.rr.com
kenbushjr@gmail.com
debjcody@gmail.com
cejordan@cnymail.com
julieabbottkenan@gmail.com
wtkinne@gmail.com
marykuhn@ongov.net
mannjr_1983@hotmail.com
cjryan1123@yahoo.com
lindaervin@ongov.ne
peggychase2013@twcny.rr.com
CityHall@SyrGov.net

**Comment by brickaney** [comment]
I’m reviewing.

**Comment by brickaney** [comment]
To: 

Syracuse Legislative Emails:
mayor@syrgov.net
ContactEX@ongov.net
hhudson@syrgov.net
kbey@syrgov.net
Mgreene@syrgov.net
TRudd@syrgov.net
rpaniagua@syrgov.net
jcarni@syrgov.net
phogan@syrgov.net
cmajok@syrgov.ne
LAllen@syrgov.net
Jdriscoll@syrgov.net
davidknapp@ongov.net
cejordan@cnymail.com
marykuhn@ongov.net
lindaervin@ongov.ne
peggychase2013@twcny.rr.com
CityHall@SyrGov.net

Subject: [INSERT UNIQUE SUBJECT LINE]

IMPORTANT: [Don’t forget to replace the [x]’s with your information]

TEMPLATE -

To the Syracuse Common Council and to Mayor Ben Walsh,

Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Syracuse Police Department.

According to a 2018 U.S. Census Bureau Report, the city of Syracuse was identified as having one of the highest poverty rates in the nation (31.8%) [1]. It is necessary to emphasize that those residents living in poverty are disproportionately Black.

In order to improve communal safety; we must publicly recognize that poverty, race, and crime are intersectional systemic issues that disproportionately affect Black Americans. Research shows that a living wage, access to health services, social programs, affordable housing, as well as employment and educational opportunities are more effective and cost-efficient at promoting public safety than policing and imprisonment.

Yet, despite our staggeringly high poverty rate, and the known racial disparities regarding poverty, the City of Syracuse’s Budget continues to fund its’ Police Department at an increased rate which amounts to more than all of these effective community-enriching departments combined.

For example, the Syracuse Police Budget proposed for 2021 is set to be increased to an approximate $49,416,893 [2]. Meanwhile, Departments with the ability to directly promote communal safety are underfunded. I request you to consider that instead of inflated funding for the Police, this money from our proposed 2021 budget should be used more effectively through increased funding for:

“Department of Neighborhood Business Development”, which works to ensure safe and affordable housing for the community. This department received a decrease in proposed funding for 2021 from $539,992 to $488,192 [2].

“Syracuse Opportunity Works”, which places Syracuse youth into employment-based opportunities prompting the development of basic work and interpersonal skills. This Department only received $61,873 in proposed funding for the 2021 budget [2].

“Division of Minority Affairs”, which helps promote women and minority businesses in our community. This department only received $90,582 in proposed funding [2].

“Division of Recreation and Youth Programs”, responsible for all public programs in the City of Syracuse which includes physical, social, cultural, and creative programs for all ages. This department only received $3,979,706 in proposed funding [2].

The funding for these departments combined comprises approximately $4,620,353, making up only 1.8% of proposed 2021 budget spending, compared with the 19% of budget spending allotted to the Syracuse Police Department [2]. Not only is this spending gap an irresponsible and ineffective use of constituent’s tax dollars, but it is also counterintuitive to the goal of promoting public safety in our community. Public safety measures implemented by police departments often escalate violence and are racially discriminatory towards non-white community members, specifically Black residents.

The City of Syracuse has already identified at least 8 million dollars in savings by cutting police overtime; I ask that you please consider other funding inefficiencies that exist within the police department. This funding could then be redistributed to departments who are effective in enacting meaningful change in our community.

Furthermore, I demand an intentional redistribution of police department funds towards providing our community members with better access to affordable housing, neighborhood development, social programs, as well as employment and educational opportunities. Only when you implement this priority shift in funding will you ensure, as elected representatives of our community, that you are truthfully moving towards building a safer and healthier community for all.

Thank you for your courtesies,
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] https://www.census.gov/quickfacts/syracusecitynewyork
[2] http://www.syrgov.net/uploadedFiles/Departments/Budget/Content/Book_ProposedBudget%202020-2021.pdf

**Comment by cusechange** [comment]
Do I need to change the label or is this all set?
