### ISSUE TITLE
Add Millbrae, CA

### ISSUE THREAD

**Issue by Megdav19** [defund12/defund12.org#1308]
Email addresses: rholober@ci.millbrae.ca.us; aschneider@ci.millbrae.ca.us; aoliva@ci.millbrae.ca.us; gpapan@ci.millbrae.ca.us; waynejlee@ci.millbrae.ca.us

Mayor Reuben D. Holober, Vice Mayor Ann Schneider, Councilmember Anne Oliva, Councilmember Gina Papan and Councilmember Wayne Lee,

My name is [YOUR NAME], and I am a resident of Millbrae. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

Given the recent agreement to closure of the Millbrae Sheriff's Office and contract with the San Mateo County Sheriff's Office, it is your responsibility to advocate for change within the SMCSO, an institution that continues to perpetuate systemic racism. The San Mateo County Sheriff's Office's recommended budget for FY 2020-2021 calls for a $10.6 million dollar increase. 

There is not just a need for police reform, but police defunding, because the underlying culture of the police force is build upon racism and inequity. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to re-imagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, demilitarization of our forces, and reallocation of funds from police to behavioral health crisis response and community-led health and safety strategies. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

It is your duty to represent your constituents. I am urging you to support defunding the police for the 2020-2021 fiscal year, so that we can invest more in social and human services to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

Copied from defund12.org

**Comment by wendywx** [comment]
edits in bold:

----------------------------------------------------------------

Email addresses: rholober@ci.millbrae.ca.us; aschneider@ci.millbrae.ca.us; aoliva@ci.millbrae.ca.us; gpapan@ci.millbrae.ca.us; waynejlee@ci.millbrae.ca.us

**To** Mayor Reuben D. Holober, Vice Mayor Ann Schneider, Councilmember Anne Oliva, Councilmember Gina Papan, and Councilmember Wayne Lee,

My name is [YOUR NAME], and I am a resident of Millbrae. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. **I am demanding** real change be made to the way this city allocates its resources.

Given the agreement to closure of the Millbrae Sheriff's Office and contract with the San Mateo County Sheriff's Office, it is your responsibility to advocate for change within the SMCSO, an institution that continues to perpetuate systemic racism. The San Mateo County Sheriff's Office's recommended budget for FY 2020-2021 calls for a $10.6 million dollar increase **[1]**. **This comes during a year when Millbrae's spending is "projected to reach $32.1 million in the upcoming budget, despite cutting spending in the Department of Public Works from $10.4 million in the current fiscal year to $4.5 million in FY 2020-21" [2].** 

There is not just a need for police reform, but police defunding, because the underlying culture of the police force is buil**t** upon racism and inequity. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate, **according to the results of a 2015 survey by the Police Executive Research Forum**. They are not trained or equipped to react to the vast majority of crises. Phillip McHarris, **a** doctoral candidate focusing on race, argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, **and** mental health cases. Policies to “improve the police” are not enough, as ther**e i**s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing **[3]**. We need to re-imagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

**I** demand *the City Council to immediately freeze* budget increases to the **Millbrae Police Bureau**, **demilitarize** our forces, and **reallocate** funds from police to behavioral health crisis response and community-led health and safety **initiatives**. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons **[4]**.

It is your duty to represent your constituents. I am urging you to support defunding the police for the 2020-2021 fiscal year, so that we can invest more in social **programs and resources**. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Sources:
[1] San Mateo County FY 2020-21 Recommended Budget - https://cmo.smcgov.org/sites/cmo.smcgov.org/files/documents/files/FY%202020-21%20Recommended%20Budget_0.pdf
[2] San Mateo Daily Journal - https://www.smdailyjournal.com/news/local/millbrae-eyes-budget-blow/article_5ea64608-a3b3-11ea-8596-ab4ff9270a49.html
[3] Urban Institute - https://www.urban.org/sites/default/files/publication/100705/learning_to_build_police-community_trust_3.pdf
[4] Center for Popular Democracy - https://populardemocracy.org/sites/default/files/Freedom%20To%20Thrive%2C%20Higher%20Res%20Version.pdf**

--------------------------------------------

I removed "recent" in "Given the recent agreement to closure of the Millbrae Sheriff's Office" because the [announcement](https://www.ci.millbrae.ca.us/Home/Components/News/News/205/) shows that "On Sunday, March 4, 2012, the San Mateo County Sheriff's Office will begin providing law enforcement services for the City of Millbrae."
Added some additional statistics as well as per https://www.smdailyjournal.com/news/local/millbrae-eyes-budget-blow/article_5ea64608-a3b3-11ea-8596-ab4ff9270a49.html and updated the sources to cite the original research studies.
Also revised sentences to be first person and removed the hashtags as per [email style guildelines](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md) 

Marking this as ready for PR.
