### ISSUE TITLE
Salem Virginia Defund Police template

### ISSUE THREAD

**Issue by jabbarwocky** [defund12/defund12.org#1311]
[SALEM VA TEMPLATE.docx](https://github.com/defund12/defund12.org/files/4760300/SALEM.VA.TEMPLATE.docx)

To: rfoley@salemva.gov jjohnson@salemva.gov bjones@salemva.gov   jmartin@salemva.gov jsaunders@salemva.gov 

Subject: I Demand Divestment from Police and an Investment in Black Communities 🔗

Message (Don't forget to replace the [x]'s with your information!) 🔗

Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].
I DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:
Vote no on all increases to police budgets
Vote yes to decrease police spending and budgets
Vote yes to increase spending on Health care, education and community programs that keep us safe.
Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police, Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia, Breonna Taylor an EMT killed while asleep in her bed in Louisville, KY, Dreasjon Reed in Indianapolis and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.
At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus,with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors.
It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.
The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs”.
Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the US census, Salem is nearly 90% White alone and 7.7% Black or African American. Our community needs to support everyone and at the moment, it is not a safe space for people of color and especially Black individuals who are facing white supremacy and systemic racism still present in our world, and very present in Salem City. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer. Police do not belong in our communities and especially not in our schools. 
The Salem city police budget for the fiscal year 2020-2021 has police spending at a total of $6,122,993. From the 2019 budget to the proposed 2021 budget, Salem is increasing police spending by over half a million dollars ($616,988). The proposed 2021 police budget is at $6,122,993, increasing from 2020 by $212,005. There is also an increase in Detention and Correction. Cuts to the farmers market, and the library will all have lasting negative impacts on our community. Substantial cuts are being made in Community Development, Parks, Recreation, and Culture, and Non-departmental expenditures. These areas could use more funding instead. 
I am demanding a defunding of the Salem police. This means Salem divesting and investing: diverting the money to areas disproportionately affected by poverty and lack of infrastructure. This mean redirecting resources into community-based initiatives: helping local grassroots groups that have been doing work in those areas and know how to engage with their communities. This means implementing non-police solutions to social problems in Roanoke: Affordable housing, affordable, accessible, and adequate mental and physical healthcare, employment, education. Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, hiring mental health professionals and education professionals, to childcare, to support a vibrant Black future. The possibilities are endless.
These are all safety issues. Instead of punitive or criminalized, restorative and supportive community measures can address these issues. I call for more counselors, after-school programs, trauma services, anti-violence programs. I do not call for police reform, I instead call for defunding, divestment, and reinvestment into the community we all care for. 
I join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And I call for the end to police terror in Salem. I hope to see you do the same.
Sincerely, The People of Salem, Virginia
[NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

To: rfoley@salemva.gov jjohnson@salemva.gov bjones@salemva.gov jmartin@salemva.gov jsaunders@salemva.gov

Subject: I Demand Divestment from Police and an Investment in Black Communities 🔗

Message (Don't forget to replace the [x]'s with your information!) 🔗

Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].

I DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:
- Vote no on all increases to police budgets.
- Vote yes to decrease police spending and budgets.
- Vote yes to increase spending on health care, education and community programs that keep us safe.

Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police, Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia, Breonna Taylor, an EMT killed while asleep in her bed in Louisville, KY, Dreasjon Reed in Indianapolis, and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.

At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus,with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors.

It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.

The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs.”

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the US census, Salem is nearly 90% White alone and 7.7% Black or African American. Our community needs to support everyone and at the moment, it is not a safe space for people of color and especially Black individuals who are facing white supremacy and systemic racism still present in our world, and very present in Salem City. 

According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer. Police do not belong in our communities and especially not in our schools.

The Salem city police budget for the fiscal year 2020-2021 has police spending at a total of $6,122,993. From the 2019 budget to the proposed 2021 budget, Salem is increasing police spending by over half a million dollars ($616,988). The proposed 2021 police budget is at $6,122,993, increasing from 2020 by $212,005. There is also an increase in Detention and Correction. Cuts to the farmers market and the library will all have lasting negative impacts on our community. Substantial cuts are being made in Community Development, Parks, Recreation, and Culture, and Non-departmental expenditures. These areas could use more funding instead.

I am demanding a defunding of the Salem police. This means Salem divesting and investing: diverting the money to areas disproportionately affected by poverty and lack of infrastructure. This mean redirecting resources into community-based initiatives: helping local grassroots groups that have been doing work in those areas and know how to engage with their communities. This means implementing non-police solutions to social problems in Salem: Affordable housing, affordable, accessible, and adequate mental and physical healthcare, employment, education. Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, hiring mental health professionals and education professionals, to childcare, to support a vibrant Black future. The possibilities are endless.

These are all safety issues. Instead of punitive measures or criminalization, restorative and supportive community measures can address these issues. I call for more counselors, after-school programs, trauma services, anti-violence programs. I do not call for police reform, I instead call for defunding, divestment, and reinvestment into the community we all care for.

I join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And I call for the end to police terror in Salem. I hope to see you do the same.

Sincerely, 
[NAME] 
[PHONE_NUMBER] 
[EMAIL] 
[ADDRESS]
