### ISSUE TITLE
Roanoke Virginia, Defund ROA Police Template

### ISSUE THREAD

**Issue by jabbarwocky** [defund12/defund12.org#1312]
[ROANOKE VA TEMPLATE.docx](https://github.com/defund12/defund12.org/files/4760308/ROANOKE.VA.TEMPLATE.docx)

ROANOKE VA TEMPLATE
To: sherman.lea@roanokeva.gov michelle.dykstra@roanokeva.gov  ‎ joseph.cobb@roanokeva.gov  bill.bestpitch@roanokeva.gov  djuna.osborne@roanokeva.gov  trish.white-boyd@roanokeva.gov  anita.price@roanokeva.gov  

Subject: I Demand Divestment from Police and an Investment in Black Communities 🔗

Message (Don't forget to replace the [x]'s with your information!) 🔗
	
Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].
I demand:
Vote no on all increases to police budgets
Vote yes to decrease police spending and budgets
Vote yes to increase spending on Health care, education and community programs that keep us safe.
Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police, Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia, Breonna Taylor an EMT killed while asleep in her bed in Louisville,KY, Dreasjon Reed in Indianapolis and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.
At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus, with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors.
It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.
The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs”.
Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. The Roanoke city police budget for the fiscal year 2020-2021 has police spending at a total of $21,620,936. The police spending increased from fiscal year 2019-2020 to 2020-2021 by $489,426. They are spending 12,408,432 on police patrol. More money is going into our police than into the “Livability” sector. I am seeing substantial cuts in “Non-departmental” and “Outside Agencies” including small organizations such as the arts. Where our money goes matters.
I no longer want to see the police budget rise and community and public institutions paying the price. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer. Police do not belong in our communities and especially not in our schools. What I ask for includes fewer patrols, reducing unnecessary civilian-police interaction, taking police out of schools, demilitarizing the tools and weapons that the police are equipped with. 
I am demanding a defunding of the Roanoke police. This means divesting and investing: diverting the money to areas disproportionately affected by poverty and lack of infrastructure. This means redirecting resources into community-based initiatives: helping local grassroots groups that have been doing work in those areas and know how to engage with their communities. This means implementing non-police solutions to social problems in Roanoke: Affordable housing, affordable, accessible, and adequate mental and physical healthcare, employment, education. Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, hiring mental health professionals and education professionals, to childcare, to support a vibrant Black future. The possibilities are endless.
These are all safety issues. Instead of punitive or criminalized, restorative and supportive community measures can address these issues. I call for more counselors, after-school programs, trauma services, anti-violence programs. I do not call for police reform, I instead call for defunding, divestment, and reinvestment into the community we all care for. 
I join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And I call on you to end police terror in Roanoke. 
Sincerely, The People of Roanoke, Virginia
[NAME] [PHONE_NUMBER] [EMAIL] [HOME/LIVING ADDRESS]

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

To: sherman.lea@roanokeva.gov michelle.dykstra@roanokeva.gov ‎ joseph.cobb@roanokeva.gov bill.bestpitch@roanokeva.gov djuna.osborne@roanokeva.gov trish.white-boyd@roanokeva.gov anita.price@roanokeva.gov

Subject: I Demand Divestment from Police and an Investment in Black Communities 🔗

Message (Don't forget to replace the [x]'s with your information!) 🔗

Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].

I demand that you, my local officials, will:
- Vote no on all increases to police budgets
- Vote yes to decrease police spending and budgets
- Vote yes to increase spending on Health care, education and community programs that keep us safe.

Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police, Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia, Breonna Taylor, an EMT killed while asleep in her bed in Louisville,KY, Dreasjon Reed in Indianapolis, and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.

At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus, with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors.

It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.

The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs.”

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. 

The Roanoke city police budget for the fiscal year 2020-2021 has police spending at a total of $21,620,936. The police spending increased from fiscal year 2019-2020 to 2020-2021 by $489,426. They are spending $12,408,432 on police patrol. More money is going into our police than into the “Livability” sector. I am seeing substantial cuts in “Non-departmental” and “Outside Agencies” including small organizations such as the arts. Where our money goes matters.
I no longer want to see the police budget rise and community and public institutions paying the price. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer. Police do not belong in our communities, and especially not in our schools. What I ask for includes fewer patrols, reducing unnecessary civilian-police interaction, taking police out of schools, and demilitarizing the tools and weapons that the police are equipped with.

I am demanding a defunding of the Roanoke police. This means divesting and investing: diverting the money to areas disproportionately affected by poverty and lack of infrastructure. This means redirecting resources into community-based initiatives: helping local grassroots groups that have been doing work in those areas and know how to engage with their communities. This means implementing non-police solutions to social problems in Roanoke: affordable housing, affordable, accessible, and adequate mental and physical healthcare, employment, and education. Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to hiring mental health professionals and education professionals, to childcare, to support a vibrant Black future. The possibilities are endless.

These are all safety issues. Instead of punitive measures or criminalization, restorative and supportive community measures can address these issues. I call for more counselors, after-school programs, trauma services, and anti-violence programs. I do not call for police reform. I instead call for defunding, divestment, and reinvestment into the community we all care for.

I join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And I call on you to end police terror in Roanoke.

Sincerely, 
[NAME] 
[PHONE_NUMBER] 
[EMAIL] 
[HOME/LIVING ADDRESS]

**Comment by todd-m** [comment]
on it
