### ISSUE TITLE
Columbia, SC - letter to Mayor and City Council Members

### ISSUE THREAD

**Issue by daliadalili** [defund12/defund12.org#1317]
skbenjamin@columbiasc.net, shalaine.archie@columbiasc.gov, sam.davis@columbiasc.gov, tidevine@jilawfirm.com, Howard.Duvall@columbiasc.gov, Edward.McDowell@columbiasc.gov, djrickenmann@Columbiasc.gov, Will.Brennan@columbiasc.gov

Subject: Defunding the North Charleston Police Department

Message:
Dear Mayor Benjamin and Columbia City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Columbia City Police department and invest them into social services that would directly improve the well-being of Columbia citizens.

The budget for 2019 was $40,165,765, and the budget for 2020 is $42,366,353. This is almost a 6% increase from 2019 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the city of Columbia’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Columbia City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Rtrott** [comment]
Reviewing now!

**Comment by Rtrott** [comment]
skbenjamin@columbiasc.net; shalaine.archie@columbiasc.gov; sam.davis@columbiasc.gov ;tidevine@jilawfirm.com; Howard.Duvall@columbiasc.gov; Edward.McDowell@columbiasc.gov; djrickenmann@Columbiasc.gov; Will.Brennan@columbiasc.gov;

Subject: [ INSERT UNIQUE SUBJECT LINE]

Message:
Dear Mayor Benjamin and Columbia City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Columbia City Police department and invest them into social services that would directly improve the well-being of Columbia citizens.

The general fund budget for the CPD in 2019 was $40,165,765, and the budget for 2020 is $42,366,353. This is almost a 6% increase from 2019 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the city of Columbia’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Columbia City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
