### ISSUE TITLE
Email to Peoria, IL City Council about Police Department

### ISSUE THREAD

**Issue by lilmura** [defund12/defund12.org#1321]
To: rali@peoriagov.org, bjensen@peoriagov.org, sruckriegel@peoriagov.org, zoyler@peoriagov.org, jkelly@peoriagov.org 

Subject: [***INSERT UNIQUE SUBJECT LINE ***]

Message: (Don’t forget to replace the [ ]’s with your information!)

Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Peoria’s inordinate investment in the Peoria Police Department (PPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests many Peoria residents are dismayed by the current conduct of the Peoria Police. 

I am therefore writing to demand that the City Council vote to reapportion funds allocated to the PPD to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is concerning that the Peoria Police department on their website promotes “broken window’ policing which has been used to target African- Americans and has been shown to be ineffective at deterring crime. It is morally reprehensible to dedicate 44% of the budget towards “ Public Safety”, with 22% of the budget going to policing alone, while funding for the arts (9% of total budget), neighborhood livability (8%), and environmental health (17%) has been neglected. 

I also urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Peoria without consequence.

People are marching in the streets because they know that these actions will result in a healthier, safer, more just society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by aurendisson** [comment]
reviewing now!

**Comment by aurendisson** [comment]
Editing notes: 
I added more email addresses per the Board of Trustees list here: https://www.peoriatownship.com/officials. 
"Broken window" policing on the PPD website confirmed here: http://www.peoriagov.org/peoria-police-department/ 
I edited to emphasize the call for defunding.

Email needs work notes:
I couldn't confirm the stats provided in this email. I'm new to this, so please advise! 
Should we consider that the city is reducing the public safety budget already? http://www.peoriagov.org/content/uploads/2015/10/Peoria-2019-Revised-Budget_factsheet_1542142185_add.pdf 


To: rali@peoriagov.org, bjensen@peoriagov.org, cgrayeb@peoriagov.org, dcyr@peoriagov.org, dmoore@peoriagov.org, jardis@peoriagov.org, jkelly@peoriagov.org, jmontelongo@peoriagov.org, sruckriegel@peoriagov.org, triggenbach@peoriagov.org, zoyler@peoriagov.org, 

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]

Dear Peoria City Council members,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Peoria’s inordinate investment in the Peoria Police Department (PPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests, many Peoria residents are dismayed by the current conduct of the Peoria police.

I am therefore writing to demand that the City Council vote to defund the PPD and reapportion those funds to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is concerning that the PPD on their website promotes "broken window" policing, which has been used to target Black Americans and has been shown to be ineffective at deterring crime. It is morally reprehensible to dedicate 44% of the budget towards “Public Safety,” with 22% of the budget going to policing alone, while funding for the arts (9% of total budget), neighborhood livability (8%), and environmental health (17%) have been neglected.

I also urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Peoria without consequence.

People are marching in the streets because they know that these actions will result in a healthier, safer, more just society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@lilmura could you provide the sources used for the data in the email? Thanks so much

**Comment by lilmura** [comment]
Here is where I got the data about the 2020 budget: http://www.peoriagov.org/2020-budget-information/

**Comment by lilmura** [comment]
Is there anything else I need to do?

**Comment by mahrer** [comment]
@lilmura I think we're good! I'm going to review this now so that we can go ahead and approve it.

**Comment by mahrer** [comment]
Edited slightly to remove "crime" language:

---

To: rali@peoriagov.org, bjensen@peoriagov.org, cgrayeb@peoriagov.org, dcyr@peoriagov.org, dmoore@peoriagov.org, jardis@peoriagov.org, jkelly@peoriagov.org, jmontelongo@peoriagov.org, sruckriegel@peoriagov.org, triggenbach@peoriagov.org, zoyler@peoriagov.org,

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]

Dear Peoria City Council members,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Peoria’s inordinate investment in the Peoria Police Department (PPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests, many Peoria residents are dismayed by the current conduct of the Peoria police.

I am therefore writing to demand that the City Council vote to defund the PPD and reapportion those funds to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens. It is concerning that the PPD on their website promotes "broken window" policing, which has been used to target Black Americans and has been shown to be ineffective at keeping our communities safe. It is morally reprehensible to dedicate 44% of the budget towards “Public Safety,” with 22% of the budget going to policing alone, while funding for the arts (9% of total budget), neighborhood livability (8%), and environmental health (17%) have been neglected.

I also urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Peoria without consequence.

People are marching in the streets because they know that these actions will result in a healthier, safer, more just society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by lilmura** [comment]
@mahrer Those percentages that you used in the email are not consistent with the numbers used in the official Budget report shown here:
![0D91AAFE-7E67-4BF1-BEAE-4EA3E7A7A770](https://user-images.githubusercontent.com/66742452/84691289-850cda80-af09-11ea-802f-251194a3d3e6.png)
![646419A6-BD92-4EDB-815F-9A47A3F45F76](https://user-images.githubusercontent.com/66742452/84691290-85a57100-af09-11ea-9d19-bc77dfbf65bf.png)
![C04F7890-3BED-4E31-B9B6-EFC79A1B72C9](https://user-images.githubusercontent.com/66742452/84691292-85a57100-af09-11ea-87a3-36942c5dfd9c.png)
![39E18D4C-46DF-44B2-9033-990EAE038D8F](https://user-images.githubusercontent.com/66742452/84691293-863e0780-af09-11ea-93e5-091ac7f97f25.png)

**Comment by rpalakkal** [comment]
on it

**Comment by todd-m** [comment]
on it

**Comment by littleseeds** [comment]
@lilmura I'm going to go ahead and update the numbers back to the originals.(@mahrer did you see other numbers?) Thanks!

**Comment by mahrer** [comment]
@littleseeds yes actually, a new issue was opened at #1600 and the issue taken care of :) Thanks for checking in.
