### ISSUE TITLE
Mt. Pleasant, SC - letter to Mayor and Town Council Members

### ISSUE THREAD

**Issue by daliadalili** [defund12/defund12.org#1324]
councilclk@tompsc.com

Subject: Defunding the Mount Pleasant Police Department

Message:
Dear Mayor Haynie and Mount Pleasant Town Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Mt. Pleasant Police department and invest them into social services that would directly improve the well-being of Mt. Pleasant citizens.

The budget for 2018 was $15,188,275, and the budget for 2020 is $17,253,001. This is almost a 14% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the town of Mt. Pleasant’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Mount Pleasant Town Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

councilclk@tompsc.com

Subject: Defunding the Mount Pleasant Police Department

Message:
Dear Mayor Haynie and Mount Pleasant Town Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Mt. Pleasant Police department and invest them into social services that would directly improve the well-being of Mt. Pleasant citizens.

The police department budget for 2018 was $15,188,275, and the budget for 2020 is $17,253,001. This is almost a 14% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the town of Mt. Pleasant’s budget be better spent on quality of life for all. In particular, for those in our Black, Indigenous, and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Mount Pleasant Town Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
