### ISSUE TITLE
Add Novato, CA to your list

### ISSUE THREAD

**Issue by lanaw** [defund12/defund12.org#1326]
Please send this email to:
novatocouncil@novato.org, dathas@novato.org, peklund@novato.org, elucan@novato.org,  apeele@novato.org, swernick@novato.org. 

"Dear Novato City Leaders,

I am writing to you today out of great concern for our community and our future. I am [INSERT IDENTIFYING INFO BUT ONLY AS MUCH AS YOU FEEL COMFORTABLE WITH INCLUDING THE AMOUNT OF TIME YOU’VE BEEN A RESIDENT OF SR, WHERE YOU WORK, IF YOU’RE A LOCAL BUSINESS OWNER, ANY OTHER COMMUNITY TIES LIKE FAITH COMMUNITY OR OTHER COMMUNITY-BASED ORGS]

As Black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor, an EMT killed by officers while asleep in her bed in Louisville. Their names are added to a devastatingly long list of Black people who have been killed at the hands of law enforcement—it is time for us to make different decisions, because what we've done so far is NOT working. Police reforms, such as the Obama administration's or 8 Can't Wait, are NOT enough. Why? Because we can't reshape an institution that is historically and fundamentally racist, especially in one of the most racially disparate counties in the country. We demand change in the operation of the criminal legal system, we demand that we take care of our community instead of criminalizing those amongst us who need help, and we demand that police are not the front line responders to every emergency or call for help. 

In Novato, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. I am writing to you today to demand that the Novato City Council invest in alternative responses to law enforcement that keep our community safe and healthy. 

Increasingly, the United States has responded to every emergency or call for help with law enforcement. Meanwhile, our communities desperately lack meaningful access to healthcare, employment, and housing. Rather than fixing these societal issues, we expect the police to solve them. And how do they do this? They criminalize the homeless so that you don't have to house them. They criminalize substance abuse and drug addiction so you don't have to address our public health problem. They criminalize the mentally ill so that you don't have to face our mental health crisis. They criminalize the poor so that you don't have to address wealth inequality (a direct result of the decades of segregation and racist policies in Marin). In Marin, according to Race Counts data, black people are 14 times more likely to be incarcerated than white people. Black minors are 11 times more likely to be arrested for a status offense than white minors. The Sausalito Marin City School District was hit with California's first desegregation order in 50 years. Novato, we are no less guilty of systemic racism than any other city. 

We have the largest military budget in the world, and some of the most well-funded and militarized police departments. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, while funding for public health has decreased every year. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion. A 220 percent increase. In Novato, funding for local police makes up 42% of the city budget. Housing and community services accounts for only 1%. That is a staggering and illuminating statistic. What does it say about our community? It says that rather than responding to the needs in our community with meaningful support and resources, we respond with more funds to law enforcement. This is unacceptable. Where could that money go? It could go towards building additional housing for low-income residents, helping the homeless with mental health services and providing access to shelter, to education, to childcare or after school programs for families who cannot meet the financial needs, or to organizations/programs that support BIPOC in Novato. The possibilities are endless. The safest communities don't have the most cops; they have the most resources.

Therefore, we demand the following: A reduction in funding for police in the Novato City budget, and instead invest more in housing and community services. Investment in local alternatives to policing. This should include investments in existing community based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including: Unarmed mediation and intervention teams, Social worker teams and mental health experts, as well as Restorative Justice programs. We further request that an emergency meeting of the full city council be immediately scheduled to address these concerns. You are welcome to contact me with any questions or concerns regarding these requests.

Regards,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]"

**Comment by lanaw** [comment]
Hi! Just checking on the status of this request.

**Comment by mahrer** [comment]
Hey @lanaw! Thanks for checking in. We've been a bit delayed lately and appreciate your patience. I'll review this request now.

**Comment by mahrer** [comment]
Edited slightly below. 

Send to:
novatocouncil@novato.org, dathas@novato.org, peklund@novato.org, elucan@novato.org, apeele@novato.org, swernick@novato.org.
Message:

Dear Novato City Leaders,

I am writing to you today out of great concern for our community and our future. My name is [YOUR NAME] and I am [INSERT IDENTIFYING INFO BUT ONLY AS MUCH AS YOU FEEL COMFORTABLE WITH INCLUDING THE AMOUNT OF TIME YOU’VE BEEN A RESIDENT, WHERE YOU WORK, IF YOU’RE A LOCAL BUSINESS OWNER, ANY OTHER COMMUNITY TIES LIKE FAITH COMMUNITY OR OTHER COMMUNITY-BASED ORGS].

As Black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor, an EMT killed by officers while asleep in her bed in Louisville. Their names are added to a devastatingly long list of Black people who have been killed at the hands of law enforcement—it is time for us to make different decisions, because what we've done so far is NOT working. Police reforms, such as the Obama administration's or 8 Can't Wait, are NOT enough. Why? Because we can't reshape an institution that is historically and fundamentally racist, especially in one of the most racially disparate counties in the country. I demand change in the operation of the criminal legal system, I demand that we take care of our community instead of criminalizing those amongst us who need help, and I demand that police are not the front line responders to every emergency or call for help.

In Novato, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. I am writing to you today to demand that the Novato City Council invest in alternative responses to law enforcement that keep our community safe and healthy.

Increasingly, the United States has responded to every emergency or call for help with law enforcement. Meanwhile, our communities desperately lack meaningful access to healthcare, employment, and housing. Rather than fixing these societal issues, we expect the police to solve them. And how do they do this? They criminalize the homeless so that you don't have to house them. They criminalize substance abuse and drug addiction so you don't have to address our public health problem. They criminalize the mentally ill so that you don't have to face our mental health crisis. They criminalize the poor so that you don't have to address wealth inequality (a direct result of the decades of segregation and racist policies in Marin). In Marin, according to Race Counts data, black people are 14 times more likely to be incarcerated than white people. Black minors are 11 times more likely to be arrested for a status offense than white minors. The Sausalito Marin City School District was hit with California's first desegregation order in 50 years. Novato, we are no less guilty of systemic racism than any other city.

The United States has the largest military budget in the world, and some of the most well-funded and militarized police departments. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, while funding for public health has decreased every year. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion. A 220 percent increase. 

In Novato, funding for local police makes up 42% of the city budget. Housing and community services accounts for only 1%. That is a staggering and illuminating statistic. What does it say about our community? It says that rather than responding to the needs in our community with meaningful support and resources, we respond with more funds to law enforcement. This is unacceptable. Where could that money go? It could go towards building additional housing for low-income residents, helping the homeless with mental health services and providing access to shelter, to education, to childcare or after school programs for families who cannot meet the financial needs, or to organizations/programs that support Black people, Indigenous people, and People of Color in Novato. The possibilities are endless. The safest communities don't have the most cops; they have the most resources.

Therefore, I demand the following: Reduce funding for police in the Novato City budget, and instead invest more in housing and community services. Invest in local alternatives to policing. This should include investments in existing community based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including: Unarmed mediation and intervention teams, Social worker teams and mental health experts, and Restorative Justice programs. I further request that an emergency meeting of the full city council be immediately scheduled to address these concerns. You are welcome to contact me with any questions or concerns regarding these requests.

Regards,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]
