### ISSUE TITLE
Email For Scotts Valley, CA

### ISSUE THREAD

**Issue by defundsvpd** [defund12/defund12.org#1341]
Emails: rlj12@comcast.net dtimm@scottsvalley.org jdilles@scottsvalley.org dlindslind@earthlink.net jimreedSV@gmail.com tmcfarlane@scottsvalley.org lgrundy@scottsvalley.org 

Dear Scotts Valley City Council and Finance Department,

My name is [insert your name], and I am a resident of Scotts Valley, California. Amidst the recent protests demanding justice for George Floyd, Breonna Taylor, and countless other black Americans, it has become clear that the police are not filling the role that we expect them to. Too many Americans live in fear of the police and the power they have; power which is often abused.
In the age of widespread technology and social media, it has become ever apparent that reforms such as requiring body-cameras have failed to hold our criminal justice system accountable for police brutality. It has come to my attention that the budget for 2021 is being decided as these protests continue. As a resident, I propose that we reallocate the budget away from funding the SVPD and towards programs that will better enrich Scotts Valley. Bigger changes need to be made concerning the role of police in our community and the greater United States; the clearest path towards that is how we spend our money.
The Scotts Valley Police Department has become grossly overfunded, while other issues many citizens face remain unattended to. Too much pressure is put on the police to manage issues they are not equipped to handle. Rather than using the money from the general fund and our tax dollars to enrich our community, it has served to further militarize the Scotts Valley Police Department.
To relieve the pressure of the responsibilities placed on the police department and have funds to invest in the community, there should be cuts made on PR endeavors, surveillance, swat teams, and D.A.R.E. 

For example, public relations for the police department should be about communicating with the community and taking in their input rather than using social media as an advertising opportunity or to further contribute to racial profiling by sharing pictures of criminals on the social media pages. So, what funds currently go towards PR endeavors such as the Facebook page should go towards creating new opportunities for communication amongst the police and the residents within their jurisdiction.     

Moreover, recent developments of surveillance within the criminal investigation have heavily influenced the role of America’s police (much like the growth of social media). Studies have shown that people of color are unequally surveilled and thus more likely to be interrogated or arrested. Rather than spending money on technology that contributes to racism and the mass incarceration of people of color, Scotts Valley should do more work to identify and refuse to tolerate racial prejudice among its police force.    

Another example of misused money is in spending on high tech gear and officers trained for high violence situations. Only 7% percent of crime in Scotts Valley is classified as violent and in an even smaller fraction of those incidents, would the SWAT team’s expertise have been useful. Violent crimes could be reduced more effectively through preventative measures instead. For example, offering support, within our town, to those experiencing domestic abuse or sexual harassment, as well as sponsoring mental wellness programs and positive cultural environments within the individual neighborhoods.   

 Furthermore, the money spent from D.A.R.E should be reinvested into a program run by psychologists and experts in drug addiction who understand the trauma and mental health issues that cause drug abuse. In this way, they would be more capable of fostering open conversations with the youth in our town. Of which are currently inhibited through having an authority figure, trained to arrest and punish drug usage, providing very little space for vulnerability and honesty due to intimidation.     

The Scotts Valley Police Department has become an extremely integral part of our community. However, the bond of trust that binds the Department and our community is endangered by further militarization and the possibility of corruption that comes with augmented power and money. Also, there is a funding crisis currently across many cities in California including Scotts Valley. Many civil servants, such as police rightfully, fear for their jobs and if they will have enough to stay afloat during these trying times. Thus, calls to “defund” are concerning. Yet, this financial uncertainty is exactly why reallocating funds and making sure our tax dollars and general fund are being utilized to their fullest potential is so necessary. What we all want for Scotts Valley is a peaceful and nourishing community, I believe we can uphold those values more completely with the redirection of funding away from the SVPD.          
The Scotts Valley City Council has a responsibility as our governing body to uphold its end of the social contract that promises the protection of its citizens’ rights equally. Without re-evaluating our systems which are heavily susceptible to bias and institutionalized discrimination, many citizens will be left disproportionally behind. Now is the time to join numerous other cities in defunding the police to seek peace through equality and equity.             

Sincerely,
[Your Name] [Your Address] [Your Email] [Your Phone Number]

**Comment by NickCrews** [comment]
Still on it, it's a tricky one...

**Comment by NickCrews** [comment]
Emails: rlj12@comcast.net dtimm@scottsvalley.org jdilles@scottsvalley.org dlindslind@earthlink.net jimreedSV@gmail.com tmcfarlane@scottsvalley.org lgrundy@scottsvalley.org

Dear Scotts Valley City Council and Finance Department,

My name is [YOUR NAME], and I am a resident of Scotts Valley, California. Amidst the recent protests demanding justice for George Floyd, Breonna Taylor, and countless other Black Americans, it has become clear that the police are not filling the role that we expect them to. Too many Americans live in fear of the police and the power they often abuse, and are not benefiting from the "services" they provide. It has become apparent that reforms such as requiring body-cameras are inadequate to hold our criminal justice system accountable for police brutality and other forms of racism. Therefore, I demand further action: Defunding the SVPD in the 2021 budget and reallocating those funds to more effective community programs and preventative measures.

SVPD is overfunded and ineffectual, and often wastes money on programs that foster racism and reduce community involvement. To some degree, how can we blame them? They are expected to manage issues that they are not equipped to handle. Community programs and preventative measures can serve our community better, more safely, and for less money. For example, four programs that particularly need to be reallocated are PR endeavors, surveillance, swat teams, and D.A.R.E.

Public relations for the police department should be about communicating with the community and taking in their input, rather than using social media as an advertising opportunity or to further contribute to racial profiling by sharing pictures of criminals on social media. Therefore, what funds currently go towards PR endeavors should go towards creating new opportunities for the community to directly manage community safety, so that public does not have to take a backseat to the Police.

Moreover, recent developments of surveillance have heavily influenced the role of America’s police (much like the growth of social media). Studies have shown that People of Color are unequally surveilled and thus more likely to be interrogated or arrested. Scotts Valley should not spend money on technology that contributes to racism and the mass incarceration of People of Color.

Another example of misused money is SVPD's spending on high-tech gear and high-violence training. Only 7% percent of crime in Scotts Valley is classified as violent and in an even smaller fraction of those incidents would the SWAT team’s expertise have been useful. Violent crimes are reduced more effectively through preventative measures instead. For example, offering support within our town to those experiencing domestic abuse and sexual harassment, as well as sponsoring mental wellness programs and positive cultural environments within the individual neighborhoods.

Furthermore, the money spent from D.A.R.E should be reinvested into a program run by psychologists and experts in drug addiction. Cops don't understand the trauma and mental health issues that cause drug abuse. Instead, they act as authority figures, trained to arrest and punish drug usage, providing very little space for vulnerability and honesty. Well-funded programs run by drug abuse experts are more capable of fostering open conversations and preventing drug abuse in the first place.

There is a funding crisis currently across many cities in California including Scotts Valley. Many civil servants, including the police, fear for their jobs and if they will have enough to stay afloat during these trying times. Many will say that right now is not the time for "defunding." Yet, this financial uncertainty is exactly why it is so necessary for you to reallocate funds and tax dollars to programs that use them to their fullest potential.

The Scotts Valley City Council has a responsibility as our governing body to uphold its end of the social contract that promises the protection of its citizens’ rights equally. Without re-evaluating our systems which are heavily susceptible to bias and institutionalized discrimination, many citizens will be left disproportionally behind. Now is the time to join numerous other cities in defunding the police to seek peace through equality and equity. Enormous changes need to be made concerning the role of police in our community and the greater United States; the clearest path towards that is how we spend our money.

Sincerely,
[Your Name] [Your Address] [Your Email] [Your Phone Number]

**Comment by defundsvpd** [comment]
This looks great! Thank you so much. I just have one more question... if I look up defund12.org/scottsvalley is this what will show up?

**Comment by NickCrews** [comment]
Let me know what you think @defundsvpd! I tried to make each paragraph be a little more focused on one point it was trying to get across. I tried to keep all of your points in there. I did modify some phrasing that sounded a bit like suggestions of reform to sound more like defunding.

One thing is I would like there to be a bit more evidence that SVPD actually uses surveillance tools

**Comment by defundsvpd** [comment]
I'll look into their official budget rn to see what it says.

**Comment by NickCrews** [comment]
@defundsvpd no, this will not appear yet. We need someone to format this into code and then commit it into the website

**Comment by defundsvpd** [comment]
I just found this on the SVPD website https://www.scottsvalleypd.com/surveillance-cams it looks like it is more so a partnership with local businesses to get security footage, but I'll keep looking for evidence of the traffic cams and surveillance they install and maintain

**Comment by defundsvpd** [comment]
@NickCrews Okay so eventually it will be on a website with that link

**Comment by averymcguirt** [comment]
Looks good! Marking as ready for PR. Just a few changes for sentence clarity.

Emails: rlj12@comcast.net dtimm@scottsvalley.org jdilles@scottsvalley.org dlindslind@earthlink.net jimreedSV@gmail.com tmcfarlane@scottsvalley.org lgrundy@scottsvalley.org

Dear Scotts Valley City Council and Finance Department,

My name is [YOUR NAME], and I am a resident of Scotts Valley, California. Amidst the recent protests demanding justice for George Floyd, Breonna Taylor, and countless other Black Americans, it has become clear that the police are not filling the role that we expect them to. Too many Americans live in fear of the police and the power they often abuse, and are not benefiting from the "services" they provide. It has become apparent that reforms such as requiring body-cameras are inadequate to hold our criminal justice system accountable for police brutality and other forms of racism. Therefore, I demand further action: Defunding the SVPD in the 2021 budget and reallocating those funds to more effective community programs and preventative measures.

SVPD is overfunded and ineffectual, and often wastes money on programs that foster racism and reduce community involvement. To some degree, how can we blame them? They are expected to manage issues that they are not equipped to handle. Community programs and preventative measures can serve our community better, more safely, and for less money. For example, four programs that particularly need to be reallocated are PR endeavors, surveillance, swat teams, and D.A.R.E.

Public relations for the police department should be about communicating with the community and taking in their input, rather than using social media as an advertising opportunity or to further contribute to racial profiling through public fear-mongering. Therefore, what funds currently go towards PR endeavors should go towards creating new opportunities for the community to directly manage community safety, so that public does not have to take a backseat to the Police.

Recent developments in surveillance technology have heavily influenced the role of America’s police (much like the growth of social media). Studies have shown that People of Color are unequally surveilled and thus more likely to be interrogated or arrested. Scotts Valley should not spend money on technology that contributes to racism and the mass incarceration of People of Color.

Another example of misused money is SVPD's spending on high-tech gear and high-violence training. Only 7% percent of crime in Scotts Valley is classified as violent and in an even smaller fraction of those incidents would the SWAT team’s expertise have been useful. Violent crimes are reduced more effectively through preventative measures instead. For example, offering support within our town to those experiencing domestic abuse and sexual harassment, as well as sponsoring mental wellness programs and positive cultural environments within the individual neighborhoods would promote safety more effectively than expanded capacities for police violence.

Furthermore, the money spent from D.A.R.E should be reinvested into a program run by psychologists and experts in drug addiction. Cops don't understand the trauma and mental health issues that cause drug abuse. Instead, they act as authority figures, trained to arrest and punish drug usage, providing very little space for vulnerability and honesty. Well-funded programs run by drug abuse experts are more capable of fostering open conversations and preventing drug abuse in the first place.

There is a funding crisis currently across many cities in California including Scotts Valley. Many civil servants, including the police, fear for their jobs and if they will have enough to stay afloat during these trying times. Many will say that right now is not the time for "defunding." Yet, this financial uncertainty is exactly why it is so necessary for you to reallocate funds and tax dollars to programs that use them to their fullest potential.

The Scotts Valley City Council has a responsibility as our governing body to uphold its end of the social contract that promises the equal protection of its citizens’ rights. Without re-evaluating our systems, which are built upon bias and institutionalized discrimination, many citizens will be left disproportionately behind. Now is the time to join numerous other cities in defunding the police to seek peace through equality and equity. Enormous changes need to be made concerning the role of police in our community and the greater United States; the clearest path towards that is how we spend our money.

Sincerely,
[Your Name] [Your Address] [Your Email] [Your Phone Number]

**Comment by defundsvpd** [comment]
I just re-checked for the surveillance part and here is what they said about traffic cams at least  https://www.scottsvalley.org/faq.aspx?TID=40

**Comment by NickCrews** [comment]
> I just re-checked for the surveillance part and here is what they said about traffic cams at least https://www.scottsvalley.org/faq.aspx?TID=40

eh that doesn't seem relevant at all. I think it's probably fine as is, and @averymcguirt seems to agree

**Comment by NickCrews** [comment]
I'll format this to code a make a PR

**Comment by defundsvpd** [comment]
okay sounds good I was just wondering because it says through traffic cams you actually can't see  facial features so I didn't know if the relevance of the study I brought up earlier was still applicable
