### ISSUE TITLE
Add Victorville California 

### ISSUE THREAD

**Issue by alexjade29** [defund12/defund12.org#1347]
![defundvictorvillepolice](https://user-images.githubusercontent.com/66755957/84328173-1b21b900-ab36-11ea-8506-304bdc493b6c.PNG)

Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

To: 
ggarcia@victorvilleca.gov rramirezdean@victorvilleca.gov jcox@victorvilleca.gov bagomez@victorvilleca.gov dsjones@victorvilleca.gov
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!)
Dear Gloria Garcia and City Council Members,
My name is [YOUR NAME] and I am a Victorville resident writing to urge you to defund the Victorville Police Department.
The 2019-2020 proposed budget for the city of Victorville allocated $22,823,029 for the police. The funding for police increased 6% this year while spending was decreased for Community Services by 3%, Engineering by 45%, Fire by 28%, Public Works by 11%, and Water by 25%. In actuality, Victorville spent over 29.1 million renewing the contrat with San Bernardino County Sheriff’s Department. The new contract granted 3% wage increases to employees for five years, beginning in August 2019; while those with prior experience trained in law enforcement were given an additional 1% increase for four years to start January 2021.  The investment in policing has not made us safer – the police remain an embarrassment to the city and a lethal threat to Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With current finances already strained and other vital departments suffering, it is clear that we must defund the police. The city needs to priortize infrastructure, community services, and mental health to properly serve the community's needs. Rather than spending half a million dollars on technology in an attempt to help catch red light runners, the budget could be spent on projects that lead to job creation or helping Victorville's ever growing houselessness community. 
As Victorville residents, we therefore demand that you take immediate action to ensure the following:
Adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police
Drastically reduce Victorville Police's allocation from the General Fund 
Disallow unauthorized overtime 
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Victorville  cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund Victorville Police and end the city's contract with the San Bernardino's County Sheriff's Office. 

Thank you,

[YOUR NAME]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing now!

**Comment by aurendisson** [comment]
Email ready for pr! 

Editing notes: I added fields for information at the end to align with our template, corrected the budget number per this link: victorvilleca.gov/home/showdocument?id=2790 
Stats about the contract with San Bernardino are confirmed here: https://www.vvdailypress.com/news/20200423/victorville-to-spend-over-3m-more-for-law-enforcement-from-last-year 
I updated information about the red light cameras per this article: https://www.vvdailypress.com/news/20200412/victorville-license-plate-scanners-to-be-installed-in-city-after-council-decision 

To: ggarcia@victorvilleca.gov, rramirezdean@victorvilleca.gov, jcox@victorvilleca.gov, bagomez@victorvilleca.gov, dsjones@victorvilleca.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information! Please add a couple of sentences in your own words to avoid filters. )

Dear Gloria Garcia and City Council Members,

My name is [YOUR NAME], and I am a Victorville resident writing to urge you to defund the Victorville Police Department.

The 2019-2020 proposed budget for the city of Victorville allocated $27,132,208 for the police. The funding for police increased 6% this year while spending was decreased for community services by 3%, engineering by 45%, fire by 28%, public works by 11%, and water by 25%. In actuality, Victorville spent over $29.1 million renewing the contract with San Bernardino County Sheriff’s Department. The new contract granted 3% wage increases to employees for five years, beginning in August 2019; while those with prior experience trained in law enforcement were given an additional 1% increase for four years, starting January 2021. 

The investment in policing has not made us safer. The police remain an embarrassment to the city and a lethal threat to Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With current finances already strained and other vital departments suffering, it is clear that we must defund the police. The city needs to prioritize infrastructure, community services, and mental health to properly serve the community's needs. Rather than spending $450,000 on technology in an attempt to help catch people running red lights, the budget could be spent on projects that lead to job creation or helping Victorville's ever-growing community of people experiencing houselessness.

As Victorville residents, we demand that you take immediate action to ensure the following:
- Adopt a people’s budget that prioritizes community wellbeing and redirects funding away from the police. 
- Drastically reduce Victorville Police's allocation from the General Fund.
- Disallow unauthorized overtime.
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
- Invest in housing, jobs, youth programs, restorative justice, and mental health workers, which are all more effective at promoting community safety.

Victorville cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Victorville Police and end the city's contract with the San Bernardino's County Sheriff's Office.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by aurendisson** [comment]
Hi, folks. First, I want to say that I am so sorry to have just learned about the recent hanging/potential lynching of Malcolm Harsch in Victorville, CA. This is a tragedy and needs to be thoroughly investigated. 

If we think it would be appropriate, I want to help create an updated version of the email that includes this recent news and further urges local officials to act.
https://www.nbclosangeles.com/news/deputies-investigating-death-of-black-man-found-hanging-in-victorville/2380077/ 

I'm thinking after the introductory sentence, we can say something along the lines of: 

The realities of violence against our Black community are playing out across the U.S., closeby in other California cities, and potentially in our own town. On May 31, Malcolm Harsch was found hanging from a tree by the Victorville City Library. While initially ruled a suicide, the possibility of a hate crime should be thoroughly investigated by an independent party. Only 50 miles away and 10 days later, Rober Fuller was found hanging from a tree in Palmdale, California. These tragedies should not be looked over, and these deaths should not be in vain. 

Let me know what you think, if you have anything to add, any areas of concern, etc., and I'll work to edit this further and help in whatever way I can.

**Comment by mahrer** [comment]
The above content change request has been opened in issue #1651 if anyone would like to add to it or edit it.
