### ISSUE TITLE
Denver, CO email budget numbers may be wrong

### ISSUE THREAD

**Issue by jillianrosile** [defund12/defund12.org#1360]
The Denver email says:

> For FY2020, over $500,000,000 was allocated for policing (40% of the budget) while only $7.7m was allocated for safety net programs. 

I couldn't find a source for these numbers. In looking at the line items for the FY2020 budget (around page 83 of [this pdf](https://www.denvergov.org/content/dam/denvergov/Portals/344/documents/Budget/2020/2020BudgetVolume1.pdf)), it looks like over 500 million goes to the department of public safety, but this includes "safety programs" and fire as well as police/sheriff.

I also couldn't figure out how the $7.7 million for safety net programs was determined at all. I'm not sure what is defined as a safety net program, but it looks like there is a lot more than $7.7 million in programs that look like they could go under that umbrella (e.g. "safety management" and "safety programs" add up to over $20 million).

Just wanted to see if a source could be linked/mentioned in the email or these numbers could be updated to be more easily searchable/verifiable, because I want to get the message across without losing credibility or having officials think this is just a matter of educating people on the budget numbers rather than actually making changes.

**Comment by jillianrosile** [comment]
I also think 40% might be off, because while the "general fund" is 1.4 billion, the total for all funds is 2.6 billion and the total budget/expenses is 3.7 billion.

**Comment by serifluous** [comment]
@jillianrosile thanks for the fact checking!

I added budget numbers for Health, housing stability, economic development, and parks and rec. I was hesitant to add the numbers for "Safety Programs" because some of the specific programs seemed to be intermingled with incarceration programs.

imo calculating the budget as a percentage of the general fund is a pretty convincing argument because the general fund is made up of and is where the bulk of sales tax and property tax revenue goes. If that's ok to keep, let me know, and I'll approve these suggested edits. Otherwise, feel free to reply with an updated email!

**Suggested edits in bold** 

Dear Denver City Council,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY].

I am writing to demand a reallocation of funding from the Denver Police Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our city needs a budget that adequately and effectively meets the needs of at-risk Denver residents.

For FY2020, over **$405,000,000** was allocated for policing (**29% of the general fund** budget) while **less than $217m was allocated for health, housing stability, economic development, and parks and recreation combined**. In a June 6th interview, Mayor Hancock said that there is no plan to address this inequality. This is unacceptable, and I demand that the city council remedy this gross display of priorities. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Denver city budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by jillianrosile** [comment]
This looks great to me, thank you for the edits!

**Comment by ctneal91** [comment]
on it now
