### ISSUE TITLE
Defund Billerica Police Department 

### ISSUE THREAD

**Issue by jtolan132** [defund12/defund12.org#1363]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Hi there! 

Here is the template I am submitting for Billerica, MA 

[Defund the Billerica Police Department Template.pdf](https://github.com/defund12/defund12.org/files/4762354/Defund.the.Billerica.Police.Department.Template.pdf)

). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by jtolan132** [comment]
[Defund the Billerica Police Department Template.pdf](https://github.com/defund12/defund12.org/files/4762363/Defund.the.Billerica.Police.Department.Template.pdf)

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Pasting here for ease of editing:

---

Selectmen
mikerosaselectman@att.net dan.burns177@gmail.com saker@town.billerica.ma.us egiroux@town.billerica.ma.us anewton77@hotmail.com kim.conway@town.billerica.ma.us

Health Director
rberube@town.billerica.ma.us

Town Manager
jcurran@town.billerica.ma.us codea@town.billerica.ma.us kbernard@town.billerica.ma.us cmain@town.billerica.ma.us smichelini@town.billerica.ma.us

Town Clerk
sschult@town.billerica.ma.us mryan@town.billerica.ma.us sodell@town.billerica.ma.us Ksmith@town.billerica.ma.us

8,516,778 19,808,285
43% of public safety funds 179,857,871.00
4.7% of total funds 2,049,503
937,161

Dear [​Name of Mayor / City Chief of Police​],

My name is [YOUR NAME] and I am a resident of Billerica. I am writing to you today to ask what you are doing to address police brutality in our community. After witnessing the death of
                
 George Floyd at the hands of the Minneapolis Police Department, I am left feeling outraged, frustrated, and hurt. The system is currently built to continue to systematically fail Black and Brown citizens. Breonna Taylor’s murderers are still not only walking free but are currently employed by the Louisville Police Department. Tony McDade’s murder has yet to even have their name released by the Police Department. The list goes on and on because the system is working exactly as it is designed to.

I urge you to advocate for a meaningful reallocation of the city's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. For example, there are no funds in the FY2020 budget allocated to the Commission on Disabilities or the Housing Partnership.

The BPD budget is $8.5 million, which makes up 43% of total public safety funds, and is 4x the budget of the Library and Recreation and 9x the budget of Health and Human Services. This is a gross discrepancy and I urge you to reassess this disparity before the next budget meeting.
I want to make sure that Billerica begins to end that system and begin a new pattern. I am demanding the following:

1. Reduce the Billerica Police Department’s annual budget for FY2021 and establish a long-term plan to defund the department and reallocate funds to community-led safety initiatives.
2. Set up a committee to assess the needs of the city and how to reallocate funds.
3. Create a community oversight board with legal power.
4. Replace School Resource Officers with counselors and eliminate programs like DARE.
5. Establish community-led Restorative Justice programs in schools.
6. Eliminate police-based mental health and addiction services.
7. Place a moratorium on surveillance technology used to police political activity.
8. Place a moratorium on ICE collaborations.
9. Stop using COP-LINK, a database that shares information with immigration.
10. I would like to see the Billerica Police Department collect and report data on civilian deaths that occurred in custody and as a result of an officer’s use of excessive force. The data should be broken down by demographics and should showcase the race, gender, sexuality, and religion of the civilians. Allowing the public access to this information will show us where we, as a community, fall short.

Thank you for your time and I hope that we can work together to dismantle the current system so we can protect the Black and Brown members of the Billerica community. I refuse to let the next hashtag come from here.

Sincerely,
[​YOUR NAME​]
[​YOUR ADDRESS​] [​YOUR EMAIL​]
[​YOUR PHONE NUMBER​]

**Comment by aurendisson** [comment]
Editing now!

**Comment by aurendisson** [comment]
Editing notes: I reformatted a little to align with the template and simply listed out each email address. I also updated the health director's email address (from rberube@town.billerica.ma.us to kbennett@town.billerica.ma.us, pulled from https://www.town.billerica.ma.us/169/Board-of-Health). Other edits were pretty minor. Thank you for the thorough email! 

To: mikerosaselectman@att.net, dan.burns177@gmail.com, saker@town.billerica.ma.us, egiroux@town.billerica.ma.us, anewton77@hotmail.com, kim.conway@town.billerica.ma.us, kbennett@town.billerica.ma.us, jcurran@town.billerica.ma.us, codea@town.billerica.ma.us, kbernard@town.billerica.ma.us, cmain@town.billerica.ma.us, smichelini@town.billerica.ma.us, sschult@town.billerica.ma.us, mryan@town.billerica.ma.us, sodell@town.billerica.ma.us, ksmith@town.billerica.ma.us

Subject Line: [*** INSERT UNIQUE SUBJECT LINE ***] 

Message: (Don't forget to replace the [x]'s with your information! Also consider adding a couple of sentences of your own to encourage officials to read the message.)

Dear Billerica city officials,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to you today to ask what you are doing to address police brutality in our community. 

After witnessing the death of George Floyd at the hands of the Minneapolis Police Department, I am left feeling outraged, frustrated, and hurt. The system is currently built to continue to systematically fail Black and Brown citizens. Breonna Taylor’s murderers are still not only walking free but are currently employed by the Louisville Police Department. Tony McDade’s murder has yet to even have their name released by the Police Department. The list goes on and on because the system is working exactly as it is designed to.

I urge you to advocate for a meaningful reallocation of the city's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. For example, there are no funds in the FY2020 budget allocated to the Commission on Disabilities or the Housing Partnership.

The BPD budget is $8.48 million, which makes up 43% of total public safety funds, and is more than four times the budget of the library and recreation and nine times the budget of human services. This is a gross discrepancy, and I urge you to reassess this disparity before the next budget meeting.

I want to make sure that Billerica begins to end that system and begin a new pattern. I am demanding the following:
- Reduce the Billerica Police Department’s annual budget for FY2021 and establish a long-term plan to defund the department and reallocate funds to community-led safety initiatives.
- Set up a committee to assess the needs of the city and how to reallocate funds.
- Create a community oversight board with legal power.
- Replace school resource officers with counselors and eliminate programs like DARE.
- Establish community-led restorative justice programs in schools.
- Eliminate police-based mental health and addiction services.
- Place a moratorium on surveillance technology used to police political activity.
- Place a moratorium on ICE collaborations.
- Stop using COPLINK, a database that shares information with immigration.
- I would like to see the Billerica Police Department collect and report data on civilian deaths that occurred in custody and as a result of an officer’s use of excessive force. The data should be broken down by demographics and should showcase the race, gender, sexuality, and religion of the civilians. Allowing the public access to this information will show us where we, as a community, fall short.

Thank you for your time. I hope that we can work together to dismantle the current system so we can protect the Black, Brown, and Indigenous members of the Billerica community. I refuse to let the next hashtag come from here.

Sincerely,
[​YOUR NAME​]
[​YOUR ADDRESS​] 
[​YOUR EMAIL​]
[​YOUR PHONE NUMBER​]

**Comment by jtolan132** [comment]
Hi Auren,

Thank you SO much for the edits as well as all the work you are doing. Please let me know if anything needs to be added/changed.

All the best,

Jill Tolan
________________________________

**Comment by todd-m** [comment]
on it
