### ISSUE TITLE
Please add Miami, FL!

### ISSUE THREAD

**Issue by sunflower10** [defund12/defund12.org#14]

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by d4nc3r5ky** [comment]
Hello, here are the first two parts, and I'm working on the message. I would love to collaborate if there's a way.

**Subject**
Miami Demands a People's Budget

**Emails**
Mayor: fsuarez@miamigov.com
District 1 Commissioner: adiazdelaportilla@miamigov.com
District 2 Commissioner: krussell@miamigov.com
District 3 Commissioner: jcarollo@miamigov.com
District 4 Commissioner: mreyes@miamigov.com
District 5 Commissioner: KHardemon@miamigov.com
City Manager: anoriega@miamigov.com
City Clerk: clerks@miamigov.com
City Attorney: VMendez@miamigov.com

**Comment by d4nc3r5ky** [comment]
I hope I'm not stepping on any toes here, just think it's important to get this going. Here's a draft of a message I cobbled together, partly sampling from other letters. I think it could be pared down, if anyone could take a look:

**Message**
My name is [NAME], I am a resident of [CITY/NEIGHBORHOOD/DISTRICT]. I am writing to demand that the City of Miami adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police. We will not be content with “reform;” we are demanding that real change be made to the way this city allocates its resources.

The 2019-2020 FY Budget allocated $265,621,000 for the operating budget of the police, amounting to 35.8% of the total operating budget for all City departments. That number is 30 times the amount allocated to the Neighborhood Enhancement Team, 109 times the amount allocated to Housing and Community Development, 522 times the amount allocated to Equal Opportunity and Diversity Programs, 10 times the amount allocated for Resilience and Public Works, 44 times the amount allocated to Human Services, 319 times the amount allocated to Resilience and Sustainability. 

We demand that the City of Miami’s elected officials meaningfully defund the Miami Police Department. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Miamians during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

To really “fight crime,” we don’t need more police officers. Crime usually happens when someone has been unable to meet their basic needs through other means. What we need are more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

Miami deserves better. We deserve better. We need you to help us create a space in which more mental health service providers, social workers, victim/survivor advocates, educators, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another.

We urge you to do the right thing and embrace the responsibility of your role at this moment in history. Can we count on you to work to pass an alternative budget that puts a focus on social service programs and the wellbeing of the community? 

Thank you,

[Name] [Address] [Email address]  [Phone number]

**Comment by serifluous** [comment]
budget info confirmed on p17 of FY2020 Operating Budget link here: http://archive.miamigov.com/Budget/

**Comment by serifluous** [comment]
Edits in bold:

My name is [NAME], I am a resident of **Miami**. I am writing to demand that the City of Miami adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police. We will not be content with “reform;” we are demanding that real change be made to the way this city allocates its resources.

The 2019-2020 FY Budget allocated $265,621,000 for the operating budget of the police, amounting to 35.8% of the total operating budget for all City departments. That number is 30 times the amount allocated to the Neighborhood Enhancement Team, 109 times the amount allocated to Housing and Community Development, 522 times the amount allocated to Equal Opportunity and Diversity Programs, 10 times the amount allocated for Resilience and Public Works, 44 times the amount allocated to Human Services, 319 times the amount allocated to Resilience and Sustainability.

We demand that the City of Miami’s elected officials meaningfully defund the Miami Police Department. We join the calls of those across the country to **defund the police**. We demand a budget that adequately and effectively meets the needs of at-risk Miamians during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

To really “fight crime,” we don’t need more police officers. Crime usually happens when someone has been unable to meet their basic needs through other means. What we need are more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

Miami deserves better. We deserve better. We need you to help us create a space in which more mental health service providers, social workers, victim/survivor advocates, educators, religious leaders, neighbors, and friends — all of the people who really make up our community - can look out for one another.

We urge you to do the right thing and embrace the responsibility of your role at this moment in history. Can we count on you to work to pass an alternative budget that puts a focus on social service programs and the wellbeing of the community?

Thank you,
**[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]**

**Comment by todd-m** [comment]
on it

**Comment by lhmzhou** [comment]
🤦‍♀️ oops, I create a PR without seeing this issue. @todd-m, do you want to take over or could we use https://github.com/defund12/defund12.org/pull/507?

**Comment by serifluous** [comment]
Also, I removed the mention of crime in my edits above. That slipped through, sorry!

**Comment by radskillz** [comment]
Yes please help us get for miami.

**Comment by d4nc3r5ky** [comment]
I know this is late, but I just noticed an error in the math I did earlier. The percentage of the total operating budget is **32.8%** rather than 35.8%. Can this be fixed? I had accidentally divided by last year's total operating budget instead of the current year's. My badddd

**Comment by d4nc3r5ky** [comment]
I'll start a new issue for that edit
