### ISSUE TITLE
Add Cedar Rapids, IA

### ISSUE THREAD

**Issue by sophiagustafson** [defund12/defund12.org#1401]
SEND TO: cityclerk@cedar-rapids.org, b.hart@cedar-rapids.org, t.olson@cedar-rapids.org, ann.poe@cedar-rapids.org, p.loeffler@cedar-rapids.org, m.hoeger@cedar-rapids.org, s.overland@cedar-rapids.org, dalet@cedar-rapids.org, scott.olson@cedar-rapids.org, a.vanorny@cedar-rapids.org

[UNIQUE SUBJECT LINE] 

Dear Mayor Hart and Members of City Council, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. I write this letter to urge you to begin defunding and demilitarizing the Cedar Rapids Police Department. As of now, the proposed 2021 city budget for Cedar Rapids shows that Cedar Rapids Police Department is allotted 31% of the city’s budget. If the proposed 2021 budget for Cedar Rapids passes, CRPD will use more of the city’s tax dollars than the other categories of parks and recreation (9%), libraries (5%), community development (1%), and civil rights groups (<1%) combined. Even more upsetting is that increasing police funding in Cedar Rapids appears to be a continuing trend. In comparing the 2017 budget to the proposed 2021 budget, City Council has raised the police department’s budget by 18% at the expense of other programs. (Sources: Cedar Rapids City Budget, 2017 and proposed 2021 Cedar Rapids City Budget.)

As a Cedar Rapids resident, I demand that you take immediate action to ensure the following:

1. Reduce Cedar Rapid’s allocation from the General Fund by 50% (roughly $21 million)
2. Disallow unauthorized overtime by ¬¬CRPD
3. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
4. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
5. Invest in community development initiatives and programs.

Cedar Rapids cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund CRPD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by Rtrott** [comment]
SEND TO:  cityclerk@cedar-rapids.org; b.hart@cedar-rapids.org; t.olson@cedar-rapids.org; ann.poe@cedar-rapids.org; p.loeffler@cedar-rapids.org; m.hoeger@cedar-rapids.org; s.overland@cedar-rapids.org; dalet@cedar-rapids.org; scott.olson@cedar-rapids.org; a.vanorny@cedar-rapids.org

[UNIQUE SUBJECT LINE]

Dear Mayor Hart and Members of City Council,

My name is [YOUR NAME] and I am a resident of Cedar Rapids. I write this letter to urge you to begin defunding and demilitarizing the Cedar Rapids Police Department. As of now, the proposed 2021 city budget for Cedar Rapids shows that Cedar Rapids Police Department is allotted 31% of the city’s general fund budget. If the proposed 2021 budget for Cedar Rapids passes, CRPD will use more of the city’s tax dollars than the other categories of parks and recreation (9%), libraries (5%), community development (1%), and civil rights groups (<1%) combined. Even more upsetting is that increasing police funding in Cedar Rapids appears to be a continuing trend. In comparing the 2017 budget to the proposed 2021 budget, City Council has raised the police department’s budget by over 18% at the expense of other programs. 

As a Cedar Rapids resident, I demand that you take immediate action to ensure the following:

Reduce Cedar Rapid’s allocation from the General Fund by 50% ($21 million)
Disallow unauthorized overtime by CRPD
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Invest in community development initiatives and programs.

Cedar Rapids cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund CRPD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Rtrott** [comment]
'Letter to the Mayor and City Council'
