### ISSUE TITLE
Defund Riverbank CA Police

### ISSUE THREAD

**Issue by dumbneanderthal** [defund12/defund12.org#1406]
TO: robrien@riverbank.org, dbmartinez@riverbank.org, luribe@riverbank.org, cfosi@riverbank.org, ccampbell@riverbank.org

SUBJECT: [UNIQUE SUBJECT LINE HERE]

Dear Mayor O’Brien and Riverbank City Council Members, 

My name is [YOUR NAME] and I am a resident of [CITY]. I am writing to you about the Riverbank city budget presented to the public on the local government website. 

I am asking the Riverbank city council to commit to racial justice, to not be complicit in further promoting a system of policing that reinforces systemic oppression — that further reinforces the oppression of some of your constituents, who you were elected to serve and protect.  

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over 4 million dollars for funding, the only department with a six-digit funding. This year, the police received 41% of the city’s funds, leaving the remaining sixty to be distributed across fourteen departments. Purely mathematically, this is unfathomable: one department, of fifteen, receives nearly half of the entire city’s funds. This subsidy, rather than dismantling, promotes and encourages a system based in racial and class inequality. 

Research has shown, time and time again, that it is not police (or prisons) that promote community safety— it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that do, because misdemeanors and lawbreaking are often caused by unsupportive environments that rather than alleviating financial or mental issues, only dramatize them further. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair. 

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, emphasizes social services with proven impact on not just actual crime but also the welfare of your constituents, such as housing and education? 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Working on edits now!

**Comment by aurendisson** [comment]
Editing notes: Please confirm the number of police on the force. According to this document, I counted 16: https://www.riverbank.org/DocumentCenter/View/2002/FY-2019-20-Annual-Operating-Budget?bidId= (I used that document to confirm figures cited, too.) 
I consolidated a few sentences for flow and reworded some areas to emphasize defunding. 

To: robrien@riverbank.org, dbmartinez@riverbank.org, luribe@riverbank.org, cfosi@riverbank.org, ccampbell@riverbank.org

Subject: [UNIQUE SUBJECT LINE HERE]

Message: [Don't forget to replace the [x]'s with your information, and consider adding a couple of sentences in your own words to ensure this message gets past email filters.]

Dear Mayor O’Brien and Riverbank City Council Members,

My name is [YOUR NAME] and I am a resident of [CITY]. I am writing to you about the Riverbank city budget presented to the public on the local government website.

I am asking the Riverbank city council to commit to racial justice and to not be complicit in further promoting a system of policing that reinforces systemic oppression.

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over $4 million, the only department with six-digit funding. This year, the police received 41% of the city’s funds, leaving the remaining 59% to be distributed across 14 departments. Purely mathematically, this is unfathomable: one department, of 16, receives such a large portion of the entire city’s funds. This subsidy, rather than dismantling, promotes and encourages a system based in racial and class inequality.

Research has shown, time and again, that it is not the police (or prisons) that promote community safety—it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that reduce crime. Misdemeanors and lawbreaking are often caused by unsupportive environments, and policing and incarceration only further contribute to financial and mental instability. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair.

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, defunds it and reallocates funding to social services with a proven impact on the welfare of your constituents, such as housing and education?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Removed the references to the number of police officers as nobody was available to confirm it. Also made some minor edits improving readability and removing "crime" focused language. 
Final version below:

---

To: robrien@riverbank.org, dbmartinez@riverbank.org, luribe@riverbank.org, cfosi@riverbank.org, ccampbell@riverbank.org

Message: 

Dear Mayor O’Brien and Riverbank City Council Members,

My name is [YOUR NAME] and I am a resident of [CITY]. I am writing to you about the Riverbank city budget presented to the public on the local government website.

I am asking the Riverbank City Council to commit to racial justice and to not be complicit in further promoting a system of policing that reinforces systemic oppression.

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over $4 million, the only department with six-digit funding. This year, the police received 41% of the city’s funds, leaving the remaining 59% to be distributed across 14 departments. This is unfathomable. This subsidy promotes and encourages a system based in racial and class inequality.

Research has shown, time and again, that it is not the police (or prisons) that promote community safety—it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment. Misdemeanors are often caused by unsupportive environments, and policing and incarceration only further contribute to financial and mental instability. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair.

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, defunds it and reallocates funding to social services with a proven impact on the welfare of your constituents, such as housing and education?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
