### ISSUE TITLE
Defund Patterson CA Police

### ISSUE THREAD

**Issue by dumbneanderthal** [defund12/defund12.org#1407]
TO: dnovelli@ci.patterson.ca.us, jnaranjo@ci.patterson.ca.us, dmccord@ci.patterson.ca.us, dfarinha@ci.patterson.ca.us, aparham@ci.patterson.ca.us

SUBJECT: [UNIQUE SUBJECT LINE]

Dear Mayor Novelli and Patterson City Council Members, 

My name is [YOUR NAME] and I’m a resident of [CITY]. I am writing to you about the city budget presented to the public on the city government website. 

I am asking the Patterson city government to commit to racial justice, to not be complicit in further promoting a system of policing that reinforces systemic oppression — that further reinforces the oppression of some of your constituents, who you were elected to serve and protect.  

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over 5 million dollars in funding. This means they received nearly thirty percent of the city’s total funds, leaving the rest to be distributed among the more essential services that power the heartbeat of our city. This subsidy, rather than dismantling, promotes and encourages a system based in racial and class inequality. 

Research has shown, time and time again, that it is not police (or prisons) that create sustainable, safe communities— it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that do so, because misdemeanors and lawbreaking are often caused by unsupportive environments that rather than alleviating financial or mental issues, only dramatize them further. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair. 

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, emphasizes social services with proven impact on not just actual crime but also the welfare of your constituents, such as housing and education? 

Thank you, 

[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
I'm working on this! I'll use my edits from Riverbank (#1406) and work to confirm the budgets/stats for #1407-1409. This might take a couple of days, but I'll do my best to get this done by Saturday.

**Comment by aurendisson** [comment]
Editing notes: Edits made per #1406. 
Police budget confirmed here: https://ci.patterson.ca.us/DocumentCenter/View/4879/Fiscal-Year-2019-to-2020-Adopted-Budget-PDF 

To: dnovelli@ci.patterson.ca.us, jnaranjo@ci.patterson.ca.us, dmccord@ci.patterson.ca.us, dfarinha@ci.patterson.ca.us, aparham@ci.patterson.ca.us

Subject: [UNIQUE SUBJECT LINE HERE]

Message: [Don't forget to replace the [x]'s with your information, and consider adding a couple of sentences in your own words to ensure this message gets past email filters.]

Dear Mayor Novelli and Patterson City Council Members,

My name is [YOUR NAME] and I’m a resident of [CITY]. I am writing to you about the city budget presented to the public on the city government website.

I am asking the Patterson City Council to commit to racial justice and to not be complicit in further promoting a system of policing that reinforces systemic oppression.

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over $5 million in funding. This means they received nearly 30% of the city’s total funds, leaving the rest to be distributed among the more essential services that power the heartbeat of our city. This subsidy, rather than dismantling, promotes and encourages a system based in racial and class inequality.

Research has shown, time and again, that it is not the police (or prisons) that promote community safety—it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that reduce crime. Misdemeanors and lawbreaking are often caused by unsupportive environments, and policing and incarceration only further contribute to financial and mental instability. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair.

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, defunds it and reallocates funding to social services with a proven impact on the welfare of your constituents, such as housing and education?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
thanks @aurendisson and @dumbneanderthal! i'll get on this now.
