### ISSUE TITLE
Defund Ceres CA Police

### ISSUE THREAD

**Issue by dumbneanderthal** [defund12/defund12.org#1408]
TO: chris.vierra@ci.ceres.ca.us, ken.lane@ci.ceres.ca.us,  bret.durossette@ci.ceres.ca.us, mike.kline@ci.ceres.ca.us, linda.ryno@ci.ceres.ca.us

SUBJECT: [UNIQUE SUBJECT LINE]

Dear Mayor Vierra and Ceres City Council Members, 

My name is [YOUR NAME] and I’m a resident of Ceres. I am writing to you about the city budget presented to the public on the city government website. 

I am asking the Ceres city government to commit to racial justice, to not be complicit in further promoting a system of policing that reinforces systemic oppression — that further reinforces the oppression of some of your constituents, who you were elected to serve and protect.  

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over 14 million dollars in funding.This means one — ONE — department received one fifth of the total city budget. This subsidy promotes, rather than dismantles, a system based in racial and class inequality.

Research has shown, time and time again, that it is not police (or prisons) that create protected and safe communities— it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that do so, because misdemeanors and lawbreaking are often caused by unsupportive environments that rather than alleviating financial or mental issues, only dramatize them further. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair. 

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, emphasizes social services with proven impact on not just actual crime but also the welfare of your constituents, such as housing and education? 

Thank you, 

[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: Edits made per #1406. I updated Chris Vierra's email address per his page on the City Council website: https://www.ci.ceres.ca.us/403/Chris-Vierra-Mayor. I also added Channce Condit's email address. It looks like Ken Lane is no longer on City Council per this story, https://www.cerescourier.com/news/local/ken-lane-honored-he-leaves-city-council/, but I left his email on in case he's still active in local government/can advocate to current council people. 

To: cvierra@ci.ceres.ca.us, ken.lane@ci.ceres.ca.us, bret.durossette@ci.ceres.ca.us, mike.kline@ci.ceres.ca.us, linda.ryno@ci.ceres.ca.us, channce.condit@ci.ceres.ca.us

Subject: [UNIQUE SUBJECT LINE HERE]

Message: [Don't forget to replace the [x]'s with your information, and consider adding a couple of sentences in your own words to ensure this message gets past email filters.]

Dear Mayor Vierra and Ceres City Council Members,

My name is [YOUR NAME] and I’m a resident of Ceres. I am writing to you about the city budget presented to the public on the city government website.

I am asking the Ceres City Council to commit to racial justice and to not be complicit in further promoting a system of policing that reinforces systemic oppression.

To do so, I demand future funding for the police department be redirected elsewhere. In 2019, this fiscal year, police services were allocated over $14 million in funding. This means a single department received one-fifth of the total city budget. This subsidy promotes, rather than dismantles, a system based in racial and class inequality.

Research has shown, time and again, that it is not the police (or prisons) that promote community safety—it is affordable housing, educational opportunities, community violence intervention programs, and access to holistic health treatment that reduce crime. Misdemeanors and lawbreaking are often caused by unsupportive environments, and policing and incarceration only further contribute to financial and mental instability. Support funding departments that prioritize your constituents rather than aggressively funding a system far beyond repair.

Can I count on you to consider an alternative budget that, rather than emphasizing law enforcement, defunds it and reallocates funding to social services with a proven impact on the welfare of your constituents, such as housing and education?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
