### ISSUE TITLE
St. Louis County - Letter to Mayors and City Councillors

### ISSUE THREAD

**Issue by mcgoetzke** [defund12/defund12.org#1436]
Elected officials of St. Louis County:

I am [YOUR NAME], a resident of [CITY]. I demand the defunding and disbanding of St. Louis County police departments. I hold you accountable as county representatives to advocate for the reallocation of funding towards opening social worker positions and de-escalation and mental health support training programs. St. Louis County must stop increasing the annual police budget and instead invest in community-led measures to put an end to the systemically racist policing forces which have targeted, brutalized, and contributed to the oppression of people of color, especially Black people in our communities and country.

According to a recent KBIA article, Chief of Police Mary Barton has said that officers are already required to report when fellow officers don’t follow department policy on things like use of force, and will limit inappropriate jokes among officers. However, these have proven time and time again to be ineffective approaches to changing the “culture”' of policing while not addressing the system in which policing itself is couched. In the same interview, Barton said “...I think to say that there’s systemic racism in the police department is overly broad and probably not accurate.” From its origins as a body which oversaw runaway enslaved peoples and now incarcerates Black people en masse, the police are a racist body which have not strayed far from this history. The racist inherent in this system is undeniable, and Barton’s claim is frankly absurd and indeed shameful for a representative of the department responsible for the murder of Michael Brown. I ask that city councillors and local mayors stand in firm opposition to Mayor Barton and make immediate change to our policing system.

As a constituent, I cannot rely on the SLCPD to self-evaluate. I can never forget Michael Brown, who was murdered by later acquitted Ferguson police officer Darren Wilson 2014, recharging the nationwide conversation on police brutality. Since 2014, police departments have continued to fail their community and show no sign of reform despite the efforts Barton claims the department has made. Florissant officer Joshua Smith brutally ran down a suspect, a Black man, with his car, for a crime he did not commit. Joshua Smith was sued for shooting a man in 2015 for shooting another man in 2013, which internal investigations ruled a “suicide” and Abayomi “Alan” Afolabi’s family contests. Smith has merely been fired from his position after spending several days on review with pay, without guarantee by systems in place that he will be rehired by another department. In March 2020, Marvia Gray, a 68 year old Black woman, was falsely accused of stealing at a Des Peres Sam’s Club. Four officers permanently injured her while giving her 43-year-old son, Derek, a concussion and three shattered teeth. No disciplinary action has been taken against these officers, who after beating Marvia and her son, still pursued charges for resisting arrest for the crime she did not commit.

There are countless more examples of wrongful death and brutalization of Black people in this county. It is not the job of police to try, convict, kill (or attempt to kill) suspects who have not been processed through the judicial system; yet time and time again, St. Louis County officers overstep the line of their responsibilities and terrorize with impunity. As we have seen, these are nationwide phenomena, and no amount of proposed reform will redress the senseless violence police officers are allowed to enact with impunity on defenseless citizens, many of them people of color.

The St. Louis County Police Department’s budget of $143 million this year has grown by 45% since 2014, an unreasonable amount in comparison to the $4.4 million budgeted for human services $1.3 million afforded to public housing initiatives. According to public records, in 2020, the only federal, state, or miscellaneous funds planned for mental health are through the police department. Direct taxpayer dollars towards helping your constituents. Shift money away from the police and towards areas of education, public housing, and healthcare which deserve attention and address the systemic issues behind crime as a survival tactic. I urge you to find sustainable solutions that work for the taxpayers of the St. Louis County community to build a better police-free future.

Sincerely,

[YOUR NAME]

**Comment by mahrer** [comment]
Hi @mcgoetzke! Thanks for your interest in adding St. Louis County to the site. Would you mind replying here with email addresses of the government officials you'd like to receive this message?

Thank you!

**Comment by mcgoetzke** [comment]
For sure.

rdays@stlouisco.com
tfitch@stlouisco.com
kdunaway@stlouisco.com
rgray@stlouisco.com
lclancy@stlouisco.com
etrakas@stlouisco.com
mharder@stlouisco.com
tpogue@ballwin.mo.usp
seanmflower@gmail.com
mroemerman@ellisville.mo.us
rsdoug@sbcglobal.net
mclement@manchestermo.gov
mayor@town-and-country.org
jbowlin@cityofwildwood.com
smyers@pacificmissouri.com
bnation@chesterfield.mo.us

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits below:

---

Send to: rdays@stlouisco.com
tfitch@stlouisco.com
kdunaway@stlouisco.com
rgray@stlouisco.com
lclancy@stlouisco.com
etrakas@stlouisco.com
mharder@stlouisco.com
tpogue@ballwin.mo.usp
seanmflower@gmail.com
mroemerman@ellisville.mo.us
rsdoug@sbcglobal.net
mclement@manchestermo.gov
mayor@town-and-country.org
jbowlin@cityofwildwood.com
smyers@pacificmissouri.com
bnation@chesterfield.mo.us

Message:

Dear Elected officials of St. Louis County,

I am [YOUR NAME], a resident of [CITY]. I demand the defunding of St. Louis County police departments. I hold you accountable as county representatives to advocate for the reallocation of funding towards resources that are more effective at promoting a safe and equitable community, such as opening social worker positions and de-escalation and mental health support training programs. St. Louis County must stop increasing the annual police budget and instead invest in community-led measures to put an end to the systemically racist policing forces which have targeted, brutalized, and contributed to the oppression of people of color, especially Black people in our communities and country.

According to a recent KBIA article, Chief of Police Mary Barton has said that officers are already required to report when fellow officers don’t follow department policy on things like use of force, and will limit inappropriate jokes among officers. However, these have proven time and time again to be ineffective approaches to changing the “culture”' of policing while not addressing the system in which policing itself is couched. In the same interview, Barton said “...I think to say that there’s systemic racism in the police department is overly broad and probably not accurate.” From its origins as a body which oversaw runaway enslaved peoples and now incarcerates Black people en masse, the police are a racist body which have not strayed far from this history. The racism inherent in this system is undeniable, and Barton’s claim is frankly absurd and indeed shameful for a representative of the department responsible for the murder of Michael Brown. I ask that city councillors and local mayors stand in firm opposition to Mayor Barton and make immediate change to our policing system.

As a constituent, I cannot rely on the SLCPD to self-evaluate. I can never forget Michael Brown, who was murdered by later acquitted Ferguson police officer Darren Wilson 2014, recharging the nationwide conversation on police brutality. Since 2014, police departments have continued to fail their community and show no sign of reform despite the efforts Barton claims the department has made. Florissant officer Joshua Smith brutally ran down a Black man with his car, for a crime he did not commit. Joshua Smith was sued for shooting a man in 2015 for shooting another man in 2013, which internal investigations ruled a “suicide” and Abayomi “Alan” Afolabi’s family contests. Smith has merely been fired from his position after spending several days on review with pay, without guarantee by systems in place that he will be rehired by another department. In March 2020, Marvia Gray, a 68 year old Black woman, was falsely accused of stealing at a Des Peres Sam’s Club. Four officers permanently injured her while giving her 43-year-old son, Derek, a concussion and three shattered teeth. No disciplinary action has been taken against these officers, who after beating Marvia and her son, still pursued charges for resisting arrest for the crime she did not commit.

There are countless more examples of wrongful death and brutalization of Black people in this county. It is not the job of police to try, convict, kill, or attempt to kill suspects who have not been processed through the judicial system; yet time and time again, St. Louis County officers overstep the line of their responsibilities and terrorize with impunity. As we have seen, these are nationwide phenomena, and no amount of proposed reform will redress the senseless violence police officers are allowed to enact with impunity on defenseless citizens, many of them Black, Indigenous, or  People of Color.

The St. Louis County Police Department’s budget of $143 million this year has grown by 45% since 2014, an unreasonable amount in comparison to the $4.4 million budgeted for Human Services $1.3 million afforded to Public Housing Initiatives. According to public records, in 2020, the only federal, state, or miscellaneous funds planned for mental health are through the police department. Direct taxpayer dollars towards helping your constituents. Shift money away from the police and towards areas of education, public housing, and healthcare which deserve attention and address the systemic issues behind crime as a survival tactic. I urge you to find sustainable solutions that work for the taxpayers of the St. Louis County community to build a better police-free future.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
