### ISSUE TITLE
Add Contra Costa County, CA

### ISSUE THREAD

**Issue by pi8992** [defund12/defund12.org#1476]
TO: David.Twa@cao.cccounty.us, john_gioia@bos.cccounty.us, supervisorandersen@bos.cccounty.us, supervisor_burgis@bos.cccounty.us, supervisormitchoff@bos.cccounty.us, district5@bos.cccounty.us 

SUBJECT: [INSERT UNIQUE SUBJECT LINE!]

MESSAGE: [DON’T FORGET TO PUT IN YOUR OWN INFORMATION!]

To the Contra Costa County Administrator and Board of Supervisors,

My name is [INSERT NAME], and I am a resident of [CITY] in Contra Costa County. Since the day after George Floyd’s death, there have been protests in cities across the United States demanding an end to racism and anti-Blackness. We must reevaluate, in a deep and meaningful way, the role of policing in our communities, as it disproportionately and unjustly impacts people of color. We can reimagine public safety, not as reactive violence in the face of emergencies, but as mediation and the de-escalation of conflict, along with increased access to social services.

While the 2020-2021 Recommended Budget for Contra Costa County has already been put together - including an increase of $7,210,904 in funding for the Sheriff-Coroner Department - it has not yet been approved. The Recommended Budget includes $255,146,498 allocated to the Sheriff-Coroner Department, 14% of the General Fund. I demand that you defund the Contra Costa County Sheriff, by significantly reducing their budget, and to re-invest those funds into community-led strategies for health and safety. 

If you reduce the budget of the Sheriff-Coroner Department, resources will be made available that can be invested in community services and non-law enforcement emergency response teams. Many emergencies can be handled by healthcare workers, mental health professionals, and other trained professionals. Defunding the Sheriff’s Department is a process that must include the close collaboration of community leaders and organizations, to ensure that funds stay in the county and meet the needs of Black residents in particular. These redirected funds should also go towards affordable housing and services for the un-housed, education and youth programs, restorative justice, and community health. 

Amid the dual public health crises of police violence and COVID-19, Contra Costa County cannot wait for a budget that supports community well-being. I urge you to make these changes in the 2020-2021 budget: to reduce funding for law enforcement, and invest in community services and healing instead. 

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
I made some slight changes to time sensitive information so that the template will last longer, as well as some readability edits:

---

TO: David.Twa@cao.cccounty.us, john_gioia@bos.cccounty.us, supervisorandersen@bos.cccounty.us, supervisor_burgis@bos.cccounty.us, supervisormitchoff@bos.cccounty.us, district5@bos.cccounty.us

MESSAGE:

To the Contra Costa County Administrator and Board of Supervisors,

My name is [INSERT NAME], and I am a resident of [CITY] in Contra Costa County. Since the day after George Floyd’s death, there have been protests in cities across the United States demanding an end to racism and anti-Blackness. We must reevaluate, in a deep and meaningful way, the role of policing in our communities, as it disproportionately and unjustly impacts people of color. We can reimagine public safety, not as reactive violence in the face of emergencies, but as mediation and the de-escalation of conflict, along with increased access to social services.

The 2020-2021 Recommended Budget for Contra Costa County includes an increase of $7,210,904 in funding for the Sheriff-Coroner Department. The Sheriff-Coroner Department's budget is $255,146,498, or 14% of the General Fund. I demand that you defund the Contra Costa County Sheriff by significantly reducing their budget, and re-investing those funds into community-led strategies for health and safety.

If you reduce the budget of the Sheriff-Coroner Department, resources will be made available that can be invested in community services and non-law enforcement emergency response teams. Many emergencies can be handled by healthcare workers, mental health professionals, and other trained professionals. Defunding the Sheriff’s Department is a process that must include the close collaboration of community leaders and organizations, to ensure that funds stay in the county and meet the needs of Black residents in particular. These redirected funds should also go towards affordable housing and services for the un-housed, education and youth programs, restorative justice, and community health.

Amid the dual public health crises of police violence and COVID-19, Contra Costa County cannot wait for a budget that supports community well-being. I urge you to make these changes in the 2020-2021 budget: to reduce funding for law enforcement, and invest in community services and healing instead.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
