### ISSUE TITLE
Topeka, KS

### ISSUE THREAD

**Issue by rantingtonoone** [defund12/defund12.org#1485]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

To: btrout@topeka.org, khiller@topeka.org, cvaldivia-alcala@topeka.org, sortiz@topeka.org, temerson@topeka.org, mpadilla@topeka.org, hnaeger@topeka.org, ndobler@topeka.org, sduncan@topeka.org, mlesser@topeka.org, council@topeka.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!) 

Dear Mayor De La Isla, Topeka City Councilors, and City Manager Brent Trout,

My name is [YOUR NAME] and I am a resident of Topeka. I am writing to demand that the Topeka City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.
As you know, in the 2019 budget, the City of Topeka allocated an increase of over 4 million dollars to fund the Topeka Police Department. In the 2020 budget, the City of Topeka increased the Police Department budget another 7 hundred thousand dollars. The TPD budget equates to an inordinate 42.43% of our taxpayers contributions to the city’s general fund, at over 40 million dollars. 
I demand that the City Council begin meaningfully defunding the Topeka Police Department and reallocating those funds to programs which effectively promote a safe and equitable community; such as the YWCA Center for Safety and Empowerment. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police.
History has shown that police “reform” is not enough. The 2020 Topeka City Budget includes a desire to promote public safety and to shift public perception of health/safety in Topeka, this cannot be done through police reform alone. We must take a hard look at the way the current system in place fails to serve—and in fact actively harms—our community and come together to reimagine the role of police in our city.
I am urging you to completely revise the current budget as well as the 2021 budget, and to invest our taxpayer money back into the people, not in the police. We trust that you will do the right thing for us, because we put our trust in you when we elected you to serve us. This is a moment for you to step up and show that you care for our community.

Thank you for your time,

[YOUR NAME] [ADDRESS] [EMAIL] [PHONE ]

**Comment by rantingtonoone** [comment]
Another local community aid organization which would benefit from the reallocation of funds is Community Action. I've added this to the email and copied below 

To: btrout@topeka.org, khiller@topeka.org, cvaldivia-alcala@topeka.org, sortiz@topeka.org, temerson@topeka.org, mpadilla@topeka.org, hnaeger@topeka.org, ndobler@topeka.org, sduncan@topeka.org, mlesser@topeka.org, council@topeka.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor De La Isla, Topeka City Councilors, and City Manager Brent Trout,

My name is [YOUR NAME] and I am a resident of Topeka. I am writing to demand that the Topeka City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.
As you know, in the 2019 budget, the City of Topeka allocated an increase of over 4 million dollars to fund the Topeka Police Department. In the 2020 budget, the City of Topeka increased the Police Department budget another 7 hundred thousand dollars. The TPD budget equates to an inordinate 42.43% of our taxpayers contributions to the city’s general fund, at over 40 million dollars.
I demand that the City Council begin meaningfully defunding the Topeka Police Department and reallocating those funds to programs which effectively promote a safe and equitable community; such as the YWCA Center for Safety and Empowerment and Community Action. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police.
History has shown that police “reform” is not enough. The 2020 Topeka City Budget includes a desire to promote public safety and to shift public perception of health/safety in Topeka, this cannot be done through police reform alone. We must take a hard look at the way the current system in place fails to serve—and in fact actively harms—our community and come together to reimagine the role of police in our city.
I am urging you to completely revise the current budget as well as the 2021 budget, and to invest our taxpayer money back into the people, not in the police. We trust that you will do the right thing for us, because we put our trust in you when we elected you to serve us. This is a moment for you to step up and show that you care for our community.

Thank you for your time,

[YOUR NAME] [ADDRESS] [EMAIL] [PHONE ]

**Comment by brickaney** [comment]
@skullface Please change label. I’ve completed my review.

Edits made: Minor edits, added a reference.

“To: 
btrout@topeka.org, 
khiller@topeka.org, 
cvaldivia-alcala@topeka.org, 
sortiz@topeka.org, 
temerson@topeka.org, 
mpadilla@topeka.org, 
hnaeger@topeka.org, 
ndobler@topeka.org, 
sduncan@topeka.org, 
mlesser@topeka.org, 
council@topeka.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor De La Isla, Topeka City Councilors, and City Manager Brent Trout,

My name is [YOUR NAME] and I am a resident of Topeka. I am writing to demand that the Topeka City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.
As you know, in the 2019 budget, the City of Topeka allocated an increase of over 4 million dollars to fund the Topeka Police Department. In the 2020 budget, the City of Topeka increased the Police Department budget another 700 thousand dollars. The TPD budget equates to an inordinate 42.43% of our taxpayers contributions to the city’s general fund, at over 40 million dollars [1].

I demand that the City Council begin meaningfully defunding the Topeka Police Department and reallocating those funds to programs which effectively promote a safe and equitable community; such as the YWCA Center for Safety and Empowerment and Community Action. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police.

History has shown that police “reform” is not enough. The 2020 Topeka City Budget includes a desire to promote public safety and to shift public perception of health/safety in Topeka, this cannot be done through police reform alone. We must take a hard look at the way the current system in place fails to serve—and in fact actively harms—our community and come together to reimagine the role of police in our city.

I am urging you to completely revise the current budget as well as the 2021 budget, and to invest our taxpayer money back into the people, not in the police. We trust that you will do the right thing for us, because we put our trust in you when we elected you to serve us. This is a moment for you to step up and show that you care for our community.

Thank you for your time,
[YOUR NAME] 
[ADDRESS] 
[EMAIL] 
[PHONE ]

[1] https://cot-wp-uploads.s3.amazonaws.com/wp-content/uploads/finance/Budget/2020+Adopted+Budget+Book.pdf

**Comment by todd-m** [comment]
on it
