### ISSUE TITLE
Add City of Beaverton, Oregon

### ISSUE THREAD

**Issue by tarak503** [defund12/defund12.org#1541]
citymail@BeavertonOregon.gov
lbeaty@beavertonoregon.gov
mayormail@beavertonoregon.gov

Beaverton Mayor Doyle and City Council, 

My name is [YOUR NAME] and I am a resident of Beaverton, Oregon. 

As a resident of Beaverton, I do not believe your proposed budget for the City of Beaverton is appropriate and I urge you to defund the police. The proposed 20/21 budget allocates 41% of the general fund to police. This is compared to only 12% of the general fund going toward community development. Last year's proposed budget also allocated 41% of the budget to police. In fact last year's proposed budget allocated 14% to community development. Even amongst cuts due to COVID-19, Beaverton has decided the largest chunk of the budget should go toward the police department and is willing to fund the police at the expense of much needed development. 

On Tuesday, June 16th, the Beaverton City Council is meeting to adopt this budget. I do not believe that a budget that does not defund the police can provide a viable solution. Further, the city council is meeting to discuss reforms which have proven ineffective historically. This is an utter waste of tax payer money. This letter is my public comment and I hope it is seriously considered.

In my experience living in Beaverton, the diversity of this city is one of its greatest assets. Continuing to allocate the police funding does not protect Beaverton residents. It actively endangers Black Beaverton residents who deserve to live in our city safely. This is a time for Beaverton to invest in our community rather than invest in policing our community. I can see the ways in which policing continues to perpetuate violence against Black, brown, houseless people, and against people in mental health crisis. 

The city, the state, and country are all watching. And so am I. I call on the Mayor and City Council Members to use their powers to continue to reduce the budget and pledge to increase Police accountability and transparency. I promise that you will lose my support and my vote if you aren't willing to make a public and vocal stand to help defund the Beaverton Police department. 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by tarak503** [comment]
Thanks for reviewing the content! I just wanted to flag that Beaverton is having a city council meeting to approve the proposed budget THIS tuesday (in the letter), so getting this out before then would be useful. It will still be helpful after Tuesday, but would be nice to get this one out earlier rather than later.

**Comment by tarak503** [comment]
The city council meeting occurred on June 16th and they voted to approve the budget but left the for open for revisions and acknowledged they need to reconsider the police budget. I've changed the letter slightly to reflect this. See below: 

citymail@BeavertonOregon.gov
lbeaty@beavertonoregon.gov
mayormail@beavertonoregon.govBeaverton Mayor Doyle and City Council,My name is [YOUR NAME] and I am a resident of Beaverton, Oregon.As a resident of Beaverton, I do not believe your proposed budget for the City of Beaverton is appropriate and I urge you to defund the police. The proposed 20/21 budget allocates 41% of the general fund to police. This is compared to only 12% of the general fund going toward community development. Last year's proposed budget also allocated 41% of the budget to police. In fact last year's proposed budget allocated 14% to community development. Even amongst cuts due to COVID-19, Beaverton has decided the largest chunk of the budget should go toward the police department and is willing to fund the police at the expense of much needed development.On Tuesday, June 16th, the Beaverton City Council met and adopted this budget for FY 2020/2021. I am disappointed by this decision, but was heartened to hear the council is planning on amending the budget after further consideration of the police budget. The reforms being discussed have proven ineffective and is an utter waste of taxpayer money. I do not believe that a budget that does not defund the police can provide a viable solution. This letter should serve as a reminder to continue the conversation on police funding and lower the police budget as soon as possible. This letter is my public comment and I hope it is seriously considered. I will be paying attention and intend on holding the council accountable. In my experience living in Beaverton, the diversity of this city is one of its greatest assets. Continuing to allocate the police funding does not protect Beaverton residents. It actively endangers Black Beaverton residents who deserve to live in our city safely. This is a time for Beaverton to invest in our community rather than invest in policing our community. I can see the ways in which policing continues to perpetuate violence against Black, brown, houseless people, and against people in mental health crisis.The city, the state, and country are all watching. And so am I. I call on the Mayor and City Council Members to use their powers to continue to reduce the budget and pledge to increase Police accountability and transparency. I promise that you will lose my support and my vote if you aren't willing to make a public and vocal stand to help defund the Beaverton Police department.Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
@mahrer Please change to next label, I’ve completed my review.

Edits made: structural edits, added a reference to the budget, and edited the content to ensure its aligned with the email guidelines: more generic language.

“TO:
citymail@BeavertonOregon.gov
lbeaty@beavertonoregon.gov
mayormail@beavertonoregon.gov

Subject: [UNIQUE SUBJECT LINE]

Beaverton Mayor Doyle and City Council,

My name is [YOUR NAME] and I am a resident of Beaverton, Oregon. As a resident of Beaverton, I do not believe your proposed budget for the City of Beaverton is appropriate and I urge you to defund the police. The proposed 20/21 budget allocates 41% of the general fund to police [1]. This is compared to only 12% of the general fund going toward community development [1]. 

Last year's proposed budget also allocated 41% of the budget to police. In fact last year's proposed budget allocated 14% to community development. Even amongst cuts due to COVID-19, Beaverton has decided the largest chunk of the budget should go toward the police department and is willing to fund the police at the expense of much needed development.

On Tuesday, June 16th, the Beaverton City Council met and adopted this budget for FY 2020/2021. I am disappointed by this decision, but was heartened to hear the council is planning on amending the budget after further consideration of the police budget. 

Police reforms being discussed have proven ineffective and I do not believe that a budget that does not defund the police can provide a viable solution. This is a time for Beaverton to invest in our community rather than invest in policing our community. 

I call on the Mayor and City Council Members to use their powers to continue to reduce the budget and pledge to increase Police accountability and transparency.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] https://www.beavertonoregon.gov/DocumentCenter/View/28690/General-Fund-Summary

**Comment by todd-m** [comment]
on it

**Comment by todd-m** [comment]
made a few more edits for clarity and to highlight the prior year's budget comparison:

Dear Mayor Doyle and City Council,

  My name is [YOUR NAME] and I am a resident of Beaverton, Oregon. As your constituent, I do not believe your proposed budget for the City of Beaverton is in the public interest. 

  Last year's proposed budget allocated 41% to police, with 14% set aside for community development. The proposed '20-21 budget still preserves 41% of the general fund for police, but cuts the allocation for community development to 12%. In the midst of a pandemic, Beaverton has decided the largest chunk of the budget should continue to fund the police at the expense of other priorities.

  On June 16th, the Beaverton City Council met and adopted this budget for FY '20-21. I am disappointed by this decision, but was heartened to hear the council is planning on amending the budget after further consideration of police funding.

  Efforts at police reform being discussed have proven ineffective elsewhere. A budget that does not defund the police is not a viable solution. This is a time for Beaverton to invest in our community rather than investing in policing it.

  I call on the Mayor and City Council Members to use their powers to continue to reduce the law enforcement budget and to pledge to increase police accountability and transparency.

  Thank you for your time,

  [YOUR NAME]
  [YOUR ADDRESS]
  [YOUR EMAIL]
  [YOUR PHONE NUMBER]

  [1] https://www.beavertonoregon.gov/DocumentCenter/View/28690/General-Fund-Summary

-- this should be merged in shortly.
