### ISSUE TITLE
Correction request - Denver

### ISSUE THREAD

**Issue by mgk526** [defund12/defund12.org#1547]
![0D73E110-668E-4124-9EF3-87EF8AD48D82](https://user-images.githubusercontent.com/66912313/84596433-b8793780-ae2b-11ea-9874-c88f277644d2.jpeg)

**Comment by ctneal91** [comment]
on it now

**Comment by ctneal91** [comment]
@mgk526 I can't find the reference to $1.6 million. 

"Dear Denver City Council,\n\nMy name is [YOUR NAME] and I am a resident of
  [NEIGHBORHOOD/BOROUGH/CITY]. \n\nI am writing to demand a reallocation of funding
  from the Denver Police Department to social and public programming for our communities.
  With record unemployment and a seemingly intractable pattern of abuse and unequal
  treatment by police, our city needs a budget that adequately and effectively meets
  the needs of at-risk Denver residents.\n\nFor FY2020, over $405,000,000 was allocated
  for policing (29% of the general fund budget) while less than $217m was allocated
  for health, housing stability, economic development, and parks and recreation combined.
  In a June 6th interview, Mayor Hancock said that there is no plan to address this
  inequality. This is unacceptable, and I demand that the city council remedy this
  gross display of priorities. You must support a budget that supports social equity
  in our community, rather than empowering the police forces that tear us apart.\n\nIt
  is your duty to represent your constituents. I am urging you to advocate for revision
  of the Denver city budget for the upcoming fiscal year to reflect the decades of
  research showing that education and social programs better promote the safety of
  a city than policing.\n\nThank you for your time,\n\n[YOUR NAME]\n[YOUR ADDRESS]\n[YOUR
  EMAIL]\n[YOUR PHONE NUMBER]"

**Comment by mgk526** [comment]
Looking at the templates it looks like maybe it was changed. When I sent
out my emails there were two links for denver. So maybe it was already
corrected!
