### ISSUE TITLE
Hampton, VA

### ISSUE THREAD

**Issue by cheuch04** [defund12/defund12.org#1572]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by cheuch04** [comment]
Dear Mayor Tuck and City Council Members,

My name is [YOUR NAME], and I am a resident of Hampton. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to institutionalized racism. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Hampton PD receives a disproportionate amount of our city's financial resources. In FY 2020, the Hampton Police Division has a budget of almost $25 million.   While we’ve been spending extraordinary amounts on policing, we have not seen significant improvements to safety, homelessness, mental health, or affordability in our city.

I call on you to meaningfully restrict the Hampton PD budget and instead use those extraordinary resources towards, for example, solving homelessness, which is felt most by our Black neighbors and veterans. Research shows social programs and education to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely, [YOUR NAME][YOUR ADDRESS] [YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by cheuch04** [comment]
Email Addresses: 

dtuck@hampton.gov, eleanor.brown@hampton.gov, steven.brown@hampton.gov, lcurtis@hampton.gov, bhobbs@hampton.gov, csnead@hampton.gov

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Changelog**
1. "This past week" --> "In recent weeks" (since this is no longer technically true)
2. FY 2020 --> FY20 (per formatting on the city's website)
3.

### **Edited Email Copy**
dtuck@hampton.gov, eleanor.brown@hampton.gov, steven.brown@hampton.gov, lcurtis@hampton.gov, bhobbs@hampton.gov, csnead@hampton.gov

Dear Mayor Tuck and City Council Members,

My name is [YOUR NAME], and I am a resident of Hampton. In recent weeks, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to institutionalized racism. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Hampton PD receives a disproportionate amount of our city's financial resources. In FY20, the Hampton Police Division has a budget of almost $25 million. While we’ve been spending extraordinary amounts on policing, we have not seen significant improvements to safety, homelessness, mental health, or affordability in our city.

I call on you to meaningfully restrict the Hampton PD budget and instead use those extraordinary resources towards, for example, solving homelessness, which is felt most by our Black neighbors and veterans. Research shows social programs and education to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
This is ready for PR!

**Comment by root2point0** [comment]
on it
