### ISSUE TITLE
NEW AND UPDATED Add Worcester, MA

### ISSUE THREAD

**Issue by mpuch012** [defund12/defund12.org#1578]
TO: 
Mayor Joseph M. Petty: mayor@worcesterma.gov
Councilor-At-Large Moe A. Bergman: BergmanM@worcesterma.gov
Councilor-At-Large Donna M. Colorio: ColorioD@worcesterma.gov
Councilor-At-Large Khrystian E. King: KingK@worcesterma.gov
Councilor-At-Large Gary Rosen: RosenG@worcesterma.gov
Councilor-At-Large Kathleen M. Toomey: ToomeyK@worcesterma.gov
District 1 Councilor Sean M. Rose: RoseS@worcesterma.gov
District 2 Councilor Candy F. Mero-Carlson: Mero-CarlsonC@worcesterma.gov
District 3 Councilor George J. Russell: RussellG@worcesterma.gov
District 4 Councilor Sarai Rivera: RiveraSA@worcesterma.gov
District 5 Councilor Matthew E. Wally: WallyM@worcesterma.gov
City Manager Edward M. Augustus, Jr.: CityManager@worcesterma.gov

Dear [CITY OFFICIAL'S NAME],

My name is [YOUR NAME] and I am a resident of Worcester living in District [YOUR DISTRICT NUMBER]. I am writing to express my concern over the current proposed budget increase of $254,320 for the Worcester Police Department (WPD). I urge you to reject this increase and allocate it to services that benefit our community.

[INSERT YOUR REASONS HERE; FEEL FREE TO PULL FROM THE SCRIPT BELOW. INCLUDE YOUR OWN PERSONAL EXPERIENCE]

In light of recent events across our country, I believe our view towards policing needs to change completely.  Police can not be used as band-aids for social problems, while services that would actually support our community lack sufficient funding.  Please consider the following:

- Black and brown people are being murdered by police with near impunity. The American Public Health Association has identified that police violence is a public health emergency and “U.S. policing has failed to equitably deliver safety, placing an inequitable burden of mental and physical harm on socially and economically marginalized populations.”.  

- Police are called to respond to situations they were never meant to solve. Creating true public safety means we must invest robustly in education, health care access, employment programs, transportation, affordable housing, and community restorative justice initiatives.  

- Investments in more policing have never brought about reform.  Cities like Dallas and Los Angeles are taking steps to shift their priorities.  A comprehensive report on a 150-year review on the Minneapolis Police Department further proves the lack of success investing in police brings.  

We have called into council meetings, left messages and emails demanding a more inclusive process for citizen input in our budget. The City Council must take a stand for racial justice by significantly defunding policing and investing in real public safety for our community - starting with reallocating the proposed increase in WPD funding to various social services.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @mpuch012! Thanks so much for your submission.
The Worcester letter has been added to the site from a previous submission. 
https://defund12.org/worcester 

If you would like to make specific changes to the existing content (rather than replacing the entire template), please open a new issue so we can follow-up. 
Thank you!

**Comment by mpuch012** [comment]
Hello @mahrer ! I would like to replace the entire template. There is inaccurate information and my team and I decided it would be best to go with another template altogether. Also, what does "closed" mean for the issue?

**Comment by mahrer** [comment]
Hi @mpuch012 would you mind stating what is inaccurate in the template? Because our templates are written by community members, we try to make the process collaborative instead of just replacing one with the other.

After looking at the closed issue #773, it looks like the data was confirmed from this source:
http://www.worcesterma.gov/uploads/f9/cc/f9cc1ae9dd5bb1e7cf34b6a4eaca6613/budget-fy21.pdf

**Comment by mpuch012** [comment]
Yes so first, the first email template is stating that the 2020 FY budget allocated over 52 million when it is actually the 2021 FY budget that does it. Another thing is that it doesn't include all city officials that can be contacted, just a select few, I'm not sure why. My email template includes the reasons why the police should be defunded as well as the city officials names and emails in a more professional manner. Let me know what you think!

**Comment by mahrer** [comment]
@mpuch012 Thanks for pointing out these inaccuracies. I've taken a shot at updating the previous template with your team's contributions. Let me know what you think:

---

TO:
Mayor Joseph M. Petty: mayor@worcesterma.gov
Councilor-At-Large Moe A. Bergman: BergmanM@worcesterma.gov
Councilor-At-Large Donna M. Colorio: ColorioD@worcesterma.gov
Councilor-At-Large Khrystian E. King: KingK@worcesterma.gov
Councilor-At-Large Gary Rosen: RosenG@worcesterma.gov
Councilor-At-Large Kathleen M. Toomey: ToomeyK@worcesterma.gov
District 1 Councilor Sean M. Rose: RoseS@worcesterma.gov
District 2 Councilor Candy F. Mero-Carlson: Mero-CarlsonC@worcesterma.gov
District 3 Councilor George J. Russell: RussellG@worcesterma.gov
District 4 Councilor Sarai Rivera: RiveraSA@worcesterma.gov
District 5 Councilor Matthew E. Wally: WallyM@worcesterma.gov
City Manager Edward M. Augustus, Jr.: CityManager@worcesterma.gov

Dear [CITY OFFICIAL'S NAME],

My name is [YOUR NAME] and I am a resident of Worcester living in District [YOUR DISTRICT NUMBER]. I am writing to express my concern over the current proposed budget increase of $254,320 for the Worcester Police Department (WPD). Rather than invest in a system that has been founded on racist principles and that has perpetuated the unnecessary deaths of so many Black people nation wide, I suggest we reallocate money towards building up and supporting the Black and Brown communities that make Worcester the city it is.

The 2021 fiscal budget allocated over $52 million to the Worcester Police Department. I believe that this money could be have a greater use being invested in education, healthcare, and countless other social programs at the benefit of Worcester's Black and Brown communities. The City Council must take a stand for racial justice by significantly defunding policing.

[INSERT YOUR REASONS HERE; FEEL FREE TO PULL FROM THE SCRIPT BELOW. INCLUDE YOUR OWN PERSONAL EXPERIENCE]

In light of recent events across our country, I believe our view towards policing needs to change completely. Police can not be used as band-aids for social problems, while services that would actually support our community lack sufficient funding. Please consider the following:

Black and brown people are being murdered by police with near impunity. The American Public Health Association has identified that police violence is a public health emergency and “U.S. policing has failed to equitably deliver safety, placing an inequitable burden of mental and physical harm on socially and economically marginalized populations.”

Police are called to respond to situations they were never meant to solve. Creating true public safety means we must invest robustly in education, health care access, employment programs, transportation, affordable housing, and community restorative justice initiatives.

Investments in more policing have never brought about reform. Cities like Dallas and Los Angeles are taking steps to shift their priorities. A comprehensive report on a 150-year review on the Minneapolis Police Department further proves the lack of success investing in police brings.

Community members have called into council meetings, left messages and emails demanding a more inclusive process for citizen input in our budget. The City Council must take a stand for racial justice by significantly defunding policing and investing in real public safety for our community - starting with reallocating the proposed increase in WPD funding to various social services.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mpuch012** [comment]
Could you take out the first "The City Council must take a stand for racial justice by significantly defunding policing" since there is the same sentence in the last paragraph as well? Also, the 2021 fiscal budget is not approved yet so we can't exactly say the money has been allocated yet. And the first email states that the police have a budget of over 52 million, which I am sure it is information the city officials know already. How about this draft (Let me know what you think):

Dear [CITY OFFICIAL'S NAME],

My name is [YOUR NAME] and I am a resident of Worcester living in District [YOUR DISTRICT NUMBER]. I am writing to express my concern over the current proposed budget increase of $254,320 for the Worcester Police Department (WPD). Rather than invest in a system that has been founded on racist principles and has brought the unnecessary deaths of so many Black and Brown people nationwide, I suggest we reallocate that money towards services that will build up and support their communities instead.

[INSERT YOUR REASONS HERE; FEEL FREE TO PULL FROM THE SCRIPT BELOW. INCLUDE YOUR OWN PERSONAL EXPERIENCE]

In light of recent events across our country, I believe our view towards policing needs to change completely. Police can not be used as band-aids for social problems, while services that would actually benefit our community lack sufficient funding. Please consider the following:

- Black and brown people are being murdered by police with near impunity. The American Public Health Association has identified that police violence is a public health emergency and “U.S. policing has failed to equitably deliver safety, placing an inequitable burden of mental and physical harm on socially and economically marginalized populations.”

- Police are called to respond to situations they were never meant to solve. Creating true public safety means we must invest robustly in education, health care access, employment programs, transportation, affordable housing, and community restorative justice initiatives.

- Investments in more policing have never brought about reform. Cities like Dallas and Los Angeles are taking steps to shift their priorities. A comprehensive report on a 150-year review on the Minneapolis Police Department further proves the lack of success investing in police brings.

Community members have called into city council meetings, left messages, and wrote emails demanding a more inclusive process for citizen input in our budget. The City Council must take a stand for racial justice by significantly defunding policing and investing in real public safety for our community - starting with reallocating the proposed increase in WPD funding to various social services.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@mpuch012 I agree with your first edit. But I do think that including the total police budget is important in order to make a stronger point, regardless of whether the recipients already know the information. I have edited that paragraph to say "proposed FY2021 operating budget" to reflect that it may not be approved yet (this is the title of the source document as well). Thanks so much for your willingness to collaborate. Let me know what you think:

---

TO:
Mayor Joseph M. Petty: mayor@worcesterma.gov
Councilor-At-Large Moe A. Bergman: BergmanM@worcesterma.gov
Councilor-At-Large Donna M. Colorio: ColorioD@worcesterma.gov
Councilor-At-Large Khrystian E. King: KingK@worcesterma.gov
Councilor-At-Large Gary Rosen: RosenG@worcesterma.gov
Councilor-At-Large Kathleen M. Toomey: ToomeyK@worcesterma.gov
District 1 Councilor Sean M. Rose: RoseS@worcesterma.gov
District 2 Councilor Candy F. Mero-Carlson: Mero-CarlsonC@worcesterma.gov
District 3 Councilor George J. Russell: RussellG@worcesterma.gov
District 4 Councilor Sarai Rivera: RiveraSA@worcesterma.gov
District 5 Councilor Matthew E. Wally: WallyM@worcesterma.gov
City Manager Edward M. Augustus, Jr.: CityManager@worcesterma.gov

Dear [CITY OFFICIAL'S NAME],

My name is [YOUR NAME] and I am a resident of Worcester living in District [YOUR DISTRICT NUMBER]. I am writing to express my concern over the current proposed budget increase of $254,320 for the Worcester Police Department (WPD). Rather than invest in a system that has been founded on racist principles and has brought the unnecessary deaths of so many Black and Brown people nationwide, I suggest we reallocate that money towards services that will build up and support their communities instead.

The proposed FY2021 operating budget allocated over $52 million to the Worcester Police Department. I believe that this money could be have a greater use being invested in education, healthcare, and countless other social programs at the benefit of Worcester's Black and Brown communities. 

[INSERT YOUR REASONS HERE; FEEL FREE TO PULL FROM THE SCRIPT BELOW. INCLUDE YOUR OWN PERSONAL EXPERIENCE]

In light of recent events across our country, I believe our view towards policing needs to change completely. Police can not be used as band-aids for social problems, while services that would actually benefit our community lack sufficient funding. Please consider the following:

- Black and brown people are being murdered by police with near impunity. The American Public Health Association has identified that police violence is a public health emergency and “U.S. policing has failed to equitably deliver safety, placing an inequitable burden of mental and physical harm on socially and economically marginalized populations.”

- Police are called to respond to situations they were never meant to solve. Creating true public safety means we must invest robustly in education, health care access, employment programs, transportation, affordable housing, and community restorative justice initiatives.

- Investments in more policing have never brought about reform. Cities like Dallas and Los Angeles are taking steps to shift their priorities. A comprehensive report on a 150-year review on the Minneapolis Police Department further proves the lack of success investing in police brings.

Community members have called into city council meetings, left messages, and wrote emails demanding a more inclusive process for citizen input in our budget. The City Council must take a stand for racial justice by significantly defunding policing and investing in real public safety for our community - starting with reallocating the proposed increase in WPD funding to various social services.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mpuch012** [comment]
Thank you so much for being so considerate of my edits! This means a lot. I just made one more change, and that is taking information from the second paragraph and putting it into the first. I didn't use information from the second part of the 2nd paragraph because I think it is already included in the 3rd bullet. Again, please let me know what you think!

TO:
Mayor Joseph M. Petty: mayor@worcesterma.gov
Councilor-At-Large Moe A. Bergman: BergmanM@worcesterma.gov
Councilor-At-Large Donna M. Colorio: ColorioD@worcesterma.gov
Councilor-At-Large Khrystian E. King: KingK@worcesterma.gov
Councilor-At-Large Gary Rosen: RosenG@worcesterma.gov
Councilor-At-Large Kathleen M. Toomey: ToomeyK@worcesterma.gov
District 1 Councilor Sean M. Rose: RoseS@worcesterma.gov
District 2 Councilor Candy F. Mero-Carlson: Mero-CarlsonC@worcesterma.gov
District 3 Councilor George J. Russell: RussellG@worcesterma.gov
District 4 Councilor Sarai Rivera: RiveraSA@worcesterma.gov
District 5 Councilor Matthew E. Wally: WallyM@worcesterma.gov
City Manager Edward M. Augustus, Jr.: CityManager@worcesterma.gov

Dear [CITY OFFICIAL'S NAME],

My name is [YOUR NAME] and I am a resident of Worcester living in District [YOUR DISTRICT NUMBER]. I am writing to express my concern over the current proposed FY2021 operating budget allocating over $52 million to the Worcester Police Department (WPD). I do not support the WPD's budget increase of $254,320. Rather than invest in a system that has been founded on racist principles and has brought the unnecessary deaths of so many Black and Brown people nationwide, I urge that you reject this increase and reallocate that money towards services that will build up and support their communities instead.

[INSERT YOUR REASONS HERE; FEEL FREE TO PULL FROM THE SCRIPT BELOW. INCLUDE YOUR OWN PERSONAL EXPERIENCE]

In light of recent events across our country, I believe our view towards policing needs to change completely. Police can not be used as band-aids for social problems, while services that would actually benefit our community lack sufficient funding. Please consider the following:

- Black and brown people are being murdered by police with near impunity. The American Public Health Association has identified that police violence is a public health emergency and “U.S. policing has failed to equitably deliver safety, placing an inequitable burden of mental and physical harm on socially and economically marginalized populations.”

- Police are called to respond to situations they were never meant to solve. Creating true public safety means we must invest robustly in education, health care access, employment programs, transportation, affordable housing, and community restorative justice initiatives.

- Investments in more policing have never brought about reform. Cities like Dallas and Los Angeles are taking steps to shift their priorities. A comprehensive report on a 150-year review on the Minneapolis Police Department further proves the lack of success investing in police brings.

Community members have called into city council meetings, left messages, and wrote emails demanding a more inclusive process for citizen input in our budget. The City Council must take a stand for racial justice by significantly defunding policing and investing in real public safety for our community - starting with reallocating the proposed increase in WPD funding to various social services.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@mpuch012 this looks good to me! Thanks for your patience in the process. The next step is for someone from our development team to process your request. We've been a little swamped lately but it should be processed shortly.

**Comment by todd-m** [comment]
on it

**Comment by mpuch012** [comment]
Thanks! Will I get a notification of when it does get on the website?

**Comment by todd-m** [comment]
This letter is now live at [defund12.org/worcester](https://defund12.org/worcester). Thanks again for submitting!
