### ISSUE TITLE
Letter to Mayor Trantalis and Board of Fort Lauderdale City Commissioners, FL

### ISSUE THREAD

**Issue by rakf713** [defund12/defund12.org#1589]
To (City Commisioners): dtrantalis@fortlauderdale.gov; swyman@fortlauderdale.gov; zdurand@fortlauderdale.gov; RMcKinzie@fortlauderdale.gov; mconingsby@fortlauderdale.gov; SGlassman@fortlauderdale.gov; BSorensen@fortlauderdale.gov

Additional Emails (Aides): VHoward@fortlauderdale.gov; TRoach@fortlauderdale.gov; cgisleson@fortlauderdale.gov; praju@fortlauderdale.gov; Jusaavedra@fortlauderdale.gov; aheathcock@fortlauderdale.gov

Subject: Something unique relating to defunding/demilitarizing the police

Please edit the email to personalize it:
 
Dear Mayor Trantalis and Board of Fort Lauderdale City Commissioners,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the Mayor and City Commission support our community and hear our call for:

-Efforts to defund and de-escalate the police department, and to reallocate money to programs and city-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
-Rejection of expanded and militarized police budgets.
-Efforts to improve oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

As the City of Fort Lauderdale currently creates the budget for the 2021 fiscal year, we urge you to listen to your constituents and defund the police department. It is unacceptable that a third of our city budget, $130 million, goes towards the police, while critical departments such as Sustainable Development only receive $14 million. We are not asking for you to disband the police. We respect our officers and the safety they bring to our community; however, we are asking for you to take a stand and support people of color by allocating funds to other critical social services.

Moreover, we ask that you implement constructive and necessary reforms within the police department to keep our community safe. Tear gas is a chemical weapon banned in war, yet our own officers employed tear gas on peaceful protestors on Sunday, May 31st at the Black Lives Matter gathering. We understand the need to retaliate against agitators who infiltrate peaceful protestors, but tear gas should NOT be used under any circumstance. Police budgets should be used on effective training (including anti-racism coaching), not on chemical weapons, military-style equipment, or new infrastructure.

Since the 1970s, spending on police has nearly tripled, reaching $114.5 billion in 2017, much of that funding going towards detention centers. This is an unnecessary use of our resources. Lawmakers in at least 16 U.S. cities have proposed or made pledges that would divest resources from the police. As a country, we are hurting and demand change from our elected officials.

I urge you to reimagine the way the justice system works in Fort Lauderdale. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force. Until the city of Fort Lauderdale and Broward County does this, we are failing to serve communities of color.

We urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration. As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE ]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by rakf713** [comment]
How long does reviewing take? :p Would love to get this published!

**Comment by mahrer** [comment]
Hey @rakf713! Thanks for your patience. We are completely run by volunteers and it seems we're a bit behind right now, so I'll get the ball rolling on this.

The letter looks good, but I was wondering if you could put in more specific budget numbers to make it more compelling. I notice you said that a third of the budget goes towards police. Can we maybe compare the number of the police budget with the budgets of other departments? (If you link the budget document here, I can do that part.)

**Comment by rakf713** [comment]
Thanks @mahrer appreciate all of your support! I read in a news article that the budget is a third (or 35%). I was able to find the exact numbers and proposed budget for my county (Broward- thanks for helping with that letter!) but I'm struggling to find the information for my city (Fort Lauderdale) I imagine its here: https://www.fortlauderdale.gov/departments/city-manager-s-office/budget-cip-and-grants-division/annual-budgets

**Comment by rakf713** [comment]
@mahrer ok I just found this. The proposed budget for 2020 was $130.4 million. I'll do some more research! https://fortlauderdale.abalancingact.com/fy-2020-proposed-budget

**Comment by mahrer** [comment]
Hey @rakf713, here's an edited version with more data below. I also removed some respectability language towards police. 

---

To (City Commisioners): dtrantalis@fortlauderdale.gov; swyman@fortlauderdale.gov; zdurand@fortlauderdale.gov; RMcKinzie@fortlauderdale.gov; mconingsby@fortlauderdale.gov; SGlassman@fortlauderdale.gov; BSorensen@fortlauderdale.gov

Additional Emails (Aides): VHoward@fortlauderdale.gov; TRoach@fortlauderdale.gov; cgisleson@fortlauderdale.gov; praju@fortlauderdale.gov; Jusaavedra@fortlauderdale.gov; aheathcock@fortlauderdale.gov

Subject: Something unique relating to defunding/demilitarizing the police

Message:

Dear Mayor Trantalis and Board of Fort Lauderdale City Commissioners,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the Mayor and City Commission support our community and hear my call to:

- Defund and de-escalate the police department.
- Reallocate money to programs and city-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
- Reject expanded and militarized police budgets.
- Improve oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

As the City of Fort Lauderdale creates the budget for the 2021 fiscal year, we urge you to listen to your constituents and defund the police department. According to the FY 2020 Proposed Budget, $130.4 million is proposed to be allocated to the police department while only $50.5 million goes towards Parks and Recreation, $14 million goes towards Sustainable Development, $5.4 million goes towards Public Works, and $2.8 million goes towards Transportation and Mobility.

It is unacceptable that a third of our city budget, $130 million, goes towards the police, while critical departments such as Sustainable Development only receive $14 million. This is an unacceptable disparity in funding. I ask you to take a stand and support Black people, Indigenous people, and people of color in your community by allocating funds to other critical social services.

Moreover, I ask that you implement constructive and necessary reforms within the police department to keep our community safe. Tear gas is a chemical weapon banned in war, yet our own officers employed tear gas on peaceful protestors on Sunday, May 31st at the Black Lives Matter gathering. Tear gas should not be used under any circumstance. Police budgets should be used on effective training (including anti-racism coaching), not on chemical weapons, military-style equipment, or new infrastructure.

Since the 1970s, U.S. spending on police has nearly tripled, reaching $114.5 billion in 2017, much of that funding going towards detention centers. This is an unnecessary use of our resources. Lawmakers in at least 16 U.S. cities have proposed or made pledges that would divest resources from the police. As a country, we are hurting and demand change from our elected officials.

I urge you to reimagine the way the justice system works in Fort Lauderdale. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force. Until the city of Fort Lauderdale and Broward County does this, we are failing to serve communities of color.

We urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration. As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE ]
