### ISSUE TITLE
To Palmdale, CA City Council members

### ISSUE THREAD

**Issue by freegonzo** [defund12/defund12.org#1598]
To: shofbauer@cityofpalmdale.org, rloa@cityofpalmdale.org, abishop@cityofpalmdale.org, lbettencourt@cityofpalmdale.org, jcarrillo@cityofpalmdale.org
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)🔗
Dear City Council Members of Palmdale,
My name is [YOUR NAME] and I am a resident of Palmdale, California. It is clear that you all care deeply about our city and want to improve our home. I am emailing in support of the nationwide initiative to defund police departments in favor of supporting community based public safety measures. This includes an increased budget for social services to fight homelessness, addiction, mental illness, domestic violence, and sexual assault.  
As you know, George Floyd, Ahmaud Arbery, Breonna Taylor, Tony McDade, Atatiana Jefferson, Tamir Rice, Philando Castile, Anthony Hill, Oscar Grant, Eric Garner, Yvette Smith, Desmond Phillips, and so many unnamed others have been killed as a result of deeply-rooted systemic racism and police brutality.  This has led to a renewed focus on every city, including Palmdale, which is in need of reassessing local priorities on a national and perhaps even global stage. 
Residents want answers to Robert Fuller’s death and to feel safe, regardless of race.  According to NPR, Neo-Nazi groups have been reported in the area and the Justice Department has investigated discriminatory housing and policing practices Palmdale and our neighbor Lancaster.  Is this what we want to be known for as a city?  
As a result of these events, I ask that the city council review their 2020-2021 budget. I ask you to reallocate funds from the police department to other areas that desperately need it. These areas include community development, mental health treatment, affordable housing, funding for domestic violence shelters, and investing in the Black and Indigenous communities. 
Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (Sources: The Nation, The Atlantic). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.
I demand immediate reduction of the police force budget, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies. We should redirect police funding to efforts that are actually proven to reduce crime, such as affordable housing, shelters, and mental health services.
It is your duty to represent your constituents. I am urging you to revise the Palmdale, CA recommended operating budget for FY 2020-21, and to increase funds to non-punitive community efforts.
This is a small step in light of a national discussion including defunding, disarming, and disbanding police forces. Major cities nationwide are having these discussions and just because Palmdale isn’t a metropolitan area, does not mean that local Black Lives Matter any less. We should be having these discussions alongside the national narrative. We need to reimagine the systems that keep our community safe.
Thank you for all you do for the City of Palmdale, and for your consideration.
Sincerely, [YOUR NAME][YOUR ADDRESS] [YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
The copy has been edited slightly for grammar, flow, and clarity. I also added a source link for the NPR article mentioned. Aside from that, no major or message-impacting changes were made.

---------

To: shofbauer@cityofpalmdale.org, rloa@cityofpalmdale.org, abishop@cityofpalmdale.org, lbettencourt@cityofpalmdale.org, jcarrillo@cityofpalmdale.org
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)🔗
Dear City Council Members of Palmdale,
My name is [YOUR NAME] and I am a resident of Palmdale, California. It is clear that you all care deeply about our city and want to improve our home. I am emailing in support of the nationwide initiative to defund police departments in favor of supporting community-based public safety measures. This includes an increased budget for social services to fight homelessness, addiction, mental illness, domestic violence, and sexual assault.

As you know, George Floyd, Ahmaud Arbery, Breonna Taylor, Tony McDade, Atatiana Jefferson, Tamir Rice, Philando Castile, Anthony Hill, Oscar Grant, Eric Garner, Yvette Smith, Desmond Phillips, and so many unnamed others have been killed as a result of deeply-rooted systemic racism and police brutality in our country. This has led to a renewed focus in every city, including Palmdale, which is in need of reassessing local priorities on a national and perhaps even global stage.

Residents want answers to Robert Fuller’s death and to feel safe, regardless of race. According to NPR, [Neo-Nazi groups have been reported in the area and the Justice Department has investigated discriminatory housing and policing practices Palmdale and our neighbor Lancaster](https://www.npr.org/sections/live-updates-protests-for-racial-justice/2020/06/14/876807835/california-city-residents-demand-answers-after-black-man-found-hanging-from-tree). Is this what we want to be known for as a city?

As a result of these events, I ask that the city council review their 2020-2021 budget. I ask you to reallocate funds from the police department to other areas that desperately need it. These areas include community development, mental health treatment, affordable housing, funding for domestic violence shelters, and investing in the Black and Indigenous communities.

Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (Sources: The Nation, The Atlantic). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

I demand immediate reduction of the police force budget, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies. We should redirect police funding to efforts that are actually proven to reduce crime, such as affordable housing, shelters, and mental health services.

It is your duty to represent your constituents. I am urging you to revise the Palmdale, CA recommended operating budget for FY 2020-21, and to increase funds to non-punitive community efforts.

This is a small step in light of a national discussion including defunding, disarming, and disbanding police forces. Major cities nationwide are having these discussions and just because Palmdale isn’t a metropolitan area, does not mean that local Black Lives Matter any less. We should be having these discussions alongside the national narrative. We need to reimagine the systems that keep our community safe.

Thank you for all you do for the City of Palmdale, and for your consideration.
Sincerely, 
[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
I don't have labels permissions, but this entry is now ready for PR!
