### ISSUE TITLE
Error in Peoria, IL Email

### ISSUE THREAD

**Issue by lilmura** [defund12/defund12.org#1600]
The email has incorrect information and also a grammatical error about the 2020 budget. The correct sentence should read: 

The City of Peoria 2020 Budget dedicates 44% of the budget towards “Public Safety,” with 22% of the budget going to policing alone, while funding for the arts (9% of total budget), neighborhood livability (8%), and environmental health (17%) has been neglected.

This can be verified in the official report starting at around page 63 found here: http://www.peoriagov.org/2020-budget-information/

**Comment by mahrer** [comment]
Thanks for catching this! After these edits the entire email should read:

---

To: rali@peoriagov.org, bjensen@peoriagov.org, cgrayeb@peoriagov.org, dcyr@peoriagov.org, dmoore@peoriagov.org, jardis@peoriagov.org, jkelly@peoriagov.org, jmontelongo@peoriagov.org, sruckriegel@peoriagov.org, triggenbach@peoriagov.org, zoyler@peoriagov.org,

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]

Dear Peoria City Council members,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Peoria’s inordinate investment in the Peoria Police Department (PPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests, many Peoria residents are dismayed by the current conduct of the Peoria police.

I am therefore writing to demand that the City Council vote to defund the PPD and reapportion those funds to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens. It is concerning that the PPD on their website promotes "broken window" policing, which has been used to target Black Americans and has been shown to be ineffective at keeping our communities safe. The City of Peoria 2020 Budget dedicates 44% of the budget towards “Public Safety,” with 22% of the budget going to policing alone, while funding for the arts (9% of total budget), neighborhood livability (8%), and environmental health (17%) have been neglected. This is morally reprehensible.

I also urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Peoria without consequence.

People are marching in the streets because they know that these actions will result in a healthier, safer, more just society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
