### ISSUE TITLE
Letter to Dover City Government Officials

### ISSUE THREAD

**Issue by alecmiran** [defund12/defund12.org#1625]
![image](https://user-images.githubusercontent.com/67085549/84973299-c90d0480-b0ee-11ea-8a8b-3f5b42670415.png)

**Comment by alecmiran** [comment]
Letter to Dover City Government Officials
Dover, NH
To: r.carrier@dover.nh.gov, d.ciotti@dover.nh.gov, l.williams@dover.nh.gov, j.oconnor@dover.nh.gov, m.muffett-lipinski@dover.nh.gov, d.thibodeaux@dover.nh.govm, j.manley@dover.nh.gov, d.shanahan@dover.nh.gov, f.cullen@dover.nh.gov 

Hello,

I am a resident of Dover, writing to demand that the Dover Mayor and City Council adopt a budget prioritizing community wellbeing and redirecting funding away from the Dover Police Department.

Our country, state, and city are in the midst of widespread upheaval over the systemic violence of policing. At the same time, we face a growing economic crisis in the wake of COVID-19, with Dover’s unemployment rate at 17.3% as of April 2020. We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Despite the clear need to fund services dedicated to mental health, substance abuse, and affordable housing, the current budget proposal for FY 2021 calls for an increase of half a million dollars in funding for the Dover Police Department. More funding for Dover’s already 50-plus-officer force is not what our community needs in this moment. In a recent interview with Fosters, Police Chief Breault’s own words made plain why a shift away from increased funding for police is imperative right now. In describing the 22% increase in service calls since 2010, Chief Breault noted that this increase was largely driven by so-called “‘social service related calls,’ which include drugs, homelessness and mental illness.”

Under Chief Breault’s own reasoning, Dover needs to allocate funding for services that will address our interrelated crises in mental health resources, substance use treatment, and affordable housing. Our police officers are not experts in these fields, and it is unfair of us to demand that they shoulder these burdens in addition to their role as law enforcement. Our community’s challenges are best addressed with skilled and dedicated social workers and other support staff who can provide trained expertise and assistance in these interconnected areas that affect those in poverty and/or struggling with substance use. Adding more police officers and making them the first line of response in myriad crises does not effectively serve the needs of everyone in our community. I insist as a taxpayer of the city of Dover that funds be reallocated from the Dover Police into services that meet these needs. 

Finally, as we continue to witness acts of police brutality against people of color in the United States, this moment demands that we reorient funds in our community. We must stand with cities around the country who have called to defund the police. We likewise demand increased investment in services that provide support affordable housing, education, and other human services for the most in need. The current crises we face require a drastic reorienting of our priorities. Further funding for the police will not adequately address the issues we face today. 

Thank you for your time and attention,

[YOUR NAME][YOUR ADDRESS] [YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by alecmiran** [comment]
Hey, just wanted to see the status of this request? If it's ready to be posted, I was hoping to start sharing the link with some friends. Let me know if there are additional edits I need to make. Thanks!

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits below:

---

Letter to Dover City Government Officials
Dover, NH

To: r.carrier@dover.nh.gov, d.ciotti@dover.nh.gov, l.williams@dover.nh.gov, j.oconnor@dover.nh.gov, m.muffett-lipinski@dover.nh.gov, d.thibodeaux@dover.nh.govm, j.manley@dover.nh.gov, d.shanahan@dover.nh.gov, f.cullen@dover.nh.gov

Dear Dover City Government Officials,

I am a resident of Dover, writing to demand that the Dover Mayor and City Council adopt a budget prioritizing community wellbeing and redirecting funding away from the Dover Police Department.

Our country, state, and city are in the midst of widespread upheaval over the systemic violence of policing. At the same time, we face a growing economic crisis in the wake of COVID-19, with Dover’s unemployment rate at 17.3% as of April 2020. We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Despite the clear need to fund services dedicated to mental health, substance abuse, and affordable housing, the current budget proposal for FY 2021 calls for an increase of $511,672 in funding for the Dover Police Department. More funding for Dover’s already 50-plus-officer force is not what our community needs in this moment. In a recent interview with Fosters, Police Chief Breault’s own words made plain why a shift away from increased funding for police is imperative right now. In describing the 22% increase in service calls since 2010, Chief Breault noted that this increase was largely driven by so-called “‘social service related calls,’ which include drugs, homelessness and mental illness.”

Under Chief Breault’s own reasoning, Dover needs to allocate funding for services that will address our interrelated crises in mental health resources, substance use treatment, and affordable housing. Our police officers are not experts in these fields. Our community’s challenges are best addressed with skilled and dedicated social workers and other support staff who can provide trained expertise and assistance in these interconnected areas that affect those in poverty and/or struggling with substance use. Adding more police officers and making them the first line of response in myriad crises does not effectively serve the needs of everyone in our community. I insist as a taxpayer of the city of Dover that funds be reallocated from the Dover Police into services that meet these needs.

Finally, as we continue to witness acts of police brutality against People of Color in the United States, this moment demands that we reorient funds in our community. We must stand with cities around the country who have called to defund the police. I likewise demand increased investment in services that provide support affordable housing, education, and other human services for the most in need. The current crises we face requires a drastic reorienting of our priorities. Further funding for the police will not adequately address the issues we face today.

Thank you for your time and attention,

[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@alecmiran Now that it has been reviewed and fact checked, the dev team will process it shortly! Thanks for your patience.

**Comment by todd-m** [comment]
on it

**Comment by alecmiran** [comment]
So, is there anything else I need to do at this point or can it be posted? Just wanted to start sharing the link with friends. Thanks!

**Comment by mahrer** [comment]
@alecmiran just waiting on someone to close the pull request, thanks for your patience!
