### ISSUE TITLE
Please add Tiburon CA

### ISSUE THREAD

**Issue by jill3666** [defund12/defund12.org#1627]
To: town@townoftiburon.org , afredericks@townoftiburon.org , hollithiertiburontowncouncil@gmail.com , dkulik@townoftiburon.org , jryan@townoftiburon.org , jwelner@townoftiburon.org ,

Subject: [**INSERT UNIQUE SUBJECT LINE**]

My name is [YOUR NAME] and I am a resident of Tiburon. I am writing to demand that the Tiburon City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police and towards housing, jobs, youth programs, restorative justice and mental health workers to help the community. 

In FY2017-2018, the City of Tiburon allocated an egregious $3,137,544 to our police department and have only increased this amount since then. Next year, there will likely be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Tiburon Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Tiburon residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the budget for the 2020-2021 fiscal year and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
I made a few edits to sentence structure in the interest of grammar, flow, and clarity. I also changed "The city may recoup these funds..." to "The city **should** recoup these funds..." to strengthen the argument.
-------

Subject: [INSERT UNIQUE SUBJECT LINE]

My name is [YOUR NAME] and I am a resident of Tiburon. I am writing to demand that the Tiburon City Council adopt a city budget that prioritizes community well-being by redirecting funding away from the police and toward creating housing, jobs, youth programs, restorative justice and mental health workers to help the community.

In FY2017-2018, the City of Tiburon allocated an egregious $3,137,544 to our police department and have only increased this amount since then. Next year, there will likely be deficits as a result of the pandemic. The city should recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Tiburon Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Tiburon residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the budget for the 2020-2021 fiscal year and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
This is ready for pr.

**Comment by root2point0** [comment]
on it
