### ISSUE TITLE
UMD Must Cut Ties with UMPD and PGPD

### ISSUE THREAD

**Issue by mlewis1998** [defund12/defund12.org#1628]
To UMD President and Provost 

TO: pines@umd.edu, mrankin@umd.edu

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear President Pines,

I am writing to you today in both deep sorrow and hope. I am a [YEAR] at the University of Maryland, [college and major, if you wish]. [I am a [YEAR] graduate from the University of Maryland, [college and major, if you wish].]

On May 27th, the University of Minnesota published a statement on their commitment to the termination of their relationship with the Minneapolis Police Department, and I found their decision to be both extremely necessary and a promising first step in the university's efforts towards becoming a more just and equitable institution. The statement explains that campus police will no longer contract or collaborate with the MPD. 

As a [YOUR ROLE AT UMD, ALUMN, STUDENT, STAFF], I demand and insist that the University of Maryland follow the University of Minnesota’s example. Research has overwhelmingly demonstrated that police presence in schools and on university campuses target and harm Black, Brown and disabled students. A termination of the Concurrent Jurisdiction Agreement that binds the UMPD to the Prince George’s County Police Department is necessary to ensure a safer environment for our Black students and staff on campus, and thus a stronger and healthier community at UMD. The Prince George’s Police Department has a history of incidents of excessive force and corruption: a 2004 investigation by the DOJ; the brutal beating of an unarmed Black student in 2010 followed by a disturbing overturning of the officer’s conviction in 2014; a violent attack on a Black skateboarder right in front of our University’s Landmark apartments in 2019; and just this month two officers and their immediate supervisor were suspended for kicking a man twice while handcuffing him.

Furthermore, I believe the university has a responsibility to demilitarize the University of Maryland Police Department. Like the PGPD, the UMPD also has a history of violence and abuse of Black students. Just in 2016, an officer was suspended after terrorizing Black students at a graduation party with pepper spray when called to investigate a mere noise complaint. As of 2014, UMPD had received over $200k worth of equipment from the Department of Defense through their 1033 program which sends surplus military equipment to police departments across the country. According to a study conducted at USC, there is a positive and significant correlation between police militarization and the number of people killed in incidents with police. 

The number of Black students enrolling at the University of Maryland has been on a steady decline since 2006, with only a very slight increase in enrollment in 2019. Still, in 2019 Black students made up over a third of high school graduates in the state of Maryland, but only 11.1% of the freshman class enrolled at UMD. The disproportionate numbers of high school graduates and Maryland freshmen not only suggests biased admissions, but also exposes a failure on the University’s behalf to establish itself as a safe and welcoming environment for prospective Black students. In fact, the 2018 Campus Climate Survey reported that 67% of Black students surveyed at least somewhat agreed that hate and bias incidents negatively influenced their experiences at UMD, and 18% at least somewhat agreed that they had considered leaving UMD as a result of personal experiences of hate and bias incidents. Close to 30% of Black students reported they had considered leaving as a result of witnessing these events and more than twice as many Black students than white students surveyed reported that they greatly wished they chose a different university. This is clear proof of the hostile environment being cultivated on campus. The University has failed its alumni, and current and prospective Black students. 

Instead of these dangerous and hostile relationships, UMD can and should invest in more on-call staff trained in culturally specific responses for conflict resolution, personal development, drug and substance abuse, and mental health. Additionally, funds should be reallocated to spaces that support Black students and their experiences at UMD such as the Multicultural Involvement Community Advocacy Office, the Nyumburu Cultural Center and the African American Studies Department. All undergraduate students should be required to take AASP 100 and/or AASP 101 as a part of the general education requirements. I demand tangible and material changes to how the University operates. The time for discussions and task forces has passed, there is no middle ground. Vacuous statements on diversity and inclusion do nothing to keep Black and Brown students safe at UMD.

The University of Maryland claims to be an advocate for community based progress and learning and encourages students to “Do Good”, yet it maintains these dangerous and expensive relationships with PGPD, UMPD, and the Dept. of Defense. Our school has a long history of participating in, of glossing over, of ignoring racism and prejudice. A few examples from the many: Maryland Stadium memorialized a segregationist until 2015, maintained contracts with ICE despite student opposition, maintained relationships with MD Correctional Facilities and their exploitative labor practices, and was the site of a racially motivated murder in 2017. Due to the university’s minimal and non committal responses to the deaths of Richard Collins III and Jordan McNair, it is clear the administration does not value Black lives. Ending our relationship with PGPD and demilitarizing UMPD will not excuse our past transgressions, but it will be a step towards a safer, more just future. It’s time for the University of Maryland to actively stand by its students and lead Big Ten schools by example.

I will not be donating to the University of Maryland until it commits to divestment and demilitarization. 

Black Lives Matter.

Sincerely, 
[NAME] [College ‘year]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Made slight edits to punctuation.

----------

TO: pines@umd.edu, mrankin@umd.edu

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear President Pines and Provost Rankin,

I am writing to you today in both deep sorrow and hope. I am a [YEAR] at the University of Maryland, [college and major, if you wish]. [**or, if you're an alum**: I am a [YEAR] graduate from the University of Maryland, [college and major, if you wish].]

On May 27th, the University of Minnesota published a statement on their commitment to the termination of their relationship with the Minneapolis Police Department, and I found their decision to be both extremely necessary and a promising first step in the university's efforts towards becoming a more just and equitable institution. The statement explains that campus police will no longer contract or collaborate with the MPD.

As a [YOUR ROLE AT UMD, ALUMN, STUDENT, STAFF], I demand and insist that the University of Maryland follow the University of Minnesota’s example. Research has overwhelmingly demonstrated that police presence in schools and on university campuses target and harm Black, Brown, and disabled students. A termination of the Concurrent Jurisdiction Agreement that binds the UMPD to the Prince George’s County Police Department is necessary to ensure a safer environment for our Black students and staff on campus, and thus a stronger and healthier community at UMD. The Prince George’s Police Department has a history of incidents of excessive force and corruption: a 2004 investigation by the DOJ; the brutal beating of an unarmed Black student in 2010 followed by a disturbing overturning of the officer’s conviction in 2014; a violent attack on a Black skateboarder right in front of our University’s Landmark apartments in 2019; and just this month two officers and their immediate supervisor were suspended for kicking a man twice while handcuffing him.

Furthermore, I believe the university has a responsibility to demilitarize the University of Maryland Police Department. Like the PGPD, the UMPD also has a history of violence and abuse of Black students. Just in 2016, an officer was suspended after terrorizing Black students at a graduation party with pepper spray when called to investigate a mere noise complaint. As of 2014, UMPD had received over $200k worth of equipment from the Department of Defense through their 1033 program which sends surplus military equipment to police departments across the country. According to a study conducted at USC, there is a positive and significant correlation between police militarization and the number of people killed in incidents with police.

The number of Black students enrolling at the University of Maryland has been on a steady decline since 2006, with only a very slight increase in enrollment in 2019. Still, in 2019 Black students made up over a third of high school graduates in the state of Maryland, but only 11.1% of the freshman class enrolled at UMD. The disproportionate numbers of high school graduates and Maryland freshmen not only suggests biased admissions, but also exposes a failure on the University’s behalf to establish itself as a safe and welcoming environment for prospective Black students. In fact, the 2018 Campus Climate Survey reported that 67% of Black students surveyed at least somewhat agreed that hate and bias incidents negatively influenced their experiences at UMD, and 18% at least somewhat agreed that they had considered leaving UMD as a result of personal experiences of hate and bias incidents. Close to 30% of Black students reported they had considered leaving as a result of witnessing these events and more than twice as many Black students than white students surveyed reported that they greatly wished they chose a different university. This is clear proof of the hostile environment being cultivated on campus. The University has failed its alumni, and current and prospective Black students.

Instead of these dangerous and hostile relationships, UMD can and should invest in more on-call staff trained in culturally specific responses for conflict resolution, personal development, drug and substance abuse, and mental health. Additionally, funds should be reallocated to spaces that support Black students and their experiences at UMD such as the Multicultural Involvement Community Advocacy Office, the Nyumburu Cultural Center and the African American Studies Department. All undergraduate students should be required to take AASP 100 and/or AASP 101 as a part of the general education requirements. I demand tangible and material changes to how the University operates. The time for discussions and task forces has passed, there is no middle ground. Vacuous statements on diversity and inclusion do nothing to keep Black and Brown students safe at UMD.

The University of Maryland claims to be an advocate for community based progress and learning and encourages students to “Do Good,” yet it maintains these dangerous and expensive relationships with PGPD, UMPD, and the Dept. of Defense. Our school has a long history of participating in, of glossing over, of ignoring racism and prejudice. A few examples from the many: Maryland Stadium memorialized a segregationist until 2015, maintained contracts with ICE despite student opposition, maintained relationships with MD Correctional Facilities and their exploitative labor practices, and was the site of a racially-motivated murder in 2017. Due to the university’s minimal and non committal responses to the deaths of Richard Collins III and Jordan McNair, it is clear the administration does not value Black lives. Ending our relationship with PGPD and demilitarizing UMPD will not excuse our past transgressions, but it will be a step towards a safer, more just future. It’s time for the University of Maryland to actively stand by its students and lead Big Ten schools by example.

I will not be donating to the University of Maryland until it commits to divestment and demilitarization.

Black Lives Matter.

Sincerely,
[NAME] [College ‘year]

**Comment by erinb223** [comment]
Also wanna say that this letter is badass and thank you for writing it. It's ready for pr.
