### ISSUE TITLE
Please add Lynnwood, WA 

### ISSUE THREAD

**Issue by kaybc** [defund12/defund12.org#1647]
**Email addresses:** 
mayor@LynnwoodWA.gov; cfrizzell@LynnwoodWA.gov; ssessions@LynnwoodWA.gov; jcrosby@LynnwoodWA.gov; icotton@LynnwoodWA.gov; ghurst@LynnwoodWA.gov; rross@LynnwoodWA.gov; jsmith@LynnwoodWA.gov
Message: 

**Dear Lynnwood City Leadership,**

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the well documented history of police murdering Black people. I will no longer accept empty gestures and suggestions of “reform.” I am  demanding that my voice be heard now, and that real change be made to the way this city allocates its resources. 

In the 2019-2020 annual budget, the Lynnwood Police Department was granted $43,868,774, with an adopted budget of $22,811,762 in 2020. In contrast, community development was allocated a total of $3,611,495. Further, diversity efforts were not properly funded in the 2019-2020 budget, as a total of $50,000 was allocated to be split amongst the Parks and Recreation board, History and Heritage, and the Diversity, Equity, and Inclusion Commission. 

This pandemic has had severe economic consequences including high unemployment causing many people to be unable to pay rent.  Support for communities in need is necessary now, more than ever. In order to address this, funds must be diverted from the police department, as this money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

I demand that the City Council reduce the budget allocated to the Lynnwood Police Department. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of those who are at risk in Lynnwood. I demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Made one slight grammatical edit. 

-----------

Email addresses:
mayor@LynnwoodWA.gov; cfrizzell@LynnwoodWA.gov; ssessions@LynnwoodWA.gov; jcrosby@LynnwoodWA.gov; icotton@LynnwoodWA.gov; ghurst@LynnwoodWA.gov; rross@LynnwoodWA.gov; jsmith@LynnwoodWA.gov
Message:

Dear Lynnwood City Leadership,

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the well-documented history of police murdering Black people. I will no longer accept empty gestures and suggestions of “reform.” I am demanding that my voice be heard now, and that real change be made to the way this city allocates its resources.

In the 2019-2020 annual budget, the Lynnwood Police Department was granted $43,868,774, with an adopted budget of $22,811,762 in 2020. In contrast, community development was allocated a total of $3,611,495. Further, diversity efforts were not properly funded in the 2019-2020 budget, as a total of $50,000 was allocated to be split amongst the Parks and Recreation board, History and Heritage, and the Diversity, Equity, and Inclusion Commission.

This pandemic has had severe economic consequences including high unemployment causing many people to be unable to pay rent. Support for communities in need is necessary now, more than ever. In order to address this, funds must be diverted from the police department, as this money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

I demand that the City Council reduce the budget allocated to the Lynnwood Police Department. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of those who are at risk in Lynnwood. I demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
This is ready for pr

**Comment by root2point0** [comment]
on it
