### ISSUE TITLE
Victorvilla CA edit

### ISSUE THREAD

**Issue by mahrer** [defund12/defund12.org#1651]
Added paragraph written by @aurendisson about the recent death of Malcolm Harsch in Victorville:

---

To: ggarcia@victorvilleca.gov, rramirezdean@victorvilleca.gov, jcox@victorvilleca.gov, bagomez@victorvilleca.gov, dsjones@victorvilleca.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information! Please add a couple of sentences in your own words to avoid filters. )

Dear Gloria Garcia and City Council Members,

My name is [YOUR NAME], and I am a Victorville resident writing to urge you to defund the Victorville Police Department.

The 2019-2020 proposed budget for the city of Victorville allocated $27,132,208 for the police. The funding for police increased 6% this year while spending was decreased for community services by 3%, engineering by 45%, fire by 28%, public works by 11%, and water by 25%. In actuality, Victorville spent over $29.1 million renewing the contract with San Bernardino County Sheriff’s Department. The new contract granted 3% wage increases to employees for five years, beginning in August 2019; while those with prior experience trained in law enforcement were given an additional 1% increase for four years, starting January 2021.

The investment in policing has not made us safer. The police remain an embarrassment to the city and a lethal threat to Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With current finances already strained and other vital departments suffering, it is clear that we must defund the police. The city needs to prioritize infrastructure, community services, and mental health to properly serve the community's needs. Rather than spending $450,000 on technology in an attempt to help catch people running red lights, the budget could be spent on projects that lead to job creation or helping Victorville's ever-growing community of people experiencing houselessness.

The reality of violence against our Black community is playing out across the U.S., close by in other California cities, and in our own town. On May 31, Malcolm Harsch was found hanging from a tree by the Victorville City Library. While initially ruled a suicide, the possibility of a hate crime should be thoroughly investigated by an independent party. Only 50 miles away and 10 days later, Robert Fuller was found hanging from a tree in Palmdale, California, initially ruled a suicide. These tragedies should not be looked over, and these deaths should not be in vain.

As Victorville residents, we demand that you take immediate action to ensure the following:

Adopt a people’s budget that prioritizes community wellbeing and redirects funding away from the police.
Drastically reduce Victorville Police's allocation from the General Fund.
Disallow unauthorized overtime.
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers, which are all more effective at promoting community safety.
Victorville cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Victorville Police and end the city's contract with the San Bernardino's County Sheriff's Office.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it. made a few minor edits per style guide, that slipped through in the original.

Dear Mayor Garcia and City Council Members,

  My name is [YOUR NAME], and I am a Victorville resident writing to urge you to defund the Victorville Police Department.

  The 2019-2020 proposed budget for the city of Victorville allocated $27,132,208 for the police. The funding for police increased 6% this year while spending was decreased for community services by 3%, engineering by 45%, fire by 28%, public works by 11%, and water by 25%. In actuality, Victorville spent over $29.1 million renewing the contract with San Bernardino County Sheriff’s Department. The new contract granted 3% wage increases to employees for five years, beginning in August 2019; while those with prior experience trained in law enforcement were given an additional 1% increase for four years, starting January 2021.

  The investment in policing has not made us safer. The police remain a lethal threat to Black, Brown, and Indigenous communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With current finances already strained and other vital departments suffering, it is clear that we must defund the police. The city needs to prioritize infrastructure, community services, and mental health to properly serve the community's needs. 

  The reality of violence against our Black community is playing out across the U.S., close by in other California cities, and in our own town. On May 31, Malcolm Harsch was found hanging from a tree by the Victorville City Library. While initially ruled a suicide, the possibility of a hate crime should be thoroughly investigated by an independent party. Only 50 miles away and 10 days later, Robert Fuller was found hanging from a tree in Palmdale, California, initially ruled a suicide. These tragedies should not be overlooked, and these deaths must not be in vain.

  As a Victorville resident, I demand that you take immediate action to ensure the following:

  * Adopt a people’s budget that prioritizes community well-being and redirects funding away from the police.
  * Drastically reduce Victorville Police's allocation from the General Fund.
  * Disallow unauthorized overtime.
  * Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
  * Invest in housing, jobs, youth programs, restorative justice, and mental health workers, which are all more effective at promoting community safety.

  Victorville cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Victorville Police and end the city's contract with the San Bernardino's County Sheriff's Office.

  Thank you,

  [YOUR NAME]
  [YOUR ADDRESS]
  [YOUR EMAIL]
  [YOUR PHONE NUMBER]
