### ISSUE TITLE
Please add Salem, OR

### ISSUE THREAD

**Issue by SpencerDub** [defund12/defund12.org#1665]
budgetoffice@cityofsalem.net, citycouncil@cityofsalem.net, cbennett@cityofsalem.net, ckaser@cityofsalem.net, tandersen@cityofsalem.net, bnanke@cityofsalem.net, jleung@cityofsalem.net, mausec@cityofsalem.net, choy@cityofsalem.net, vnordyke@cityofsalem.net, jlewis@cityofsalem.net, manager@cityofsalem.net

Subject: [UNIQUE SUBJECT LINE]

Dear Mayor Bennett, City Manager Powers, City Councillors, and Budget Committee Members,

My name is [X] and I am a Salem resident. I understand that the Salem City Budget will soon be finalizing the budget for the 2020-21 fiscal year, and I urge you to oppose the increase in funding from $62.48mil in 2019-20 to $64.11mil in 2020-21. Rather than increasing our spending on policing, I'm urging you to meaningfully restrict it. How we spend our public funds expresses our values as a city, and I do not believe that our city should continue to over-invest scarce resources in the Salem Police Department.

Policing plays a strong role in enforcing racism and social control of communities of color through disempowerment, displacement, and repression. Black people and communities of color have been disproportionately targeted and brutalized by the police throughout American history. In Salem, especially at this time of unprecedented crisis, we must invest our scarce resources in the health and well-being of our communities rather than in expanding the scope and mandate of police.

Despite a decrease in crime over the past few decades, police funding across the United States has continued to increase, and the propose 2020-21 budget for Salem continues this nonsensical trend. Additionally, Salem police have received frivolous military-grade hardware from the Department of Defense's 1033 program, such as a mine-resistant vehicle. As a Salem citizen, I am strongly opposed to the expansion and militarization of our police force, and I am calling on you to reverse it.

The funds freed by meaningfully defunding the Salem Police Department could be spent on services that serve our community and address social issues at the root. Our neighbor to the south, Eugene, has set a fine example with their CAHOOTS (Crisis Assistance Helping Out On The Streets) program, which has been praised as a cost-effective approach based on de-escalation tactics and the skills of medical and mental health professionals. Funds currently allocated for police could also be spent to expand public housing, provide food assistance to Salem residents in need, and strengthen community mental health resources. The City of Salem could tackle systemic issues from the ground up instead of relying on police.

This moment of reckoning with our nation's history of racist policing practices is an opportunity to rethink public safety in this city and reinvest in services that more effectively benefit our residents. We know that meeting the basic needs of our communities is the only way to ensure their health and safety. This starts by divesting funding from the Salem Police Department in the upcoming 2020-21 financial year.

Thank you for your time,

[ YOUR NAME ]
[ YOUR ADDRESS ]
[ YOUR EMAIL ]
[ YOUR PHONE NUMBER ]

**Comment by SpencerDub** [comment]
[Here's the proposed 2020-21 budget.](https://www.cityofsalem.net/CityDocuments/proposed-budget-book-1-fy-2020-21.pdf)

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Great letter! @SpencerDub do you know when this vote to approve the budget takes place? It might be worth tweaking the language in the template so that the letter makes sense even after the vote takes place (saying something like on all future budget votes instead of this specific budget vote). I'll leave it for now!

Minor edits below:

---

budgetoffice@cityofsalem.net, citycouncil@cityofsalem.net, cbennett@cityofsalem.net, ckaser@cityofsalem.net, tandersen@cityofsalem.net, bnanke@cityofsalem.net, jleung@cityofsalem.net, mausec@cityofsalem.net, choy@cityofsalem.net, vnordyke@cityofsalem.net, jlewis@cityofsalem.net, manager@cityofsalem.net

Message:

Dear Mayor Bennett, City Manager Powers, City Councillors, and Budget Committee Members,

My name is [YOUR NAME] and I am a Salem resident. I understand that the Salem City Budget will soon be finalizing the budget for the 2020-21 fiscal year, and I urge you to oppose the increase in funding from $62.48mil in 2019-20 to $64.11mil in 2020-21. Rather than increasing our spending on policing, I'm urging you to meaningfully restrict it. How we spend our public funds expresses our values as a city, and I do not believe that our city should continue to over-invest scarce resources in the Salem Police Department.

Policing plays a strong role in enforcing racism and social control of communities of color through disempowerment, displacement, and repression. Black people and communities of color have been disproportionately targeted and brutalized by the police throughout American history. In Salem, especially at this time of unprecedented crisis, we must invest our scarce resources in the health and well-being of our communities rather than in expanding the scope and mandate of police.

Despite a decrease in crime over the past few decades, police funding across the United States has continued to increase, and the propose 2020-21 budget for Salem continues this nonsensical trend. Additionally, Salem police have received frivolous military-grade hardware from the Department of Defense's 1033 program, such as a mine-resistant vehicle. As a Salem citizen, I am strongly opposed to the expansion and militarization of our police force, and I am calling on you to reverse it.

The funds freed by meaningfully defunding the Salem Police Department could be spent on services that serve our community and address social issues at the root. Our neighbor to the south, Eugene, has set a fine example with their CAHOOTS (Crisis Assistance Helping Out On The Streets) program, which has been praised as a cost-effective approach based on de-escalation tactics and the skills of medical and mental health professionals. Funds currently allocated for police could also be spent to expand public housing, provide food assistance to Salem residents in need, and strengthen community mental health resources. The City of Salem could tackle systemic issues from the ground up instead of relying on police.

This moment of reckoning with our nation's history of racist policing practices is an opportunity to rethink public safety in this city and reinvest in services that more effectively benefit our residents. We know that meeting the basic needs of our communities is the only way to ensure their health and safety. This starts by divesting funding from the Salem Police Department in the upcoming 2020-21 financial year.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
