### ISSUE TITLE
Brevard County, Florida

### ISSUE THREAD

**Issue by rawtilapia** [defund12/defund12.org#1704]
To Brevard County Commissioners:
Commissioner Rita Pritchett - D1.Commissioner@BrevardFL.gov
Commissioner Bryan Lober - D2.Commissioner@BrevardFL.gov
Commissioner John Tobia - D3.Commissioner@BrevardFL.gov
Commissioner Kurt Smith - D4.Commissioner@BrevardFL.gov
Commissioner Kristine Isnardi - D5.Commissioner@BrevardFL.gov

Dear Brevard County Commissioners, 

My name is [YOUR NAME], resident of Brevard County.  I am writing to demand that the County Commissioners adopt a budget that prioritizes community well-being and redirects funding away from the Brevard County Sheriff’s Office.

The Brevard County Sheriff’s Department is asking for £1.33 billion dollars for next year’s budget, over 2x the budget of Brevard County schools. Reasons cited for the budget increases were “the cost of fighting the opioid crisis and the increased expense to help protect local schools in the wake of the Parkland shootings last year”. (https://eu.floridatoday.com/story/news/local/2019/09/24/brevard-commissioners-ok-1-33-b-budget-sheriffs-critical-needs/2427044001/)   Both these issues are social issues that will not be solved by more officers with guns. These are social issues that need to be alleviated by allocating more funds on rehabilitation programs for drug users and  mental health services for students. Another reason cited for an increased police budget is outdated vehicles, while 65% of Brevard County public schools have buildings that are over 50 years old and are in need of regular renovations, maintenance and repairs. 

I urge Brevard County Commissioners to address its Vision to provide for the health, safety, education and local needs of the community and shift funds from the Sheriff Department in order to have the budget to bolster educational needs, including educational infrastructure, mental health services and job support, which will prevent crime from happening and protect Brevard citizens instead of criminalizing them.
 
Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by rawtilapia** [comment]
Addresses for the commissioners:

District 1
Commissioner Rita Pritchett
2000 South Washington Avenue
2nd Floor
Titusville, Florida 32780

District 2
Commissioner Bryan Lober
Merritt Island Service Complex
2575 North Courtenay Parkway Suite 200
Merritt Island, Florida 32953

District 3
Commissioner John Tobia
2539 Palm Bay Rd. N.E.
Suite 4
Palm Bay, Florida 32905

District 4
Commissioner Curt Smith
2725 Judge Fran Jamieson Way
Building C Suite 214
Viera, Florida 32940

District 5
Commissioner Kristine Isnardi
490 Centre Lake Drive
Suite 175
Palm Bay, Florida 32907

**Comment by aurendisson** [comment]
Editing notes: I removed references to "crime" per our style and tightened copy in various areas throughout.
Stats confirmed via: https://eu.floridatoday.com/story/news/local/2019/09/24/brevard-commissioners-ok-1-33-b-budget-sheriffs-critical-needs/2427044001/ 
https://www.floridatoday.com/story/news/2017/09/08/brevard-school-buildings-shelters-in-good-shape-take-irma/645297001/

To: D1.Commissioner@BrevardFL.gov, D2.Commissioner@BrevardFL.gov, D3.Commissioner@BrevardFL.gov, D4.Commissioner@BrevardFL.gov, D5.Commissioner@BrevardFL.gov

Dear Brevard County Commissioners,

My name is [YOUR NAME], a resident of Brevard County. I am writing to demand that the county commissioners adopt a budget that prioritizes community well-being and redirects funding away from the Brevard County Sheriff’s Office.

The Brevard County Sheriff’s Department is asking for $1.33 billion for next year’s budget, over twice the budget of Brevard County schools. Reasons cited for the budget increases were outdated vehicles and “the cost of fighting the opioid crisis and the increased expense to help protect local schools in the wake of the Parkland shootings last year.” Both of these issues are social issues that will not be solved by more officers with guns. These are issues that need to be alleviated by allocating more funds to rehabilitation programs for drug users and mental health services for students. Our schools are also underfunded, with the majority of Brevard County public school buildings being over 50 years old and need regular renovations, maintenance, and repairs.

I urge Brevard County commissioners to address its vision to provide for the health, safety, education, and local needs of the community. Shift funds from the Sheriff Department in order to have the budget to bolster educational needs, including educational infrastructure, mental health services, and job support.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
