### ISSUE TITLE
Decatur, Alabama

### ISSUE THREAD

**Issue by rawtilapia** [defund12/defund12.org#1708]
Mayor Tab Bowling
402 Lee Street NE
Decatur, AL 35601
(256) 341-4502

tbowling@decatur-al.gov

To The Honorable Mayor Tab Bowling:

My name is [YOUR NAME], resident of Decatur.  I am writing to demand that the City of Decatur adopt a budget that prioritizes community well-being and redirects funding away from the police.
The police department had been allocated over $14 million for police last year, yet only £1 million for community development and only $800,000 for youth services that could be used to bolster the community and prevent crimes from occurring in the first place.

Furthermore the events of that transpired on March 15th, 2020 with business owner Kevin Penn, are unacceptable. Mr. Penn called the police in a time of need because of a robbery in his shop and was then assaulted by the police himself when they responded to his call. We, as residents of Decatur, demand that police reports and other records related to the case, including the personnel files of the officer who punched Penn and all unedited body camera video of the incident be released to the public and the investigation be completed in a timely manner. 

This behaviour did not stand up to the Decatur Police Core Values of having a servant’s heart, being a problem solver, or being compassionate. The officer who used this excessive use of force should be fired immediately, arrested and charged with assault. 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

https://www.decaturalabamausa.com/wp-content/uploads/2020/06/CAFR-September-30-2019.pdf

https://www.al.com/news/2020/06/decatur-police-officer-punches-liquor-store-owner-who-reported-robbery.html

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: I added email addresses of the city council members, removed references to preventing crime per our style, used more specific budget numbers. Thank you for sharing the links to news and budget resources! 

https://www.decaturalabamausa.com/wp-content/uploads/2020/06/CAFR-September-30-2019.pdf
https://www.al.com/news/2020/06/decatur-police-officer-punches-liquor-store-owner-who-reported-robbery.html

To: tbowling@decatur-al.gov, wejackson@decatur-al.gov, khill@decatur-al.gov, pbibbee@decatur-al.gov, ckirby@decatur-al.gov, card@decatur-al.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!) 

Dear Honorable Mayor Tab Bowling and Decatur City Council Members,

My name is [YOUR NAME], resident of Decatur. I am writing to demand that the City of Decatur adopt a budget that prioritizes community well-being and redirects funding away from the police.

The police department had been allocated over $14 million last year, yet only $1,045,635 for community development and only $850,401  for youth services that could be used to bolster the community more efficiently than policing. 

Furthermore, the events that transpired on March 15, 2020, with business owner Kevin Penn are unacceptable. Mr. Penn called the police in a time of need because of a robbery in his shop and was then assaulted by the police himself when they responded to his call. We, as residents of Decatur, demand a thorough investigation and that police reports and other records related to the case, including the personnel files of the officer who punched Penn, and all unedited body camera video of the incident be released to the public. 

This behavior did not stand up to the Decatur Police Core Values of having a servant’s heart, being a problem-solver, or being compassionate. The officer who used this excessive use of force should be fired immediately, arrested, and charged with assault.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
