### ISSUE TITLE
please add Anne Arundel County, MD

### ISSUE THREAD

**Issue by leachnotabug** [defund12/defund12.org#1713]
send to :: expitt99@aacounty.org , slacey@aacounty.org , allison.pickard@aacounty.org , nathan.volke@aacounty.org , andrew.pruski@aacounty.org , amanda.fiedler@aacounty.org , lisa.rodvien@aacounty.org , Jessica.Haire@aacounty.org , 

Dear County Executive Steuart Pittman and Anne Arundel County Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD]. I write this letter to urge you to defund the Anne Arundel County Police Department & reallocate funds into projects that prioritize community services such as health, rehabilitation, housing, employment.

Maryland has the highest number of Black men incarcerated per capita. It is crucial we address the policies in which systematic racism has become a norm. Why should the police be funded given their history of violence within our community? Every member of our community deserves a quality of life that promotes safety, justice & the ability to live without fear from the government/police.

The Anne Arundel County Police Department is to be allocated 11% of the 2021 budget. 88 million of the allocated 156 million will be going to Patrol Services, of which is included School Resource Officers – "Partner with County Board of Education to assist with identifying students at risk for academic failure, truancy, and/or involvement in criminal activities." (a direct link in the school to prison pipeline). While the entire department Social Services is being allocated 3.2% of the total 2021 budget.
(Source: Anne Arundel County FY2021 Proposed Budget Message and Current Expense Budget) .

As residents of Anne Arundel County, we demand that you take immediate action to ensure the health, safety & wellness of our people.
Defund the Police Department.
Invest in social services that allow help & guidance to those in need, rather than incarceration.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Invest in community development initiatives and programs.
Invest in environmental restoration & policy.
Anne Arundel County is filled with beautiful humans, souls, wilderness areas and opportunities. As the 5th largest county in Maryland, we residents demand change! A reform that reflects the people.

Thank you,

[YOUR NAME][YOUR ADDRESS]
[YOUR PHONE][YOUR EMAIL]

**Comment by mahrer** [comment]
Hi @leachnotabug! Thanks for your interest in adding Anne Arundel County to the site. Can you edit your email comment to provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers? To get your submission published quicker, please provide source(s) for the data as well.

I see you mentioned a $10 million budget for police infrastructure in the third paragraph. I think it would be effective to add a few more numbers here, perhaps comparing this budget to the budgets of other programs, or maybe comparing to previous police budgets if there has been an increase. Also, would you mind citing the source of this number?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by leachnotabug** [comment]
ok thank you! i have updated the letter.
let me know if this has more detail which can offer a more compelling argument.

thanks
molly

**Comment by mahrer** [comment]
Thank you! Some minor edits below:

---

Send to: 
expitt99@aacounty.org , slacey@aacounty.org , allison.pickard@aacounty.org , nathan.volke@aacounty.org , andrew.pruski@aacounty.org , amanda.fiedler@aacounty.org , lisa.rodvien@aacounty.org , Jessica.Haire@aacounty.org

Dear County Executive Steuart Pittman and Anne Arundel County Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD]. I write this letter to urge you to defund the Anne Arundel County Police Department and reallocate funds into projects that prioritize community services such as health, rehabilitation, housing, employment.

Maryland has the highest number of Black men incarcerated per capita. It is crucial we address the policies in which systematic racism has become a norm. Why should the police be funded given their history of violence within our community? Every member of our community deserves a quality of life that promotes safety, justice and the ability to live without fear from the government/police.

The Anne Arundel County Police Department is to be allocated 11% of the 2021 budget. $88 million of the allocated $156 million will be going to Patrol Services. This includes School Resource Officers, who "Partner with County Board of Education to assist with identifying students at risk for academic failure, truancy, and/or involvement in criminal activities." (a direct link in the school to prison pipeline). Meanwhile, the entire department Social Services is allocated 3.2% of the total 2021 budget (Source: Anne Arundel County FY2021 Proposed Budget Message and Current Expense Budget).

As a resident of Anne Arundel County, I demand that you take immediate action to ensure the health, safety & wellness of our people.
Defund the Police Department.
Invest in social services that allow help & guidance to those in need, rather than incarceration.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Invest in community development initiatives and programs.
Invest in environmental restoration and policy.
Anne Arundel County is filled with beautiful humans, souls, wilderness areas and opportunities. As the 5th largest county in Maryland, we residents demand change! A reform that reflects the people.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

**Comment by leachnotabug** [comment]
looks good!

**Comment by root2point0** [comment]
on it
