### ISSUE TITLE
Please add Avon, CO

### ISSUE THREAD

**Issue by Levinator55** [defund12/defund12.org#1718]
- Email addresses (at least one) of the government officials you’d like to receive the message:

jfancher@avon.org; shymes@avon.org; jwolf@avon.org; sprince@avon.org; aphillips@avon.org; cthuon@avon.org; tunderwood@avon.org

- Detailed message concerning the budgeting decisions at stake in your community

Dear Avon Town Council,

My name is [INSERT YOUR NAME HERE] and I am writing to demand the defunding of the Avon Police Department and a reallocation to social and public programs for our community. 

The Avon Police Department was funded $4,320,911 for 2020. This is $401,758 more than in 2019 and is part of a trend happening yearly since at least 2010. Adjusted for inflation has been increased a total of $1,304,684 since 2010. Additionally, the City of Rifle, CO is spending $1,076,212 less on their police budget than the Town of Avon is spending in 2020. The City of Rifle also has significantly more people than the Town of Avon does. The Town of Avon police spending is excessive and must be reallocated.

I demand a budget that adequately and effectively meets the needs of at-risk Avon residents. I call on you to meaningfully restrict the Avon Police Department budget and instead meaningfully reallocate funds towards social programs and resources that support health care, child care, education, affordable housing, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowering the police forces that tear us apart.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: I formatted up top and tightened the copy around police budget. I also removed the reference to the budget increasing annually since 2010 because the budget was lower in 2012. I removed the reference to inflation and updated the numbers based on budgets.
Current police budget confirmed here: https://www.avon.org/DocumentCenter/View/20017/2020-Adopted-Budget 
2010 police budget: https://www.avon.org/DocumentCenter/View/17545/2010-Website-Budget?bidId= 

To: jfancher@avon.org, shymes@avon.org, jwolf@avon.org, sprince@avon.org, aphillips@avon.org, cthuon@avon.org, tunderwood@avon.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

Dear Avon Town Council,

My name is [INSERT YOUR NAME HERE] and I am writing to demand the defunding of the Avon Police Department and reallocation to social and public programs for our community.

The Avon Police Department was funded $4,320,911 for 2020. This is $401,758 more than in 2019 and is part of a trend of increasing police budgeting since at least 2010. The Avon Police Department has been increased a total of $1,756,764 since 2010. Additionally, the City of Rifle, Colorado, is budgeting $1,076,212 less for its police budget than Avon, despite Rifle's higher population. The Town of Avon's police spending is excessive and must be reallocated.

I demand a budget that adequately and effectively meets the needs of at-risk Avon residents. I call on you to meaningfully restrict the Avon Police Department budget and instead meaningfully reallocate funds towards social programs and resources that support health care, child care, education, affordable housing, and other critical community needs. We demand a budget that supports community well-being, rather than empowering the police forces that tear us apart.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
