### ISSUE TITLE
Please add Kissimmee, Florida

### ISSUE THREAD

**Issue by mayakendra** [defund12/defund12.org#1721]
TO: jaalvarez@kissimmee.org , ogonzalez@kissimmee.org , fortiz@kissimmee.org , aeady@kissimmee.org , jfisher@kissimmee.org 

My name is [YOUR NAME] and I live in [AREA/NEIGHBORHOOD]. I am writing to you today to demand the immediate reallocation of funds away from the Kissimmee Police Department and into desperately needed community resources and programs. Specifically in the form of: safe and affordable housing, a living wage, more accessible and extensive public transport, services and shelter for the homeless and vulnerable populations, ensured investment in community based food banks, co-ops and gardens, free and non-coercive healthcare infrastructure, economic assistance, COVID-19 relief, youth programs that promote safety and wellbeing, and equal job and educational opportunities for all.

In the adopted 2020 budget the Kissimmee Police Department is slated to receive 25 million dollars. Significantly more than any other department in the General Fund and more than several other departments combined. Yet while this generous funding of our communities policing takes place; Social and Quality of Life Services throughout the city remain critically defunded. With places like the Osceola Council on Aging, HOPE Community Center, Park Place Behavioral Healthcare, and the Osceola County Boys and Girls Club, left amongst other groups to share a mere $350,000. While it is easy to see this absurd disparity in funding. To put this number into further context, this year alone KPD will spend more than $350,000 just putting gas in their cars.

Are the needs of the people not worth more? 

I invite you to imagine what 25 million dollars could do if it were poured into the people of this city instead of a system designed to keep our most vulnerable enslaved. To imagine what our schools, our libraries, our hospitals, our community centers, our parks, our buses, our roads could look like. To imagine what our people could do if they were adequately cared for. We do not need more police. Now more than ever it is evident cops do not make our cities any safer. In fact their very existence actively drains from the resources that do. 

Elected officials, your action is imperative. The members of this community refuse to continue to support a budget that does not meet the needs of its people. Can I count on you to reallocate and reinvest these funds? If not, you can count on me to help vote you out.

Sincerely, 
[YOUR NAME HERE]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mayakendra** [comment]
Link to annual budget for City of Kissimmee : https://www.kissimmee.org/government/finance/annual-budget-documents

**Comment by aurendisson** [comment]
Editing notes: I tightened up some copy, removing a few sentences in order to have the message be a little more direct. I used the exact numbers for budget stats (and did a double-take at that shared social and quality-of-life services fund wow). https://www.kissimmee.org/home/showdocument?id=7124 

To: jaalvarez@kissimmee.org, ogonzalez@kissimmee.org, fortiz@kissimmee.org, aeady@kissimmee.org, jfisher@kissimmee.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

My name is [YOUR NAME] and I live in [AREA/NEIGHBORHOOD]. I am writing to you today to demand the immediate reallocation of funds away from the Kissimmee Police Department and into desperately needed community resources and programs. Specifically, I am advocating for safe and affordable housing, a living wage, more accessible and extensive public transport, services and shelter for the homeless and vulnerable populations, investment in community-based food banks, co-ops and gardens, free and non-coercive health care infrastructure, economic assistance, COVID-19 relief, youth programs that promote safety and well-being, and equal job and educational opportunities for all.

In the adopted 2020 budget, the Kissimmee Police Department is slated to receive $25,698,675, significantly more than any other department in the General Fund and more than several other departments combined. While this generous funding of our city's policing takes place, social and quality-of-life services throughout Kissimmee remain critically underfunded. Precious resources such as the Osceola County Council on Aging, HOPE Community Center, Park Place Behavioral Healthcare, Boys and Girls Club of Osceola County, and more are left to share a mere $350,000. 

Are the needs of the people not worth more? 

I invite you to imagine what $25 million could do if it were poured into the people of this city instead of a system designed to keep our most vulnerable enslaved. Imagine what our schools, our libraries, our hospitals, our community centers, our parks, our buses, our roads could look like. Imagine what our people could do if they were adequately cared for. We do not need more police. Now, more than ever, it is evident cops do not make our cities any safer. In fact, their very existence actively drains from the resources that do. 

Elected officials, your action is imperative. The members of this community refuse to continue to support a budget that does not meet the needs of its people. Can I count on you to reallocate and reinvest these funds? If not, you can count on me to help vote you out.

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
