### ISSUE TITLE
Letter for Hummelstown, PA

### ISSUE THREAD

**Issue by thakurs4** [defund12/defund12.org#1722]
[https://tinyurl.com/y7ffxcye](url)

borough@hummelstown.net,
Mokeefe@hummelstown.net,
wryan@hummelstown.net, dhummer@hummelstown.net,
dspittle@hummelstown.net

[Insert Unique Subject Line]

Dear Administration of the Borough of Hummelstown,

My name is {...} and I am a resident of Hummelstown, PA. I am writing to you today to discuss defunding the Hummelstown Police Department.

In 2015, former Hummelstown Police Officer Lisa Mearkle fatally shot 59-year-old man David Kassik during a traffic stop and was acquitted of all charges. Even if the police department reached a settlement, that man will never get his life back. Furthermore, she tazed and subdued him before firing, which means that she could have avoided risking his life by shooting him. You must improve police officers’ training so they know how to de-escalate situations before using firearms.

Upon review of the Hummelstown Borough website, there was no clear mention of how much of the budget was going toward the police department. This should be amended. For residents to be properly aware of where their money is going, there should be a clear budget delineated regularly. 

Instead of increasing the police budget, it would be better for the community of Hummelstown if we invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Sincerely,
[Name, Address, Email, Phone Number]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

A couple of notes:
- This is the first time I've seen no budget available online - usually we require submitters to include budget numbers, but since they aren't available, I think this will suffice.
- Regarding the third paragraph: although more training may be beneficial, our mission at defund12 is to focus on defund the police, not reforming them. The reviewer may choose to change or omit this paragraph.

**Comment by aurendisson** [comment]
Editing notes: Thank you for submitting! This is the 20th email I've edited and the first with no budget, so I was a bit surprised to not find one on the city website. Thank you for advocating for records to be available! I added that the "Right-to-Know Law" being on the website is not sufficient. https://www.hummelstown.net/index.asp?SEC=95AAAC8C-4804-4989-8748-46C02766BD8F&Type=B_BASIC 
I agree with mahrer's note about reform, so I reworded that sentence to read, "De-escalation training and holding police officers accountable should be a priority along with defunding the Hummelstown Police Department." 

To: borough@hummelstown.net, mokeefe@hummelstown.net, wryan@hummelstown.net, dhummer@hummelstown.net, dspittle@hummelstown.net

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

Dear Administration of the Borough of Hummelstown,

My name is [YOUR NAME] and I am a resident of Hummelstown, Pennsylvania. I am writing to you today to discuss defunding the Hummelstown Police Department.

In 2015, former Hummelstown Police Officer Lisa Mearkle fatally shot 59-year-old man David Kassik during a traffic stop and was acquitted of all charges. Even if the police department reached a settlement, that man will never get his life back. Furthermore, she tased and subdued him before shooting him in the back. De-escalation training and holding police officers accountable should be a priority along with defunding the Hummelstown Police Department. 

Upon review of the Hummelstown Borough website, there was no clear mention of how much of the budget was going toward the police department. This should be amended. For residents to be properly aware of where their money is going, there should be a clear budget delineated regularly. The Open Records and "Right-to-Know Law" on the website is not sufficient. 

Instead of increasing the police budget, it would be better for the community of Hummelstown if we invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
