### ISSUE TITLE
Please add Cook County, IL

### ISSUE THREAD

**Issue by marykohl3** [defund12/defund12.org#1749]
(hello! I think I followed all the guidelines but if I left anything out please let me know!) 

To: 
President Toni Preckwinkle
118 N. Clark St.
Room 537
Chicago, IL 60602
United States

Message: (Don't forget to replace the [x]'s with your information!)

Dear President Toni Preckwinkle, 
	My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. While I am glad to hear about Cook County passing a resolution to reduce police funding, I am writing to you today to ask you and the rest of the Cook County Board to set mandated deadlines and expectations for defunding the Cook County PD. 
	According to the 2021 Cook County Preliminary Budget Forecast, the police department’s budget is increasing to $75,308,817 from the 2020 Approved and Adopted $69,998,591. Police funding needs to be reduced and put towards programs like community development, COVID relief, and education.
	Thank you for your support in defunding the police and I look forward to hearing about the action steps you and the rest of the Cook County Board plan on taking.

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: I added emails for the board and made the language a bit more forceful (demanding instead of asking). Budget numbers confirmed here: https://www.cookcountyil.gov/sites/default/files/service/2021-cook-county-preliminary-forecast.pdf 

To: cookcountyboard@cookcountyil.gov, Brandon.johnson@cookcountyil.gov, Dennis.Deer@cookcountyil.gov, bill.lowry@cookcountyil.gov, stanley.moore2@cookcountyil.gov, deborah.sims@cookcountyil.gov, donna.miller@cookcountyil.gov, alma.anaya@cookcountyil.gov, cookcty9@aol.com, luis.arroyojr@cookcountyil.gov, district10@cookcountyil.gov, john.daley@cookcountyil.gov, bridget.degnen@cookcountyil.gov, lsuffredin@aol.com, Scott.Britton@cookcountyil.gov, kevin.morrison@cookcountyil.gov, Frank.Aguilar@cookcountyil.gov, sean.morrison@cookcountyil.gov 

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

Dear President Toni Preckwinkle and Cook County Board of Commissioners,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. While I am glad to hear about Cook County passing a resolution to reduce police funding, I am writing to you today to demand the Cook County Board to set mandated deadlines and expectations for defunding the Cook County Sheriff's Office.

According to the 2021 Cook County Preliminary Budget Forecast, the police department’s budget is increasing to $75,308,817 from the 2020 approved and adopted $69,998,591. Police funding needs to instead be reduced and put towards programs like community development, COVID-19 care and economic relief, and education.

Thank you for your support in defunding the police, and I look forward to hearing about the action steps the Cook County Board plans on taking.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE]
