### ISSUE TITLE
Orange County, Florida

### ISSUE THREAD

**Issue by rawtilapia** [defund12/defund12.org#1766]
Mayor Jerry L. Demings 
201 S. Rosalind Avenue, 5th floor Orlando, Florida 32801

mayor@ocfl.net
District1@ocfl.net
District2@ocfl.net
District3@ocfl.net
District4@ocfl.net
District5@ocfl.net
District6@ocfl.net

Dear Mayor Demings and County Commissioners:

My name is [YOUR NAME], resident of Orange County, Florida. In light of the Black Lives Matter movement, I am writing to request that your budget for next year prioritizes community well-being and redirects funding away from law enforcement and corrections facilities to continue to disproportionately target Black Americans and other minorities.

This year’s budget allotted $279 million towards police services, a $16.4 million increase over last year. I understand safety is a top priority for Orange County, however after these tragic encounters with the police that keep occurring time and time again, it’s naive to think that having more officers and a bigger budget will actually contribute to keeping communities safer. 

I propose that instead of increasing police budgets, we increase the budget for Mayor Demings' Housing for All initiative and other programs that will bolster education, help people in need and reduce the need for punitive policing.  I also propose removing all police from schools in order to cut the school to prison pipeline.

I, as your constituent, urge you to take a closer look at what Orange County can do to mitigate the harm that has been caused by the over-policing of minorities throughout the years and become a leader in creating a community where residents have resources available to them to break the systemic cycle of criminality that has been the norm in the United States for so many years.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
 
Source: https://www.orangecountyfl.net/Portals/0/resource%20library/open%20government/OrangeCountyAdoptedFiscalYear2020Budget.pdf

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: I formatted a little and was more specific with wording about the BLM movement. Budget is confirmed here: https://www.orangecountyfl.net/Portals/0/resource%20library/open%20government/OrangeCountyAdoptedFiscalYear2020Budget.pdf  

To: mayor@ocfl.net, District1@ocfl.net, District2@ocfl.net, District3@ocfl.net, District4@ocfl.net, District5@ocfl.net, District6@ocfl.net

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

Dear Mayor Demings and County Commissioners,

My name is [YOUR NAME], a resident of Orange County, Florida. In light of the recent protests surrounding police brutality, I am writing to request that your budget for next year prioritizes community well-being and redirects funding away from law enforcement and corrections facilities that continue to disproportionately target Black, Brown, and Indigenous Americans and other minorities.

The 2019-2020 budget allotted $279 million towards police services, a $16.4 million increase over the previous period. I understand safety is a top priority for Orange County. However, after witnessing these tragic encounters with the police that keep occurring time and time again, it’s naive to think that having more officers and a bigger budget will actually contribute to keeping communities safer.

I propose that instead of increasing police budgets, we increase the budget for Mayor Demings' Housing for All Task Force and other programs that will bolster education, help people in need, and reduce the need for punitive policing. I also propose removing all police from schools in order to cut the school-to-prison pipeline.

I, as your constituent, urge you to take a closer look at what Orange County can do to mitigate the harm that has been caused by the over-policing of minorities throughout the years, and become a leader in creating a community where residents have resources available to them to break the systemic cycle of criminality that has been the norm in the U.S. for so many years.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE]
