### ISSUE TITLE
Please Add Greensboro North Carolina. 

### ISSUE THREAD

**Issue by racistswilldiecallousanddiseased** [defund12/defund12.org#215]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by serifluous** [comment]
Notice on [city council email form](https://www.greensboro-nc.gov/government/city-council/e-mail-city-council): "Any e-mail sent is subject to the public records law and will be made available to the media. This communication is not confidential. All threats and harassment will be logged." See issue #306 .

Emails:
City Manager David Parrish, david.parrish@greensboro-nc.gov
Mayor Nancy Vaughan, nancy.vaughan@greensboro-nc.gov
Mayor Pro Tem Yvonne Johnson, yvonne.johnson@greensboro-nc.gov
Council At-Large Marikay Abuzuaiter, marikay.abuzuaiter@greensboro-nc.gov
Council At-Large Michelle Kennedy, michelle.kennedy@greensboro-nc.gov
District 1 Councilmember Sharon Hightower, sharon.hightower@greensboro-nc.gov
District 2 Councilmember Goldie Wells, goldie.wells@greensboro-nc.gov
District 3 Councilmember Justin Outling, jason.outling@greensboro-nc.gov
District 4 Councilmember Nancy Hoffmann, nancy.hoffmann@greensboro-nc.gov
District 5 Councilmember Tammi Thurm, tammi.thurm@greensboro-nc.gov

[2020–21 budget info](https://www.greensboro-nc.gov/home/showdocument?id=45773):
- $78,583,248 for police department recommended by City Manager for 2020–21. (p15)
- $76,559,015 of that would be contributed by the general fund (p135), which is 25% of the total general fund expenditure (p28).
- Saw a 4% increase in crime in 2018–2019 (p136), despite a 4% increase in their budget that same fiscal year ([p16 of the 2019–20 budget](https://www.greensboro-nc.gov/home/showdocument?id=43275)).

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
