### ISSUE TITLE
Please add Arlington, VA

### ISSUE THREAD

**Issue by ghost** [defund12/defund12.org#217]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by serifluous** [comment]
Emails:
County Manager Mark Schwartz, countymanager@arlingtonva.us
County Board Chair Libby Garvey, lgarvey@arlingtonva.us
County Board Member Matt de Ferranti, mdeferranti@arlingtonva.us
County Board Member Katie Cristol, kcristol@arlingtonva.us
County Board Member Christian Dorsey, cdorsey@arlingtonva.us

Budget info: https://budget.arlingtonva.us/fy-2021-proposed-budget/ The page notes that the budget was revised in April due to covid, but the FY 2021 budget links are from February. Someone more familiar with Arlington than I am may be a better source for this info.

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
