### ISSUE TITLE
Add Tulsa, Oklahoma

### ISSUE THREAD

**Issue by zturus** [defund12/defund12.org#236]
http://www.tulsacouncil.org/councilors/city-councilors/
This is a link to Tulsa city district councilors, I feel each of these leaders should take actions to defund the Tulsa police and start over from the ground up with people of the community trained in proper skills for handling A wide variety of situations. The way Oklahoma handles racism is terrible. https://www.okc.gov/government/contact-us
This is a link to OkC officials, I can seem to get an address for their emails to any official. 
https://www.governor.ok.gov/contact/general-info
That’s a link to ok governor website. Same issue. 
Oklahoma is one the worst states in terms of education and handing of well everything almost. Our police are some of the worst in the country and I firmly believe actions and steps to change are not enough, defunding and starting over are the best course.

**Comment by ratulesrar3** [comment]
@zturus if you could follow the email template for OKC in #341 and create one for Tulsa, that would be super helpful!

**Comment by zturus** [comment]
To: mayor@cityoftulsa.org, dist1@tulsacouncil.org, dist2@tulsacouncil.org, dist3@tulsacouncil.org, dist4@tulsacouncil.org, dist5@tulsacouncil.org, dist6@tulsacouncil.org, dist7@tulsacouncil.org, dist8@tulsacouncil.org, dist9@tulsacouncil.org

Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].
The City of Tulsa must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, City Manager Freeman formally proposed deep spending cuts due to the pandemic In OKC, I urge you to re-evaluate our police agencies. We are facing a tipping point in our country’s growth, we must take action to create a better agency of trained professionals, who protect all people and not just the white ones. A system must be put into place with a more specialized training, giving people the skills to handle any situation without violence. 
Oklahoma has a long history of racism and hate, let us work together to move forward, take responsibility, improve and raise up every community. Let’s push towards a bright future. Together we can create a better world. 


I’m not really great with this kind of thing, so this is a decent template

**Comment by la-michel** [comment]
I would also include the County Commissioners - they have a lot of influence over the county jail system. https://www.tulsacounty.org/tulsacounty/dynamic.aspx?id=726 

Commissioner District #1:
Stan Sallee
918-596-5020
 918-596-4647

Commissioner District #2:
Karen Keith
918-596-5016
 918-596-4647

Commissioner District #3:
Ron Peters (Chairman)
918-596-5010
 918-596-4647

**Comment by la-michel** [comment]
Freeman is the City Manager in OKC, not Tulsa. Edited letter below: 

Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].
The City of Tulsa must do better by its residents. I am urging you to divest from the criminalization of our community and reduce police spending in the budget for the 2021 fiscal year. The Tulsa City Council will review and discuss the Mayor’s proposed budget and must approve a budget for the upcoming fiscal year at least seven days prior to June 30, the end of the City’s fiscal year. After the budget has been approved, Fiscal Year 20 -21 will begin July 1. 

As a Tulsan, I demand the Mayor and City Council amend the proposed budget in order to create an ethical reallocation of the city’s expenditures towards sectors that facilitate the dismantling of racial and class inequality. This includes, but is not limited to improving access to health services and treatment, educational opportunity, and stable housing, which have proven far more successful at promoting community safety and social equity than policing. As such, I demand more aggressive financial support be directed to those areas.

Tulsa is the site of one of the greatest race massacres in our nation's history. Last weekend was the 99th Anniversary of the Tulsa Race Massacre, yet our Black friends and neighbors in this city are still under attack. I know many of you feel strongly about racial justice and equity. It is time to take action. Individual solutions will not fix systemic problems. It is time for Tulsa, its leaders, and residents to create a more equitable city for ALL of us. Have the moral clarity to create a budget focused on communities instead of investing in a racist and destructive institution. Defund the Tulsa Police Department.

Thank you, [NAME] [ADDRESS] [EMAIL] [PHONE NUMBER]

**Comment by zturus** [comment]
Thank you so much! I wanted to do what eve I can, I’ve never done anything like this! You’re help is greatly appreciated! I feel you’ve done better than my original.

**Comment by la-michel** [comment]
Thank you!!! I have no experience with coding - how do we get this published on the site?

**Comment by zturus** [comment]
I just assumed with time it would be approved and posted.

**Comment by la-michel** [comment]
Okay cool! I'll do some digging and see if there are any steps we're missing just in case. Thank you for all your help. If you're not a Tulsan, know that we appreciate you!

**Comment by ratulesrar3** [comment]
I'll create a pull request to add it!

**Comment by averymcguirt** [comment]
@zturus ; @ratulesrar3 ; @la-michel Sorry this request seems to have stalled! Thank you for your submission and editing work. I've made a few more minor tweaks to fit our style guide https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

I will close the issue and add this directly to the website since it's been waiting for a while! Please reopen the issue if you have any concerns.

: mayor@cityoftulsa.org, dist1@tulsacouncil.org, dist2@tulsacouncil.org, dist3@tulsacouncil.org, dist4@tulsacouncil.org, dist5@tulsacouncil.org, dist6@tulsacouncil.org, dist7@tulsacouncil.org, dist8@tulsacouncil.org, dist9@tulsacouncil.org, ssallee@tulsacounty.org, kfothergill@tulsacounty.org, rpeters@tulsacounty.org

Dear Tulsa City Council and County Commissioners,
 My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/WARD].
The City of Tulsa must do better by its residents. I am urging you to divest from the criminalization of our community and reduce police spending in the budget for the 2021 fiscal year. The Tulsa City Council will review and discuss the Mayor’s proposed budget and must approve a budget for the upcoming fiscal year at least seven days prior to June 30, the end of the City’s fiscal year. After the budget has been approved, Fiscal Year 20 -21 will begin July 1.

As a Tulsan, I demand the Mayor and City Council amend the proposed budget in order to create an ethical reallocation of the city’s expenditures towards sectors that facilitate the dismantling of racial and class inequality. This includes, but is not limited to improving access to health services and treatment, educational opportunity, and stable housing, which have proven far more successful at promoting community safety and social equity than policing. As such, I demand more aggressive financial support be directed to those areas.

Tulsa is the site of one of the greatest race massacres in our nation's history. Last weekend was the 99th Anniversary of the Tulsa Race Massacre, yet our Black friends and neighbors in this city are still under attack. I know many of you feel strongly about racial justice and equity. It is time to take action. Individual solutions will not fix systemic problems. It is time for Tulsa, its leaders, and residents to create a more equitable city for ALL of us. Have the moral clarity to create a budget focused on communities instead of investing in a racist and destructive institution. Defund the Tulsa Police Department.

Thank you, [NAME] [ADDRESS] [EMAIL] [PHONE NUMBER]

**Comment by la-michel** [comment]
@averymcguirt Hey! The letter is also directed towards the Mayor, please include if possible. The County Commission is actually called "The Tulsa County Board of Commissioners." Any way to edit to include these changes?

**Comment by averymcguirt** [comment]
Edited now, should reflect changes within a few minutes. Thanks.
