### ISSUE TITLE
Please add Riverside, CA

### ISSUE THREAD

**Issue by anniewolfy** [defund12/defund12.org#421]
We need change in Riverside CA!! Riverside County has one of the highest rates of fatal officer-involved shootings per person in California. 

Mayor Rusty Bailey 
2mayor@riversideca.gov

City Council Ward 1: 
Erin Edwards 
EEdwards@riversideca.gov

City Council Ward 2: 
Andy Melendrez 
asmelendrez@riversideca.gov

City Council Ward 3: 
Ronaldo Fierro 
RFierro@riversideca.gov

City Council Ward 4: 
Chuck Conder 
cconder@riversideca.gov

City Council Ward 5: 
Gaby Plascencia
GPlascencia@riversideca.gov

City Council Ward 6: 
Jim Perry 
jperry@riversideca.gov

City Council Ward 7:
Steve Hemenway 
SHemenway@riversideca.gov

County Supervisor 1st District: 
Kevin Jeffries
district1@rivco.org

County Supervisor 2nd District:
Karen Sue Spirgel 
district2@rivco.org

County Supervisor 3rd District: 
Chuck Washington 
4080 Lemon St. Riverside, CA 92501

County Supervisor 5th District: 
Jeff Hewitt
district5@rivco.org

DA Mike Hestrin 
3960 Orange Street
Riverside, CA 92501
(951) 955-5400

**Comment by emilyhuntsman** [comment]
Hi, @anniewolfy do you have a specific email you want to send to the above recipients? We will need that and a corresponding subject line in order to proceed! After that I can send in a PR for Riverside

**Comment by milesalex** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
