### ISSUE TITLE
Add Kingston, NY 

### ISSUE THREAD

**Issue by Wildwoodswomen** [defund12/defund12.org#461]

**Comment by mahrer** [comment]
commoncouncil@kingston-ny.gov 
ward1@kingston-ny.gov
ward2@kingston-ny.gov
ward3@kingston-ny.gov
ward4@kingston-ny.gov
ward5@kingston-ny.gov
ward6@kingston-ny.gov
ward7@kingston-ny.gov
ward8@kingston-ny.gov
ward9@kingston-ny.gov 

Source:
https://kingston-ny.gov/content/8399/10762/10766/default.aspx

**Comment by milesalex** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
