### ISSUE TITLE
NORMAN OKLAHOMA DEFUND THE POLICE EMAIL

### ISSUE THREAD

**Issue by evelasco13** [defund12/defund12.org#466]
Dear [Mayor Clark/Your City Councilperson], 

My name is [Your Name] and I am a resident of Norman, Oklahoma. I am emailing today to stand against the harmful institutions that build our country. I believe that this begins with changes within our own community. With the current unrest regarding police brutality and the killings of George Floyd and Breonna Taylor, I am demanding the divestment of funds from the police department and subsequent reallocation to measures that actively invest in our community, especially Black and other minority communities.

Currently, the police department receives the largest amount of funding from the City of Norman’s General Fund, totaling $22,350,569 or 27% of total General Fund expenditures. Out of the 251 police personnel, 177 are represented by the Fraternal Order of Police (FOP) union, who have continuously stood for policies that hurt communities of color and backed police who have murdered countless Black victims. I am calling for Norman to cut ties with this union, beginning with the firing of Jacob McDonough, the police officer responsible for the use of KKK imagery in emails to the department this past May. Article 34 of the City’s contract with the FOP protects officers like McDonough from facing the consequences of their disgraceful and racist actions. 

In addition, I am demanding the decrease of the police department budget and reallocation of these funds towards food security programs, educational opportunities, arts programs, community centers, and mental health resources, many of which currently operate on a meager and uncertain budget. While $22.3 million was allocated to the police department this year alone, the community development fund (which includes programs that support social services, affordable housing, and anti-poverty initiatives) only received $5,342,871. Instead of having police officers respond to emergencies such as domestic violence/sexual assault, homelessness, or mental health (all cases in which the police have far too often abused their power), there must be a shift to specialized response teams like healthcare workers and social workers who have been specifically trained to respond to these situations. These measures would have prevented the death of Norman resident Marconia Kesse, a Black mentally-ill homeless man taunted and arrested by Officers Kyle Canaan and Daniel Brown, who died in jail two hours after his arrest. Other cities (e.g., Dallas) across the country are beginning to implement this policy with positive results. 

These are the first steps we can take as a municipality to combat the racially unjust systems in our country and state and work towards a safe and equitable society. I believe this is our responsibility to step up and demonstrate that Norman holds no tolerance for racism at any level. I urge you to stand with me in our efforts to be better. 

Sincerely,
[Your Name]
[Your Address]

FIND YOUR CITY COUNCILOR
Mayor Clark: mayor@NormanOK.gov, (405) 366-5402
Ward 1: Kate Bierman, ward1@NormanOK.gov 405-652-9444
Ward 2: Joe Carter, ward2@NormanOK.gov 405-288-6460
Ward 3: Alison Petrone, ward3@NormanOK.gov 405-310-9332
Ward 4: Lee Hall, ward4@NormanOK.gov 405-650-9088
Ward 5: Sereta Wilson, ward5@NormanOK.gov, 405-613-7083 
Ward 6: Bill Scanlon, ward6@NormanOK.gov 405-317-2225
Ward 7: Stephen Holman, ward7@NormanOK.gov 405-535-7523
Ward 8: Alexandra Scott, ward8@NormanOK.gov 405-514-0669

**Comment by averymcguirt** [comment]
Minor copy-editing, ready for PR.

TO:
Mayor Clark: mayor@NormanOK.gov, 
Ward 1: Kate Bierman, ward1@NormanOK.gov 
Ward 2: Joe Carter, ward2@NormanOK.gov 
Ward 3: Alison Petrone, ward3@NormanOK.gov 
Ward 4: Lee Hall, ward4@NormanOK.gov 
Ward 5: Sereta Wilson, ward5@NormanOK.gov, 
Ward 6: Bill Scanlon, ward6@NormanOK.gov 
Ward 7: Stephen Holman, ward7@NormanOK.gov
Ward 8: Alexandra Scott, ward8@NormanOK.gov 

Dear Mayor Clark and Norman City Council,

My name is [Your Name] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am emailing today to stand against institutional inequity and racism endemic to our country. I believe that this begins with changes in our own community. With the current unrest evoked by police brutality and the killings of George Floyd and Breonna Taylor, I am demanding the divestment of funds from the police department and reallocation to programs that actively strengthen our community, especially Black and other minority communities.

Currently, the police department receives the largest amount of funding from the City of Norman’s General Fund, totaling $22,350,569 or 27% of total General Fund expenditures. Out of the 251 police personnel, 177 are represented by the Fraternal Order of Police (FOP) union, who have continuously stood for policies that hurt communities of color and backed police who have murdered countless Black victims. I am calling for Norman to cut ties with this union, beginning with the firing of Jacob McDonough, the police officer responsible for the use of KKK imagery in emails to the department this past May. Article 34 of the City’s contract with the FOP protects officers like McDonough from facing the consequences of their disgraceful and racist actions.

In addition, I am demanding the decrease of the police department budget and reallocation of these funds towards food security programs, educational opportunities, arts programs, community centers, and mental health resources--many of which currently operate on a meager and uncertain budget, and all of which more effectively promote a safe and equitable community than policing. While $22.3 million was allocated to the police department this year alone, the community development fund (which includes programs that support social services, affordable housing, and anti-poverty initiatives) only received $5,342,871. Instead of having police officers respond to emergencies such as domestic violence/sexual assault, homelessness, or mental health (all cases in which the police have far too often abused their power), there must be a shift to specialized response teams like healthcare workers and social workers who have been specifically trained to respond to these situations. These measures would have prevented the death of Norman resident Marconia Kesse, a Black mentally-ill homeless man taunted and arrested by Officers Kyle Canaan and Daniel Brown, who died in jail two hours after his arrest. Other cities (e.g., Dallas) across the country are beginning to implement this policy with positive results.

These are the first steps we can take as a municipality to combat the racially unjust systems in our country and state and work towards a safe and equitable society. I believe this is our responsibility to step up and demonstrate that Norman holds no tolerance for racism at any level. I urge you to stand with me in our efforts to be better.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[EMAIL]
[PHONE NUMBER]

**Comment by Ceshion** [comment]
I can take this one!
