### ISSUE TITLE
Please Add Kansas City, MO

### ISSUE THREAD

**Issue by tatermaiden** [defund12/defund12.org#487]
Subject line: Defunding the Kansas City Police Department

Email addresses:  
Mayor: mayorq@kcmo.org
Councilmembers:
heather.hall@kcmo.org ; Kevin.ONeill@kcmo.org ; ‎amy.justis@kcmo.org ; dan.fowler@kcmo.org ; Brandon.Ellington@kcmo.org ; Melissa.Robinson@kcmo.org ; Melissa.Robinson@kcmo.org ; Eric.Bunch@kcmo.org; ‎Keema.McCoy@kcmo.org ;Angela.Pearson@kcmo.org ;Katrina.Foster@kcmo.org ; fred.wickham@kcmo.org ; kevin.mcmanus@kcmo.org ;Teresa.Loar@kcmo.org, katheryn.shields@kcmo.org, Lee.barnes@kcmo.org, ryana.parks-shaw@kcmo.org, Andrea.bough@kcmo.org; earnest_rouse@kcmo.org

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police. The concession to fund body cameras is hardly a long term solution; KC needs to defund. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. It's clear evidence that fewer police = fewer violent acts. It's proof that police "reform"  isn't enough, police **removal** is.

The coronavirus pandemic showed us months ago: Support for at-risk communities is crucial now, more than ever. Starting June 1st Kansas City resumed evictions as normal, utilizing our police to force families out into the streets while numbers of the infected spike. It is abhorrent that our officials would prefer to spend taxpayer dollars making people **homeless** than funding programs that might lift them out of poverty. We demand a budget that invests in vulnerable Kansas City residents during this trying and uncertain time.  We demand a budget that supports our residents' families, rather than empowers the police forces that tear them apart.

As per the 2020 budget, Kansas City spends twice as much on "public safety" than any other sector. This is unacceptable. When I walk around the city I can't help but notice dilapidated public housing, inner city parks plagued by litter, and severely underfunded (if not downright closed) public schools. East of JC Nichols' infamous redline-- Troost-- streets are a patchwork of paved potholes, neighborhood sidewalks are cracked and crumbling (if they even exist at all), all the while our people are left to the wayside. 

How can we spend twice as much taxpayer money outfitting police like soldiers when any common sense citizen could see there are more pressing issues at hand? Pumping more funding into our police merely perpetuates race-driven police violence and the prison feedback loop that oppresses so many of our community members into a lifetime of instability and trauma. Isn't it finally time we shake up the foundation?

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me; you can see it plainly in the streets, from here to Paris.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]"

**Comment by dtrzn** [comment]
@tatermaiden Well done. I was working on one for KC as well. Would you mind adding in this sentiment to the opening paragraph?

"I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. Let that serve as a picture of how our city ought to operate as a whole."

And if you like this, I feel like it is relevant:

"We do not believe violent crime is a justification for a larger police force. This creates a negative feedback loop where the Police Department is in fact rewarded for doing a worse job and even for contributing to the violence in our city."

**Comment by tatermaiden** [comment]
@dtrzn I'd be happy to add those! I can trim down some other stuff too so it's more concise

**Comment by dtrzn** [comment]
@tatermaiden Thanks! Also council members: Teresa.Loar@kcmo.org, katheryn.shields@kcmo.org, Lee.barnes@kcmo.org, ryana.parks-shaw@kcmo.org, and Andrea.bough@kcmo.org

And city manager: earnest_rouse@kcmo.org

**Comment by tatermaiden** [comment]
@dtrzn I shall add those! Thanks. Also going to submit a new one for justice for our murder victims of police brutality

**Comment by dtrzn** [comment]
@tatermaiden your paragraph on the 2020 budget I think focuses on city infrastructure and materials, and while I do agree that those improvements would be nice, I think it would be good to focus more on community nourishment. Here is what my people came up with:

KCPD makes up over 23% of the city’s total budget at $262m. These funds must be divested into community well-being programs such as meal programs, mental health programs, social work outside of KCPD, and housing programs.

**Comment by skullface** [comment]
Hi @tatermaiden and @dtrzn, thanks for your contribution! I am a [content reviewer](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) looking over your email for Kansas City.

Confirming from the above discussion that the content you’re requesting is:

### All email addresses
```
- mayorq@kcmo.org
- heather.hall@kcmo.org 
- Kevin.ONeill@kcmo.org
- ‎amy.justis@kcmo.org 
- dan.fowler@kcmo.org
- Brandon.Ellington@kcmo.org
- Melissa.Robinson@kcmo.org 
- Melissa.Robinson@kcmo.org
- Eric.Bunch@kcmo.org
- Keema.McCoy@kcmo.org 
- Angela.Pearson@kcmo.org 
- Katrina.Foster@kcmo.org 
- red.wickham@kcmo.org
- kevin.mcmanus@kcmo.org
- Teresa.Loar@kcmo.org
- katheryn.shields@kcmo.org
- Lee.barnes@kcmo.org
- ryana.parks-shaw@kcmo.org
- Andrea.bough@kcmo.org
- earnest_rouse@kcmo.org
```

### Message
I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police. The concession to fund body cameras is hardly a long term solution; KC needs to defund. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. It's clear evidence that fewer police = fewer violent acts. It's proof that police "reform" isn't enough, police removal is.

The coronavirus pandemic showed us months ago: Support for at-risk communities is crucial now, more than ever. Starting June 1st Kansas City resumed evictions as normal, utilizing our police to force families out into the streets while numbers of the infected spike. It is abhorrent that our officials would prefer to spend taxpayer dollars making people homeless than funding programs that might lift them out of poverty. We demand a budget that invests in vulnerable Kansas City residents during this trying and uncertain time. We demand a budget that supports our residents' families, rather than empowers the police forces that tear them apart.

KCPD makes up over 23% of the city’s total budget at $262m. These funds must be divested into community well-being programs such as meal programs, mental health programs, social work outside of KCPD, and housing programs.

How can we spend twice as much taxpayer money outfitting police like soldiers when any common sense citizen could see there are more pressing issues at hand? Pumping more funding into our police merely perpetuates race-driven police violence and the prison feedback loop that oppresses so many of our community members into a lifetime of instability and trauma. Isn't it finally time we shake up the foundation?

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me; you can see it plainly in the streets, from here to Paris.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dtrzn** [comment]
LGTM!

**Comment by tatermaiden** [comment]
Reads perfectly! Get her up there!

**Comment by serifluous** [comment]
There's an existing issue #490 and PR #529 for Kansas City. Can we consolidate there?

**Comment by skullface** [comment]
Yes! I have edited the messaging of this email body per the [defund12.org style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) and am tagging @tatermaiden and @dtrzn for review in #490. Please visit the new issue to continue the conversation!

Closing this issue in favor of #490.
