### ISSUE TITLE
Kansas City, Missouri

### ISSUE THREAD

**Issue by dpyles** [defund12/defund12.org#490]
To: MayorQ@kcmo.org, heather.hall@kcmo.org, Kevin.ONeill@kcmo.org, Teresa.Loar@kcmo.org, amy.justis@kcmo.org, Brandon.Ellington@kcmo.org, Melissa.Robinson@kcmo.org, katheryn.shields@kcmo.org, Eric.Bunch@kcmo.org, Keema.McCoy@kcmo.org, Angela.Pearson@kcmo.org, Katrina.Foster@kcmo.org, fred.wickham@kcmo.org

Subject: Defund the Kansas City Police Department

Message (Don't forget to replace the [x]'s with your information!) 

Hello, 

My name is [NAME] and I am a resident of Kansas City’s [YOUR DISTRICT]. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education. 

The city’s recently approved FY2020-21 budget promises ~$270 million to police alone, which is ~$50 million more than the entire budget for Neighborhoods, Housing, and Healthy Communities in this fiscal year. This year’s policing budget brings a $10.7 million increase from the previous year’s budget, an increase enabling ten new police officer positions as well as wage increases and pensions for existing officers. 

As the city’s policing budget increases, direct investment in our communities continues to be overlooked. No part of the budget was reserved for the fulfillment of Office of Tenant Advocate, a mere $1.2 million dollar budget proposal from the KC Tenants group to Mayor Lucas. This proposal, made to fulfill the Tenants Bill of Rights passed by the mayor and city council in December 2019, was seemingly ignored in the city’s budget. This is but one example of the way that police funding interferes with and blocks the allocation of funds back into our communities, as a result perpetuating racial and economic inequality in Kansas City. 

On June 4th, 2020, Mayor Lucas announced “significant” police oversight measures. While these measures indicate that the mayor and city council are open to hearing the demands of the people and pursuing police accountability, the measures themselves do not address the issue of police department overfunding in the city’s FY2020-21 budget.  

There is little evidence that more policing and increased wages for police officers correlates to safer communities. Investment in the police does not equal an investment in communities. To truly hold police accountable and uplift civilians, I would like to see an immediate reconsideration and revision of police funding in our city so that we might begin to adequately invest in our communities. 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Dear Mayor Lucas and City Council,

My name is [NAME] and I am a resident of Kansas City’s [YOUR DISTRICT]. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education.

The city’s recently approved FY2020-21 budget promises ~$270 million to police alone, which is ~$50 million more than the entire budget for Neighborhoods, Housing, and Healthy Communities in this fiscal year. This year’s policing budget brings a $10.7 million increase from the previous year’s budget, an increase enabling ten new police officer positions as well as wage increases and pensions for existing officers.

As the city’s policing budget increases, direct investment in our communities continues to be overlooked. No part of the budget was reserved for the fulfillment of Office of Tenant Advocate, a mere $1.2 million dollar budget proposal from the KC Tenants group to Mayor Lucas. This proposal, made to fulfill the Tenants Bill of Rights passed by the mayor and city council in December 2019, was seemingly ignored in the city’s budget. This is but one example of the way that police funding interferes with and blocks the allocation of funds back into our communities, as a result perpetuating racial and economic inequality in Kansas City.

On June 4th, 2020, Mayor Lucas announced “significant” police oversight measures. While these measures indicate that the mayor and city council are open to hearing the demands of the people, the measures themselves do not address the issue of police department overfunding in the city’s FY2020-21 budget.

There is little evidence that more policing and increased wages for police officers correlates to safer communities. Investment in the police does not equal an investment in communities. To truly help our citizens, I would like to see an immediate reconsideration and revision of police funding in our city so that we might begin to adequately invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Kansas City can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police department. 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]


added a generalized list of demands, removed reformist reforms
@milesalex ready for pr

**Comment by Ceshion** [comment]
I can take this one!

**Comment by Ceshion** [comment]
added via #529

**Comment by skullface** [comment]
Continuing conversation from #487: @tatermaiden and @dtrzn wrote a letter that preceded #490. After editing for style guide consistency, it reads:

> I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police. The concession to fund body cameras is hardly a long term solution; KC needs to defund. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. It's clear evidence that fewer police = fewer violent acts. It's proof that police "reform" isn't enough, police removal is.

> The Coronavirus pandemic has shown us support for at-risk communities is crucial, now more than ever. Starting June 1st, Kansas City resumed evictions as normal, utilizing our police to force families out into the streets, while numbers of infections spike. It is abhorrent that officials would prefer to spend taxpayer dollars making people homeless than funding programs that might lift them out of poverty. I demand a budget that invests in vulnerable Kansas City residents during this trying and uncertain time. I demand a budget that supports our residents' families rather than a budget that empowers the police forces that tear them apart.

> KCPD makes up over 23% of the city’s total budget at $262m. These funds must be divested into community well-being programs such as meal programs, mental health programs, social work outside of KCPD, and housing programs.

> How can we spend twice as much taxpayer money outfitting police like soldiers when any common sense citizen could see there are more pressing issues at hand? Pumping more funding into our police merely perpetuates race-driven police violence and the prison feedback loop that oppresses so many of our community members into a lifetime of instability and trauma. Isn't it finally time we shake up the foundation?

> As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year to fund community care instead of policing. You need to adopt a People’s Budget. Public opinion is with me; you can see it plainly in the streets, from here to Paris.

> Thank you for your time,
> [YOUR NAME]
> [YOUR ADDRESS]
> [YOUR EMAIL]
> [YOUR PHONE NUMBER]

---

Can you and @dpyles consolidate the two messages? Thank you!

**Comment by dtrzn** [comment]
What @dpyles has is good IMHO. I would only remove the need for stating your ward/district and add a line referencing the de-escalation of police presence at the protests.

I am good with whatever though, I just want to help us get something up for KC!

> Dear Mayor Lucas and City Council,
>
> My name is [NAME] and I am a resident of Kansas City. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. Let that serve as a picture of how our city ought to operate as a whole.
>
> The city’s recently approved FY2020-21 budget promises ~$270 million to police alone, which is ~$50 million more than the entire budget for Neighborhoods, Housing, and Healthy Communities in this fiscal year. This year’s policing budget brings a $10.7 million increase from the previous year’s budget, an increase enabling ten new police officer positions as well as wage increases and pensions for existing officers.
>
> As the city’s policing budget increases, direct investment in our communities continues to be overlooked. No part of the budget was reserved for the fulfillment of Office of Tenant Advocate, a mere $1.2 million dollar budget proposal from the KC Tenants group to Mayor Lucas. This proposal, made to fulfill the Tenants Bill of Rights passed by the mayor and city council in December 2019, was seemingly ignored in the city’s budget. This is but one example of the way that police funding interferes with and blocks the allocation of funds back into our communities, as a result perpetuating racial and economic inequality in Kansas City.
>
> On June 4th, 2020, Mayor Lucas announced “significant” police oversight measures. While these measures indicate that the mayor and city council are open to hearing the demands of the people, the measures themselves do not address the issue of police department overfunding in the city’s FY2020-21 budget.
>
> There is little evidence that more policing and increased wages for police officers correlates to safer communities. Investment in the police does not equal an investment in communities. To truly help our citizens, I would like to see an immediate reconsideration and revision of police funding in our city so that we might begin to adequately invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
>
> Kansas City can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police department.
>
> Thank you for your time,
> [YOUR NAME]
> [YOUR ADDRESS]
> [YOUR EMAIL]
> [YOUR PHONE NUMBER]

**Comment by dpyles** [comment]
I'm happy with the edits @dtrzn made to my original letter above. Definitely want to get something up for KC so I'm open to more edits if needed but this looks good to me.

**Comment by skullface** [comment]
Awesome, thank you! We will get it live as soon as we can.

**Comment by dtrzn** [comment]
@minicreative Thank you for working on this! If it's not too late, there was an update to the opening paragraph we had that isn't reflected in #529.  No worries if it is too late.

>My name is [NAME] and I am a resident of Kansas City. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. Let that serve as a picture of how our city ought to operate as a whole.
