### ISSUE TITLE
Add every city in the Silicon Valley. Too much money here :) Thank you!!!!!!

### ISSUE THREAD

**Issue by aron408** [defund12/defund12.org#494]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by milesalex** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
