### ISSUE TITLE
Email template for Portland, OR has discrepancy

### ISSUE THREAD

**Issue by AlYan20** [defund12/defund12.org#495]
Hello!

The email template for Defunding PPB in Portland, OR says both that we have a problem with eliminating the funding for body cams, AND that we oppose body cams.

If you could please fix to say one or the other, that would make our emails more effective and clear—thank you!

Ally

**Comment by milesalex** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by swallan** [comment]
@milesalex @AlYan20 this is a bug, not new request

**Comment by AlYan20** [comment]
Ok thank you, will resubmit as bug

**Comment by swallan** [comment]
@AlYan20 probably no need to resubmit, I already opened a PR to address it

**Comment by milesalex** [comment]
Ok, will reopen. Sorry. Just getting the hang of new workflow

**Comment by swallan** [comment]
No problem!

**Comment by AlYan20** [comment]
Awesome, thank you! There are actually several other mis-quoted pieces of
information and inconsistencies as well—we are researching the correct
numbers and re-writing the template. Should I just submit that as a new
ticket, or send it to you directly?

**Comment by swallan** [comment]
you can suggest them on #500 if you want
