### ISSUE TITLE
OC Mayors and City Council Members List and edited OC Script 

### ISSUE THREAD

**Issue by enbyabbey** [defund12/defund12.org#533]
I have compiled the emails of all the OC mayors and city council members and edited the OC board of supervisors script to include information from these articles on the people on OC's push to defund police departments (most allocate half or more of their general budget to policing) and the unconsitutional nature of Irvine's mayor comments to keep protests out of Irvine. 
https://voiceofoc.org/2020/06/protests-in-orange-county-are-focusing-on-police-budgets-and-show-a-changing-oc/
https://voiceofoc.org/2020/06/thurgood-marshall-bar-association-to-speak-out-on-comments-by-irvine-mayor/

Heres the google doc. the script is at the end of the document and can be used for any OC city. 
https://docs.google.com/document/d/1CYKEhuprEYzygIES5N5HBhZmtW3GfEUSkmtcQfknOwQ/edit?usp=sharing

DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by milesalex** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by swallan** [comment]
Also, edit the contents to not include `We need to invest in services that prevent crime `
