### ISSUE TITLE
Letter to Santa Fe Council: Vote No at 6/9 meeting for approval of AR-15s, Tasers, SWAT

### ISSUE THREAD

**Issue by ChloeRuiz** [defund12/defund12.org#554]
Subject Line: Please vote *no* on upcoming 6/9 approval of AR-15s, Tasers, SWAT

Santa Fe City Council Members:

Alan Webber - mayor@santafenm.gov
Renee Villarreal - rdvillarreal@santafenm.gov
Signe I. Lindell - silindell@santafenm.gov
Michael Garcia - mjgarcia@santafenm.gov
Carol Romero-Wirth - cromero-wirth@santafenm.gov
Chris Rivera - cmrivera@santafenm.gov
Roman "Tiger" Abeyta - rrabeyta@santafenm.gov
Jamie Cassutt - Sanchez - jcsanchez@santafenm.gov
JoAnne Vigil Coppler - jvcoppler@santafenm.gov

Dear City Council Members & Leaders,

I first want to thank you for your work, energy and service for our city. As a resident here, I deeply appreciate and am grateful for your service and all the energy your pour in to keeping our community.

As a representative of my voice, I ask you to please vote *no* at the June 9th meeting on any resolution to approve the Santa Fe County Five Year Capital Plan Fixed Assets Summary - so long as it includes any expenditures for rifles, tasers, and SWAT equipment.

I am deeply concerned about the weaponization of our police force and using these weapons against your own citizens - the very ones who you are here to be of service to.  As a community member, the presence of weapons does not help me feel safe and in fact elicits an opposite impact in the community. 

There are no circumstance that can justify the use of military weapons against your own people, and I cannot understand or approve this choice and use of our city's funds.

As such please vote against  allocating $88,000 toward the purchase of weapons including 20 AR-15 rifles, 500 tasers, and SWAT helmet video cameras for the Sheriff's Department. 

Thank you for listening and honoring my voice so it may translate into action and change. 

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
Some edits (in bold):

------------------------

Subject Line: **[INSERT UNIQUE SUBJECT LINE]**

Santa Fe City Council Members:

Alan Webber - mayor@santafenm.gov
Renee Villarreal - rdvillarreal@santafenm.gov
Signe I. Lindell - silindell@santafenm.gov
Michael Garcia - mjgarcia@santafenm.gov
Carol Romero-Wirth - cromero-wirth@santafenm.gov
Chris Rivera - cmrivera@santafenm.gov
Roman "Tiger" Abeyta - rrabeyta@santafenm.gov
Jamie Cassutt - Sanchez - jcsanchez@santafenm.gov
JoAnne Vigil Coppler - jvcoppler@santafenm.gov

Dear City Council Members & Leaders,

**My name is [YOUR NAME] and I am a resident of Santa Fe.** I first want to thank you for your work, energy and service for our city. As a resident here, I deeply appreciate and am grateful for your service and all the energy your pour in to keeping our community.

**Accordingly, it has come to my attention that budget for 2021 will be submitted on July 31, and hearings will begin on July 13.** As a representative of my voice, I ask you to please vote _no_ at on any resolution to approve the Santa Fe County Five Year Capital Plan Fixed Assets Summary - so long as it includes any expenditures for rifles, tasers, and SWAT equipment.

I am deeply concerned about the weaponization of our police force and using these weapons against your own citizens - the very ones who you are here to be of service to. As a community member, the presence of weapons does not help me feel safe and in fact elicits an **opposite impact and does not promote community safety**. 

I cannot understand or approve this choice and use of our city's funds. As such please 

 weapons including 20 AR-15 rifles, 500 tasers, and SWAT helmet video cameras for the Sheriff's Department. **I urge you to instead advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.**

Thank you for listening and honoring my voice so it may translate into action and change.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

------------------------

Since this change likely won't make it in time for the 6/9 council meeting, I updated it to reflect the dates for budget hearings as per https://www.santafenewmexican.com/news/local_news/city-finance-committee-begins-to-tackle-challenge-of-lean-budget/article_d3aa1014-8ee2-11ea-8053-73cb08d313da.html

I am also unable to validate the $88,000 amount, @ChloeRuiz could you provide a resource?

**Comment by ChloeRuiz** [comment]
Thank you for these excellent edits and updates - and yes, as it won't be in time for 6/9 vote, the updates are great. I appreciate it. 

This is where I found the $88,000 reference - - 

https://actionnetwork.org/forms/no-ar-15s-no-tasers-no-swat-in-santa-fe?link_id=0&can_id=0c022a6e751497e6d4c6b09f4affb6b8&source=email-stop-the-county-from-buying-20-ar-15-rifles-500-tasers&email_referrer=email_821184___from_1112670___subject_1112669&email_subject=stop-the-madness&fbclid=IwAR2A5fxZC7bK0YdeyNSNIZaH6YPHo6YQK6ytCALV_5oUjnDpprIDohwRLPE

**Comment by todd-m** [comment]
Thanks, @ChloeRuiz and @wendywx -- working on this now.
