### ISSUE TITLE
Add LA County for those outside LA city

### ISSUE THREAD

**Issue by ablack16-1636683** [defund12/defund12.org#557]
To: FirstDistrict@bos.lacounty.gov, MarkRidley-Thomas@bos.lacounty.gov, Sheila@bos.lacounty.gov, FourthDistrict@bos.lacounty.gov, kathryn@bos.lacounty.gov

Subject: DEFUND AND RESTRUCTURE LA COUNTY SHERIFFS DEPARTMENT BUDGET

Body:
Dear County Supervisor(s), 

My name is [YOUR NAME]. I am a resident of Los Angeles County, residing in the [YOUR DISTRICT], and I am emailing to demand the restructuring of the Los Angeles county budget, so as to prioritize more social services for communities, and to drastically minimize spending on the sheriff’s department. 

I demand of the county supervisors to prove their love and dedication to the people of their county and reallocate funds to directly benefit those in need. 

It is absolutely absurd that the Sheriff’s budget exceeds $3,500,000,000. That is money that could be used to improve our communities, rather than funding an organization with an extremely racist past and present. 

Defunding the police and restructuring the budget is an absolute necessity now more than ever. There are 58,936 DOCUMENTED houseless people in Los Angeles CITY alone. There are healthcare workers without proper equipment. More than 30% of Los Angeles County residents have filed for unemployment. Our transportation infrastructure continues to be one of the most prominent examples of INSUFFICIENT PUBLIC SPENDING, and we all know that with even a fraction of the money given to the Sheriff’s Office we could completely transform our transportation system and social programs. However, we are not asking for a fractional cut. We demand large spending cuts to the Sheriff’s Office. In recent years, the most prominent news about the LA County Sheriff’s Office has been word of The Banditos, a gang of police officers who find themselves above the law and have a DECADES-LONG well-documented history of both police brutality and silencing any “good police officers” who try to challenge them. THIS is not what our county represents. It is time to recognize the change occurring nationwide, and to DEFUND THE LA COUNTY SHERIFF.

While The Sheriff’s Department has more funding than it knows what to do with, there are communities who desperately need funding and every day they don't receive it their quality of life worsens. Thousands have died who did not need to. You have the ability to change this, so do it. 

While I primarily write as a concerned constituent who is ashamed of local government members failing to take action out of cowardice, I also write as a voter. We implore you to take steps to defund a paramilitarized force of organized state violence with a WELL-DOCUMENTED HISTORY of brutality and state-sanctioned extrajudicial murder. We DEMAND that you defund the LA County Sheriff’s Office. It is imperative to note that the sheriff’s department and LA county police do not keep ALL of us safe. They have historically targeted Black people, people of color, and queer people within our own communities. This is both systemic on a nationwide scale and VERY SPECIFIC TO THE LA COUNTY SHERIFF’S DEPARTMENT. Again, we demand that you defund this department. 

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Hi @ablack16-1636683,

Thanks for the submission! Please make a few revisions to enhance it before we can add it to the site:

- add a salutation to directly who the email will reach, `Dear [Councilmember, Mayor, Etc],`
- some of the tone of the email is a bit aggressive. It should be more constructive, as attacks aren't likely to be well responded to.  Our passion for this issue can be conveyed without threats.

**Comment by ablack16-1636683** [comment]
updated!

**Comment by averymcguirt** [comment]
Minor copy-edits below (making last paragraph 1st person, removing reference to sender as 'voter'; see our style guide:  https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md )
Let me know if any concerns, and thanks for your submission! 
Ready for PR

To: FirstDistrict@bos.lacounty.gov, MarkRidley-Thomas@bos.lacounty.gov, Sheila@bos.lacounty.gov, FourthDistrict@bos.lacounty.gov, kathryn@bos.lacounty.gov

Subject: DEFUND AND RESTRUCTURE LA COUNTY SHERIFFS DEPARTMENT BUDGET

Body:
Dear County Supervisor(s),

My name is [YOUR NAME]. I am a resident of Los Angeles County, residing in the [YOUR DISTRICT], and I am emailing to demand the restructuring of the Los Angeles county budget, so as to prioritize more social services for communities, and to drastically minimize spending on the sheriff’s department.

I demand of the county supervisors to prove their love and dedication to the people of their county and reallocate funds to directly benefit those in need.

It is absolutely absurd that the Sheriff’s budget exceeds $3,500,000,000. That is money that could be used to improve our communities, rather than funding an organization with an extremely racist past and present.

Defunding the police and restructuring the budget is an absolute necessity now more than ever. There are 58,936 DOCUMENTED houseless people in Los Angeles CITY alone. There are healthcare workers without proper equipment. More than 30% of Los Angeles County residents have filed for unemployment. Our transportation infrastructure continues to be one of the most prominent examples of INSUFFICIENT PUBLIC SPENDING, and we all know that with even a fraction of the money given to the Sheriff’s Office we could completely transform our transportation system and social programs. However, we are not asking for a fractional cut. We demand large spending cuts to the Sheriff’s Office. In recent years, the most prominent news about the LA County Sheriff’s Office has been word of The Banditos, a gang of police officers who find themselves above the law and have a DECADES-LONG well-documented history of both police brutality and silencing any “good police officers” who try to challenge them. THIS is not what our county represents. It is time to recognize the change occurring nationwide, and to DEFUND THE LA COUNTY SHERIFF'S DEPARTMENT.

While The Sheriff’s Department has more funding than it knows what to do with, there are communities who desperately need funding and every day they don't receive it their quality of life worsens. Thousands have died who did not need to. You have the ability to change this, so do it.

I implore you to take steps to defund a militarized force of organized state violence with a WELL-DOCUMENTED HISTORY of brutality and state-sanctioned extrajudicial murder. I DEMAND that you defund the LA County Sheriff’s Office. It is imperative to note that the sheriff’s department and LA county police do not keep ALL of us safe. They have historically targeted Black people, people of color, and queer people within our own communities. This is both systemic on a nationwide scale and VERY SPECIFIC TO THE LA COUNTY SHERIFF’S DEPARTMENT. Again, I demand that you defund this department.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
On it!
