### ISSUE TITLE
Defund Greensboro, NC Police Department

### ISSUE THREAD

**Issue by mlmoore7** [defund12/defund12.org#570]
To: nancy.vaughan@greensboro-nc.gov , yvonne.johnson@greensboro-nc.gov , sharon.hightower@greensboro-nc.gov , marikay.abuzuaiter@greensboro-nc.gov ,  michelle.kennedy@greensboro-nc.gov ,  goldie.wells@greensboro-nc.gov ,  justin.outling@greensboro-nc.gov ,  nancy.hoffmann@greensboro-nc.gov ,  tammi.thurm@greensboro-nc.gov , David.parrish@greensboro-nc.gov.  

Subject: Defund the Greensboro Police & Reallocate Funds 

Message (Don't forget to replace the [x]'s with your information!) 

Dear Mayor Vaughan & City Council Members:
My name is [YOUR NAME]. I am a resident of Greensboro. I am writing to object to the allocation of over $78M to the Greensboro Police Department in the 2020-2021 city budget. It is indefensible to increase the police budget when city workers are experiencing layoffs and denial of wage increases, and thousands of our community members face unemployment and housing/food insecurity in the midst of the COVID-19 pandemic.

The police cannot protect us from these challenges. In fact, more often than not, when police are dispensed, rather than more qualified medical, psychiatric, and social work professionals, the effect is to bring violence where none previously existed. So, to really promote community safety we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

Reallocate all proposed increases in police budget to Greensboro Public Schools, affordable housing and rent subsidies, eviction diversions, food resources, and medical supplies, which have both immediate and longstanding consequences that will more positively affect our current residents. Implement a plan to reallocate existing police resources to institutions and experts better equipped to deal with many of the issues GPD have been conscripted, without adequate training, to do. Resources should be allocated to EMTs, social workers, and other social service providers to respond to the majority of current police business, including health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. Additional money should go to community education around de-escalation and community support for drug, SV/DV, and property-related incidents. There is no reason to have armed officers responding to the majority of emergency needs in Greensboro.

Finally, I request that you divest from offensive weapons. Offensive weapons are known to escalate violence, especially when deployed in situations where none existed before. Almost all the current litany of Black men and women dead from police violence were non-violent, unarmed people, for whom armed police became the site of death and brutality. We don’t need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another.

Can I count on you to consider an alternative budget that puts a focus on social service programs?
Thank you, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Hi @mlmoore7,

Thanks for the submission! A few things to enhance your email before we can add it:

- refrain from phrasing things from a policed point of view, specifically in reference to crime.  From the email writing guide: 

>  Instead of summarizing social programs as being more effective than policing at “reducing crime,” say that they are more effective at “promoting community safety.”

- consider breaking up the large paragraph into bullet points

Overall, nice!

**Comment by mlmoore7** [comment]
Hi @swallan,

Thank you for your notes. I have updated my email with appropriate language and spaced paragraphs. Thank you!!

**Comment by averymcguirt** [comment]
Looks great, thanks for your submission. Minor copy-edits below (please reach out with any concerns). 
Ready for PR


To: 
nancy.vaughan@greensboro-nc.gov 
yvonne.johnson@greensboro-nc.gov 
sharon.hightower@greensboro-nc.gov 
marikay.abuzuaiter@greensboro-nc.gov 
michelle.kennedy@greensboro-nc.gov
goldie.wells@greensboro-nc.gov 
justin.outling@greensboro-nc.gov 
nancy.hoffmann@greensboro-nc.gov
tammi.thurm@greensboro-nc.gov
David.parrish@greensboro-nc.gov

Subject: Defund the Greensboro Police & Reallocate Funds

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Vaughan & City Council Members,

My name is [YOUR NAME]. I am a resident of [DISTRICT/NEIGHBORHOOD]. I am writing to object to the allocation of over $78M to the Greensboro Police Department in the 2020-2021 city budget. It is indefensible to increase the police budget when city workers are experiencing layoffs and denial of wage increases, and thousands of our community members face unemployment and housing/food insecurity in the midst of the COVID-19 pandemic.

The police cannot protect us from these challenges. In fact, more often than not, when police are dispatched, rather than more qualified medical, psychiatric, and social work professionals, the effect is to bring violence where none previously existed. So, to really promote community safety we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

Reallocate all proposed increases in police budget to Greensboro Public Schools, affordable housing and rent subsidies, eviction diversions, food resources, and medical supplies, which have both immediate and longstanding consequences that will more positively affect our current residents. Implement a plan to reallocate existing police resources to institutions and experts better equipped to deal with many of the issues to which GPD have been assigned without adequate training to do. Resources should be allocated to EMTs, social workers, and other social service providers to respond to the majority of current police business, including health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. Additional money should go to community education around de-escalation and community support for drug, SV/DV, and property-related incidents. There is no reason to have armed officers responding to the majority of emergency needs in Greensboro.

Finally, I request that you divest from offensive weapons. Offensive weapons are known to escalate violence, especially when deployed in situations where none existed before. Almost all the current litany of Black men and women dead from police violence were non-violent, unarmed people, for whom armed police became the site of death and brutality. We don’t need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another.

Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mlmoore7** [comment]
@averymcguirt ,

Thank you for the updates. Everything looks great. I appreciate it!

**Comment by dionlarson** [comment]
On it!
