### ISSUE TITLE
Greenville, South Carolina

### ISSUE THREAD

**Issue by haningtatum** [defund12/defund12.org#576]
To: rmccaskill@greenvillecounty.org, kwhite@greenvillesc.gov, mefird@greenvillesc.gov, jdeworken@greenvillesc.gov, lflemming@greenvillesc.gov, kgibson@greenvillesc.gov, wbrasington@greenvillesc.gov, ddowe@greenvillesc.gov, rstall@greenvillesc.gov

Subject: Defunding Greenville Police Department

Message:

Dear Mayor White and Greenville County Council Members, 

My name is [YOUR NAME], and I am a resident of Greenville County. 

I am demanding you reallocate funds from the Greenville County Police department and invest them into social services that would directly improve the well-being of Greenville County citizens.  The two year budget for the Sheriff’s Office for the 2020-2021 fiscal year is $96,307,964. This is a 6% increase in the budget from the 2018-2019 fiscal year. The largest budget enhancement of the 2020-2021 budget is the addition of fourteen deputies in 2020 and fourteen deputies in 2021- eight more total than the Sheriff requested.

I am also requesting that the budget vote be delayed and an emergency meeting be called before the fiscal year goes into effect in order to deny/revise the proposed budget.

There is research to support that affordable housing, educational opportunities, and community outreach programs are more successful at promoting safe and stable communities than law enforcement.

I am demanding long term and sustainable change. I am demanding that the city of Greenville's budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. Programs that support education, housing, healthcare, and community centers deserve our attention and funding. 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@haningtatum Thanks for the great email, please make any applicable revisions before we can add it to the site: 

- please make the primary / first request be a reduced police budget. Delaying a vote is secondary and may be mentioned but should not be first

**Comment by haningtatum** [comment]
I’ll update it!

Thanks!

Sent from my iPhone

On Jun 7, 2020, at 1:27 AM, Sam Wallan <notifications@github.com> wrote:

﻿

@haningtatum<https://github.com/haningtatum> Thanks for the great email, please make any applicable revisions before we can add it to the site:

  *   please make the primary / first request be a reduced police budget. Delaying a vote is secondary and may be mentioned but should not be first

**Comment by haningtatum** [comment]
Updated below: 

To: rmccaskill@greenvillecounty.org, kwhite@greenvillesc.gov, mefird@greenvillesc.gov, jdeworken@greenvillesc.gov, lflemming@greenvillesc.gov, kgibson@greenvillesc.gov, wbrasington@greenvillesc.gov, ddowe@greenvillesc.gov, rstall@greenvillesc.gov

Subject: Defunding Greenville Police Department

Message:

Dear Mayor White and Greenville County Council Members,

My name is [YOUR NAME], and I am a resident of Greenville County.

I am demanding you reallocate funds from the Greenville County Police department and invest them into social services that would directly improve the well-being of Greenville County citizens. The two year budget for the Sheriff’s Office for the 2020-2021 fiscal year is $96,307,964. This is a 6% increase in the budget from the 2018-2019 fiscal year. The largest budget enhancement of the 2020-2021 budget is the addition of fourteen deputies in 2020 and fourteen deputies in 2021- eight more total than the Sheriff requested.

I am also requesting that the budget vote be delayed and an emergency meeting be called before the fiscal year goes into effect in order to deny/revise the proposed budget.

There is research to support that affordable housing, educational opportunities, and community outreach programs are more successful at promoting safe and stable communities than law enforcement.

I am demanding long term and sustainable change. I am demanding that the city of Greenville's budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. Programs that support education, housing, healthcare, and community centers deserve our attention and funding.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ronaldtep** [comment]
Heads up-- I've sent an email to the same recipients about the police department, and I was referred the the Greenville County Council Representatives by Dorothy Dowe (a city council member). 

Here's the email I got:

> Thank you for reaching out, however, as a City Council, we do not have jurisdiction over County matters, which include the Sheriff’s department. Have you forwarded your request to your Greenville County Council representatives? Here is a link to their contact information: https://www.greenvillecounty.org/Council/
> 
> Dorothy Dowe
> City Councilmember
> ddowe@greenvillesc.gov | www.greenvillesc.gov
> 
> Phone:  864-884-4444

**Comment by ronaldtep** [comment]
Here is the contact info on the county council from that website.

Names:
Butch Kirven
Willis Meadows
Xanthene Norris
Joe Dill
Michael Barnes
Sid Cates
Rick Roberts
Bob Taylor
Liz Seman
Ennis Fant
Lynn Ballard
Dan Tripp

emails:
BKirven@greenvillecounty.org
WMeadows@greenvillecounty.org
XNorris@greenvillecounty.org
JDill@greenvillecounty.org
MBarnes@greenvillecounty.org
SCates@greenvillecounty.org
RRoberts@greenvillecounty.org
BTaylor@greenvillecounty.org
LSeman@greenvillecounty.org
EFant@greenvillecounty.org
LBallard@greenvillecounty.org
DTripp@greenvillecounty.org

**Comment by averymcguirt** [comment]
Seems that perhaps there is mixed messaging here between asks of the County sheriff's dep't and city police dep't. 
Cursory search on the county leads to https://www.greenvilleonline.com/story/news/local/2019/05/23/heres-how-you-can-review-greenville-county-proposed-607-million-budget/3767827002/
showing that county wants to give 28 more officers to sheriff's department--more than they even asked for! (final vote is in 10 days, Jun. 18)

Could you clarify the letter to target one or the other department, or more clearly synthesize them into a single letter if you would like to target both groups of officials? Won't presume because I don't live there, but maybe it would be of interest to include the proposed sheriff numbers?

**Comment by haningtatum** [comment]
Hi!

Does this revised version work? Sorry about the miscommunication. I did use that Greenville article as part of my research on the budget! I was having trouble finding the budget specifically for GCPD. They did publish their sheriff budget though.

Dear Mayor White and Greenville County Council Members,


My name is (your name), and I am a resident of Greenville County.


I am demanding you reallocate funds from the Greenville County Police department, more specifically, the Greenville County Sheriff’s Office, and invest them into social services that would directly improve the well-being of Greenville County citizens. For example, the two-year budget for the Sheriff’s Office for the 2020-2021 fiscal year is $96,307,964. This is a 6% increase in the budget from the 2018-2019 fiscal year. The largest budget enhancement of the 2020-2021 budget is the addition of fourteen deputies in 2020 and fourteen deputies in 2021, which is- eight more total than the Sheriff requested. These additional resources are unwarranted and do not contribute to the safety of our community. Current research supports the notion that affordable housing, educational opportunities, and community outreach programs are more successful at promoting safe and stable communities than law enforcement.


I am requesting that the budget vote be delayed and an emergency meeting be called before the fiscal year goes into effect in order to deny/revise the proposed budget. Specifically, I am requesting this delay in order for the money to be reallocated from the Greenville County Police Department and Sheriff’s Office, and be pumped back into our Black, POC, and lower-income communities.


I am demanding long term and sustainable change. I am demanding that the city of Greenville's budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. Programs that support education, housing, healthcare, and community centers deserve our attention and, most importantly, our funding.


Thank you,


(Your name)


________________________________

**Comment by averymcguirt** [comment]
Looks to me that the misunderstanding is that the city has a police department, while the county has the sheriff's department (as in, I don't think there is a GCPD)
Based on your language, let's go with a letter targeted to the county sheriffs (?). Then if you're interested we could make a template targeted to the city government later.

I'll approve this version for PR creation now.

Dear Mayor White and County Council,

My name is [YOUR NAME], and I am a resident of Greenville County. I am demanding you reallocate funds from the Greenville County Sheriff’s Office, and invest them into social services that would directly improve the well-being of Greenville County residents. For example, the two-year budget for the Sheriff’s Office for the 2020-2021 fiscal year is $96,307,964. This is a 6% increase in the budget from the 2018-2019 fiscal year. The largest budget enhancement of the 2020-2021 budget is the addition of fourteen deputies in 2020 and fourteen deputies in 2021, which is eight more total than the Sheriff requested. These additional resources are unwarranted and do not contribute to the safety of our community. Current research supports the notion that affordable housing, educational opportunities, and community outreach programs are more successful at promoting safe and stable communities than law enforcement.

I am requesting that the budget vote be delayed and an emergency meeting be called before the fiscal year goes into effect in order to deny/revise the proposed budget. Specifically, I am requesting this delay in order for the money to be reallocated from the Greenville County Sheriffs, and be pumped back into our Black, POC, and lower-income communities.

I am demanding long term and sustainable change. I am demanding that the county's budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. Programs that support education, housing, healthcare, and community centers deserve our attention and, most importantly, our funding.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

**Comment by haningtatum** [comment]
Ok great! Thanks for the revisions and help. I’ll do some more research!

Sent from my iPhone

On Jun 9, 2020, at 5:15 PM, averymcguirt <notifications@github.com> wrote:

﻿

Looks to me that the misunderstanding is that the city has a police department, while the county has the sheriff's department (as in, I don't think there is a GCPD)
Based on your language, let's go with a letter targeted to the county sheriffs (?). Then if you're interested we could make a template targeted to the city government later.

I'll approve this version for PR creation now.

Dear Mayor White and County Council,

My name is [YOUR NAME], and I am a resident of Greenville County. I am demanding you reallocate funds from the Greenville County Sheriff’s Office, and invest them into social services that would directly improve the well-being of Greenville County residents. For example, the two-year budget for the Sheriff’s Office for the 2020-2021 fiscal year is $96,307,964. This is a 6% increase in the budget from the 2018-2019 fiscal year. The largest budget enhancement of the 2020-2021 budget is the addition of fourteen deputies in 2020 and fourteen deputies in 2021, which is eight more total than the Sheriff requested. These additional resources are unwarranted and do not contribute to the safety of our community. Current research supports the notion that affordable housing, educational opportunities, and community outreach programs are more successful at promoting safe and stable communities than law enforcement.

I am requesting that the budget vote be delayed and an emergency meeting be called before the fiscal year goes into effect in order to deny/revise the proposed budget. Specifically, I am requesting this delay in order for the money to be reallocated from the Greenville County Sheriffs, and be pumped back into our Black, POC, and lower-income communities.

I am demanding long term and sustainable change. I am demanding that the county's budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. Programs that support education, housing, healthcare, and community centers deserve our attention and, most importantly, our funding.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]
