### ISSUE TITLE
Add Southfield, MI

### ISSUE THREAD

**Issue by lorflor** [defund12/defund12.org#581]
To: ksiver@cityofsouthfield.com, lcrews@cityofsouthfield.com, tmorris@cityofsouthfield.com, nbanks@cityofsouthfield.com, dbrightwell@cityofsouthfield.com, jhoskins@cityofsouthfield.com, mmandelbaum@cityofsouthfield.com, ltaylor@cityofsouthfield.com, ilowenberg@cityofsouthfield.com 

SUBJECT: Southfield Resident for Defunding of SPD

To Mayor Siver, Southfield City Council and elected officials: 

My name is [INSERT NAME HERE] and I am a resident of [INSERT CITY/NEIGHBORHOOD]. For centuries, our nation has held persistent racist and oppressive policies against Black communities. And during this past week our nation has come together to mourn, mobilize, and strategize the chokeholds of white supremacy in law enforcement.

Therefore, I am calling for a rapid and meaningful reconsideration of the role of law enforcement in the Southfield Community. In Southfield’s 19-20 FY budget, expenditures on Police vastly exceeded every other category at $45,764,271 allowing for more than half of the city’s expenditures to go towards policing. This is unacceptable for a city where 70.3% of it’s residents are Black and thus more likely to be criminalized, assaulted, and incarcerated by our own law enforcement. 

As our city and neighboring ones alike, march and rally against the unjust murder of George Floyd, I am concerned that the proposed raise in the Police budget will have a negative affect on Black Southfield residents.

I call on you to disinvest the SPD budget for FY 21 and meaningfully reinvest funds into the community. Instead of feeding the disenfranchisement of Black lives, the reallocated funds must be put towards social supports such as affordable housing, quality education, mental health response teams and public health approaches to violence prevention. We must begin valuing and trusting those who live in the community, to know how to best protect our community.

The safest communities don’t have more police—they have more resources. 

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by lorflor** [comment]
Ready for pr

**Comment by averymcguirt** [comment]
Hi there, thanks for your submission. I am a content reviewer, and wondering if you have a source for the $45.8m police budget you cite? Looks to me like it was $27m (35% of the budget--still egregious of course!) 
source: https://www.cityofsouthfield.com/sites/default/files/2019-08/19-20-budget-resolution_final.pdf

I've edited for this, and some minor copy-editing, and unless you have a correction to this budget finding we can go ahead and publish.

To: 
ksiver@cityofsouthfield.com, lcrews@cityofsouthfield.com, tmorris@cityofsouthfield.com, nbanks@cityofsouthfield.com, dbrightwell@cityofsouthfield.com, jhoskins@cityofsouthfield.com, mmandelbaum@cityofsouthfield.com, ltaylor@cityofsouthfield.com, ilowenberg@cityofsouthfield.com

SUBJECT: Southfield Resident for Defunding of SPD

To Mayor Siver and Southfield City Council,

My name is [INSERT NAME HERE] and I am a resident of [INSERT CITY/NEIGHBORHOOD]. For centuries, our nation has upheld and perpetuated persistent racist and oppressive policies against Black communities. And during this past week our nation has come together to mourn, and mobilize against the chokehold of white supremacy in law enforcement.

Therefore, I am calling for a rapid and meaningful reconsideration of the role of law enforcement in the Southfield community. In Southfield’s 19-20 FY budget, expenditures on Police vastly exceeded every other category at $26,774,810. This is unacceptable especially in a city where 70.3% of it’s residents are Black and thus more likely to be criminalized, assaulted, and incarcerated by our own law enforcement.

As we march and rally against the unjust murder of George Floyd, I am concerned that the proposed raise in the Police budget will have a negative affect on Black Southfield residents.

I call on you to divest from the SPD and meaningfully reinvest funds into the community. Instead of feeding the disenfranchisement of Black lives, the reallocated funds must be put towards social supports such as affordable housing, quality education, mental health response teams and public health approaches to violence prevention. We must begin valuing and trusting those who live in the community, to know how to best protect our community.

The safest communities don’t have more police—they have more resources.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by lorflor** [comment]
@averymcguirt Hi! Thank you for reviewing. Here is the source for the 45.8m budget:  https://www.cityofsouthfield.com/sites/default/files/2019-12/city-of-southfield-2019_projected-budget.pdf This number includes police and fire so your data is probably more accurate.

**Comment by dionlarson** [comment]
I'll put together a PR for this now.
