### ISSUE TITLE
Add Belmont, California

### ISSUE THREAD

**Issue by MagicalOwl123** [defund12/defund12.org#586]
To: wlieberman@belmont.gov, cstone@belmont.gov, dhurt@belmont.gov, jmates@belmont.gov, tmccune@belmont.gov, aoskoui@belmont.gov, tfil@belmont.gov, 
Subject: Defund the BPD
Message (Don’t forget to fill in your info)
To the Mayor Lieberman, Vice Mayor Stone, the Belmont City Council, Belmont City Manager, and Belmont Finance Manager: 
My name is [YOUR NAME], and I am a resident of Belmont. I am writing to demand that the Belmont City Council adopts a People’s Budget that prioritizes community wellbeing, and redirects funding away from the police.
This past week our nation has faced protests calling for a rapid and meaningful reconsideration of the role of policing in communities, as well as an end to racism and anti-Blackness in America. The Bay Area, including our small town, has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.
Belmont PD has been a waste of our resources. In 2019 the budget for Law Enforcement and Crime Control was $10,052,972. This means that in 2019 Belmont PD cost us taxpayers twice as much as we spent on Street Maintenance, Parks and Open Spaces, Recreation Programs, Senior Services, and Affordable Housing combined. The Belmont PD budget is excessive for a small town, with a very low crime rate. Also, despite spending an astonishing amount on police, the crime rate rises every year. In light of these facts, I am alarmed to see that Belmont’s projected budget for 2021 shows an increase in spending on police. 
We can be a leader in this issue, if you and our other city officials have the courage to step up. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Belmont residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the Belmont PD budget and instead meaningfully reallocate funds towards social programs and resources that support affordable housing, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.
As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.
We can be a beacon for other cities to follow, if only we have the courage to change.
Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Minor copy-edits below, including replacing language of "crime" (see our style guide https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md )
Follow up with any concerns. 
Ready for PR.

To: wlieberman@belmont.gov, cstone@belmont.gov, dhurt@belmont.gov, jmates@belmont.gov, tmccune@belmont.gov, aoskoui@belmont.gov, tfil@belmont.gov

Subject: Defund the BPD

Dear Mayor Lieberman, Vice Mayor Stone, the Belmont City Council, Belmont City Manager, and Belmont Finance Manager,

My name is [YOUR NAME], and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to demand that the Belmont City Council adopts a budget that prioritizes community wellbeing, and redirects funding away from the police.

This past week our nation has faced protests calling for a rapid and meaningful reconsideration of the role of policing in communities, as well as an end to racism and anti-Blackness in America. The Bay Area, including our small town, has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.
Belmont PD has been a waste of our resources. In 2019 the budget for Law Enforcement and Crime Control was $10,052,972. This means that in 2019 Belmont PD cost us taxpayers twice as much as we spent on Street Maintenance, Parks and Open Spaces, Recreation Programs, Senior Services, and Affordable Housing combined. The Belmont PD budget is excessive for a small town, and I am alarmed to see that Belmont’s projected budget for 2021 shows an increase in spending on police despite historic unemployment, economic instability, and popular resistance to widespread police abuses.

We can be leaders on this issue, if you and our other city officials have the courage to step up. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Belmont residents during this trying and uncertain time, when livelihoods are on the line. I call on you to meaningfully restrict the Belmont PD budget and instead meaningfully reallocate funds towards social programs and resources that support affordable housing, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowering the police forces that tear us apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.
We can be a beacon for other cities to follow, if only we have the courage to change.

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
On it!
