### ISSUE TITLE
Add Santa Monica, CA

### ISSUE THREAD

**Issue by cheekw** [defund12/defund12.org#587]
To: info@santamonica.gov, rick.cole@smgov.net, manager@smgov.net, Katie.Lichtig@smgov.net, Anuj.Gupta@smgov.net, Christopher.J.Smith@smgov.net, debbie.lee@smgov.net, Erin.Taylor@smgov.net, Constance.Farrell@smgov.net, russ.maloney@smgov.net, Tim.Dodd@smgov.net, Lindsay.Barker@smgov.net, julie.rusk@smgov.net, alisa.orduna@smgov.net, council@smgov.net, gleam.davis@smgov.net, terry.oday@smgov.net, anamaria.jara@smgov.net, kevin.mckeown@smgov.net, sue.himmelrich@smgov.net, greg.morena@smgov.net, ted.winterer@smgov.net

Subject:  Reallocate Santa Monica Police Department Funds	

Message: Dear Santa Monica City Managers and Council Members,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand the allocation of resources to prioritize the safety and wellbeing of the city, and away from policing.

In the fiscal year of 2019-2020, Santa Monica's Police Departments allocated budget have escalated to a total of 97 million dollars. This budget has increased by 5.7% (92 million to 97 million) since the fiscal year of 2018-2019. A sharp contrast to the decrease of 19.1% (7.3 million to 5.3 million) spent towards affordable housing and economic development and the meager increase of 3.1% (29 million to 30 million) in community and cultural services which include the social, natural, and cultural resources to advance priorities of affordability, climate change, engaged and thriving community, mobility and access, and reducing homelessness. 

With the increased budget towards the police department every year, the City of Santa Monica has not seen any correlation with a decrease in crime rate. On the contrary, the systematic obstacles that lead to the disproportionate targeting of minority groups and residents of color has caused people in our city to live in fear rather than safety. Police brutality, injustice, and discrimination are intolerable issues of significant importance, yet there have been no signs of improvement in our police systems to uphold impartial security.

I request you to reconsider these spendings on policing when the resources can be distributed towards essential care to ensure the neccesities of the health and wellbeing of all those that reside in our city, addressing healthcare, homelessness, restorative justice, employment, housing, youth programs, public education, and mental health. It is evident throughout historic and existing exemplar nations that the methods of solving social issues have been successful when they are put forth towards a cure for the problem rather than a treatment of the symptoms.

Again, I ask of you as a concerned resident, please consider the demands to improve our community.
 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by cheekw** [comment]
Sources: 
https://finance.smgov.net/budgets-reports/annual#/
https://finance.smgov.net/Media/Default/annual-reports/FYE2020/FYE2020-Operating-Budget.pdf
https://www.santamonica.gov/blog/understanding-santa-monica-s-crime-picture

**Comment by todd-m** [comment]
To: info@santamonica.gov, rick.cole@smgov.net, manager@smgov.net, Katie.Lichtig@smgov.net, Anuj.Gupta@smgov.net, Christopher.J.Smith@smgov.net, debbie.lee@smgov.net, Erin.Taylor@smgov.net, Constance.Farrell@smgov.net, russ.maloney@smgov.net, Tim.Dodd@smgov.net, Lindsay.Barker@smgov.net, julie.rusk@smgov.net, alisa.orduna@smgov.net, council@smgov.net, gleam.davis@smgov.net, terry.oday@smgov.net, anamaria.jara@smgov.net, kevin.mckeown@smgov.net, sue.himmelrich@smgov.net, greg.morena@smgov.net, ted.winterer@smgov.net

Subject: Reallocate Santa Monica Police Department Funds

Message: Dear Santa Monica City Managers and Council Members,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand the allocation of resources to prioritize the safety and well-being of the city, and away from policing.

In the fiscal year of 2019-2020, Santa Monica's Police Departments allocated budget have escalated to a total of $97 million. Their budget has increased by 5.7% ($5 million) since the fiscal year of 2018-2019. This funding is in sharp contrast to the decrease of 19.1% ($2 million) spent towards affordable housing and economic development, and the meager increase of 3.1% ($1 million) in community and cultural services.

Despite the increased budget towards the police department every year, the City of Santa Monica has not seen a meaningful improvement in public safety. On the contrary, the systematic and disproportionate targeting of minority groups and residents of color has caused people in our city to live in fear. Police brutality, injustice, and discrimination are intolerable issues of significant importance, yet there have been no signs of improvement in our police systems to ensure equal treatment of the whole community.

I request that you reconsider excessive spending on policing when these resources can be distributed towards ensuring the health and well-being of all those that reside in our city, by focusing on homelessness, restorative justice, employment, affordable housing, youth programs, public education, and mental health. It is evident throughout history that the challenges of solving social issues have been overcome when they are able to address the problem rather than merely treating its symptoms.

Again, I ask of you as a concerned resident, please consider the demands to improve our community.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
Thanks @cheekw, and appreciate the sources!

**Comment by caldric** [comment]
Converting...

**Comment by cheekw** [comment]
> To: [info@santamonica.gov](mailto:info@santamonica.gov), [rick.cole@smgov.net](mailto:rick.cole@smgov.net), [manager@smgov.net](mailto:manager@smgov.net), [Katie.Lichtig@smgov.net](mailto:Katie.Lichtig@smgov.net), [Anuj.Gupta@smgov.net](mailto:Anuj.Gupta@smgov.net), [Christopher.J.Smith@smgov.net](mailto:Christopher.J.Smith@smgov.net), [debbie.lee@smgov.net](mailto:debbie.lee@smgov.net), [Erin.Taylor@smgov.net](mailto:Erin.Taylor@smgov.net), [Constance.Farrell@smgov.net](mailto:Constance.Farrell@smgov.net), [russ.maloney@smgov.net](mailto:russ.maloney@smgov.net), [Tim.Dodd@smgov.net](mailto:Tim.Dodd@smgov.net), [Lindsay.Barker@smgov.net](mailto:Lindsay.Barker@smgov.net), [julie.rusk@smgov.net](mailto:julie.rusk@smgov.net), [alisa.orduna@smgov.net](mailto:alisa.orduna@smgov.net), [council@smgov.net](mailto:council@smgov.net), [gleam.davis@smgov.net](mailto:gleam.davis@smgov.net), [terry.oday@smgov.net](mailto:terry.oday@smgov.net), [anamaria.jara@smgov.net](mailto:anamaria.jara@smgov.net), [kevin.mckeown@smgov.net](mailto:kevin.mckeown@smgov.net), [sue.himmelrich@smgov.net](mailto:sue.himmelrich@smgov.net), [greg.morena@smgov.net](mailto:greg.morena@smgov.net), [ted.winterer@smgov.net](mailto:ted.winterer@smgov.net)
> 
> Subject: Reallocate Santa Monica Police Department Funds
> 
> Message: Dear Santa Monica City Managers and Council Members,
> 
> My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand the allocation of resources to prioritize the safety and well-being of the city, and away from policing.
> 
> In the fiscal year of 2019-2020, Santa Monica's Police Departments allocated budget have escalated to a total of $97 million. Their budget has increased by 5.7% ($5 million) since the fiscal year of 2018-2019. This funding is in sharp contrast to the decrease of 19.1% ($2 million) spent towards affordable housing and economic development, and the meager increase of 3.1% ($1 million) in community and cultural services.
> 
> Despite the increased budget towards the police department every year, the City of Santa Monica has not seen a meaningful improvement in public safety. On the contrary, the systematic and disproportionate targeting of minority groups and residents of color has caused people in our city to live in fear. Police brutality, injustice, and discrimination are intolerable issues of significant importance, yet there have been no signs of improvement in our police systems to ensure equal treatment of the whole community.
> 
> I request that you reconsider excessive spending on policing when these resources can be distributed towards ensuring the health and well-being of all those that reside in our city, by focusing on homelessness, restorative justice, employment, affordable housing, youth programs, public education, and mental health. It is evident throughout history that the challenges of solving social issues have been overcome when they are able to address the problem rather than merely treating its symptoms.
> 
> Again, I ask of you as a concerned resident, please consider the demands to improve our community.
> 
> Thank you for your time,
> [YOUR NAME]
> [YOUR ADDRESS]
> [YOUR EMAIL]
> [YOUR PHONE NUMBER]

**Comment by cheekw** [comment]
My bad I hit the wrong button when I closed the issue.

Couple of errors:
1. In the fiscal year of 2019-2020, Santa Monica's Police Department's allocated budget has...
2. ...merely treat its symptoms.

**Comment by todd-m** [comment]
@cheekw Thanks! I've passed your first edit along to the person implementing it. The second one may pertain to an older draft as the verb forms appear to match in the current one.
