### ISSUE TITLE
Ventura, CA

### ISSUE THREAD

**Issue by vandelay-vandelayindustries** [defund12/defund12.org#594]
To: mlavere@cityofventura.ca.gov, srubalcava@cityofventura.ca.gov, lbrown@cityofventura.ca.gov, jfriedman@cityofventura.ca.gov, cheitmann@cityofventura.ca.gov, enasarenko@cityofventura.ca.gov, cweir@cityofventura.ca.gov

SUBJECT: Ventura Resident for Defunding the VPD

Dear Mayor LaVere and City Councilmembers,

My name is [YOUR NAME] and I am a resident of Ventura. I am writing to demand that you defund the Ventura Police Department, and use that money to create solutions that work for the people of our city

For the past few weeks, hundreds of thousands of Americans across the country have taken to the streets to protest for change. They want to finally put an end to racism in this country, and win justice for those (especially black Americans) who have been treated unfairly by law enforcement. Furthermore, they want their cities to dramatically reduce the role police play in our society.

I am enraged by the Ventura Police Department’s enormous budget. One in every three dollars spent by the City of Ventura last year went to the VPD -- more than five times what we spent on community development. The FY 2021 Budget recently proposed to the Council guts funding for community development by more than 17%, but barely touches the VPD. This budget punishes Ventura’s most vulnerable while virtually leaving alone a department that eats up $40 of our general fund. Even more outrageous is that the VPD is allotted 25% more funding than it received just four years ago. Spending on police has ballooned, and investment in our communities has stagnated.

Research has shown that community efforts to address homelessness, food insecurity, and mental health keep people far safer than putting more officers on the street. We do not need more police -- we need far fewer police, and we need immediate help for the Venturans bearing the brunt of the ongoing recession. I call on you to slash Ventura’s police spending, and reinvest that money in developing our communities.

We can’t cut programs that help our communities in order to protect our soaring police budget. Instead, we should set an example for cities across America by eliminating the VPD’s bloat and investing in our most vulnerable -- in affordable housing, education, jobs, and more. However, we can only do it if you have the courage to stand up and change our city. Can I count on you to support a budget that reflects what Venturans actually need?

Thank you,

YOUR NAME
YOUR ADDRESS
YOUR EMAIL
YOUR PHONE NUMBER

**Comment by mahrer** [comment]
Some minor edits:

To: mlavere@cityofventura.ca.gov, srubalcava@cityofventura.ca.gov, lbrown@cityofventura.ca.gov, jfriedman@cityofventura.ca.gov, cheitmann@cityofventura.ca.gov, enasarenko@cityofventura.ca.gov, cweir@cityofventura.ca.gov

SUBJECT: Ventura Resident for Defunding the VPD

Dear Mayor LaVere and City Councilmembers,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am writing to demand that you defund the Ventura Police Department and reinvest that funding into solutions that work for the people of our city.

For the past few weeks, hundreds of thousands of Americans across the country have taken to the streets to protest for change. They want to finally put an end to racism in this country, and win justice for those (especially Black Americans) who have been treated unfairly by law enforcement. Furthermore, they want their cities to dramatically reduce the role police play in our society.

I am enraged by the Ventura Police Department’s enormous budget. One in every three dollars spent by the City of Ventura last year went to the VPD -- more than five times what we spent on community development. The FY 2021 Budget recently proposed to the Council guts funding for community development by more than 17%, but barely touches the VPD. This budget punishes Ventura’s most vulnerable while virtually leaving alone a department that eats up $40 of our general fund. Even more outrageous is that the VPD is allotted 25% more funding than it received just four years ago. Spending on police has ballooned, and investment in our communities has stagnated.

Research has shown that community efforts to address homelessness, food insecurity, and mental health keep people far safer than putting more officers on the street. We do not need more police -- we need far fewer police, and we need immediate help for the Venturans bearing the brunt of the ongoing recession. I call on you to slash Ventura’s police spending, and reinvest that money in developing our communities.

We can’t cut programs that help our communities in order to protect our soaring police budget. Instead, we should set an example for cities across America by eliminating the VPD’s bloat and investing in our most vulnerable -- in affordable housing, education, jobs, and more. However, we can only do it if you have the courage to stand up and change our city. Can I count on you to support a budget that reflects what Venturans actually need?

Thank you,

YOUR NAME
YOUR ADDRESS
YOUR EMAIL
YOUR PHONE NUMBER

**Comment by dionlarson** [comment]
On it!

**Comment by root2point0** [comment]
oh I'm sorry! @dionlarson I should have commented I put one in already but can close it if you've pushed!

**Comment by dionlarson** [comment]
No worries @root2point0 just pushed but you have the PR open already so keep yours 🙂

**Comment by vandelay-vandelayindustries** [comment]
thank you guys!
