### ISSUE TITLE
Aurora - Letter to Mayor, City Council, Office of Planning and Budget, and City Management

### ISSUE THREAD

**Issue by undvddattn** [defund12/defund12.org#595]
Aurora - Letter to Mayor, City Council, Office of Planning and Budget, City Management

Subject: Defund Aurora Police Department

Dear Aurora City Council,
I write to demand a reallocation of funding from Aurora PD to social and public programming that takes place in our communities.

I join the calls of those across the country to Defund the Police. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, we need a budget that adequately and effectively meets the needs of at-risk Aurora residents. The Police Department’s 2020 budget increased by $7.0 million (5.7 percent) over the 2019 Budget, making for a total of $128,772,136. This is unacceptable, and I demand that the city council remedy this gross display of priorities. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

Aurora, Colorado has a history of police violence against community members. Due to this history of police violence I demand Aurora establish a Civilian Police Accountability Council (CPAC). I call on Mayor Coffman to open a new investigation into the officers Nathan Woodyard, Jason Rosenblatt, and Randy Roedema responsible for the death of Elijah McClain, and that each officer be taken off duty immediately.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Aurora city budget for the upcoming fiscal year, to reflect the decades of research showing that education and social programs much better promote the safety of a city than policing.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

mcoffman@auroragov.org
cmurillo@auroragov.org
njohnsto@auroragov.org
mberzins@auroragov.org
jmarcano@auroragov.org
acoombs@auroragov.org
fbergan@auroragov.org
cgardner@auroragov.org
dgruber@auroragov.org
ahiltz@auroragov.org
alawson@auroragov.org
budget1@auroragov.org
citymanager@auroragov.org

**Comment by mahrer** [comment]
Aurora - Letter to Mayor, City Council, Office of Planning and Budget, City Management

Subject: Defund Aurora Police Department

Dear Aurora City Council,
I write to demand a reallocation of funding away from Aurora PD and into social and public programming that takes place in our communities.

I join the calls of those across the country to Defund the Police. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, we need a budget that adequately and effectively meets the needs of impacted Aurora residents. The Police Department’s 2020 budget increased by $7.0 million (5.7 percent) over the 2019 Budget, making for a total of $128,772,136. This is unacceptable, and I demand that the city council remedy this gross display of priorities. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or housing affordability in our city. Instead, we see wasteful and harmful actions of our police. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

Aurora, Colorado has a history of police violence against community members. In addition to being defunded, Aurora PD needs to be held accountable. I call on Mayor Coffman to open a new investigation into the officers Nathan Woodyard, Jason Rosenblatt, and Randy Roedema responsible for the death of Elijah McClain, and that each officer be taken off duty immediately.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Aurora city budget for the upcoming fiscal year, reflecting the decades of research showing that education and social programs much better promote the safety of a city than policing.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

mcoffman@auroragov.org
cmurillo@auroragov.org
njohnsto@auroragov.org
mberzins@auroragov.org
jmarcano@auroragov.org
acoombs@auroragov.org
fbergan@auroragov.org
cgardner@auroragov.org
dgruber@auroragov.org
ahiltz@auroragov.org
alawson@auroragov.org
budget1@auroragov.org
citymanager@auroragov.org

**Comment by undvddattn** [comment]
I accept the edits! Thank you for creating this site.

**Comment by undvddattn** [comment]
Can I ask your reasoning for removing the CPAC request?

**Comment by mahrer** [comment]
Per the style guide:
"8. If an email widely pulls in other issues or hones in on something very specific (e.g., funding being reallocated to a single, specific category rather than a more general array of social services), try to generalize. People using this tool can customize their emails to be more specific should they choose."

https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md 

I'm open to input from other team members on this as well. Thanks for your contribution!

**Comment by root2point0** [comment]
@mahrer got it
