### ISSUE TITLE
Add Riverside County, CA

### ISSUE THREAD

**Issue by defundRC** [defund12/defund12.org#599]
To: District1@rivco.org, District2@rivco.org, District3@rivco.org, District4@rivco.org, District5@rivco.org, BcFederico@rivco.org, cob@rivco.org, jaki@rivcoda.org

Subject: Riverside County Resident for Defunding the Police

Dear County of Riverside Officials,

My name is [x], and I am a resident of [x]. I am writing to demand that you, as officials for the County of Riverside, revise your budget proposal to defund the police and redirect that funding into portfolios that prioritizes community wellbeings such as education, housing, and homelessness prevention programs. 

As you may know, we are in the midst of widespread upheaval over the systemic violence of over-policing our communities. George Floyd's murder is one of many instances that show how the role of policing leads to death when racism and anti-Blackness still exist in America. Hence, instead of "reforming" or "reviewing police policies," the time has come to defund the police.

Currently, the County of Riverside recommended a 3% increase appropriation of $1.5 billion towards Public Safety for FY2020-2021. This proposed appropriation is what continues to fund and sustain systemic violence in our county against the Black and Brown community through policing and mass incarceration. As seen with George Floyd's murder, and many others before him, funding the police will not be the solution for a change. 

As such, I urge you to join the calls of those across the country to defund the police. The County of Riverside cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police and support community wellbeing. 

It is your duty to represent your constituents. Thus, I am urging you to revise the County of Riverside budget for FY2020-2021 completely. Public opinion is with me.

Thank you for your time,
[YOUR NAME] 
[ADDRESS] 
[EMAIL] 
[PHONE NUMBER]

**Comment by estecommie** [comment]
Budget Source:
[https://countyofriverside.us/Portals/0/Government/Budget%20Information/20-21/Riverside_FY20-21_Recommended_Budget_FINAL_2020-06-01.pdf?ver=2020-06-02-130433-630&timestamp=1591128279033](url)

page 31

**Comment by itsmemary** [comment]
There's a typo in the first paragraph.. should be "prioritizes" instead of "priorities".

**Comment by defundRC** [comment]
updated!

**Comment by mahrer** [comment]
Edited slightly for grammar but it looks good to me -


To: District1@rivco.org, District2@rivco.org, District3@rivco.org, District4@rivco.org, District5@rivco.org, BcFederico@rivco.org, cob@rivco.org, jaki@rivcoda.org

Subject: Riverside County Resident for Defunding the Police

Dear County of Riverside Officials,

My name is [YOUR NAME], and I am a resident of [NEIGHBORHOOD/CITY]. I am writing to demand that you, as officials for the County of Riverside, revise your budget proposal to defund the police and redirect that funding into services that prioritize community well-being such as education, housing, and homelessness prevention programs.

As you may know, we are in the midst of widespread upheaval over the systemic violence of over-policing our communities. George Floyd's murder is one of many instances that show how the role of policing leads to death when racism and anti-Blackness still exist in America. Hence, instead of "reforming" or "reviewing police policies," the time has come to defund the police.

Currently, the County of Riverside recommended a 3% increase appropriation of $1.5 billion towards Public Safety for FY2020-2021. This proposed appropriation is what continues to fund and sustain systemic violence in our county against the Black and Brown community through policing and mass incarceration. As seen with George Floyd's murder and many others before him, funding the police will not be the solution for a change.

I urge you to join the calls of those across the country to defund the police. The County of Riverside cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police and support community well-being.

It is your duty to represent your constituents. Thus, I am urging you to revise the County of Riverside budget for FY2020-2021 completely. Public opinion is with me.

Thank you for your time,
[YOUR NAME]
[ADDRESS]
[EMAIL]
[PHONE NUMBER]

**Comment by root2point0** [comment]
great :) will do

**Comment by defundRC** [comment]
Edits are in bold. Community members wanted it to be specific to the Sheriffs' department.

Dear County of Riverside Officials,

My name is [YOUR NAME], and I am a resident of [NEIGHBORHOOD/CITY]. I am writing to demand that you, as officials for the County of Riverside, revise your budget proposal to defund the **Riverside County Sheriffs Department** and redirect that funding into services that prioritize community well-being such as education, housing, and homelessness prevention programs.

As you may know, we are in the midst of widespread upheaval over the systemic violence of over-policing our communities. George Floyd's murder is one of many instances that show how the role of policing leads to death when racism and anti-Blackness still exist in America. Hence, instead of "reforming" or "reviewing police policies," the time has come to defund the **Riverside County Sheriffs Department**.

Currently, the County of Riverside recommended a 3% increase appropriation of $1.5 billion towards Public Safety for FY2020-2021. This proposed appropriation is what continues to fund and sustain systemic violence in our county against the Black and Brown community through policing and mass incarceration. As seen with George Floyd's murder and many others before him, funding the law enforcement will not be the solution for a change.

I urge you to join the calls of those across the country to defund the police. The County of Riverside cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police and support community well-being.

It is your duty to represent your constituents. Thus, I am urging you to revise the County of Riverside budget for FY2020-2021 completely. Public opinion is with me.

Thank you for your time, [YOUR NAME] [ADDRESS] [EMAIL] [PHONE NUMBER]

**Comment by defundRC** [comment]
@mahrer Someone already tried merging already and I believe we are just waiting for admin approval. 

[https://github.com/defund12/defund12.org/issues/1030](url)
