### ISSUE TITLE
Add Tucson, AZ

### ISSUE THREAD

**Issue by supasama123** [defund12/defund12.org#628]
To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department 

Message (Don't forget to replace the [x]'s with your information!):
Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year (starting July 1, 2020). In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430 million dollars, that is more than Parks and Recreation ($53,126,400), and Housing and Community Development ($89,091,600). Continuous budgets cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events. 

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities instead of investing in a racist and destructive institution. Defund the Tucson Police Department.

Thank you, 
[NAME]
[Address]
[Phone number]
[Email]

**Comment by todd-m** [comment]
Looks really good, just cleaned it up a little below.

To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department

Message (Don't forget to replace the [x]'s with your information!):
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430, more than Parks and Recreation ($53,126,400) and Housing and Community Development ($89,091,600). Continuous budget cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events.

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and, on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities instead of investing in a racist and destructive institution. Defund the Tucson Police Department.

Thank you,
[NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL]

**Comment by laurensides** [comment]
I think this sounds great, but I think you should also add a line about repealing Ordinance 11746:

To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department

Message (Don't forget to replace the [x]'s with your information!):
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD] and I am emailing today to demand a complete overhaul on the Tucson Police Department in light of the Black Lives Matter protests being demonstrated across the US and in our city. 

I ask that you, my local officials, will:

1.	Vote NO on all increases to police budgets. 
2.	Votes YES to decrease police spending and budgets. 
3.	Vote YES to increase spending on health care, education, and community programs that keep us safe. 
4.	Repeal Ordinance 11746. 

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430, more than Parks and Recreation ($53,126,400) and Housing and Community Development ($89,091,600). Continuous budget cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events.

Furthermore, Ordinance 11746 must be repealed on that basis that it is entirely unconstitutional. Although the Supreme Court has never specifically discussed the right to record, the 1st, 3rd, 5th, 7th, 9th, and 11th U.S. Circuit Courts of Appeals have all held that the First Amendment plainly protects the filming of officers and public. When you are lawfully present in any public space, you have the right to photograph or record anything in plain view, including federal buildings and police. 

The rhetoric of Ordinance 11746 allows law enforcement officers to infringe on the rights of citizens by making our presence at a crime scene unlawful. This ordinance allows officers to decide when and where they can be recorded on duty and in public, and prevents citizens from holding officers accountable for their actions. You have witnessed across the country the value of having video evidence of police brutality – do not stand in the way of justice by allowing this ordinance to remain in effect. 

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and, on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities and to repeal Ordinance 11746. Defund the Tucson Police Department.

Thank you,
[NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL]

**Comment by supasama123** [comment]
I agree, although I think maybe focusing on the impact of the ordinance rather than the legality because legality can be argued and defended all they want by them, but the impact cannot be denied, which is what you highlighted very well. that is just my personal opinion, my edit just removed the legality paragraph

To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department

Message (Don't forget to replace the [x]'s with your information!):
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD] and I am emailing today to demand a complete overhaul on the Tucson Police Department in light of the Black Lives Matter protests being demonstrated across the US and in our city.

I ask that you, my local officials, will:

Vote NO on all increases to police budgets.
Votes YES to decrease police spending and budgets.
Vote YES to increase spending on health care, education, and community programs that keep us safe.
Repeal Ordinance 11746.

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430, more than Parks and Recreation ($53,126,400) and Housing and Community Development ($89,091,600). Continuous budget cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events.

The rhetoric of Ordinance 11746 allows law enforcement officers to infringe on the rights of citizens by making our presence at a crime scene unlawful. This ordinance allows officers to decide when and where they can be recorded on duty and in public, and prevents citizens from holding officers accountable for their actions. You have witnessed across the country the value of having video evidence of police brutality – do not stand in the way of justice by allowing this ordinance to remain in effect.

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and, on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities and to repeal Ordinance 11746. Defund the Tucson Police Department.

Thank you,
[NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL]

**Comment by todd-m** [comment]
Per our [style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) specific issues should be avoided in the templates, so we might want to keep it out overall.

**Comment by supasama123** [comment]
okay then back to the original

To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department

Message (Don't forget to replace the [x]'s with your information!):
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].

I ask that you, my local officials, will:

Vote NO on all increases to police budgets.
Votes YES to decrease police spending and budgets.
Vote YES to increase spending on health care, education, and community programs that keep us safe.

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430, more than Parks and Recreation ($53,126,400) and Housing and Community Development ($89,091,600). Continuous budget cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events.

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and, on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities. Defund the Tucson Police Department.

Thank you,
[NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL]

**Comment by todd-m** [comment]
Cool, thanks all. Just a couple tiny edits and we have:

To: Ward1@tucsonaz.gov, Ward2@tucsonaz.gov, Ward3@tucsonaz.gov, Ward4@tucsonaz.gov, Ward5@tucsonaz.gov, Ward6@tucsonaz.gov, citymanager@tucsonaz.gov, Mayor.Romero@tucsonaz.gov

Subject: Defund the Tucson Police Department

Message (Don't forget to replace the [x]'s with your information!):
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD].

I ask that you, my local officials, will:

* Vote NO on all increases to police budgets.
* Vote YES to decrease police spending and budgets.
* Vote YES to increase spending on health care, education, and community programs that keep us safe.

The City of Tucson must do better by its residents. I am urging you to divest from the criminalization of our communities and reduce police spending in the budget for the 2021 fiscal year. In May, Mayor Romero warned of deep spending cuts due to the pandemic. It is time to cut funding for the Tucson Police Department.

In the previous budget, police received $193,274,430, more than Parks and Recreation ($53,126,400) and Housing and Community Development ($89,091,600). Continuous budget cuts in Education slash essential after-school and enrichment programs, and large cuts in Parks and Rec over the years force a shortage of hours of recreation centers and special events.

I know many of you feel strongly about racial justice and equity. Mayor Romero claims to have a commitment to the people of Tucson, and, on June 2, claimed that the police require "systemic reform and meaningful policy change." Your words are meaningless unless you use your power to take action on that.

Individual solutions will not fix systemic problems. It is time for Tucson, its leaders, and residents to create a more equitable city for all of us. Have the moral clarity to reallocate a budget to focus on communities. Defund the Tucson Police Department.

Thank you,
[NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL]

**Comment by ctneal91** [comment]
on it now
