### ISSUE TITLE
Petaluma, CA

### ISSUE THREAD

**Issue by brickaney** [defund12/defund12.org#631]
To: tbarrett@cityofpetaluma.org

dfischer@cityofpetaluma.org

mhealy@cityofpetaluma.org

gkearney@cityofpetaluma.org

dking@cityofpetaluma.org

kmcdonnell@cityofpetaluma.org

kmiller@cityofpetaluma.org

Subject line: Petaluma Resident For Defunding The Petaluma Police Department

﻿(Don't forget to replace the [x]'s with your information!) 🔗 
Dear Petaluma City Leaders,

I am writing you today out of great concern for our community and our future. I am [INSERT IDENTIFYING INFO BUT ONLY AS MUCH AS YOU FEEL COMFORTABLE WITH INCLUDING THE AMOUNT OF TIME YOU’VE BEEN A RESIDENT OF PETALUMA, IF YOU’RE A LOCAL BUSINESS OWNER, ANY OTHER COMMUNITY TIES LIKE FAITH COMMUNITY OR OTHER COMMUNITY-BASED ORGS]

As Black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor an EMT killed by officers while asleep in her bed in Louisville. Their names are added to a devastatingly long list of Black people who have been killed at the hands of law enforcement - it is time for us to make different decisions. We demand change in the operation of the criminal legal system, we demand that we take care of our community instead of criminalizing those amongst us who need help, and we demand that police are not the front line responders to every emergency or call for help.

In Petaluma, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. I am writing to you today to demand that the Petaluma City Council invest in alternative responses to law enforcement that actually keep our community safe and healthy. Law Enforcement should be the Exception, not the rule.

Increasingly, The United States has responded to every emergency or call for help with law enforcement. Meanwhile, our communities desperately lack meaningful access to healthcare, employment, and housing. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, while funding for public health has decreased every year. According to the Urban Institute, in 1977, state and local governments spent $42 billion on police and corrections [1]. In 2017, they spent $115 billion [1]. A 270 percent increase. In Petaluma, funding for local police is proposed to make up 39 percent of the city budget [2]. Housing and community services accounts for only 2 percent [2]. That is a staggering and illuminating statistic. What does it say about our community? It says that rather than responding to the needs in our community with meaningful support and resources, we respond with law enforcement. This is unacceptable. Where could that money go? It could go towards building healthy communities, to housing development, to neighborhood infrastructure, to education, to childcare. The possibilities are endless.

Therefore we demand the following: The creation of a local police commission and a city council subcommittee on alternatives to policing. Investment in local alternatives to policing. This should include investments in existing community based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including: Unarmed mediation and intervention teams, Social worker teams and mental health experts, as well as Restorative Justice programs. We further request that an emergency meeting of the full city council be immediately scheduled to address these concerns. You are welcome to contact me with any questions or concerns regarding these requests.

Regards,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

[1] https://www.urban.org/policy-centers/cross-center-initiatives/state-and-local-finance-initiative/state-and-local-backgrounders/police-and-corrections-expenditures
[2] https://cityofpetaluma.org/documents/fiscal-year-2021-proposed-budget/

**Comment by brickaney** [comment]
I updated the content to include references and adjusted the statistical numbers to match said references.

**Comment by mahrer** [comment]
Some minor edits:

To: tbarrett@cityofpetaluma.org

dfischer@cityofpetaluma.org

mhealy@cityofpetaluma.org

gkearney@cityofpetaluma.org

dking@cityofpetaluma.org

kmcdonnell@cityofpetaluma.org

kmiller@cityofpetaluma.org

Subject line: Petaluma Resident For Defunding The Petaluma Police Department

﻿(Don't forget to replace the [x]'s with your information!) 🔗

Dear Petaluma City Leaders,

I am writing you today out of great concern for our community and our future. I am [INSERT IDENTIFYING INFO BUT ONLY AS MUCH AS YOU FEEL COMFORTABLE WITH INCLUDING THE AMOUNT OF TIME YOU’VE BEEN A RESIDENT OF PETALUMA, IF YOU’RE A LOCAL BUSINESS OWNER, ANY OTHER COMMUNITY TIES LIKE FAITH COMMUNITY OR OTHER COMMUNITY-BASED ORGS]

As Black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor, an EMT killed by officers while asleep in her bed in Louisville. Their names are added to a devastatingly long list of Black people who have been killed at the hands of law enforcement - it is time for us to make different decisions. We demand change in the operation of the criminal legal system, we demand that we take care of our community instead of criminalizing those amongst us who need help, and we demand that police are not the front line responders to every emergency or call for help.

In Petaluma, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. I am writing to you today to demand that the Petaluma City Council invest in alternative responses to law enforcement that actually keep our community safe and healthy.

Increasingly, The United States has responded to every emergency or call for help with law enforcement. Meanwhile, our communities desperately lack meaningful access to healthcare, employment, and housing. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, while funding for public health has decreased every year. According to the Urban Institute, in 1977, state and local governments spent $42 billion on police and corrections [1]. In 2017, they spent $115 billion [1], a 270 percent increase. 

In Petaluma, funding for local police is proposed to make up 39 percent of the city budget [2]. Housing and community services accounts for only 2 percent [2]. That is a staggering and illuminating statistic. What does it say about our community? It says that rather than responding to the needs in our community with meaningful support and resources, we respond with law enforcement. This is unacceptable. Where could that money go? It could go towards building healthy communities, to housing development, to neighborhood infrastructure, to education, to childcare. The possibilities are endless.

Therefore, I demand the following: The creation of a local police commission and a city council subcommittee on alternatives to policing. Investment in local alternatives to policing. This should include investments in existing community based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies. Some examples of alternative responses include unarmed mediation and intervention teams, social worker teams and mental health experts, and restorative justice programs. I further request that an emergency meeting of the full City Council be immediately scheduled to address these concerns.

Regards,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://www.urban.org/policy-centers/cross-center-initiatives/state-and-local-finance-initiative/state-and-local-backgrounders/police-and-corrections-expenditures
[2] https://cityofpetaluma.org/documents/fiscal-year-2021-proposed-budget/

**Comment by brickaney** [comment]
Looks good to me!

**Comment by root2point0** [comment]
on it!
