### ISSUE TITLE
Defund Jamestown PD

### ISSUE THREAD

**Issue by Ken029** [defund12/defund12.org#633]
To: billpiva8@cox.net mgblanco@cox.net meagherjamestowntc@gmail.com
jtownelc@aol.com Major510@cox.net
Subject: Budget for The Community 
Dear Jamestown Town Council, 
         My name is [Your Name] and I am a resident of [Your Neighborhood]. I am writing to demand that Jamestown Town Council adopt a town budget that prioritizes community welfare and redirects funding away from police. 
 This fiscal year the town plans to give just over 1.8 million to our police system, a substantial 15.5% of the budget. Community development interests by contrast make up only 9% of the budget collectively when the library, parks and recreation and public health budgets are added together. Out of the community development interests only 31,000 dollars is allocated to Public Health services(0.2% of the budget), and no money allocated to affordable housing. 
   I demand that Town Council begin defunding Jamestown Police, and  re-allocate those funds to community programs that could truly help the Jamestown community, like community based mental health services, affordable housing, and other improved social services. I demand a budget reflecting what the community of Jamestown needs.
    The Jamestown community needs to take part in meaningful change. We may be small, but we must consider the message that our community sends when it does not take part in considering our role in perpetuating systems of harm instead of providing for those most in need. 

Sincerely,
[Your Name]
[Your Address]
[Your Phone Number]

**Comment by averymcguirt** [comment]
Some very minor edits for sentence clarity:

To: billpiva8@cox.net mgblanco@cox.net meagherjamestowntc@gmail.com
jtownelc@aol.com Major510@cox.net
Subject: Budget for The Community

Dear Jamestown Town Council,

My name is [Your Name] and I am a resident of [Your Neighborhood]. I am writing to demand that Jamestown Town Council adopt a town budget that prioritizes community welfare and redirects funding away from police.

This fiscal year the town plans to give just over 1.8 million to our police system, a substantial 15.5% of the budget. Community development interests--including libraries, parks, recreation, and public health--by contrast make up only 9% of the budget in total. Out of the community development interests only 31,000 dollars is allocated to Public Health services(0.2% of the budget), and no money is allocated to affordable housing.

I demand that Town Council begin defunding Jamestown Police, and re-allocate those funds to community programs that could truly help the Jamestown community, like community based mental health services, affordable housing, and other improved social services. I demand a budget reflecting what the community of Jamestown needs.

The Jamestown community needs to take part in meaningful change. We may be small, but we must consider the message that our community sends when it does not take part in considering our role in perpetuating systems of harm instead of providing for those most in need.

Sincerely,
[Your Name]
[Your Address]
[Your Phone Number]

**Comment by root2point0** [comment]
on it!
