### ISSUE TITLE
Stockton, CA

### ISSUE THREAD

**Issue by tavila82** [defund12/defund12.org#647]
To: mayor@stocktonca.gov, dist1@stocktonca.gov, dist2@stocktonca.gov, dist3@stocktonca.gov, dist4@stocktonca.gov, dist5@stocktonca.gov, dist6@stocktonca.gov, Florence.low@stocktonca.gov 🔗
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
“To whom it may concern,

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. We demand that the City Council defund the SPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Stockton residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]”

**Comment by maturple** [comment]
@tavila82 hi there! My name is Mathilde and I'm a member of the "Stockton stands with Minneapolis" group on Facebook. I've been looking for resources for those who support defunding in the area. Would you mind posting this in the group or messaging me on Facebook?

**Comment by tavila82** [comment]
Hi Mathilde, thanks for reaching out. I actually don't have facebook and I'm new to github, so I don't quite know how this works entirely. I noticed that there was no entry for Stockton and decided to create one. If you're able, please share the email with your Facebook group. The city council budget meeting is this Wednesday.

**Comment by swallan** [comment]
To: mayor@stocktonca.gov, dist1@stocktonca.gov, dist2@stocktonca.gov, dist3@stocktonca.gov, dist4@stocktonca.gov, dist5@stocktonca.gov, dist6@stocktonca.gov, Florence.low@stocktonca.gov 🔗
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
“Dear Mayor Tubbs and City Council Members,

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a budget for the people that prioritizes community well-being and redirects funding away from the police, including the proposed police funding increase of $3,311,169 in the upcoming year.

We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. We demand that the City Council defund the SPD. We join the calls of those across the country to meaningfully reduce funding to the police department. We demand a budget that adequately and effectively meets the needs of impacted Stockton residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund people, not police. We must take immediate action on this issue. 

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]”

**Comment by root2point0** [comment]
working on it
