### ISSUE TITLE
Defunding the Tampa Police Department.

### ISSUE THREAD

**Issue by rainedkero** [defund12/defund12.org#652]
To: tampacitycouncil@tampagov.net

Dear Tampa City Council,

My name is [INSERT NAME] and I am a resident of [INSERT NEIGHBORHOOD, SUBDIVISION, CITY, ETC], today I am writing to you to demand that the mayor and the city council adopt a smaller budget for the police department that lends more towards community programs and outreach to keep our community safe. Programs such as housing, education, jobs and healthcare.

The recommended budget for the police department for 2020 according to the publicly released budget expense report came in at over $162,000,000. This is an astronomical number alone and as well when compared to the budgets of other departments, where this budget could have been reallocated and reinvested in the citizens rather than a militarized police force as we have seen nightly within the prior weeks. I am planting a call to action that you at the earliest possible avenue reallocate these funds to the community instead of a military police force.

The citizens of Tampa would be better benefited by investing in health care for mental health, homelessness, affordable housing, as these are issues that are still very prominent in Tampa, rather than this, we are witnessing harmful, wasteful actions by the Tampa Police Department using these funds.

I call on you as well as the mayor to slash this budget, invest in the citizens of Tampa and set an example largely for the Tampa Bay area and for the nation as a whole, with these initiatives, we can lead the nation in a new way that's been previously unimagined.

Can I count on you to reallocate and reinvest these funds? If not, you can count on me to make sure you are voted out.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
## Changelog

1. added individual emails (found [here](https://www.tampabaychamber.com/Business-Advocacy/Elected-Officials/Local.aspx))
2. Sentence structure in second paragraph
3. could -> should

## Questions

{IN PROGRESS}

## Current

To: tampacitycouncil@tampagov.net
Joseph.Citro@tampagov.net
charlie.miranda@tampagov.net
John.Dingfelder@tampagov.net
Bill.Carlson@tampagov.net
Orlando.Gudes@tampagov.net
guido.maniscalco@tampagov.net
luis.viera@tampagov.net

Dear Tampa City Council,

My name is [INSERT NAME] and I am a resident of [INSERT NEIGHBORHOOD, SUBDIVISION, CITY, ETC], today I am writing to you to demand that the mayor and the city council adopt a smaller budget for the police department that lends more towards community programs and outreach to keep our community safe. Programs such as housing, education, jobs and healthcare.

The recommended budget for the police department for 2020 according to the publicly released budget expense report came in at over $162,000,000. This is an astronomical number alone and as well when compared to the budgets of other departments. This budget should have been reallocated and reinvested in the citizens rather than a militarized police force as we have seen nightly within the prior weeks. I am planting a call to action that you at the earliest possible avenue reallocate these funds to the community instead of a military police force.

The citizens of Tampa would be better benefited by investing in health care for mental health, homelessness, affordable housing, as these are issues that are still very prominent in Tampa, rather than this, we are witnessing harmful, wasteful actions by the Tampa Police Department using these funds.

I call on you as well as the mayor to slash this budget, invest in the citizens of Tampa and set an example largely for the Tampa Bay area and for the nation as a whole, with these initiatives, we can lead the nation in a new way that's been previously unimagined.

Can I count on you to reallocate and reinvest these funds? If not, you can count on me to make sure you are voted out.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
## Changelog

1. added individual emails (found [here](https://www.tampabaychamber.com/Business-Advocacy/Elected-Officials/Local.aspx))
2. sentence structure and wording in second paragraph
3. third paragraph swapped with portion from St Pete proposal 
4. sentence structure and wording in fourth paragraph


## Questions

How's this look to you @rainedkero?

## Current

To: jane.castor@tampagov.net
tampacitycouncil@tampagov.net
joseph.citro@tampagov.net
charlie.miranda@tampagov.net
john.dingfelder@tampagov.net
bill.carlson@tampagov.net
orlando.gudes@tampagov.net
guido.maniscalco@tampagov.net
luis.viera@tampagov.net

Dear Mayor Jane Castor & Tampa City Council,

My name is [INSERT NAME] and I am a resident of [INSERT NEIGHBORHOOD, SUBDIVISION, CITY, ETC], today I am writing to you to demand that the mayor and the city council adopt a smaller budget for the police department that lends more towards community programs and outreach to keep our community safe. Programs such as housing, education, jobs and healthcare.

The recommended police department budget for 2020 according to the publicly released budget expense report came in at over $162,000,000. This is an astronomical number alone and as well when compared to the budgets of other departments. This budget should have been reallocated and reinvested in the community rather than the militarized police force we have seen clashing with peaceful protestors.

I demand that the City Council begin meaningfully defunding the Tampa Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Tampa residents.

I call on City Council as well as the mayor to slash this budget, invest in the citizens of Tampa, and set an example for the Tampa Bay area and for the nation as a whole. With these initiatives, we can lead the nation in a new way that's been previously unimagined.

Can I count on you to reallocate and reinvest these funds? If not, you can count on me to make sure you are voted out.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
Thank you for your help @rainedkero. I've taken a first pass at editing your proposed letter. I'm happy to discuss any changes with you -- my goal was to simplify language.

It looks like the review process is on pause until after a meeting tonight at 9pm ET to better coordinate the full review process. I'll pick this up again to get it on the website once approved.

**Comment by rainedkero** [comment]
Of course, I am happy to help. It looks fantastic and all cleaned up! I'm excited to help everyone out a little.

Sincerely,
Hunter
________________________________

**Comment by serifluous** [comment]
👍 Budget $ confirmed on page 93 here https://www.tampagov.net/sites/default/files/budget/files/FY2020-budget1.pdf

One change: Remove the last sentence about voting since not every email sender may have voting power.

**Comment by averymcguirt** [comment]
Concur with serifluous above. If no other issues, I think this is ready for PR.

To: jane.castor@tampagov.net, tampacitycouncil@tampagov.net, joseph.citro@tampagov.net, charlie.miranda@tampagov.net, john.dingfelder@tampagov.net, bill.carlson@tampagov.net, orlando.gudes@tampagov.net, guido.maniscalco@tampagov.net, luis.viera@tampagov.net

Dear Mayor Jane Castor & Tampa City Council,

My name is [INSERT NAME] and I am a resident of [INSERT NEIGHBORHOOD, SUBDIVISION, CITY, ETC]. This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. Today I am writing to you to demand that the mayor and the city council adopt a smaller budget for the police department that lends more towards community programs and outreach to keep our community safe. Programs such as housing, education, jobs and healthcare.

The recommended police department budget for 2020 according to the publicly released budget expense report came in at over $162,000,000. This is an astronomical number alone and as well when compared to the budgets of other departments. This budget should have been reallocated and reinvested in the community rather than the militarized police force we have seen clashing with peaceful protestors.

I demand that the City Council begin meaningfully defunding the Tampa Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Tampa residents.

I call on City Council as well as the mayor to slash this budget, invest in the citizens of Tampa, and set an example for the Tampa Bay area and for the nation as a whole. With these initiatives, we can lead the nation in a new way that's been previously unimagined.

Can I count on you to reallocate these funds for justice and social equity?

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
