### ISSUE TITLE
Add Texas cities to defund12

### ISSUE THREAD

**Issue by ecommerce-guy** [defund12/defund12.org#66]
Please add Austin, Dallas/Ft Worth, San Antonio, Houston, and El Paso

**Comment by kirkpatricia** [comment]
Thank you for opening this request!

**Comment by serifluous** [comment]
San Antonia template proposed in #226

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
