### ISSUE TITLE
ADD: Newton, MA police defunding

### ISSUE THREAD

**Issue by socash3** [defund12/defund12.org#662]
- Subject line: Defund Newton Police Department!
- Email addresses: 

rfuller@newtonma.gov,citycouncil@newtonma.gov,acicconejr@newtonma.gov,salbright@newtonma.gov,akelley@newtonma.gov,jkrintzman@newtonma.gov,dcrossley@newtonma.gov,vdanberg@newtonma.gov,mlaredo@newtonma.gov,rlipof@newtonma.gov,aleary@newtonma.gov,jauchincloss@newtonma.gov,pwright@newtonma.gov,lgentile@newtonma.gov,adowns@newtonma.gov,abowman@newtonma.gov,rwgrossman@newtonma.gov,dkalis@newtonma.gov
--

- Message:
Dear Mayor Fuller and City Council Members,

My name is [YOUR NAME] and I live in Newton, MA. I am writing to ask that you use your power to reject the proposed increase of $147k to the Newton Police Department’s FY21 budget. With a multi-billion dollar drop in revenue due to the many complications of COVID-19 and other departments losing money, an increase for the NPD budget does not make sense or benefit our city. This money should instead go toward the Library, Health & Human Services, Senior Services, Affordable Housing, Youth Services, treatment and healing for physical and mental health issues, accessible green energy jobs, or other community-building programs that benefit communities of color and low income communities.

As people across the country demand creative alternatives to policing, the last thing Newton needs is new police cruisers. Social service programs are what make our community safe, not more policing that leads to the murder and incarceration of Black, Indigenous, and Brown people of color who are already disproportionately affected by the current economic and health crisis and by police brutality. If Newton is truly a town where Black Lives Matter, as was said to protestors at City Hall, then please demonstrate it through our tax dollars.

Sincerely,
[YOUR NAME]
[ADDRESS]

**Comment by skullface** [comment]
Edited for [adherence to style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md):

```
- rfuller@newtonma.gov
- citycouncil@newtonma.gov
- acicconejr@newtonma.gov
- salbright@newtonma.gov
- akelley@newtonma.gov
- jkrintzman@newtonma.gov
- dcrossley@newtonma.gov
- vdanberg@newtonma.gov
- mlaredo@newtonma.gov
- rlipof@newtonma.gov
- aleary@newtonma.gov
- jauchincloss@newtonma.gov
- pwright@newtonma.gov
- lgentile@newtonma.gov
- adowns@newtonma.gov
- abowman@newtonma.gov
- rwgrossman@newtonma.gov
- dkalis@newtonma.gov
```

Dear Mayor Fuller and City Council Members,

My name is [YOUR NAME] and I live in Newton, MA. I am writing to ask that you use your power to reject the proposed increase of $147k to the Newton Police Department’s FY21 budget. With a multi-billion dollar drop in revenue due to the many complications of COVID-19 and other departments losing money, an increase for the NPD budget does not make sense or benefit our city. This money should instead go toward the Library, Health & Human Services, Senior Services, Affordable Housing, Youth Services, treatment and healing for physical and mental health issues, accessible green energy jobs, or other community-building programs that benefit communities of color and low-income communities.

As people across the country demand creative alternatives to policing, the last thing Newton needs is new police cruisers. Social service programs are what make our community safe, not more policing that leads to the murder and incarceration of Black people, Indigenous people, and people of color who are already disproportionately affected by the current economic and health crisis and by police brutality. If Newton is truly a town where Black Lives Matter, as was said to protestors at City Hall, then please demonstrate it through our tax dollars.

Sincerely,
[YOUR NAME]
[ADDRESS]

**Comment by ctneal91** [comment]
on it now
