### ISSUE TITLE
New City Request- Concord, NH (Partially adopted from Manchester, NH)

### ISSUE THREAD

**Issue by apribis1** [defund12/defund12.org#665]
**To:** jpbouley@comcast.net, brenttoddconcord@gmail.com, pierce4council@comcast.net, JKretovic@concordnh.gov, mhatfield@concordnh.gov, rwerner@concordnh.gov, LKenison@concordnh.gov, knyhan@concordnh.gov, gmatson@concordnh.gov, cwbouchard@concordnh.gov, zricehawkins@concordnh.gov, nfennessy@concordnh.gov, agradysexton@concordnh.gov, fkeach@concordnh.gov, chamby@comcast.net, finance@concordnh.gov

**Subject:** Defund Concord Police Department

**Message:**

Dear Concord Government Officials,
 
My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police and towards social services that actually keep our community safe. 
 
We are in the midst of a pandemic that has had severe consequences on our city. As of April 2020, the unemployment rate in Merrimack County has skyrocketed to 15.8% of the labor force. According to Concord Coalition to End Homelessness we are “bracing for a new wave of homelessness.” The responsibility of solving this rising crisis cannot fall on outside organizations and private donors. 

Supporting communities in need is necessary now, more than ever. Yet the FY 2021 Budget would increase the Concord Police's budget by nearly a million dollars. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons. As such, I demand more aggressive financial support be directed to those areas, particularly in response to the economic impact of COVID-19. I insist as a taxpayer of the city of Concord that funds be reallocated from the Concord Police to Human Services to ensure that the basic needs of all Concord citizens are met.  
 
As our poor communities and communities of color are disproportionate targets of police violence and disproportionately affected by the COVID-19 pandemic, the current proposed budget for 2021 that would increase the budget of the Concord Police is unacceptable. We must join the calls of those across the country to Defund The Police and demand a budget that adequately and ethically meets the needs of at-risk Concord residents during this trying and uncertain time, when livelihoods are on the line. I insist on a budget that supports community wellbeing, rather than empowers the police forces that tear them apart. 
 
 
Thank you for your time,
 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by apribis1** [comment]
Here are the email recipients: jpbouley@comcast.net, brenttoddconcord@gmail.com, pierce4council@comcast.net, JKretovic@concordnh.gov, mhatfield@concordnh.gov, rwerner@concordnh.gov, LKenison@concordnh.gov, knyhan@concordnh.gov, gmatson@concordnh.gov, cwbouchard@concordnh.gov, zricehawkins@concordnh.gov, nfennessy@concordnh.gov, agradysexton@concordnh.gov, fkeach@concordnh.gov, chamby@comcast.net, finance@concordnh.gov

I am unsure of where to put them within the template.

**Comment by swallan** [comment]
To: jpbouley@comcast.net, brenttoddconcord@gmail.com, pierce4council@comcast.net, JKretovic@concordnh.gov, mhatfield@concordnh.gov, rwerner@concordnh.gov, LKenison@concordnh.gov, knyhan@concordnh.gov, gmatson@concordnh.gov, cwbouchard@concordnh.gov, zricehawkins@concordnh.gov, nfennessy@concordnh.gov, agradysexton@concordnh.gov, fkeach@concordnh.gov, chamby@comcast.net, finance@concordnh.gov

Subject: Defund Concord Police Department

Message:

Dear Concord Government Officials,

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police and towards social services that actually keep our community safe.

We are in the midst of a pandemic that has had severe consequences on our city. As of April 2020, the unemployment rate in Merrimack County has skyrocketed to 15.8% of the labor force. According to Concord Coalition to End Homelessness we are “bracing for a new wave of homelessness.” The responsibility of solving this rising crisis cannot fall on outside organizations and private donors.

Supporting communities in need is necessary now, more than ever. Yet the FY 2021 Budget would increase the Concord Police's budget by nearly a million dollars. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful promoting community safety than police or prisons. As such, I demand more aggressive financial support be directed to those areas, particularly in response to the economic impact of COVID-19. I insist as a taxpayer of the city of Concord that funds be reallocated from the Concord Police to Human Services to ensure that the basic needs of all Concord citizens are met.

As our poor communities and communities of color are disproportionate targets of police violence and disproportionately affected by the COVID-19 pandemic, the current proposed budget for 2021 that would increase the budget of the Concord Police is unacceptable. We must join the calls of those across the country to Defund The Police and demand a budget that adequately and ethically meets the needs of at-risk Concord residents during this trying and uncertain time, when livelihoods are on the line. I insist on a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
