### ISSUE TITLE
Menlo Park, CA

### ISSUE THREAD

**Issue by nelbow** [defund12/defund12.org#677]
To: CTTaylor@menlopark.org; DCombs@menlopark.org; BNash@menlopark.org; CCarlton@menlopark.org; RDMueller@menlopark.org 🔗
Subject: Defund Menlo Park Police Department
Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Menlo Park City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Menlo Park City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In 2018, the City of Menlo Park allocated $25.37 million dollars Government and Public Safety where $17.8 million was directed directly to police funding. This means police funding is an inordinate 70% Government and Public Safety budget and 21% of our total budget This is compared to just $6.3 million allocated towards community development (7.5% of the budget). Within the community development budget in 2018, $4.5 million (72% of the Community Development budget) was spent on Construction Regulation and no money was allocated to housing, redevelopment or employment.

I demand that the City Council begin meaningfully defunding the Menlo Park Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Menlo Park residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to re-imagine the role of police in our city.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
Reviewed and made a few small edits below. Looks good to me otherwise.

To: CTTaylor@menlopark.org; DCombs@menlopark.org; BNash@menlopark.org; CCarlton@menlopark.org; RDMueller@menlopark.org 🔗
Subject: Defund Menlo Park Police Department
Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Menlo Park City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Menlo Park City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In 2018, the City of Menlo Park allocated $25.37 million dollars to Government and Public Safety, with $17.8 million specifically for police funding. This means police funding is an inordinate 70% of the Government and Public Safety budget, and 21% of our total budget. This is compared to just $6.3 million allocated towards community development (7.5% of the budget). Within the community development budget in 2018, $4.5 million (72% of the Community Development budget) was spent on Construction Regulation and no money was allocated to housing, redevelopment or employment.

I demand that the City Council begin meaningfully defunding the Menlo Park Police Department and reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Menlo Park residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by nelbow** [comment]
Awesome, thank you! Looks good to me.

**Comment by nelbow** [comment]
@todd-m sorry if this is obvious or not how this works, but how to do I publish this? or do admins only publish? thanks

**Comment by todd-m** [comment]
@nelbow not obvious :) I've just marked it ready to be picked up by our email dev team, who will add it to the site shortly. Nothing you need to do, but you can watch this issue for updates when that happens.

**Comment by root2point0** [comment]
on it

**Comment by nelbow** [comment]
thanks!!
