### ISSUE TITLE
Emeryville, CA

### ISSUE THREAD

**Issue by tsolo1234** [defund12/defund12.org#678]
**TO**: crpatz@emeryville.org, dmartinez@emeryville.org, jbauters@emeryville.org, sdonahue@emeryville.org, amedina@emeryville.org

**SUBJECT**: [*** INSERT UNIQUE SUBJECT LINE***]

**Message**

Dear Emeryville Mayor and City Council Members:

My name is [YOUR NAME] and I am a resident of Emeryville, CA. This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. Our little town experienced some of the righteous and valid anger that Black communities have felt for centuries. Our police force's response was less than acceptable. Videos of the Gamestop loot showed police using what looked like flash-bang grenades to disperse those kids. As a combat veteran, and with studies showing that flash bangs cause permanent hearing damage, I was appalled that police would use such weapons against their own communities. Moreover, the fact that such weapons were used against kids--it was a Gamestop after all--was even more infuriating. We may have an interest to protect property, but that interest can never overcome our interest to protect people. Gamestop has insurance, those kids, on the other hand, will continue to deal with the same systemic issues that they, their parents, and generations before them have had to face.

Such police action clearly displays that our local police embodies the same problems being marched against all across our country. At the same time, we spend more on police than any other department: 31% of our budget. Community services amounted to just 8%.

I demand that we slash the police budget and defund its programs to meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. I demand a budget that supports community wellbeing, instead of empowering police to physically hurt community members while solving none of the underlying issues. Further, police reform cannot help us, that much is clear. Instead we must move away from militaristic services provided by the polices to people-oriented services that try to resolve problems in the community, rather than beating them down.

If this is the first you are hearing about defunding police, please read the article at this link: https://www.nytimes.com/2020/06/05/us/defund-police-floyd-protests.html

Additionally, the ACLU has compiled a few guidelines that would be helpful in beginning to implement such a plan: https://action.aclu.org/petition/divest-police-invest-black-and-brown-communities

The current system has failed us. We must look to new ways of providing a safe environment to everyone in our community and reimagining the role of police in our little town.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
TO: crpatz@emeryville.org, dmartinez@emeryville.org, jbauters@emeryville.org, sdonahue@emeryville.org, amedina@emeryville.org

SUBJECT: [*** INSERT UNIQUE SUBJECT LINE***]

Message

Dear Emeryville Mayor and City Council Members:

My name is [YOUR NAME] and I am a resident of Emeryville, CA. This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. Our little town experienced some of the righteous and valid anger that Black communities have felt for centuries. Our police force's response was less than acceptable. Videos of the Gamestop loot showed police using what looked like flash-bang grenades to disperse those kids. Studies showing that flash bangs cause permanent hearing damage, and I was appalled that police would use such weapons against their own communities. Moreover, the fact that such weapons were used against kids--it was a Gamestop after all--was even more infuriating. We may have an interest to protect property, but that interest can never overcome our interest to protect people. Gamestop has insurance, those kids, on the other hand, will continue to deal with the same systemic issues that they, their parents, and generations before them have had to face.

Such police action clearly displays that our local police embodies the same problems being marched against all across our country. At the same time, we spend more on police than any other department: 31% of our budget. Community services amounted to just 8%.

I demand that we slash the police budget and defund its programs to meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. I demand a budget that supports community wellbeing, instead of empowering police to physically hurt community members while solving none of the underlying issues. Further, police reform cannot help us, that much is clear. Instead we must move away from militaristic services provided by the polices to people-oriented services that try to resolve problems in the community, rather than beating them down.

Many other cities, including Minneapolis, are now beginning to defund their police departments. It is possible, and we can look to them for guidance.

The current system has failed us. We must look to new ways of providing a safe environment to everyone in our community and reimagining the role of police in our little town.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
will do!

**Comment by tsolo1234** [comment]
TO: crpatz@emeryville.org, dmartinez@emeryville.org, jbauters@emeryville.org, sdonahue@emeryville.org, amedina@emeryville.org

SUBJECT: [*** INSERT UNIQUE SUBJECT LINE***]

Message

Dear Emeryville Mayor and City Council Members:

My name is [YOUR NAME] and I am a resident of Emeryville, CA. This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. Our little town experienced some of the righteous and valid anger that Black communities have felt for centuries. Our police force's response was less than acceptable. Videos of the Gamestop loot showed police using what looked like flash-bang grenades to disperse those kids. Studies show that flash bangs cause permanent hearing damag, and I was appalled that police would use such weapons against their own communities. Moreover, the fact that such weapons were used against kids--it was a Gamestop after all--was even more infuriating. We may have an interest in protecting property, but that interest can never overcome our interest in protecting people--that includes the people who are protesting and lashing out against a system of oppression that has pushed them down since the day they were born. Gamestop has insurance, those kids, on the other hand, will continue to deal with the same systemic issues that they, their parents, and generations before them have had to face.

Such police action clearly displays that our local police embodies the same problems being marched against all across our country. At the same time, we spend more on police than any other department: 31% of our budget. Community services amounted to just 8%.

I demand that we slash the police budget and defund its programs to meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. I demand a budget that supports community wellbeing, instead of empowering police to physically hurt community members while solving none of the underlying issues. Further, police reform cannot help us, that much is clear. Instead we must move away from militaristic services provided by the polices to people-oriented services that try to resolve problems in the community, rather than beating them down.

Many other cities, including Minneapolis, are now beginning to defund their police departments. It is possible, and we can look to them for guidance.

The current system has failed us. We must look to new ways of providing a safe environment to everyone in our community and reimagining the role of police in our little town.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]
