### ISSUE TITLE
Request to add city: Newark, DE

### ISSUE THREAD

**Issue by modonne42** [defund12/defund12.org#698]
**To:** gjclifton@verizon.net, horningfornewark@gmail.com, Shughes2853@gmail.com, jen@jenwallacefornewark.org, hamilton4newark@gmail.com, lawhornfornewark@gmail.com, stu.markham@gmail.com
**Subject:** [*** INSERT UNIQUE SUBJECT LINE***]
**Message** (Don't forget to replace the [x]'s with your information!)

Dear Honorable Mayor Clifton and City Council Members,

My name is [YOUR NAME], and I am a resident of [YOUR DISTRICT]. I am writing to request that the City of Newark reallocate money away from the Newark Delaware Police Department and towards community well-being. We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

From 2019 to 2020, the Newark Delaware Police Department budget increased by 7.1%, meaning that its operational budget for 2020 is $15,823,387. Meanwhile, the 2020 budget for community development is abysmally low at only $248,147 (a 0.2% decrease from 2019 to 2020). Support for communities in need is necessary now, more than ever. It is shameful and unacceptable that our police receive more than 60 times the amount of funding that our community development programs receive, and over 500 times the amount allocated for social services (currently funded at a measly $30,000). We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Newark residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community well-being, rather than empowers the police forces that tear them apart.

As the City Council, future budget proposals are in your hands. It is your duty to represent your constituents. Much scholarship shows that a living wage, access to social and health services, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I am asking city officials to please reject any proposed budget that increases taxpayer spending on police while cutting funding for important social and community projects. Instead, I am urging you to design the budget for 2021 (and all subsequent budgets) in a way that redirects funding away from the police and towards social and community projects. I am also asking that city officials lobby the same amount of attention and effort towards finding sustainable, long term change.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
To: gjclifton@verizon.net, horningfornewark@gmail.com, Shughes2853@gmail.com, jen@jenwallacefornewark.org, hamilton4newark@gmail.com, lawhornfornewark@gmail.com, stu.markham@gmail.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!)

Dear Honorable Mayor Clifton and City Council Members,

My name is [YOUR NAME], and I am a resident of [YOUR DISTRICT]. I am writing to request that the City of Newark reallocate money away from the Newark Delaware Police Department and towards community well-being. We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

From 2019 to 2020, the Newark Delaware Police Department budget increased by 7.1%, meaning that its operational budget for 2020 is $15,823,387. Meanwhile, the 2020 budget for community development is abysmally low at only $248,147 (a 0.2% decrease from 2019 to 2020). Support for communities in need is necessary now, more than ever. It is shameful and unacceptable that our police receive more than 60 times the amount of funding that our community development programs receive, and over 500 times the amount allocated for social services (currently funded at a measly $30,000). We join the calls of those across the country to defund the police. We demand a budget that adequately and effectively meets the needs of impacted Newark residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community well-being, rather than empowers the police forces that tear them apart.

As the City Council, future budget proposals are in your hands. It is your duty to represent your constituents. Much scholarship shows that a living wage, access to social and health services, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I am asking city officials to please reject any proposed budget that increases taxpayer spending on police while cutting funding for important social and community projects. Instead, I am urging you to design the budget for 2021 (and all subsequent budgets) in a way that redirects funding away from the police and towards social and community projects. I am also asking that city officials lobby the same amount of attention and effort towards finding sustainable, long term change.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
