### ISSUE TITLE
Add East Lansing, MI

### ISSUE THREAD

**Issue by daswickerman** [defund12/defund12.org#699]
To: rbeier@cityofeastlansing.com, astephens@cityofeastlansing.com, lbabcock@cityofeastlansing.com, jgregg@cityofeastlansing.com, mmeadows@cityofeastlansing.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 
Hello,

My name is [YOUR NAME] and I am a resident of East Lansing. I am writing to demand that funding is reallocated from the ELPD to social and public programs in our community. It is an outrage that 65% of city funding goes towards the Police Department while public works and cultural investment is less than 10% of the city budget. The ELPD has seen a number of high profile abuse and violence claims recently and the budget should reflect that poor performance.

We demand that the City Council defund the East Lansing Police Department. We join the calls of those across the country to defund the police. We demand a budget that adequately and effectively meets the needs of at-risk East Lansing residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers police.

It is your duty to represent your constituents. I am urging you to completely revise the proposed East Lansing city budget for FY2021. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
To: rbeier@cityofeastlansing.com, astephens@cityofeastlansing.com, lbabcock@cityofeastlansing.com, jgregg@cityofeastlansing.com, mmeadows@cityofeastlansing.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)
Hello,

My name is [YOUR NAME] and I am a resident of East Lansing. I am writing to demand that funding is reallocated from the ELPD to social and public programs in our community. It is an outrage that 32% of city funding goes towards the Police Department while public works and cultural investment is less than 10% of the city budget. The ELPD has seen a number of high profile abuse and violence claims recently and the budget should reflect that poor performance.

We demand that the City Council defund the East Lansing Police Department. We join the calls of those across the country to defund the police. We demand a budget that adequately and effectively meets the needs of at-risk East Lansing residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers police.

It is your duty to represent your constituents. I am urging you to completely revise the proposed East Lansing city budget for FY2021. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
