### ISSUE TITLE
Email for La Crosse WI

### ISSUE THREAD

**Issue by poetrymafia** [defund12/defund12.org#701]
gaulm@cityoflacrosse.org, 
happeld@cityoflacrosse.org, richmonda@cityoflacrosse.org, neumeisters@cityoflacrosse.org, janssenb@cityoflactosse.org, sleznikowl@cityoflacrosse.org, weaverj@cityoflactosse.org, kahlowc@cityoflacrosse.org, padeskyg@cityoflacrosse.org, olsonje@cityoflacrosse.org, ostremp@cityoflacrosse.org, medingerp@cityoflacrosse.org, christiansr@cityoflacrosse.org

Subject: We demand further measures to rein in La Crosse policing

Message:
Dear city council members,

My name is [YOUR NAME] and I live in [NEIGHBORHOOD/CITY]. Recently the city of La Crosse added a website to display ‘transparency in policing.’ While I applaud the willingness to listen to protesters and add a measure like this, we in the community are well aware that with such serious issues in our city, state, and country, more serious measures must be taken. That is why I am asking that the La Crosse Council make a more overt and visible commitment to racial justice by reallocating law enforcement funding towards city welfare programs that provide support for those most vulnerable in our community, and programs that facilitate the dismantling of racial and class inequality. 

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons. As such, I demand more aggressive financial support be directed to those areas. I also urge the La Crosse Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. Justice will only be served when the police are reformed, and this will not be possible until we defund them. People are marching in the streets because they know that these actions will result in a healthier, more just society. Can I count on your focus on social service programs?

 Thank you, 
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
gaulm@cityoflacrosse.org,
happeld@cityoflacrosse.org, richmonda@cityoflacrosse.org, neumeisters@cityoflacrosse.org, janssenb@cityoflactosse.org, sleznikowl@cityoflacrosse.org, weaverj@cityoflactosse.org, kahlowc@cityoflacrosse.org, padeskyg@cityoflacrosse.org, olsonje@cityoflacrosse.org, ostremp@cityoflacrosse.org, medingerp@cityoflacrosse.org, christiansr@cityoflacrosse.org

Subject: We demand further measures to rein in La Crosse policing

Message:
Dear city council members,

My name is [YOUR NAME] and I live in [NEIGHBORHOOD/CITY]. Recently the city of La Crosse added a website to display ‘transparency in policing.’ While I applaud the willingness to listen to protesters and add a measure like this, we in the community are well aware that with such serious issues in our city, state, and country, more serious measures must be taken. That is why I am asking that the La Crosse Council make a more overt and visible commitment to racial justice by reallocating law enforcement funding towards city welfare programs that provide support for those most vulnerable in our community, and programs that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than police or prisons. As such, I demand more aggressive financial support be directed to those areas. I also urge the La Crosse Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. People are marching in the streets because they know that these actions will result in a healthier, more just society. Can I count on your focus on social service programs?

Thank you,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
