### ISSUE TITLE
Add Boise, ID

### ISSUE THREAD

**Issue by raxtID** [defund12/defund12.org#708]
Dear Mayor McLean and Boise City Council Members,

My name is [YOUR NAME], and I am a resident of Boise. Following yet another string of highly-publicized murders of Black Americans by law enforcement, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as as a significant step in dismantling systems that do not serve, and in fact actively harm, Black Americans and Americans of color. This moment is an opportunity to rethink public safety in Boise and reinvest in services that more effectively benefit our residents now and in the long-term. We have the opportunity to creatively put into place changes that can transform our community for the better and show that Boise really is one of the most 'liveable cities in America' - for all Boiseans, present and future.

Although Boise is not at the forefront of these protests, it is not exempt from the racism and violence of the police system. I am asking that you consider reallocating significant funds from the BPD budget to fund systems and programs that serve our community more effectively. We need more affordable housing, safety nets for those at risk of eviction, food-access supports for those who need them, behavioral health crisis responders that are trained appropriately to de-escalate and provide access to holistic services, and social workers that can serve those that have experienced domestic violence and abuse. Our community needs healing - not punishment because of the lack of resources and supports being offered.

According to the City of Boise's budget, nearly 30%, or $70,006,493 is allocated to the Boise Police Department. The single LARGEST budget category in the city budget. Only .018% of this policing budget is allocated toward mental health services coordination in policing, .032% of this budget is allocated toward the crisis negotiation team. In the 2019 annual city budget report, BPD says that "Law enforcement faces a growing threat from offenders armed with higher powered weapons, so BPD is researching and purchasing more robust safety equipment to better protect officers and citizens in active shooter situations." However, according to the City of Boise's crime rate reports, violent crimes has been stagnating and decreasing in recent years - not increasing. Why has BPD been asking for funds to defend against "active shooters" when this does not seem to be a substantiated threat? As of FY20, the Boise Police Department plans to use public funds to renovate multiple stations and build another. Again, with crime decreasing in Boise, why are more stations needed? What could these resources fund instead?

The city's community engagement budget is just 1% of Boise's overall budget, which includes projects that support those experiencing housing insecurity and homelessness, as well as events that bring tourism revenue to Boise; yet within this budget it includes allocated funds for police recruitment materials. Funds allocated to support community supports should NOT be allocated to recruiting even more police officers for the city.

The city of Boise MUST reconsider how it prioritizes its budget. Boise does a disservice to all Black and brown community members by continuing to fund policing rather than actual community support systems that will lessen our dependency on police intervention. Reallocating funds will make all Boiseans safer.  

I demand that the Mayor's office and City Council begin meaningfully defunding the Boise Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Boise residents.

The added economic impact of COVID-19 requires a complete re-imagining of how we allocate local resources, and makes abundantly clear that we must prioritize investments in our community's health and well-being. The city of Boise can address deficits by divesting from the violence of policing and incarceration. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. Existing racial and economic disparities will only worsen in the wake of this ongoing health and economic crisis. We know that this virus is disproportionately affecting Black and brown communities, and that this disparity is caused by racist systems that affect how and when people receive care.

History has shown that police "reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to re-imagine the role of police in our city.  Imagine if Boise could be on the front lines of a movement of change in our country, one that could be truly transformative? What could our city look like in 5, 10, and 20 years?

Thank you for your time, 

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by shortcircuit3** [comment]
Do you have the email addresses?

**Comment by raxtID** [comment]
Sorry, yes.

Mayor McLean:  mayormclean@cityofboise.org
City Council Members:
tjthomson@cityofboise.org
elaineclegg@cityofboise.org
holliwoodings@cityofboise.org
lisasanchez@cityofboise.org
patrickbageant@cityofboise.org
jimmyhallyburton@cityofboise.org

**Comment by raxtID** [comment]
Hi - is there another step I can or should take to move this along in the review process, and get this on the website soon? Thank you!!

**Comment by ploguus** [comment]
Let's get this posted!

**Comment by averymcguirt** [comment]
Sorry this stalled! Tagging it as ready now. Thank you for the submission.

**Comment by averymcguirt** [comment]
Actually replaced one sentence about  'crime' to better fit our style guide
(9. Avoid using police framing of community problems, i.e. “crime.” Instead of summarizing social programs as being more effective than policing at “reducing crime,” say that they are more effective at “promoting community safety.”)


Dear Mayor McLean and Boise City Council Members,

My name is [YOUR NAME], and I am a resident of Boise. Following yet another string of highly-publicized murders of Black Americans by law enforcement, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as as a significant step in dismantling systems that do not serve, and in fact actively harm, Black Americans and Americans of color. This moment is an opportunity to rethink public safety in Boise and reinvest in services that more effectively benefit our residents now and in the long-term. We have the opportunity to creatively put into place changes that can transform our community for the better and show that Boise really is one of the most 'liveable cities in America' - for all Boiseans, present and future.

Although Boise is not at the forefront of these protests, it is not exempt from the racism and violence of the police system. I am asking that you consider reallocating significant funds from the BPD budget to fund systems and programs that serve our community more effectively. We need more affordable housing, safety nets for those at risk of eviction, food-access supports for those who need them, behavioral health crisis responders that are trained appropriately to de-escalate and provide access to holistic services, and social workers that can serve those that have experienced domestic violence and abuse. Our community needs healing - not punishment because of the lack of resources and supports being offered.

According to the City of Boise's budget, nearly 30%, or $70,006,493 is allocated to the Boise Police Department. The single LARGEST budget category in the city budget. Only .018% of this policing budget is allocated toward mental health services coordination in policing, .032% of this budget is allocated toward the crisis negotiation team. In the 2019 annual city budget report, BPD says that "Law enforcement faces a growing threat from offenders armed with higher powered weapons, so BPD is researching and purchasing more robust safety equipment to better protect officers and citizens in active shooter situations." However, according to the City of Boise's crime rate reports, violent crimes has been stagnating and decreasing in recent years - not increasing. Why has BPD been asking for funds to defend against "active shooters" when this does not seem to be a substantiated threat? As of FY20, the Boise Police Department plans to use public funds to renovate multiple stations and build another. Again, it's been shown that social programs and education are far more effective than policing at promoting safe communities. What could these resources fund instead?

The city's community engagement budget is just 1% of Boise's overall budget, which includes projects that support those experiencing housing insecurity and homelessness, as well as events that bring tourism revenue to Boise; yet within this budget it includes allocated funds for police recruitment materials. Funds allocated to support community supports should NOT be allocated to recruiting even more police officers for the city.

The city of Boise MUST reconsider how it prioritizes its budget. Boise does a disservice to all Black and brown community members by continuing to fund policing rather than actual community support systems that will lessen our dependency on police intervention. Reallocating funds will make all Boiseans safer.

I demand that the Mayor's office and City Council begin meaningfully defunding the Boise Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Boise residents.

The added economic impact of COVID-19 requires a complete re-imagining of how we allocate local resources, and makes abundantly clear that we must prioritize investments in our community's health and well-being. The city of Boise can address deficits by divesting from the violence of policing and incarceration. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. Existing racial and economic disparities will only worsen in the wake of this ongoing health and economic crisis. We know that this virus is disproportionately affecting Black and brown communities, and that this disparity is caused by racist systems that affect how and when people receive care.

History has shown that police "reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to re-imagine the role of police in our city. Imagine if Boise could be on the front lines of a movement of change in our country, one that could be truly transformative? What could our city look like in 5, 10, and 20 years?

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by raxtID** [comment]
Thank you!! That edit makes total sense - I appreciate your help and am very excited to start sharing this out.

**Comment by root2point0** [comment]
working on submitting!

**Comment by raxtID** [comment]
Will this be posted to the Defund12.org site today? I know there have been a lot of requests - there's potentially a brief window where we can have the Mayor and City Council's ears this week and we are trying to capture it.

**Comment by raxtID** [comment]
Hey there - email addresses are bouncing. Can someone quickly change to .gov instead of .org in the email addresses?

**Comment by root2point0** [comment]
Hey,
I was looking to confirm .gov emails on the official city website, but all
I found was .org. Have you found sources stating that it's .gov? I'm happy
to change them if we can find that! Feel free to link on the original
GitHub thread.
[image: Screen Shot 2020-06-11 at 7.44.18 AM.png]

**Comment by raxtID** [comment]
Hi there! I got the correct email addresses - they are not .gov! I deleted
the comment. I was getting different information, but I tested these emails
and they work:

mayormclean@cityofboise.org

tjthomson@cityofboise.org
eclegg@cityofboise.org
hwoodings@cityofboise.org
lsanchez@cityofboise.org
pbageant@cityofboise.org
jhallyburton@cityofboise.org

**Comment by raxtID** [comment]
If you're able to make a quick edit that would be great!!
