### ISSUE TITLE
Letter to Mayor and City Council of Lafayette CA

### ISSUE THREAD

**Issue by moldander** [defund12/defund12.org#757]
manderson@lovelafayette.org, scandell@lovelafayette.org, sbliss@lovelafayette.org, CBurks@lovelafayette.org, tgerringer@lovelafayette.org

Defund Lafayette Police Noq

To Mayor Anderson and Lafayette City Council Members,

My name is [NAME], and I am a resident of Lafayette. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The fact that the Lafayette Police Department encompasses over 6 million dollars of the city’s general operating fund (already over 3 times MORE than public works or city planning) with apparent goals to increase by hundreds of thousands of dollars each year is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote to increase police funding by over 500 Thousand dollars . Do not be complicit in the disproportionate targeting and continuous oppression of people of color. Propose and vote to expand on Lafayette’s current efforts like the Affordable Housing program and funding of nonprofits like the Lafayette. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Lafayettec city budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,
[YOUR NAME]

**Comment by skullface** [comment]
Edited for [adherence to style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md):

---

```
- manderson@lovelafayette.org
- scandell@lovelafayette.org
- sbliss@lovelafayette.org
- CBurks@lovelafayette.org
- tgerringer@lovelafayette.org
```

To Mayor Anderson and Lafayette City Council Members,

My name is [NAME] and I am a resident of Lafayette. This month our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard and that real change be made to the way this city allocates its resources.

The fact that the Lafayette Police Department encompasses over $6 million of the city’s general operating fund (already over 3 times MORE than public works or city planning) with apparent goals to increase by hundreds of thousands of dollars each year is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition. The entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris, a doctoral candidate focusing on race, argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (Source: The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

I demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

I urge you not to vote to increase police funding by over $500,000. Do not be complicit in the disproportionate targeting and continuous oppression of people of color. Propose and vote to expand on Lafayette’s current efforts like the Affordable Housing program and funding of community-focused nonprofits. I demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the Lafayette city budget for the upcoming fiscal year to fund the social programs long proven to be much more effective than policing at promoting community safety and equity. Public opinion is with me.

Thank you for your time,
[YOUR NAME]

**Comment by ctneal91** [comment]
on it now
