### ISSUE TITLE
Request to add Los Gatos PD to Defund12.org list

### ISSUE THREAD

**Issue by cvpgallinat** [defund12/defund12.org#770]
**Subject line for the email: [* INSERT UNIQUE SUBJECT LINE***]****

**Email addresses:**
mjensen@losgatosca.gov, bspector@losgatosca.gov, rrennie@losgatosca.gov, msayoc@losgatosca.gov, Police@LosGatosCA.gov, cmartinez@LosGatosCA.gov, CTada@LosGatosCA.gov, ELunsford@LosGatosCA.gov, mdantonio@LosGatosCA.gov, STada@LosGatosCA.gov, GBorromeo@losgatosca.gov, jrose@losgatosca.gov, STada@LosGatosCA.gov, planning@losgatosca.gov, jpaulson@losgatosca.gov, jfong@losgatosca.gov, szarnowitz@losgatosca.gov, jarmer@losgatosca.gov, ewalters@losgatosca.gov, jshoopman@losgatosca.gov, smullin@losgatosca.gov, rsafty@losgatosca.gov, dmora@losgatosca.gov, mchavarin@losgatosca.gov, tmaheu@losgatosca.gov, finance@losgatosca.gov, attorney@losgatosca.gov, rschultz@losgatosca.gov, llampros@losgatosca.gov, manager@losgatosca.gov, aandrews@losgatosca.gov, sneis@losgatosca.gov, jjudd@losgatosca.gov, lseastrom@losgatosca.gov, hzappala@losgatosca.gov, chill@losgatosca.gov, HTarling@losgatosca.gov, mrenn@losgatosca.gov, 

**Detailed message concerning the budgeting decisions at stake in your community:**

To Whom It May Concern,

My name is [YOUR NAME] and I am a resident of Los Gatos. I am writing to urge you to defund the Los Gatos Police Department.

LGPD takes an enormous share of the city’s general fund, and that percentage has only risen over the last two decades, taking away desperately needed resources from essential city programs and services. The investment in policing has not made us safer – LGPD is a lethal threat to Los Gatos' Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With Los Gatos current finances in dire jeopardy due to the COVID-19 financial crisis, it is clear that we must defund the police.

As Los Gatos residents, we therefore demand that you take immediate action to ensure the following:

- Reduce LGPD’s allocation from the General Fund by 50%
- Disallow unauthorized overtime by LGPD
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
- Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

We are amplifying calls to defund the police, not reform them. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

Los Gatos cannot wait any longer for a budget that meets the needs of all its residents. The only way to achieve this is to take immediate steps to Defund LGPD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @cvpgallinat ! Thanks for your interest in adding Los Gatos to the site. Can you provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by cvpgallinat** [comment]
Can someone take over for me on this? I’ve had a family emergency and needed to travel. Would really appreciate help!

**Comment by wendywx** [comment]
edits in bold:

--------------------------------------------------

Email addresses:
mjensen@losgatosca.gov, bspector@losgatosca.gov, rrennie@losgatosca.gov, msayoc@losgatosca.gov, Police@LosGatosCA.gov, cmartinez@LosGatosCA.gov, CTada@LosGatosCA.gov, ELunsford@LosGatosCA.gov, mdantonio@LosGatosCA.gov, STada@LosGatosCA.gov, GBorromeo@losgatosca.gov, jrose@losgatosca.gov, STada@LosGatosCA.gov, planning@losgatosca.gov, jpaulson@losgatosca.gov, jfong@losgatosca.gov, szarnowitz@losgatosca.gov, jarmer@losgatosca.gov, ewalters@losgatosca.gov, jshoopman@losgatosca.gov, smullin@losgatosca.gov, rsafty@losgatosca.gov, dmora@losgatosca.gov, mchavarin@losgatosca.gov, tmaheu@losgatosca.gov, finance@losgatosca.gov, attorney@losgatosca.gov, rschultz@losgatosca.gov, llampros@losgatosca.gov, manager@losgatosca.gov, aandrews@losgatosca.gov, sneis@losgatosca.gov, jjudd@losgatosca.gov, lseastrom@losgatosca.gov, hzappala@losgatosca.gov, chill@losgatosca.gov, HTarling@losgatosca.gov, mrenn@losgatosca.gov,

Detailed message concerning the budgeting decisions at stake in your community:

**To Mayor Jensen, Vice Mayor Spector, Town Council Members, and Elected Officers and Staff,**

My name is [YOUR NAME] and I am a resident of Los Gatos. I am writing to urge you to defund the Los Gatos Police Department.

LGPD takes an enormous share of the **town's** general fund, **at 36.7%. Compared to the FY 2019-20 adopted budget, the proposed budget for LGPD for FY 2020-21 increased by $647,039, while the proposed budget for Community Development decreased by $243,069. The LGPD proposed budget is also more than the proposed budgets for Community Development, Parks & Public Works, and Library Services combined.** This investment in policing has not made us safer – LGPD is a lethal threat to Los Gatos' Black, Brown, **and Indigenous** communities. With Los Gatos current finances in dire jeopardy due to the COVID-19 financial crisis, it is clear that **the LGPD budget must be reallocated**.

As **a Los Gatos resident**, **I** demand that you take immediate action and update the FY 2020-21 budget beginning July 1, 2020 to ensure the following:

1. Reduce LGPD’s allocation from the General Fund
2. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
3. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

I urge you to advocate for a meaningful reallocation of the **town's** expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

Los Gatos cannot wait any longer for a budget that meets the needs of all its residents. The only way to achieve this is to take immediate steps to **divest from** LGPD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

--------------------------------------------

I added some statistics (from https://www.losgatosca.gov/DocumentCenter/View/24483/Financial-Summaries?bidId=) and also removed the demands with specific numerical targets. Also removed "Disallow unauthorized overtime by LGPD" because I was unable to find evidence that LGPD allowed unauthorized overtime as per the LGPD [policy manual](https://www.losgatosca.gov/DocumentCenter/View/24666/RELEASE_20200611_T194221_Los_Gatos-Monte_Sereno_Police_Department_Policy_Manual). And made some edits to align with the [email guidelines](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md). Marking this ticket as ready for PR.

**Comment by todd-m** [comment]
edits look good @wendywx -- picking this up now
