### ISSUE TITLE
Request to add Worcester, MA

### ISSUE THREAD

**Issue by makechange11** [defund12/defund12.org#773]
To: mayor@worcesterma.gov, BergmanM@worcesterma.gov, ColorioD@worcesterma.gov, KingK@worcesterma.gov, RosenG@worcesterma.gov, ToomeyK@worcesterma.gov

Subject:  [*** INSERT UNIQUE SUBJECT LINE***]

Dear Mayor Joseph M. Petty and Members of the Worcester City Council,

My name is [Insert Name Here] and I am a resident of Worcester, MA. In light of the events that have occurred including but not limited to the murders of George Floyd and Breonna Taylor I demand to see the reduction of funding for the Worcester Police Department. Rather than invest in a system that has been founded on racist principles and that has perpetuated the unnecessary deaths of so many Black people nation wide, I suggest we reallocate money towards building up and supporting the Black and Brown communities that make Worcester the city it is. 

The 2020 fiscal budget allocated over $52 million to the Worcester Police Department. I believe that this money could be have a greater use being invested in education, healthcare, and countless other social programs at the benefit of Worcester's Black and Brown communities. The City Council must take a stand for racial justice by significantly defunding policing.

Racist police violence doesn’t just happen in other cities - it happens here in Worcester too. However, with action we can create change. The City Council must stop investing so large sums of money into a system created to perpetuate racism and discrimination and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.

Sincerely,
[Your Name]

**Comment by wendywx** [comment]
edits in bold:
------------------------------------------
To: mayor@worcesterma.gov, BergmanM@worcesterma.gov, ColorioD@worcesterma.gov, KingK@worcesterma.gov, RosenG@worcesterma.gov, ToomeyK@worcesterma.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Dear Mayor Joseph M. Petty and Members of the Worcester City Council,

My name is **[YOUR NAME]** and I am a resident of Worcester, MA. In light of the events that have occurred including but not limited to the murders of George Floyd and Breonna Taylor I demand to see the reduction of funding for the Worcester Police Department. Rather than invest in a system that has been founded on racist principles and that has perpetuated the unnecessary deaths of so many Black people nation wide, I suggest we reallocate money towards building up and supporting the Black and Brown communities that make Worcester the city it is.

The 2020 fiscal budget allocated over $52 million to the Worcester Police Department, **more than the budget for Health and Human Services, Human Resources, and Public Works and Parks combined.** I believe that this money could be have a greater use being invested in education, healthcare, and countless other social programs at the benefit of Worcester's Black and Brown communities. The City Council must take a stand for racial justice by significantly defunding policing.

Racist police violence doesn’t just happen in other cities - it happens here in Worcester too. However, with action we can create change. The City Council must stop investing so large sums of money into a system created to perpetuate racism and discrimination and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.

Sincerely,
**[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]**

----------------------------------------------
Confirmed statistics from:
http://www.worcesterma.gov/uploads/f9/cc/f9cc1ae9dd5bb1e7cf34b6a4eaca6613/budget-fy21.pdf

@swallan please update to ready for PR

**Comment by rpalakkal** [comment]
on it
