### ISSUE TITLE
NEW CITY; Burlington, Vermont

### ISSUE THREAD

**Issue by eliebelie** [defund12/defund12.org#779]
TO: mayor@burlingtonvt.gov, jredell@burlingtonvt.gov, adam.greshin@vermont.gov, lindsay.kurrle@vermont.gov, mike.touchette@vermont.gov, marlene.betit@vermont.gov, jenny.prosser@vermont.gov, chris.winters@vermont.gov, phil@philscott.org, EXE.MuniHelp@vermont.gov,  

Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message:
Hello Vermont Officials,
My name is [NAME] and I am a resident of [TOWN]. I am asking that you redirect money away from the Vermont State Police and into the following social services: [LIST - Our Opioid Epidemic, Community Development, COVID Relief/Healthcare, Education, Parks & Recreation, targeted support for marginalized communities].

I have noticed that in the 2021 budget proposal, from the general fund, the police department is receiving a 6.8% increase from 2020. Meanwhile, many other services are receiving cuts to their budgets. In light of recent events, I believe it is critical that policing be deprioritized relative to spending on social programs that have been proven to promote safe and equitable communities.

With the economic impact that COVID-19 has had on Vermont’s economy, difficult and thoughtful decisions will be required when it comes to the budget for Vermont in 2021. **Vermonters are experiencing homelessness, illness, unemployment, loss of income, and police brutality in record numbers.** The people that have burdened the brunt of this are People of Color, Indigenous peoples, the poor, and the working class.

I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the governor's proposed budget and reallocate these funds to resources the citizens can benefit from.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Hi there @eliebelie , thanks for your submission. I'm a content reviewer and have a few questions:

1.) Could you provide a source for the 6.8% increase?
2.) We are primarily focused on contacting local representatives (city councils, county commissions, etc.) in regard to local PDs. Could you clarify your message/recipients to reflect a local focus, if that is your intent?

**Comment by eliebelie** [comment]
1.) Source -
https://ljfo.vermont.gov/assets/Uploads/52a147084f/DPS-FY21-Budget-Proposal-1-30-20.pdf
2.) Since Vermont is such a small state I focused on all officials in the
Governor's Office but specifically the Mayor of Burlington which is the
largest city.
I have added some emails as well:

To: mayor@burlingtonvt.gov, jredell@burlingtonvt.gov,
adam.greshin@vermont.gov, lindsay.kurrle@vermont.gov,
mike.touchette@vermont.gov, marlene.betit@vermont.gov,
jenny.prosser@vermont.gov, chris.winters@vermont.gov, phil@philscott.org,
EXE.MuniHelp@vermont.gov, tasge@leg.state.vt.us,  david@zuckermanforvt.com,
phil.scott@vermont.gov, michael.schirling@vermont.gov,


Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message:


Hello Burlington Officials,

My name is [NAME] and I am a resident of [TOWN]. I am asking that you
redirect money away from the Vermont State Police and into the following
social services: Our Opioid Epidemic, Community Development, COVID
Relief/Healthcare, Education, Parks & Recreation and targeted support for
marginalized communities.


I have noticed that in the 2021 budget proposal the department of public
safety is receiving a 6.8% increase from 2020. Meanwhile, many other
services are receiving cuts to their budgets. In light of recent events, I
believe it is critical that policing be deprioritized relative to spending
on social programs that have been proven to promote safe and equitable
communities.


With the economic impact that COVID-19 has had on Vermont’s economy,
difficult and thoughtful decisions will be required when it comes to the
budget for Vermont in 2021. Vermonters are experiencing homelessness,
illness, unemployment, loss of income, and police brutality. The people
that have borne the brunt of this are People of Color, Indigenous peoples,
the poor, and the working class.


I request that an emergency meeting be called before the fiscal year goes
into effect in order to deny the governor's proposed budget and reallocate
these funds to resources the citizens can benefit from.


Change is coming, be bold, be brave, and be the elected officials that make
the difference.


Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thanks for providing your sources! Reviewing now

**Comment by mahrer** [comment]
Some minor edits below:

---

To: mayor@burlingtonvt.gov, jredell@burlingtonvt.gov,
adam.greshin@vermont.gov, lindsay.kurrle@vermont.gov,
mike.touchette@vermont.gov, marlene.betit@vermont.gov,
jenny.prosser@vermont.gov, chris.winters@vermont.gov, phil@philscott.org,
EXE.MuniHelp@vermont.gov, tasge@leg.state.vt.us,  david@zuckermanforvt.com,
phil.scott@vermont.gov, michael.schirling@vermont.gov,

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message:

Hello Burlington Officials,

My name is [NAME] and I am a resident of [TOWN]. I am asking that you redirect money away from the Vermont State Police and into the following social services: Our Opioid Epidemic, Community Development, COVID Relief/Healthcare, Education, Parks & Recreation and targeted support for marginalized communities.

I have noticed that in the 2021 budget proposal the department of public safety is receiving a 6.8% increase from 2020. Meanwhile, many other services are receiving cuts to their budgets. In light of recent events, I believe it is critical that policing be deprioritized relative to spending on social programs that have been proven to promote safe and equitable communities.

With the economic impact that COVID-19 has had on Vermont’s economy, difficult and thoughtful decisions will be required when it comes to the budget for Vermont in 2021. Vermonters are experiencing homelessness, illness, unemployment, loss of income, and police brutality. The people that have borne the brunt of this are People of Color, Indigenous peoples, the poor, and the working class.

I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the governor's proposed budget and reallocate these funds to resources the citizens can benefit from.

Change is coming, be bold, be brave, and be the elected officials that make the difference.

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Now that I've edited this I see that we already have two emails for Burlington on the site. @eliebelie if you have edits you'd like to make to those emails instead, feel free to open another issue with the label content-change-request.
