### ISSUE TITLE
Request to add Cincinnati, OH

### ISSUE THREAD

**Issue by kavkan2** [defund12/defund12.org#783]
-Subject line for the email: [INSERT UNIQUE SUBJECT LINE]
-Email addresses: mayor.cranley@cincinnati-oh.gov, CityCouncil@cincinnati-oh.gov, christopher.smitherman@cincinnati-oh.gov, chris.seelbach@cincinnati-oh.gov, greg.landsman@cincinnati-oh.gov, jan-michele.kearney@cincinnati-oh.gov, david.mann@cincinnati-oh.gov, jeff.pastor@cincinnati-oh.gov, pg.sittenfeld@cincinnati-oh.gov, betsy.sundermann@cincinnati-oh.gov, wendell.young@cincinnati-oh.gov
-Detailed message concerning the budgeting decisions at stake in your community:

Dear Mayor Cranley and Cincinnati City Council,

My name is [YOUR NAME], and I am a resident of [NEIGHBORHOOD/BOROUGH/City]. I am writing to demand that the Cincinnati City Council rewrites the budget to reallocate money away from the police department and reinvest in services to the community instead.

In light of the racist murders of George Floyd, Breonna Taylor, Ahmaud Arbery, Tony McDade, and countless other Black people, I demand to see the reduction of funding for the Cincinnati Police Department (CPD). The fiscal budget allocates around $152 million to the CPD.  This money could have a greater use being invested in education, healthcare, fighting food insecurity and homelessness, mental health resources, and countless other community programs at the benefit of Cincinnati's Black and Brown communities. The City Council must take a stand for racial justice by significantly defunding CPD immediately.

Racist police violence happens in Cincinnati just as much as it happens in other cities. However, with actions dedicated to supporting the community, we can create change. As a Cincinnati resident, I therefore demand that you take immediate action to ensure the following:

   1. Reduce CPD’s allocation from the General Fund by 50% (approximately $75 million)
  2. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
  3. Invest in housing, jobs, access to food, healthcare, child care, restorative justice, and mental health workers to keep the community safe

Cincinnati cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund CPD and reinvest in the community.

Thank you,
[YOUR NAME]
[YOUR EMAIL]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

**Comment by pinkladdylemon** [comment]
Dear Mayor Cranley and Cincinnati City Council,

My name is [YOUR NAME], and I am a resident of [NEIGHBORHOOD/BOROUGH/City]. I am writing to demand that the Cincinnati City Council rewrites the budget to reallocate money away from the police department and reinvest in services to the community instead. Reform is not enough. It is time to fundamentally rethink what public safety means without occupying our cities with militarized forces, and responding to social problems with guns and jails.

In light of the racist murders of George Floyd, Breonna Taylor, Ahmaud Arbery, Tony McDade, countless other Black people, and Cincinnati's own long history of police violence, I demand to see the reduction of funding for the Cincinnati Police Department (CPD).  The fiscal budget allocates around $152 million to the CPD. This money could have a greater use being invested in education, healthcare, fighting food insecurity and homelessness, mental health resources, and countless other community programs at the benefit of Cincinnati's Black and Brown communities. The City Council must take a stand for racial justice by significantly defunding CPD immediately.

Numerous studies attest to the positive impacts of limiting police power and budgets. In 2018, researchers at New York University found that "in a city of 100,000 people, each new non-profit community organization [led] to a 1.2 percent drop in the homicide rate, a 1 percent decrease in violent crime rate and a 0.7 percent reduction in property crime rate." (https://www.policingproject.org/) Expanding social and economic programs for under-resourced communities leads to an overall decrease in crime. These programs deserve greater investment now and in the future. A separate study in the scientific journal Nature showed that a reduction in "pro-active policing" not only led to a drop in serious crimes, but also to a decrease in serious crime complaints (https://rdcu.be/b4EAp).

The CPD has repeatedly demonstrated its commitment to obscurantism and a resistance to cooperating with civilian organizations as part of the post-2001 Collaborative Agreement (https://www.citybeat.com/news/news-feature/news/20994414/collaborative-disagreement). However, recent events across the country show that such reform efforts, even if effectively implemented with full transparency, would be insufficient. Minneapolis, for example, was at the forefront of police reform efforts and this did nothing to save the life of George Floyd. New York City had a long-standing statute against police usage of choke-holds and this did not save Eric Garner.

Together we can reimagine what public safety means in a way that does not necessitate the presence of militarized officers whose solutions to social problems are too often limited to incarceration or violence with tragic consequences. Social problems like crime cannot be incarcerated, shot, tased or beaten into non-existence. In order to live in a more just and safe city we have to address the social inequalities that drive many to commit crimes in the first place - and our city's budget should reflect that as a priority by channeling CPD funds into social services, education and public health programs.

As a Cincinnati resident, I therefore demand that you take immediate action to ensure the following demands issued by Mass Action for Black Liberation:

• Defunding the Cincinnati Police Department.

• Immediate demilitarization of the Cincinnati Police Department.

• Replace police response to wellness checks and domestic violence calls with a wraparound social work response.

• Full funding of five (non-active or retired police) investigators at the Citizen’s Complaint Authority

• Application of laws and policies fairly to all people. Eliminate racial disparity in the criminal-legal system including in arrests, convictions, and sentencing.

• Reallocation of police divestment monies into social programs including the affordable housing trust fund; with a commitment to housing all Cincinnatians.

• Reparations to families of victims of police violence.

• Initiate or reopen criminal cases of police brutality/police killings, including but not limited to: Melvin Murray, Dontez O’Neal, Paul Gaston, Jawari Porter, Quandavier Hicks.

• Investment in cooperatively owned, Black led economic initiatives.

• City of Cincinnati protect and expand current investment in community-led health, education, and safety strategies.

• Cincinnati Public School District to immediately remove all Cincinnati police officers from our schools.

• CPS immediately cease all contracts with the Cincinnati Police Department.


Thank you,
[YOUR NAME]
[YOUR EMAIL]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

**Comment by pinkladdylemon** [comment]
wrote a slightly beefed up version if y'all are interested.

**Comment by averymcguirt** [comment]
Recommending a PR for the full version put together by @pinkladdylemon 
We have had some issues with longer emails, so email-dev folks come back if this template turns out to be problematic?

**Comment by ctneal91** [comment]
on it now
