### ISSUE TITLE
Reduce JPSO Budget and Review the Police Union Contract

### ISSUE THREAD

**Issue by hp1872** [defund12/defund12.org#789]
Subject: Reduce JPSO Budget and Review the Police Union Contract
Email: jpbudget@jeffparish.net 
sheriff@jpso.com
PIO2@jpso.com
RickyTemplet@jeffparish.net
BLawson@jeffparish.net 
ScottWalker@jeffparish.net
BPGrenrood@jeffparish.net
JenniferVanVrancken@JeffParish.net
byronlee@jeffparish.net
marionedwards@jeffparish.net
DeanoBonano@jeffparish.net
dimpastato@jeffparish.net

Hello,

My name is [NAME]. I am a resident of [CITY], Louisiana. I am contacting you to demand a significant reduction to the $118 million that is currently allocated to public safety in the fiscal budget of 2020 and for a formal review of the Jefferson Parish Sheriff’s Office from an independent party that has no affiliation with JPSO. Public safety makes  up roughly 22% of the budget, while other important public services do not receive even half as much funding. By reducing police funding, we can reallocate those funds into housing, education, sanitation and other community efforts and local organizations, while preventing future police brutality and violence. 

In 2018, Keveen Robinson, 22 was killed by Jefferson Parish police officers. His death was released as a homicide, but the four officers were only relinquished to office duty. They should be prosecuted for murder. (WDSU.com)

In 2019, Modesto Reyes, 35, was a worker who served the Hard Rock hotel collapse. In 2020, Modesto Reyes was killed by Jefferson Parish police officers. They thought his phone was a gun. He recorded this on his phone, but the JPSO won’t release the footage. 

The JPSO contact has problematic language in their contract which disqualifies complaints, restricts/delays interrogation, gives officers unfair access to information, limits oversight/discipline, and erases misconduct records (checkthepolice.org). JPSO’s past behavior indicates that they have a pattern of misconduct that needs to be confronted. Which is why Jefferson Parish expects JPSO’s contract to be reviewed by an external party that has no affiliation with JPSO. 

According to the Washington Post since 2015, 1,276 black people have been shot and killed by the police; which doesn’t include those who have died in police custody or were killed using other methods. Police forces across the United States have proved that reforming the police department will not address properly or end police brutality. Jefferson Parish citizens need and deserve policing alternatives like community-led public safety and more investments into the following community services: housing, sanitation, mental health and trauma services, education and after-school care, sustainability efforts, healthcare and employment opportunities.  

Sincerely,

[NAME]

**Comment by swallan** [comment]
@hp1872 What city / location in LA is this for?

**Comment by hp1872** [comment]
> @hp1872 What city / location in LA is this for?
Jefferson Parish, LA (which includes the areas outside of New Orleans) 
@swallan

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
Some minor edits:

Subject: Reduce JPSO Budget and Review the Police Union Contract
Email: jpbudget@jeffparish.net
sheriff@jpso.com
PIO2@jpso.com
RickyTemplet@jeffparish.net
BLawson@jeffparish.net
ScottWalker@jeffparish.net
BPGrenrood@jeffparish.net
JenniferVanVrancken@JeffParish.net
byronlee@jeffparish.net
marionedwards@jeffparish.net
DeanoBonano@jeffparish.net
dimpastato@jeffparish.net

Hello,

My name is [NAME]. I am a resident of [CITY]. I am contacting you to demand a significant reduction to the $24 million that is currently allocated to public safety in the fiscal budget of 2020 and for a formal review of the Jefferson Parish Sheriff’s Office from an independent party that has no affiliation with JPSO. 

Public safety makes up roughly 22% of the Jefferson Parish's 2020 budget, while other important public services do not receive even half as much funding. By reducing police funding, we can reallocate those funds into housing, education, sanitation and other community efforts and local organizations, while preventing future police brutality and violence.

In 2018, Keveen Robinson, 22 was killed by Jefferson Parish police officers. His death was released as a homicide, but the four officers were only relinquished to office duty. They should be prosecuted for murder (WDSU.com)

In 2019, Modesto Reyes, 35, was a worker who served the Hard Rock hotel collapse. In 2020, Modesto Reyes was killed by Jefferson Parish police officers. They thought his phone was a gun. He recorded this on his phone, but the JPSO won’t release the footage.

The JPSO contact has problematic language in their contract which disqualifies complaints, restricts/delays interrogation, gives officers unfair access to information, limits oversight/discipline, and erases misconduct records (checkthepolice.org). JPSO’s past behavior indicates that they have a pattern of misconduct that needs to be confronted. This is why I demand JPSO’s contract to be reviewed by an external party that has no affiliation with JPSO.

According to the Washington Post since 2015, 1,276 Black people have been shot and killed by the police, not including those who have died in police custody or were killed using other methods. Police forces across the United States have proved that reforming the police department will not properly address or end police brutality. Jefferson Parish citizens need and deserve policing alternatives like community-led public safety and more investments into the following community services: housing, sanitation, mental health and trauma services, education and after-school care, sustainability efforts, healthcare and employment opportunities.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@hp1872 I changed the $118 million in the first paragraph to $24 million per this document:
https://jefferson-parish-government.azureedge.net/documents/departments/budget/2020AnnualBudget.PDF 

If you have a different conflicting source let me know!

**Comment by hp1872** [comment]
@mahrer hi! It has top numbers in the budget it’s the public safety function and then public safety ... which adds to $118 mil. What do u think?

**Comment by hp1872** [comment]
@mahrer but maybe I read it wrong... but the public safety function + public safety = full pub. Safety

**Comment by mahrer** [comment]
Thanks for clearing that up. I'll change it back and it should be good to go :)

**Comment by ctneal91** [comment]
on it now
