### ISSUE TITLE
Eugene - Letter to Mayor, City Commissioners, Budget Committee, and City Council

### ISSUE THREAD

**Issue by LizSten95** [defund12/defund12.org#799]
To: lvinis@eugene-or.gov, ceepdcommission@ci.eugene.or.us, eugene.budget.committee@ci.eugene.or.us, MayorCouncilandCityManager@eugene-or.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Lucy Vinis, Commissioners, Budget Committee, and City Council, 

My name is [YOUR NAME] and I am a resident of [CITY/DISTRICT]. It is my understanding that you will be reviewing the proposed 2021 City Budget on June 22th, 2020. I must urge you to oppose the increase in funding from $61.35 mil in FY-2020 to $67.97 mil in FY-2021 for the Eugene Police Department (EPD). 

Policing plays a strong role in enforcing racism and social control of communities of color through disempowerment, displacement, and repression. Black people and communities of color have been disproportionately targeted and brutalized by the police throughout American history. 

Despite a decrease in crime over the past few decades, police funding across the United States has continued to increase. As a Eugene citizen, I do not support the militarization of the police force which is accentuated by the 1033 program and I do not support the use of EPD officers in schools. 

Promises of police reform and additional training programs do not do enough to address the underlying issue of systemic racism that plagues policing in America. The only solution is immediate and aggressive divestment from police funding and real consideration given to alternative public safety measures. To quote Alex S. Vitale, professor of sociology and coordinator of the Policing and Social Justice Project at Brooklyn College and the author of The End of Policing, "The alternative is not more money for police training programs, hardware or oversight. It is to dramatically shrink their function. We must demand that local politicians develop non-police solutions to the problems poor people face. We must invest in housing, employment and healthcare in ways that directly target the problems of public safety. Instead of criminalizing homelessness, we need publicly financed supportive housing; instead of gang units, we need community-based anti-violence programs, trauma services and jobs for young people; instead of school police we need more counselors, after-school programs, and restorative justice programs." 

CAHOOTS (Crisis Assistance Helping Out On The Streets) of Eugene has been praised as a cost-effective approach that utilizes de-escalation tactics and skills of medical and mental health professionals. As stated on the White Bird Clinic Website, "CAHOOTS gets 2 percent of the police budget, but with that 2 percent they handle 17 percent of public safety calls." Per the FY20 Budget Report, CAHOOTS funding was only $281,000. When addressing continued action, White Bird Clinic states, "We’re growing our programs, demonstrating our commitment to serving low income, under-resourced community members. In response to burgeoning community need, we are expanding the hours of CAHOOTS mobile crisis services, which responded to over 23,000 calls in 2018, saving an estimated $6M in emergency medical services costs alone." 

The City of Eugene should continue to work towards the expansion of the CAHOOTS program by diverting additional funds from EPD. It is essential that the City of Eugene connects with local businesses and programs that offer a diverse range of social services to help tackle systemic issues from the ground up. Some of these local businesses include Looking Glass, Boys and Girls Club, Relief Nursery, S.A.S.S., 15th Night, and Womanspace. 

The City of Eugene has already shown willingness to invest in change by funding programs like CAHOOTS. As a community, we should continue to build on these ideals and continue to invest in evidence-based alternatives to police that directly advocate for our citizens and work to replace policing with other systems of public safety. This starts with divesting funding from the EPD in FY-2021. 

Thank you for your time, 

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Numbers appear to be correct, https://budget.eugene-or.gov/#!/year/2021/operating/0/department/Police/0/service. 

We may decide to remove the specific businesses, we don't want to advocate for any one in particualr. 

The mention of CAHOOTS is nice, and appears to follow the older (I guess current) guidelines about specific programs. 

Pending secondary review

**Comment by LizSten95** [comment]
@swallan Okay, I agree with your comment about listing specific businesses and removed that sentence from the email! 

To: lvinis@eugene-or.gov, ceepdcommission@ci.eugene.or.us, eugene.budget.committee@ci.eugene.or.us, MayorCouncilandCityManager@eugene-or.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Lucy Vinis, Commissioners, Budget Committee, and City Council,

My name is [YOUR NAME] and I am a resident of [CITY/DISTRICT]. It is my understanding that you will be reviewing the proposed 2021 City Budget on June 22th, 2020. I must urge you to oppose the increase in funding from $61.35 mil in FY-2020 to $67.97 mil in FY-2021 for the Eugene Police Department (EPD).

Policing plays a strong role in enforcing racism and social control of communities of color through disempowerment, displacement, and repression. Black people and communities of color have been disproportionately targeted and brutalized by the police throughout American history.

Despite a decrease in crime over the past few decades, police funding across the United States has continued to increase. As a Eugene citizen, I do not support the militarization of the police force which is accentuated by the 1033 program and I do not support the use of EPD officers in schools.

Promises of police reform and additional training programs do not do enough to address the underlying issue of systemic racism that plagues policing in America. The only solution is immediate and aggressive divestment from police funding and real consideration given to alternative public safety measures. To quote Alex S. Vitale, professor of sociology and coordinator of the Policing and Social Justice Project at Brooklyn College and the author of The End of Policing, "The alternative is not more money for police training programs, hardware or oversight. It is to dramatically shrink their function. We must demand that local politicians develop non-police solutions to the problems poor people face. We must invest in housing, employment and healthcare in ways that directly target the problems of public safety. Instead of criminalizing homelessness, we need publicly financed supportive housing; instead of gang units, we need community-based anti-violence programs, trauma services and jobs for young people; instead of school police we need more counselors, after-school programs, and restorative justice programs."

CAHOOTS (Crisis Assistance Helping Out On The Streets) of Eugene has been praised as a cost-effective approach that utilizes de-escalation tactics and skills of medical and mental health professionals. As stated on the White Bird Clinic Website, "CAHOOTS gets 2 percent of the police budget, but with that 2 percent they handle 17 percent of public safety calls." Per the FY20 Budget Report, CAHOOTS funding was only $281,000. When addressing continued action, White Bird Clinic states, "We’re growing our programs, demonstrating our commitment to serving low income, under-resourced community members. In response to burgeoning community need, we are expanding the hours of CAHOOTS mobile crisis services, which responded to over 23,000 calls in 2018, saving an estimated $6M in emergency medical services costs alone."

The City of Eugene should continue to work towards the expansion of the CAHOOTS program by diverting additional funds from EPD. It is essential that the City of Eugene connect with local businesses and programs that offer a diverse range of social services to help tackle systemic issues from the ground up. 

The City of Eugene has already shown willingness to invest in change by funding programs like CAHOOTS. As a community, we should continue to build on these ideals and continue to invest in evidence-based alternatives to police that directly advocate for our citizens and work to replace policing with other systems of public safety. This starts with divesting funding from the EPD in FY-2021.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
To: lvinis@eugene-or.gov, ceepdcommission@ci.eugene.or.us, eugene.budget.committee@ci.eugene.or.us, MayorCouncilandCityManager@eugene-or.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Lucy Vinis, Commissioners, Budget Committee, and City Council,

My name is [YOUR NAME] and I am a resident of [CITY/DISTRICT]. It is my understanding that you will be reviewing the proposed 2021 City Budget on June 22th, 2020. I urge you to oppose the increase in funding from $61.35 mil in FY-2020 to $67.97 mil in FY-2021 for the Eugene Police Department (EPD) and instead, decrease it.

Policing plays a strong role in enforcing racism and social control of communities of color through disempowerment, displacement, and repression. Black people and communities of color have been disproportionately targeted and brutalized by the police throughout American history.

Despite a decrease in crime over the past few decades, police funding across the United States has continued to increase. As a Eugene citizen, I do not support the militarization of the police force which is accentuated by the 1033 program and I do not support the use of EPD officers in schools.

Promises of police reform and additional training programs do not do enough to address the underlying issue of systemic racism that plagues policing in America. The only solution is immediate and aggressive divestment from police funding and real consideration given to alternative public safety measures. To quote Alex S. Vitale, professor of sociology and coordinator of the Policing and Social Justice Project at Brooklyn College and the author of The End of Policing, "The alternative is not more money for police training programs, hardware or oversight. It is to dramatically shrink their function. We must demand that local politicians develop non-police solutions to the problems poor people face. We must invest in housing, employment and healthcare in ways that directly target the problems of public safety. Instead of criminalizing homelessness, we need publicly financed supportive housing; instead of gang units, we need community-based anti-violence programs, trauma services and jobs for young people; instead of school police we need more counselors, after-school programs, and restorative justice programs."

There are already some tangible programs in action, for example, CAHOOTS (Crisis Assistance Helping Out On The Streets) of Eugene has been praised as a cost-effective approach that utilizes de-escalation tactics and skills of medical and mental health professionals. As stated on the White Bird Clinic Website, "CAHOOTS gets 2 percent of the police budget, but with that 2 percent they handle 17 percent of public safety calls." Per the FY20 Budget Report, CAHOOTS funding was only $281,000. When addressing continued action, White Bird Clinic states, "We’re growing our programs, demonstrating our commitment to serving low income, under-resourced community members. In response to burgeoning community need, we are expanding the hours of CAHOOTS mobile crisis services, which responded to over 23,000 calls in 2018, saving an estimated $6M in emergency medical services costs alone."

The City of Eugene should continue to work towards the expansion programs that benefit the community, like CAHOOTS, by diverting additional funds from EPD. It is essential that the City of Eugene connect with local businesses and programs that offer a diverse range of social services to help tackle systemic issues from the ground up.

The City of Eugene has already shown willingness to invest in change by funding programs like CAHOOTS. As a community, we should continue to build on these ideals and continue to invest in evidence-based alternatives to police that directly advocate for our citizens and work to replace policing with other systems of public safety. This starts with divesting funding from the EPD in FY-2021.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]


Light edits to generalize that funding may be towards programs like cahoots, I think it is a good candidate for a PR. If any other content reviewers prefer it even more general, leave a comment.

**Comment by dionlarson** [comment]
On it!
