### ISSUE TITLE
KNOXVILLE, TN

### ISSUE THREAD

**Issue by lecioowwl** [defund12/defund12.org#811]
to: gmckenzie@knoxvilletn.gov, tsmith@knoxvilletn.gov, aroberto@knoxvilletn.gov, ssingh@knoxvilletn.gov, lrider@knoxvilletn.gov, cathomas@knoxvilletn.gov, lfugate@knoxvilletn.gov, jtesterman@knoxvilletn.gov, amparker@knoxvilletn.gov 

SUBJECT: [*** INSERT UNIQUE SUBJECT LINE ***]
Dear Knoxville City Council,
My name is [YOUR NAME] and I am a resident of Knoxville, TN. I am writing to demand that the Knoxville City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.
In 2019, the City of Knoxville allocated 55 million dollars to our police system, an inordinate 35% of our departmental budget. This is compared to just $2.8 million allocated towards community development (1.8% of the budget).
I demand that the City Council begin meaningfully defunding the Knoxville Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Knoxville residents.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
@averymcguirt closed by PR #1147

**Comment by ctneal91** [comment]
That is unless we want to integrate these changes into the existing letter that reads
"  Hello Knoxville Elected Officials,

  My name is [YOUR NAME], and my address is [YOUR ADDRESS]. I am writing to say that I am strongly against the provisions found in the FY2020-2021 budget.

  The mayor’s budget would spend $60.7 million ($58 million of which comes directly from the Knoxville City General Fund of $164.5 million, or 35%) on a “public safety” system that does not keep us safe. The vast majority of that money would be spent on police, jails, and courts. That means the mayor wants to spend more on cops and cages than on almost all public goods combined. Fully 1/3 of the full-time government positions in this city are police officers. This isn’t how we create public safety. True public safety requires fully-funded and community-controlled resources, not more police and jails.

  In the midst of a budget crisis, the mayor is proposing we increase spending on police and jails, and decrease spending on social services, transit, and other critical public goods. This is unacceptable and will not keep us safe. The mayor has stressed the necessity of fiscal austerity during these trying times, but these cuts come at the expense of necessary community services instead of a massively overfunded police force.

  Over-policed communities are not safe communities. Thriving communities are safe communities, and communities thrive when they are well-resourced. We deserve a budget that divests from policing and jails and uses that money to invest in our community.

  Sincerely,
  [YOUR NAME]
  [YOUR ADDRESS]
  [YOUR EMAIL]
  [YOUR PHONE NUMBER]"
