### ISSUE TITLE
Add Union City, CA

### ISSUE THREAD

**Issue by whitelotusorder** [defund12/defund12.org#818]
To: CarolID@UnionCity.org, EmilyD@UnionCity.org, jaimep@UnionCity.org, PatG@UnionCity.org, GaryS@UnionCity.org, joanm@UnionCity.org,jaredr@UnionCity.org

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message: To Mayor Dutra, the Union City Council, Union City Manager, and Union City Police Chief:

My name is [YOUR NAME], and I am a resident of Union City. I am writing to demand that the City Council adopts a budget that prioritizes community wellbeing and redirects funding away from the police.

This past week, we have seen widespread protests across the country and even right here in the Tri-City area. These protests are not simply a response to the recent murder of George Floyd at the hands of the Minneapolis police; they are an amplification of a small piece in a much larger movement, one which has culminated for years and which calls for the end of police brutality and the end of the racist and oppressive system that this country was founded on. I am writing to you today because it has come to my attention that the Union City proposed budget for the 2020-2021 fiscal year helps to uphold this same system.

Union City council states that it prides itself on the City’s diversity and core values of “safety, tolerance, and caring”. However, the proposed $26,015,635 to be allocated to UCPD from the City’s 2020-2021 General Funds states otherwise. This proposal is more than 2x the proposed 2020-2021 allocation for Union City Public Works, Community & Recreation Services, and Economic & Community Development combined. If we are a city that truly stands by our core values of protecting and caring for our diverse community, you as a council would redirect funding away from the police and into social programs and services that support education, health care, community-led public safety, and other critical community needs.

During the Union City Town Hall on June 4, 2020, Reverend Jerome Brown brought up valuable points about hearing one another in order to spark change. I ask that as our representatives, you hear us and spark this very important and needed change in our City. I am urging you to revise the budget for the 2020-2021 fiscal year.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
My name is [YOUR NAME], and I am a resident of Union City. I am writing to demand that the City Council adopts a budget that prioritizes community wellbeing and redirects funding away from the police.

This past week, we have seen widespread protests across the country and even right here in the Tri-City area. These protests are not simply a response to the recent murder of George Floyd at the hands of the Minneapolis police; they are an amplification of a small piece in a much larger movement, one which has culminated for years and which calls for the end of police brutality and the end of the racist and oppressive system that this country was founded on. I am writing to you today because it has come to my attention that the Union City proposed budget for the 2020-2021 fiscal year helps to uphold this same system.

Union City council states that it prides itself on the City’s diversity and core values of “safety, tolerance, and caring.” However, the proposed $26,015,635 to be allocated to UCPD from the City’s 2020-2021 General Funds states otherwise. This proposal is more than 2x the proposed 2020-2021 allocation for Union City Public Works, Community & Recreation Services, and Economic & Community Development combined. If we are a city that truly stands by our core values of protecting and caring for our diverse community, you as a council would redirect funding away from the police and into social programs and services that support education, health care, community-led public safety, and other critical community needs.

During the Union City Town Hall on June 4, 2020, Reverend Jerome Brown brought up valuable points about hearing one another in order to spark change. I ask that as our representatives, you hear us and spark this very important and needed change in our City. I am urging you to revise the budget for the 2020-2021 fiscal year to defund the police.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

light edits for typos, double checked for correct content

**Comment by dionlarson** [comment]
PR in progress. Note: `CarolID@UnionCity.org` -> `CarolD@UnionCity.org`
