### ISSUE TITLE
Please add San Leandro CA PD 

### ISSUE THREAD

**Issue by dfotoo** [defund12/defund12.org#819]
**Email addresses**: pcutter@sanleandro.org , pballew@sanleandro.org , dcox@sanleandro.org , ehernandez@sanleandro.org , vaguilar@sanleandro.org , blee@sanleandro.org , clopez@sanleandro.org

**Subject line**: SLPD Budget Reallocation 2020

**Message:**

Dear Mayor Cutter and City Council Members, 

My name is [YOUR NAME] and I am a San Leandro (resident or business owner) writing to urge you to defund SLPD.

SLPD takes an enormous share of the city’s general fund, and that percentage has risen exponentially for the last two decades, taking away desperately needed resources from essential city programs and services. The City of San Leandro transferred $20 million to the SLPD headquarter fund in 2018-2019; money that could be used much more beneficially if inserted directly into the community. The investment in policing has not made us safer – SLPD remains an embarrassment to the city and a lethal threat to San Leandro’s Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels. With current finances so tight, it is clear that we must defund the police.

As San Leandro residents, we therefore demand that you take immediate action to ensure the following:

- Reduce SLPD’s allocation from the General Fund by 50% 
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
- Reallocate money from SLPD into housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
- San Leandro can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund SLPD.

Thank you,

[YOUR NAME]

**Comment by jamiecatton** [comment]
If there is still availability to offer suggestions, these are mine: 
**Message:**

Dear Mayor Pauline Russo Cutter and City Council Members,

My name is [YOUR NAME] and I am a San Leandro [RESIDENT/BUSINESS OWNER] writing to urge you to defund San Leandro PD.

SLPD takes an enormous share of the city’s general fund (35%), and that percentage has risen exponentially for the last two decades, taking away desperately needed resources from essential city programs and services. In the 2018-2019 Biennial Budget, the City of San Leandro allocated roughly $39 million dollars to our police system, an inordinate 34.7% of our total budget. This is compared to just $6.5 million allocated towards community development (5.7% of the budget) and recreation & human services (4.6% of the budget). The investment in policing has not made us safer – SLPD remains an embarrassment to the city and a lethal threat to San Leandro’s Black and Brown communities, while increased police spending has not returned a decrease in crime rate. With fiscal responsibility being a primary goal of this council, it is clear that you must defund the police and reallocate resources into community programs. 

The projected budget for 2020-2021 for San Leandro PD still sits at 35% of the general budget, at $42,000,485, while community development is projected at 6% of the general fund, recreation & human services at 4% of the budget, and public works also at 6%. 

Within the community development budget, $307,662 was spent on the City Innovation Division for the 2018-2019 budget (8% of budget) and has been slashed to a projected $3,434 for 2019-2020 & 2020-2021 (0.0005% of community development budget for 2020-2021). Additionally within the community development budget for 2019-2020, $326,264 was spent for housing services (4%), and $429,568 for code compliance (6%). The projected budgets for 2020-2021 come to $341,211 for housing services (5% of budget) and $458,203 for code compliance (7% of the budget). 

As San Leandro residents, we therefore demand that you take immediate action to ensure the following:

1. Reduce SLPD’s allocation from the General Fund by 50%
2. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
3. Reallocate money from SLPD into housing, jobs, youth programs, restorative justice, and mental 4. health workers to keep the community safe.

San Leandro cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund SLPD.
Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE]
