### ISSUE TITLE
Hendersonville, NC

### ISSUE THREAD

**Issue by eloisabaez** [defund12/defund12.org#821]
To: bvolk@hvlnc.gov, jerrysmith@hvlnc.gov, jmiller@hvlnc.gov, jhensley@hvlnc.gov, lsimpson@hvlnc.gov

SUBJECT: [**INSERT UNIQUE SUBJECT LINE]
Hello Mayor Volk and Members of the City Council,

My name is [INSERT NAME], and I am a resident of Hendersonville NC at [ZIP CODE]. I am emailing to demand the retracting of the Hendersonville city budget to prioritize social services for the community and significantly decrease spending on the police. 

The $5.8 million budget allocation for police in FY 2020-2021 in Hendersonville represents a large amount of resources that could be better spent improving community wellbeing through community led programs. For instance health and welfare only receives $282,480 in funding. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at increasing community safety than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas.

Reallocating funds away from the police in Hendersonville will provide much needed assistance and security to the most vulnerable people in our community.

Sincerely,
[NAME]

**Comment by swallan** [comment]
Hi @eloisabaez,

Thanks for your contribution!

Please follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md), specifically:

- Avoid using police framing of community problems, i.e. “crime.” Instead of summarizing social programs as being more effective than policing at “reducing crime,” say that they are more effective at “promoting community safety.”

**Comment by eloisabaez** [comment]
Hello, I have updated following your suggestions.

**Comment by serifluous** [comment]
Budget numbers confirmed here: https://www.hendersonvillenc.gov/sites/default/files/uploads/departments/administration/budget/fy20-21_budget-recommended.pdf

**Comment by ctneal91** [comment]
on it now
