### ISSUE TITLE
Torrance, CA - Letter to Mayor and City Council 

### ISSUE THREAD

**Issue by accountability1** [defund12/defund12.org#822]
To: PFurey@TorranceCA.Gov,HAshcraft@TorranceCA.Gov,GChen@TorranceCA.Gov,TGoodrich@TorranceCA.Gov,MGriffiths@TorranceCA.Gov,SKalani@TorranceCA.gov,AMattucci@TorranceCA.gov 🔗

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Furey and Torrance City Council Members,

My name is [NAME HERE] and I am a Torrance resident. Torrance PD takes an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Over 22% of our city’s budget is directed the police department, while only 4.4% is devoted to community services.

Torrance may be faced with up to a 22 million dollar budget deficit in the FY2020-2021 and is set to divest only 5.7% of Torrance PD's total departmental budget, while enacting steeper cuts on vital public services such as libraries, park maintenance, and public works. The investment in policing has not made us safer – Torrance PD continues to constitute a lethal threat to Torrance's Black and Brown communities. The officers responsible for fatal shooting of 23-year-old Christopher DeAndre Mitchell in December 2018 are still decorated members of the police force. With Torrance's current finances in dire jeopardy, it is clear that we must defund the police.

As a Torrance resident, I demand that you take immediate action to ensure the following:

1.Significantly reducing Torrance PD’s allocation from the general fund 2. Suspend the use of paid administrative leave for cops under investigation 3.Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence. 4.Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Torrance can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Torrance PD.

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by accountability1** [comment]
See budget sources here: 
[Torrance Budget Cuts.pdf](https://github.com/defund12/defund12.org/files/4747039/Torrance.Budget.Cuts.pdf)
[201921BudgetataGlance.pdf](https://github.com/defund12/defund12.org/files/4747040/201921BudgetataGlance.pdf)

**Comment by accountability1** [comment]
Edit on budget percentages: Over 22% of our city’s budget goes towards the police department, while only 4.4% goes towards community services.

**Comment by accountability1** [comment]
Source on budget percentages: https://www.torranceca.gov/home/showdocument?id=50806

**Comment by mahrer** [comment]
Some minor edits:

To: PFurey@TorranceCA.Gov,HAshcraft@TorranceCA.Gov,GChen@TorranceCA.Gov,TGoodrich@TorranceCA.Gov,MGriffiths@TorranceCA.Gov,SKalani@TorranceCA.gov,AMattucci@TorranceCA.gov 🔗

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Furey and Torrance City Council Members,

My name is [NAME HERE] and I am a Torrance resident. Torrance PD takes an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Over 22% of our city’s budget is directed the police department, while only 4.4% is devoted to community services.

Torrance may be faced with up to a 22 million dollar budget deficit in the FY2020-2021 and is set to divest only 5.7% of Torrance PD's total departmental budget, while enacting steeper cuts on vital public services such as libraries, park maintenance, and public works. The investment in policing has not made us safer – Torrance PD continues to constitute a lethal threat to Torrance's Black and Brown communities. Officers Anthony Chavez and Matthew Concannon, who fatally shot 23-year-old Christopher DeAndre Mitchell in December 2018, are still decorated members of the police force. With Torrance's current finances in dire jeopardy, it is clear that we must defund the police.

As a Torrance resident, I demand that you take immediate action to ensure the following:

1.Significantly reduce Torrance PD’s allocation from the general fund.
2. Suspend the use of paid administrative leave for cops under investigation.
3. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence. 
4.Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Torrance can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Torrance PD.

Thank you,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by accountability1** [comment]
Just a minor edit in demands to be consistent to Black Lives Matter - LA's demands in Torrance.

**Comment by accountability1** [comment]
To: PFurey@TorranceCA.Gov,HAshcraft@TorranceCA.Gov,GChen@TorranceCA.Gov,TGoodrich@TorranceCA.Gov,MGriffiths@TorranceCA.Gov,SKalani@TorranceCA.gov,AMattucci@TorranceCA.gov 🔗

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Furey and Torrance City Council Members,

My name is [NAME HERE] and I am a Torrance resident. Torrance PD takes an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Over 22% of our city’s budget is directed the police department, while only 4.4% is devoted to community services.

Torrance may be faced with up to a 22 million dollar budget deficit in the FY2020-2021 and is set to divest only 5.7% of Torrance PD's total departmental budget, while enacting steeper cuts on vital public services such as libraries, park maintenance, and public works. The investment in policing has not made us safer – Torrance PD continues to constitute a lethal threat to Torrance's Black and Brown communities. Officers Anthony Chavez and Matthew Concannon, who fatally shot 23-year-old Christopher DeAndre Mitchell in December 2018, are still decorated members of the police force. With Torrance's current finances in dire jeopardy, it is clear that we must defund the police.

As a Torrance resident, I demand that you take immediate action to ensure the following:

1. Significantly reduce Torrance PD’s allocation from the general fund.
2. Create an independent commission to review police misconduct and negligence by Torrance PD.
3. Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Torrance can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Torrance PD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Sure thing, looks good.
