### ISSUE TITLE
Add New Orleans, LA a letter to the mayor and city council

### ISSUE THREAD

**Issue by defund12neworleans** [defund12/defund12.org#823]
To: mayor@nola.gov, jarwilliams@nola.gov, helena.moreno@nola.gov, joseph.giarrusso@nola.gov, jay.h.banks@nola.gov, kristin.palmer@nola.gov, jcbrossett@nola.gov, cyndi.nguyen@nola.gov, 

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don’t forget to replace [x]’s with your information!)

Dear Mayor Cantrell and City Council Members, 

My name is [YOUR NAME] and I am a New Orleans resident writing to urge you to defund the New Orleans Police Department.
The NOPD takes an enormous share of the city’s budget, and that percentage has risen exponentially over the last two decades, taking away desperately needed resources from essential community programs and services. As a member of the community, I am an opposer to the high incarceration rates we have here in New Orleans. The investment in policing has not made us in the Black and Brown communities any safer and the system in which it operates is inarguably anti black, brown, and lgbtq+ – NOPD remains an embarrassment to this city and a lethal threat to what makes us New Orleans. Meanwhile you increase police spending. With New Orleans’s current precarious finances in jeopardy, it is clear that we must defund the police.

As New Orleans residents, we therefore demand that you take immediate action to ensure the following:

1. Reduce NOPD’s allocation from the General Fund by 50% (roughly $100 Million)
2. Discontinue use of fund dollars to pay for settlements due to police murder, misconduct, and negligence
3. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

New Orleans can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund NOPD.
Thank you for your time,
[YOUR NAME] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by minicreative** [comment]
Let's go with:

Dear Mayor Cantrell and City Council Members,

My name is [YOUR NAME] and I am a New Orleans resident writing to urge you to defund the New Orleans Police Department.

The NOPD takes an enormous share of the city’s budget, and that percentage has risen exponentially over the last two decades, taking away desperately needed resources from essential community programs and services. As a member of the community, I am opposed to the high incarceration rates seen in New Orleans. The investment in policing has not made our Black and Brown communities any safer. NOPD remains an embarrassment to this city and a lethal threat to what makes us New Orleans. Meanwhile, police spending has increased. With New Orleans’ budget already under stress, it is clear that we must defund the police.

As New Orleans residents, we therefore demand that you take immediate action towards the following ends:
* Reduce NOPD’s allocation from the General Fund by 50% (roughly $100 Million)
* Discontinue use of General Fund dollars to pay for settlements due to police murder, misconduct, and negligence
* Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

New Orleans can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund NOPD.

Thank you for your time,
[YOUR NAME]
[YOUR EMAIL]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

**Comment by hp1872** [comment]
Is it possible to add an email address? And add a this paragraph in the beginning? It looks great regardless! @minicreative @bingbongle @defund12neworleans 

To:
nopchief@nola.gov

My name is [NAME]. I am a resident of New Orleans, Louisiana. I am contacting you to demand a significant reduction to the $194 million that is currently allocated to public safety in the upcoming fiscal budget of 2021 and for a formal review of the New Orleans Police Department Union Contract from an independent party that has no affiliation with NOPD. The police funds make up roughly 20% of the budget, while other important public services do not receive even half as much funding. By reducing police funding and reducing incarceration rates, those funds can be reallocated to housing, education or sanitation (etc.). That way we can focus on building our community efforts and local organizations, while preventing future police brutality and violence.

**Comment by minicreative** [comment]
@hp1872 Yep, will update
