### ISSUE TITLE
Defund 12 Gainesville To: City and County Commissioners, and the Mayor

### ISSUE THREAD

**Issue by Rukmini16** [defund12/defund12.org#852]
To: City and County Commissioners, and the Mayor
citycomm@cityofgainesville.org, poelb@cityofgainesville.org, mayor@cityofgainesville.org, johnson1@cityofgainesville.org, warrenhk@cityofgainesville.org, simmonsgg@cityofgainesville.org, wardhl@cityofgainesville.org, arreoladi@cityofgainesville.org, hayessantosa@cityofgainesville.org, byerly@alachuacounty.us, mwheeler@alachuacounty.us, rhutchinson@alachuacounty.us, kcornell@alachuacounty.us, cschestnut@alachuacounty.us

Subject Line: Insert unique subject line here!

Hello, my name is [           ], and I am an Alachua County resident. 

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:
Vote no on all increases to police budgets
Vote yes to decrease police spending and budgets
Vote yes to increase spending on health care, education and community programs that keep us safe.

In 2020, the City of Gainesville has allocated 42.25 million dollars to the police department, and 59.66 million to law enforcement in general. Housing and Urban Planning-- something residents everywhere but especially on the East side need-- was allocated 6.06 million. 

People of color in American, specifically Black people, already know that the police don’t keep neighborhoods and communities safe. Police presence leads to police brutality, which is why we are demanding a defunding of police and a reallocation of resources towards community investment. Black people like Tony McDade (Tallahassee), Trayvon Martin (Sanford), and Jamee Johnson (Jacksonville) cannot keep dying at the hands of police and white actors emboldened by the state.

In a time when Black people are facing challenges to their lives such as COVID-19, which disproportionately affects communities of color, there is no excuse for the $500,000 increase in funds to law enforcement for the 2020-2021 fiscal year. 

The City of Gainesville needs an affordable grocery store on the Eastside. When the City you run has a food desert in it, that’s where funds need to be going-- to residents, and not to police that regularly use excessive force on said residents.

We call for a defunding of police and a funding of community needs.

Sincerely, 

The People of Alachua County
[Name]

**Comment by swallan** [comment]
To: City and County Commissioners, and the Mayor
citycomm@cityofgainesville.org, poelb@cityofgainesville.org, mayor@cityofgainesville.org, johnson1@cityofgainesville.org, warrenhk@cityofgainesville.org, simmonsgg@cityofgainesville.org, wardhl@cityofgainesville.org, arreoladi@cityofgainesville.org, hayessantosa@cityofgainesville.org, byerly@alachuacounty.us, mwheeler@alachuacounty.us, rhutchinson@alachuacounty.us, kcornell@alachuacounty.us, cschestnut@alachuacounty.us

Subject Line: Insert unique subject line here!

Hello, my name is [ ], and I am an Alachua County resident.

I DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:
- Vote no on all increases to police budgets
- Vote yes to decrease police spending and budgets
- Vote yes to increase spending on health care, education and community programs that keep us safe.

In 2020, the City of Gainesville has allocated 42.25 million dollars to the police department, and 59.66 million to law enforcement in general. Housing and Urban Planning-- something residents everywhere but especially on the East side need-- was allocated 6.06 million.

People of color in American, specifically Black people, already know that the police don’t keep neighborhoods and communities safe. Police presence leads to police brutality, which is why we are demanding a defunding of police and a reallocation of resources towards community investment. Black people like Tony McDade (Tallahassee), Trayvon Martin (Orlando), and Jamee Johnson (Jacksonville) cannot keep dying at the hands of police and white actors emboldened by the state.

In a time when Black people are facing challenges to their lives such as COVID-19, which disproportionately affects communities of color, there is no excuse for the $500,000 increase in funds to law enforcement for the 2020-2021 fiscal year.

The City of Gainesville needs an affordable grocery store on the Eastside. When the City you run has a food desert in it, that’s where funds need to be going-- to residents, and not to police that regularly use excessive force on said residents.

We call for a defunding of police and a funding of community needs.

Sincerely,

The People of Alachua County
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
On it!
