### ISSUE TITLE
Please add Pasadena, CA and LA County Board of Supervisors

### ISSUE THREAD

**Issue by brobb24** [defund12/defund12.org#862]

**Comment by mahrer** [comment]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by aypvee** [comment]
Subject: Defund and Demilitarize the Pasadena Police Department

Email addresses: ttornek@cityofpasadena.net, district1@cityofpasadena.net, mmcaustin@cityofpasadena.net, jkennedy@cityofpasadena.net, gmasuda@cityofpasadena.net, vgordo@cityofpasadena.net, smadison@cityofpasadena.net, awilson@cityofpasadena.net

Dear Pasadena Mayor and City Council, 

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police. 

Not only are we experiencing the trauma of global pandemic, we are also in the midst of widespread upheaval over the systemic violence embodied by American police departments’ well-documented history of murdering Black people. Empty gestures and suggestions of “reform” are unacceptable. I am demanding that the City Council of Pasadena stand with the People. I am demanding that you root out systemic and institutional racism by defunding the police and prioritizing and reallocating much-needed funds to education, housing, and community and social services.

I also entreat you to stand in solidarity with the movement by demanding change from the LAPD. As neighbors, we are duty-bound to hold each other accountable. I join the calls of those across the country to meaningfully defund the police.  The people are demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart. 

You need to adopt a budget that prioritizes the social programs proven to promote safety and equity much more effectively than policing. You need to steadfastly pressure your peers on the City Council of Los Angeles to do the same. Public opinion is with me.

Thank you for your time,
[YOURNAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@aypvee This is a great start! Do you think you could add some data specific to Pasadena? Perhaps some info on their current budget or their history with police brutality?

**Comment by aypvee** [comment]
Absolutely! See below. Almost all are demands are from the Pasadena Black Lives Matters Pasadena Chapter.

- Reallocate PPD's $91 million dollar budget towards a neglected public school system, social programs for youth/young adults, public health and housing services, etc. 
- Kendrec McDade's murderers, Matthew Griffin (badge #3125) and Jeffery Newlen (badge #6113) need to be fired and indicted. The Office of Independent Review Group concluded an investigative report in 2015 that police mishandled investigation of the officers' fatal shooting of unarmed Black teen in 2012.
- Release the video footage, autopsy report and prosecute the 6 officers involved in the murder of Reginald Thomas Jr. who died in police custody in 2016.
- Release of the video footage, autopsy report and prosecute the officers involved in the murder of Leroy Barnes in 2009 who was shot 11 times after being pulled over.
- Work in partnership with the City Council to develop a reparations ordinance as cities like Chicago have established. This policy would provide financial, mental health, educational and other resources for the families of victims of police torture.

**Comment by swallan** [comment]
Subject: Defund and Demilitarize the Pasadena Police Department

Email addresses: ttornek@cityofpasadena.net, district1@cityofpasadena.net, mmcaustin@cityofpasadena.net, jkennedy@cityofpasadena.net, gmasuda@cityofpasadena.net, vgordo@cityofpasadena.net, smadison@cityofpasadena.net, awilson@cityofpasadena.net

Dear Pasadena Mayor and City Council,

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

Not only are we experiencing the trauma of global pandemic, we are also in the midst of widespread upheaval over the systemic violence embodied by American police departments’ well-documented history of murdering Black people. Empty gestures and suggestions of “reform” are unacceptable. I am demanding that the City Council of Pasadena stand with the People. I am demanding that you root out systemic and institutional racism by defunding the police and prioritizing and reallocating much-needed funds to education, housing, and community and social services.

- Reallocate PPD's $91 million dollar budget towards a neglected public school system, social programs for youth/young adults, public health and housing services, etc.
- Work in partnership with the City Council to develop a reparations ordinance as cities like Chicago have established. This policy would provide financial, mental health, educational and other resources for the families of victims of police torture.

I also entreat you to stand in solidarity with the movement by demanding change from the LAPD. As neighbors, we are duty-bound to hold each other accountable. I join the calls of those across the country to meaningfully defund the police.  The people are demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart.

You need to adopt a budget that prioritizes the social programs proven to promote safety and equity much more effectively than policing. You need to steadfastly pressure your peers on the City Council of Los Angeles to do the same. Public opinion is with me.

Thank you for your time,
[YOURNAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rpalakkal** [comment]
on this

**Comment by burgerboy3000** [comment]
Here is email for LA County Board of Supervisors for Pasadena (LA District 5):
 Kathryn@bos.lacounty.gov
