### ISSUE TITLE
Please add: New Brunswick, NJ

### ISSUE THREAD

**Issue by circedelusion** [defund12/defund12.org#863]
SUBJECT: Defund the New Brunswick Police Department

EMAILS: jsmith@cityofnewbrunswick.org, gfleming@cityofnewbrunswick.org kegan@cityofnewbrunswick.org, janderson@cityofnewbrunswick.org, rescobar@cityofnewbrunswick.org, ssicoraludwig@cityofnewbrunswick.org, kjones11@cityofnewbrunswick.org

EMAIL TEXT:

Dear Mayor Cahill and Councilmembers:

My name is [YOUR NAME], and I am a resident of [CITY/NEIGHBORHOOD]. In light of the urgent movement for black lives happening across our nation, I am writing to urge you to advocate for a meaningful reallocation of the City's expenditures away from policing and.towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. As the tragic 2011 shooting of Barry Deloatch shows, police violence against black people is very much an urgent problem in New Brunswick.

At $20,181,528 total, representing an increase from 2019, the City’s amended 2020 budget for policing dwarfs its other appropriations. For example, the allocation for health and human services does not even reach $500,000. This is egregious, particularly in light of the global pandemic - New Brunswick has [one of the highest case counts](https://discovermiddlesex.com/total-cumulative-cases/) of COVID-19. New Brunswick’s population is [14.6% African American and 50.1% Hispanic/Latino, and 34.2% of its residents are in poverty](https://www.census.gov/quickfacts/fact/table/newbrunswickcitynewjersey/PST045219). Given that racial inequities persist throughout the nation, and that police have proven to be a dire public health threat for black Americans, it is unconscionable to continue to fund police at these disproportionate levels while starving social programs. 

I urge you to advocate for a complete overhaul of the City’s budget that directs at least $15 million away from policing. All over the country, American citizens are calling for budgets that truly represent the people’s needs. In a global pandemic, it is all the more critical to invest funds in areas like health, youth services, and other social programs. I urge you to revise the FY 2020 budget to reflect the demands of New Brunswick’s residents - ideally with participation of those residents in the budget creation - and show that the City of New Brunswick is committed to a vision of true public safety, one that reduces and eliminates harm for everyone.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
edits in bold:

--------------------------------------

SUBJECT: **[INSERT UNIQUE SUBJECT LINE]**

EMAILS: jsmith@cityofnewbrunswick.org, gfleming@cityofnewbrunswick.org kegan@cityofnewbrunswick.org, janderson@cityofnewbrunswick.org, rescobar@cityofnewbrunswick.org, ssicoraludwig@cityofnewbrunswick.org, kjones11@cityofnewbrunswick.org

EMAIL TEXT:

Dear Mayor Cahill and Council Members:

My name is [YOUR NAME], and I am a resident of [CITY/NEIGHBORHOOD]. In light of the urgent movement for black lives happening across our nation, I am writing to urge you to advocate for a meaningful reallocation of the City's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. As the tragic 2011 shooting of Barry Deloatch shows, police violence against **B**lack people is very much an urgent problem in New Brunswick.

**Accordingly, it has come to my attention that the hearing on the Budget and Tax Resolution for fiscal year 2020 will be held on July 15.** At $20,181,528 total, an increase from 2019, the City’s amended 2020 budget for policing dwarfs its other appropriations. For example, the allocation for health and human services does not even reach $500,000. This is egregious, particularly in light of the global pandemic - New Brunswick has one of the highest case counts of COVID-19. New Brunswick’s population is 14.6% African American and 50.1% Hispanic/Latino, and 34.2% of its residents are in poverty. Given that racial inequities persist throughout the nation, and that police have proven to be a dire public health threat for **B**lack Americans, it is unconscionable to continue to fund police at these disproportionate levels while starving social programs.

I urge you to advocate for a complete overhaul of the City’s budget that directs at least **[INSERT AMOUNT]** away from policing. All over the country, American citizens are calling for budgets that truly represent the people’s needs. In a global pandemic, it is all the more critical to invest funds in areas like health, youth services, and other social programs. I urge you to revise the FY 2020 budget to reflect the demands of New Brunswick’s residents - ideally with participation of those residents in the budget creation - and show that the City of New Brunswick is committed to a vision of true public safety, one that reduces and eliminates harm for everyone.

**Sincerely,** 

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

-----------------------------------

Confirmed the statistics on:
https://www.cityofnewbrunswick.org/2020%20Revised%20Introduced%20Budget.pdf
https://www.census.gov/quickfacts/newbrunswickcitynewjersey

I also removed the specific $15 million amount and instead added changed it so that the user fills in a custom amount. If that is not advised, then feel free to add the amount back.

@swallan please mark as ready for PR
