### ISSUE TITLE
Burlington, VT Reject Proposed BPD Budget

### ISSUE THREAD

**Issue by whoopnah** [defund12/defund12.org#872]
please add template for Burlington, VT to Mayor Weinberger

mayor@burlingtonvt.gov

Hello,
My name is [YOUR NAME]. I am a resident of Burlington and I am writing today to demand that Mayor Weinberger take specific measures to reduce funding for police in the city of Burlington. We are calling on the Mayor to take a serious look at the number of funds being designated towards criminalization and surveillance. The Mayor has a responsibility to address the city’s lack of investment in predominantly Black and Brown community as he considers this funding.

The city of Burlington is looking at increasing the budget of the Police Department by $17.4 million this year, as you well know. Budgets for Immigrant services, disability services, education, housing, and youth and family services pale in comparison to this excessive budget.

With the overall police budget, the City Council has the power to cut line items in the City budget. The police budget and overtime budget should be cut, with funds reinvested in Black and POC communities. The Mayor must show strength in his role as a leader of the Council and take a stand for defunding the BPD.

Burlington can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities - starting with cutting the least transparent and most harmful parts of the BPD budget.

We the residents of Burlington will hold you accountable for swift and just action, Mayor Weinberger. 

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
> The city of Burlington is looking at increasing the budget of the Police Department by $17.4 million this year, as you well know. 

couldn't verify this, seems a bit high for a smaller town

**Comment by mahrer** [comment]
@whoopnah can you provide the source used for that data?

**Comment by todd-m** [comment]
media confirms that number: https://vtdigger.org/2020/06/08/hundreds-of-burlington-residents-call-to-defund-police-department-%EF%BB%BF/

**Comment by todd-m** [comment]
Some edits below. I couldn't tell what line items were being referred to so cut that part, but feel free to respond if you'd like to clarify @whoopnah.

Dear Mayor Weinberger,

My name is [YOUR NAME]. I am a resident of Burlington and I am writing today to demand that you take specific measures to reduce funding for police in the City of Burlington. I call on you to take a serious look at the amount of funding being designated towards criminalization and surveillance. You have a responsibility to address the city’s lack of investment in predominantly Black and Brown communities.

The City of Burlington is looking at increasing the budget of the Police Department by $17.4 million this year, as you well know. Spending for immigrant services, disability services, education, housing, and youth and family services pale in comparison to this excessive budget.

Burlington can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities, starting with cutting the least transparent and most harmful parts of the BPD budget.

As Mayor, you must show strength in your role as a leader of the Council, and take a stand for defunding the BPD. We the residents of Burlington will hold you accountable for swift and just action, Mayor Weinberger.

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
gonna put this up

**Comment by todd-m** [comment]
one more note -- since we already have a letter to council/mayor for Burlington, but this one is different, researched, and pretty good(!) i'm adding the city council members and titling it as an alternate. minor edits to address council as well as mayor:

- "mayor@burlingtonvt.gov"
- "jredell@burlingtonvt.gov"
- "mtracy@burlingtonvt.gov"
- "zhightower@burlingtonvt.gov"
- "bpine@burlingtonvt.gov"
- "scarpenter@burlingtonvt.gov"
- "cmason@burlingtonvt.gov"
- "kpaul@burlingtonvt.gov"
- "adieng@burlingtonvt.gov"
- "jstromberg@burlingtonvt.gov"
- "pfreeman@burlingtonvt.gov"
- "jhanson@burlingtonvt.gov"
- "fpaulino@burlingtonvt.gov"
- "jshannon@burlingtonvt.gov"

Dear Mayor Weinberger and City Councilmembers,

  My name is [YOUR NAME]. I am a resident of Burlington and I am writing today to demand that you take specific measures to reduce funding for police in the City of Burlington. I call on you to take a serious look at the amount of funding being designated towards criminalization and surveillance. You have a responsibility to address the city’s lack of investment in predominantly Black and Brown communities.

  The City of Burlington is looking at increasing the budget of the Police Department by $17.4 million this year, as you well know. Spending for immigrant services, disability services, education, housing, and youth and family services pale in comparison to this excessive budget.

  Burlington can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities, starting with cutting the least transparent and most harmful parts of the BPD budget.

  As elected officials, you must show strength in your role as a leader of the Council, and take a stand for defunding the BPD. We the residents of Burlington will hold you accountable for swift and just action.

  Sincerely,

  [YOUR NAME]
  [YOUR ADDRESS]
  [YOUR EMAIL]
  [YOUR PHONE NUMBER]
