### ISSUE TITLE
Add Anaheim, CA

### ISSUE THREAD

**Issue by ag45501** [defund12/defund12.org#890]

**Comment by shortcircuit3** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by ag45501** [comment]
email to: Publiccomment@anaheim.net

Subject: DEFUND APD

Body:

To the Anaheim City Council: 


My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/CITY]. I am writing in deep concern for the health of the greater Anaheim community. It has become more than clear that a radical shift in our concept of policing and community health must take place at the local level. Police violence in Anaheim has disproportionately affected Black and Brown residents and that must come to an end.


The United States does not have a national healthcare system. Instead, we have the largest military budget, and some of the most well-funded and militarized police departments in the world. Anaheim is no different: the 2019-2020 budget allocated $153.8 million to law enforcement and only $1 million to community development. 


Anaheim is the 9th most violent police department in the U.S. From 2003-2016, Anaheim Police Department killed 33 people during the process of arrest, and nearly 40% of them were unarmed. Since 2014, the rate of arrest-related deaths caused by Anaheim PD exceeds that of LAPD, NYPD, and San Fran PD and is 74% higher than the average for police in California.


WE DEMAND that the city council not approve “Resolution 19” that would spend $700,000 dollars of taxpayer money on surveillance technology of anti-police brutality protests and that any future projects related to surveillance be halted. We also DEMAND that the council not approve "Resolution 5" that will use $100,000 to improve 10 police vehicles. Instead, invest that money in creating programs that benefit and enrich the community especially during a global pandemic. 


We are calling on our elected officials to stop criminalizing our community members. We as a concerned community refuse to remain silent on the use of technology to further terrorize our community.


[YOUR NAME]
