### ISSUE TITLE
PLEASE add Anaheim, CA

### ISSUE THREAD

**Issue by ag45501** [defund12/defund12.org#895]
email to: Publiccomment@anaheim.net (City Council)

subject: DEFUND APD

Body:
To the Anaheim City Council: 

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/CITY]. I am writing in deep concern for the health of the greater Anaheim community. It has become more than clear that a radical shift in our concept of policing and community health must take place at the local level. Police violence in Anaheim has disproportionately affected Black and Brown residents and that must come to an end.

The United States does not have a national healthcare system. Instead, we have the largest military budget, and some of the most well-funded and militarized police departments in the world. Anaheim is no different: the 2019-2020 budget allocated $153.8 million to law enforcement and only $1 million to community development. 

Anaheim is the 9th most violent police department in the U.S. From 2003-2016, Anaheim Police Department killed 33 people during the process of arrest, and nearly 40% of them were unarmed. Since 2014, the rate of arrest-related deaths caused by Anaheim PD exceeds that of LAPD, NYPD, and San Fran PD and is 74% higher than the average for police in California.

WE DEMAND that the city council not approve “Resolution 19” that would spend $700,000 dollars of taxpayer money on surveillance technology of anti-police brutality protests and that any future projects related to surveillance be halted. We also DEMAND that the council not approve "Resolution 5" that will use $100,000 to improve 10 police vehicles. Instead, invest that money in creating programs that benefit and enrich the community especially during a global pandemic. 

We are calling on our elected officials to stop criminalizing our community members. We as a concerned community refuse to remain silent on the use of technology to further terrorize our community.

[YOUR NAME]

**Comment by swallan** [comment]
email to: Publiccomment@anaheim.net (City Council)

subject: DEFUND APD

Body:
To the Anaheim City Council:

My name is [YOUR NAME], and I am a resident of [YOUR NEIGHBORHOOD/CITY]. I am writing in deep concern for the health of the greater Anaheim community. It has become more than clear that a radical shift in our concept of policing and community health must take place at the local level. Police violence in Anaheim has disproportionately affected Black and Brown residents and that must come to an end.

The United States does not have a national healthcare system. Instead, we have the largest military budget, and some of the most well-funded and militarized police departments in the world. Anaheim is no different: the 2019-2020 budget allocated $153.8 million to law enforcement and only $1 million to community development.

Anaheim is the 9th most violent police department in the U.S. From 2003-2016, Anaheim Police Department killed 33 people during the process of arrest, and nearly 40% of them were unarmed. Since 2014, the rate of arrest-related deaths caused by Anaheim PD exceeds that of LAPD, NYPD, and San Fran PD and is 74% higher than the average for police in California.

I demand that the city council not approve “Resolution 19” that would spend $700,000 dollars of taxpayer money on surveillance technology of anti-police brutality protests and that any future projects related to surveillance be halted. I also demand that the council not approve "Resolution 5" that will use $100,000 to improve 10 police vehicles. Instead, invest that money in creating programs that benefit and enrich the community especially during a global pandemic.

I am calling on our elected officials to stop criminalizing our community members. We as a concerned community refuse to remain silent on the use of technology to further terrorize our community.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rpalakkal** [comment]
on it
