### ISSUE TITLE
Please add Newton, MA

### ISSUE THREAD

**Issue by bobbie4u** [defund12/defund12.org#896]
Dear [Name],

My name is [Your name] and I live in Newton, MA. I am writing to ask that you use your power as [City Councilor/Mayor] to reject the proposed increase of $147k to the Newton Police Department’s FY21 budget. With a multi-billion dollar drop in revenue statewide, due to the many complications of COVID-19 and other departments losing money, an increase for the NPD budget does not make sense or benefit our city. It is especially difficult to justify that within the Police Department budget, $420k more is being put toward patrolling, which has already doubled since 2015, even as calls to service have decreased. This money should instead go toward the Library, Health & Human Services, Senior Services, Affordable Housing, or Youth Services. As people across the country demand creative alternatives to policing, the last thing Newton needs is more patrols or cruisers. Social service programs are what make our community safe, not more policing that leads to the murder and incarceration of Black, Indigenous, and Brown people of color who are already disproportionately affected by the current economic and health crisis and by police brutality. If Newton is truly a town where Black Lives Matter, as [you/Mayor Fuller] said to protestors at City Hall, then demonstrate it through our tax dollars. 

Sincerely, 
[Your name, address, ward]

**Comment by skullface** [comment]
Hi @bobbie4u! Can you provide email addresses to send this message to? Thank you!

**Comment by bobbie4u** [comment]
Hello!

rfuller@newtonma.gov , msgreenberg@newtonma.gov, enorton@newtonma.gov,
jmalakie@newtonma.gov, cmarkiewicz@newtonma.gov, bhumphrey@newtonma.gov,
bnoel@newtonma.gov, lbaker@newtonma.gov, hryan@newtonma.

THANK YOU SO MUCH

**Comment by skullface** [comment]
Thank you @bobbie4u! This is now in the queue for content review from the team.

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
@bobbie4u who do these email addresses belong to?

**Comment by mahrer** [comment]
SEND TO: rfuller@newtonma.gov , msgreenberg@newtonma.gov, enorton@newtonma.gov,
jmalakie@newtonma.gov, cmarkiewicz@newtonma.gov, bhumphrey@newtonma.gov,
bnoel@newtonma.gov, lbaker@newtonma.gov, hryan@newtonma

SUBJECT: [WRITE YOUR OWN UNIQUE SUBJECT LINE]

Dear Newton leadership,

My name is [YOUR NAME] and I live in [CITY]. I am writing to ask that you use your power as elected officials to reject the proposed increase of $147k to the Newton Police Department’s FY21 budget. 

With a multi-billion dollar drop in revenue statewide, due to the many complications of COVID-19 and other departments losing money, an increase for the NPD budget does not make sense or benefit our city. It is especially difficult to justify that within the Police Department budget, $420k more is being put toward patrolling, which has already doubled since 2015, even as calls to service have decreased. This money should instead go toward the Library, Health & Human Services, Senior Services, Affordable Housing, or Youth Services. 

As people across the country demand creative alternatives to policing, the last thing Newton needs is more patrols or cruisers. Social service programs are what make our community safe, not more policing that leads to the murder and incarceration of Black, Indigenous, and Brown People of Color who are already disproportionately affected by the current economic and health crisis and by police brutality. If Newton is truly a town where Black Lives Matter, as Mayor Fuller said to protestors at City Hall, then demonstrate it through our tax dollars.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
