### ISSUE TITLE
add McMinnville, OR

### ISSUE THREAD

**Issue by becca-cs** [defund12/defund12.org#898]
- Subject line for the email: "Funding for McMinnville Police Department"
- Email addresses (at least one) of the government officials you’d like to receive the message: scott.hill@mcminnvilleoregon.gov,sal.peralta@mcminnvilleoregon.gov,wendy.stassens@mcminnvilleoregon.gov,kellie.menke@mcminnvilleoregon.gov,zack.geary@mcminnvilleoregon.gov,Remy.Drabkin@mcminnvilleoregon.gov,Adam.Garvin@mcminnvilleoregon.gov

- Detailed message concerning the budgeting decisions at stake in your community: I wrote a quick draft, pasted below, based on defund12 email for Portland, OR:

 Dear Mayor Hill and McMinnville City Council members,

My name is [YOUR NAME] and I am a resident of McMinnville, OR. As McMinnville City Council finalizes the 2020-21 citywide budget, I want to express a concern for the amount of funding that is currently being allocated to the McMinnville Police Department. From my understanding, the 2019-2020 proposed budget allocated over $9 million to the police department, an increase of $500,000 from the 2018-2019 budget and representing almost 40% of the total General Fund expenditures. The police have historically been the single largest expenditure in the city budget. How we spend our public funds expresses our values as a city, and I do not believe that our city should continue to over-invest scarce resources in the McMinnville Police Department.

Especially at this time of unprecedented crisis, we must invest our scarce resources in the health and well-being of our communities. Funding toward life-affirming resources such as those related to housing, access to health care, and food security, must be prioritized. We must direct resources towards dignified temporary and permanent housing and rent relief, towards food assistance programs for people having trouble making ends meet, and to services provided by the library and Parks and Recreation. In particular, I am concerned about the police presence offered by School Resource Officers. I suggest that SROs be cut from the city budget, following Portland’s lead, as police can make non-white students feel unsafe in school. We must also use resources already allocated to the police department to invest in police accountability measures.

The economic impact of COVID-19 requires a complete reimagining of how we allocate county resources, and makes clear the necessity for prioritizing investments in communities’ health and well-being. The city can address any deficits by divesting from the violence of policing and incarceration. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. Existing racial and economic disparities will only worsen in the wake of this ongoing crisis. We know that this virus is disproportionately affecting Black and brown communities & that this disparity is caused by racist systems that affect how and when people receive care.

This moment of reckoning with our nation's history of racist policing practices is an opportunity to rethink public safety in this city and reinvest in services that more effectively benefit our residents. We know that meeting the basic needs of our communities is the only way to ensure their health and safety.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by becca-cs** [comment]
I edited to reflect the 2020-2021 budget (found https://www.mcminnvilleoregon.gov/sites/default/files/fileattachments/finance/page/17741/city_2020-21_proposed_budget_final.pdf)

To McMinnville City Council:

To: scott.hill@mcminnvilleoregon.gov,sal.peralta@mcminnvilleoregon.gov,wendy.stassens@mcminnvilleoregon.gov,kellie.menke@mcminnvilleoregon.gov,zack.geary@mcminnvilleoregon.gov,Remy.Drabkin@mcminnvilleoregon.gov,Adam.Garvin@mcminnvilleoregon.gov

Subject: [UNIQUE SUBJECT LINE]

Dear Mayor Hill and McMinnville City Council members,

My name is [YOUR NAME] and I am a resident of McMinnville, OR. As McMinnville City Council finalizes the 2020-21 citywide budget, I want to express a concern for the amount of funding that is currently being allocated to the McMinnville Police Department. Although the current budget proposal includes a $35,458 (0.38 percent) decrease in Police funding, the Police Department is still set to receive almost a third of our city’s budget, and $1.5 million more than their budget in 2017-2018. The police have historically been the single largest expenditure in the city budget. How we spend our public funds expresses our values as a city, and I do not believe that our city should continue to over-invest scarce resources in the McMinnville Police Department.

Especially at this time of unprecedented crisis, we must invest our scarce resources in the health and well-being of our communities. Funding toward life-affirming resources such as those related to housing, access to health care, and food security, must be prioritized. We must direct resources towards dignified temporary and permanent housing and rent relief, towards food assistance programs for people having trouble making ends meet, and to services provided by the library and Parks and Recreation. In particular, I am concerned about the police presence offered by School Resource Officers. I suggest that SROs be cut from the city budget, following Portland’s lead, as police can make non-White students feel unsafe in school. We must also use resources already allocated to the Police Department to invest in police accountability measures. A new budget proposal reallocating funds from the police budget to other departments and programs across the board could tie into all 5 points of the Mac-Town 2032 Strategic Plan.

The economic impact of COVID-19 requires a complete reimagining of how we allocate county resources, and makes clear the necessity for prioritizing investments in communities’ health and well-being. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. Existing racial and economic disparities will only worsen in the wake of this ongoing crisis. We know that this virus is disproportionately affecting Black and brown communities & that this disparity is caused by racist systems that affect how and when people receive care.

This moment of reckoning with our nation's history of racist policing practices is an opportunity to rethink public safety in this city and reinvest in services that more effectively benefit our residents. We know that meeting the basic needs of our communities is the only way to ensure their health and safety.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
edits in bold:

-------------------------------------

To McMinnville City Council:

To: scott.hill@mcminnvilleoregon.gov,sal.peralta@mcminnvilleoregon.gov,wendy.stassens@mcminnvilleoregon.gov,kellie.menke@mcminnvilleoregon.gov,zack.geary@mcminnvilleoregon.gov,Remy.Drabkin@mcminnvilleoregon.gov,Adam.Garvin@mcminnvilleoregon.gov

Subject: [UNIQUE SUBJECT LINE]

Dear Mayor Hill and McMinnville City Council members,

My name is [YOUR NAME] and I am a resident of McMinnville, OR. As McMinnville City Council finalizes the 2020-21 citywide budget, I want to express a concern for the amount of funding that is currently being allocated to the McMinnville Police Department. Although the current budget proposal includes a $35,458 (0.38 percent) decrease in Police funding, the Police Department is still set to receive almost a third of our city’s **General Fund** budget, and $1.5 million more than their budget in 2017-2018. The police have historically been the single largest expenditure in the city budget. How we spend our public funds expresses our values as a city, and I do not believe that our city should continue to over-invest scarce resources in the McMinnville Police Department.

Especially at this time of unprecedented crisis, we must invest our scarce resources in the health and well-being of our communities. Funding toward life-affirming resources such as those related to housing, access to health care, and food security, must be prioritized. We must direct resources towards dignified temporary and permanent housing and rent relief, towards food assistance programs for people having trouble making ends meet, and to services provided by the library and Parks and Recreation. In particular, I am concerned about the police presence offered by School Resource Officers. I suggest that SROs be cut from the city budget, following Portland’s lead, as police can make non-White students feel unsafe in school. We must also use resources already allocated to the Police Department to invest in police accountability measures. A new budget proposal reallocating funds from the police budget to other departments and programs across the board could tie into all 5 points of the Mac-Town 2032 Strategic Plan.

The economic impact of COVID-19 requires a complete reimagining of how we allocate county resources, and makes clear the necessity for prioritizing investments in communities’ health and well-being. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. Existing racial and economic disparities will only worsen in the wake of this ongoing crisis. We know that this virus is disproportionately affecting Black and **B**rown communities & that this disparity is caused by racist systems that affect how and when people receive care.

This moment of reckoning with our nation's history of racist policing practices is an opportunity to rethink public safety in this city and reinvest in services that more effectively benefit our residents. We know that meeting the basic needs of our communities is the only way to ensure their health and safety.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

---------------------------------------------
Confirmed the statistics in https://www.mcminnvilleoregon.gov/sites/default/files/fileattachments/finance/page/17741/city_2020-21_proposed_budget_final.pdf

@mahrer could you update this to ready for PR?
