### ISSUE TITLE
Please add Eugene, Oregon!

### ISSUE THREAD

**Issue by terpodactyl** [defund12/defund12.org#90]

**Comment by cstrouse** [comment]
- Mayor Lucy Vinis (lvinis@eugene-or.gov)
- Emily Semple (esemple@eugene-or.gov)
- Betty Taylor, Ward 2 (btaylor@eugene-or.gov)
- Alan Zelenka, Ward 3 (azelenka@eugene-or.gov)
- Jennifer Yeh, Ward 4 (jyeh@eugene-or.gov)
- Mike Clark, Ward 5 (mclark@eugene-or.gov)
- Greg Evans, Ward 6 (gevans@eugene-or.gov)
- Claire Syrett, Ward 7 (csyrett@eugene-or.gov)
- Chris Pryor, Ward 8 (cpryor@eugene-or.gov)

**Comment by teddywilson** [comment]
DUE TO HIGH VOLUME EMPTY ISSUES, OR ISSUES MISSING THE FOLLOWING INFORMATION WILL BE IMMEDIATELY CLOSED. THANK YOU!

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community
Please read more about our email style guidelines here.

If this information is copied from an external source please provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!
