### ISSUE TITLE
Please add Canandaigua, NY

### ISSUE THREAD

**Issue by kmkumler** [defund12/defund12.org#901]
Emails: Bob.Palumbo@CanandaiguaNewYork.gov; Nick.Cutri@CanandaiguaNewYork.Gov; Dan.Unrath@CanandaiguaNewYork.Gov; Karen.White@CanandaiguaNewYork.gov; Erich.Dittmar@CanandaiguaNewYork.gov; Robert.OBrien@CanandaiguaNewYork.Gov; Renee.Sutton@CanandaiguaNewYork.Gov; James.Terwilliger@CanandaiguaNewYork.Gov; Steve.Uebbing@CanandaiguaNewYork.gov; DavidBaker197@Rochester.rr.com; richardrussell02@yahoo.com

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

My name is [YOUR NAME], and I’m a resident of Canandaigua, NY. I am writing about the Canandaigua fiscal year 2021 budget and call for you to review city policies surrounding police.

I am asking that the City of Canandaigua makes a more overt and visible commitment to racial justice. I demand that the budget be amended and reviewed so that Council may find ways to redirect money away from Canandaigua Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office and our local officials towards an ethical and equal reallocation of the city’s expenditures, away from PD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas. West Virginia and our city’s budgets are already struggling. We need to devote more money to building community and community resources across the state.

Do not forget our poor communities and communities of color in New York State who are disproportionate targets of police violence. The "wellness check" that ended in Sandy Guardiola's shooting death in 2017 should have served as a wake-up call. It's not too late to prevent another violent and wholly unnecessary death. Justice will only be served when the police are reformed, and this will not be possible until we defund them.

Can I count on you to consider an alternative budget and review policing methods that puts a focus on social service programs?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by kmkumler** [comment]
Emails: Bob.Palumbo@CanandaiguaNewYork.gov; Nick.Cutri@CanandaiguaNewYork.Gov; Dan.Unrath@CanandaiguaNewYork.Gov; Karen.White@CanandaiguaNewYork.gov; Erich.Dittmar@CanandaiguaNewYork.gov; Robert.OBrien@CanandaiguaNewYork.Gov; Renee.Sutton@CanandaiguaNewYork.Gov; James.Terwilliger@CanandaiguaNewYork.Gov; Steve.Uebbing@CanandaiguaNewYork.gov; DavidBaker197@Rochester.rr.com; richardrussell02@yahoo.com

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

My name is [YOUR NAME], and I’m a resident of Canandaigua, NY. I am writing about the Canandaigua fiscal year 2021 budget and call for you to review city policies surrounding police.

I am asking that the City of Canandaigua makes a more overt and visible commitment to racial justice. I demand that the budget be amended and reviewed so that Council may find ways to redirect money away from Canandaigua Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office and our local officials towards an ethical and equal reallocation of the city’s expenditures, away from PD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas. West Virginia and our city’s budgets are already struggling. We need to devote more money to building community and community resources across the state.

Do not forget our poor communities and communities of color in New York State who are disproportionate targets of police violence. The "wellness check" that ended in Sandy Guardiola's shooting death in 2017 should have served as a wake-up call. It's not too late to prevent another violent and wholly unnecessary death. Justice will only be served when the police are reformed, and this will not be possible until we defund them.

Can I count on you to consider an alternative budget and review policing methods that puts a focus on social service programs?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @kmkumler ! Thanks for your interest in adding Canandaigua to the site. Can you provide more detail about the city budget (as well as your source) to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by serifluous** [comment]
@mahrer do you think this is ok since it mentions a recent local event in the second-to-last paragraph?

**Comment by mahrer** [comment]
@serifluous Sure, I would say go for it. Thanks for checking up on this

**Comment by todd-m** [comment]
on this

**Comment by todd-m** [comment]
made a couple small edits to replace "our elected officials" with "your colleagues" (since the letter is addressed to elected officials) and remove a reference to West Virginia:

Dear City Officials,

  My name is [YOUR NAME], and I’m a resident of Canandaigua, NY. I am writing about the Canandaigua fiscal year 2021 budget and calling for you to review city policies surrounding police.

  I am asking that the City of Canandaigua makes a more overt and visible commitment to racial justice. I demand that the budget be amended and reviewed so that Council may find ways to redirect money away from Canandaigua Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office and your colleagues towards an ethical and equal reallocation of the city’s expenditures, away from PD, and towards sectors that facilitate the dismantling of racial and class inequality.

  Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas. New York and our city’s budgets are already struggling. We need to devote more money to building community and community resources across the state.

  Do not forget our poor communities and communities of color in New York State who are disproportionate targets of police violence. The "wellness check" that ended in Sandy Guardiola's shooting death in 2017 should have served as a wake-up call. It's not too late to prevent another violent and wholly unnecessary death. Justice will only be served when the police are reformed, and this will not be possible until we defund them.

  Can I count on you to consider an alternative budget and review policing methods that puts a focus on social service programs?

  Thank you,

  [YOUR NAME]
  [YOUR ADDRESS]
  [YOUR EMAIL]
  [YOUR PHONE NUMBER]
