### ISSUE TITLE
Email for Dayton Ohio 

### ISSUE THREAD

**Issue by ahicks11** [defund12/defund12.org#902]
*body copied from Columbus email via defund12.org , revised with Dayton specific proposed budget figures*

nan.whaley@daytonohio.gov commissionerjoseph@daytonohio.gov
Ariel.walker@daytonohio.gov commissionersims@daytonohio.gov commissionershaw@daytonohio.gov commissionerfairchild@daytonohio.gov Angela.coleman@daytonohio.gov Esther.rohm@daytonohio.gov Vanessa.moon@daytonohio.gov Erica.fields@daytonohio.gov 

Subject line: Request by the people of Dayton

Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, OUR LOCAL OFFICIALS, WILL:
1. Vote no on all increases to police budgets
2. Vote yes to decrease police spending and budgets
3. Vote yes to increase spending on Health care, education and community programs that keep us safe.

In Dayton, the current proposed budget for Economic and Community Development is $23,051,900 (a near $500,000 decrease from 2019). Our proposed budget for Justice is $66,557,400. We are asking you to stand in solidarity with your community by decreasing  the budget for Justice in 2021 and redistributing those funds. 

Where could that money go? It could go towards building healthy communities, to the health of our elders and children,to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.

Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police, Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia, Breonna Taylor an EMT killed while asleep in her bed in Louisville,KY, Dreasjon Reed in Indianapolis and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.

At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus,with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors. It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.

The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs”.

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.
Sincerely, The People of Dayton, OH [NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
Some edits here:

nan.whaley@daytonohio.gov commissionerjoseph@daytonohio.gov
Ariel.walker@daytonohio.gov commissionersims@daytonohio.gov commissionershaw@daytonohio.gov commissionerfairchild@daytonohio.gov Angela.coleman@daytonohio.gov Esther.rohm@daytonohio.gov Vanessa.moon@daytonohio.gov Erica.fields@daytonohio.gov

Subject line: Request by the people of Dayton

Hello, my name is [NAME] and I live in [CITY/NEIGHBORHOOD].

I join with people in Dayton and around the world to demand that you, our local officials, will:
Vote no on all increases to police budgets.
Vote yes to decrease police spending and budgets.
Vote yes to increase spending on health care, education and community programs that keep us safe.

In Dayton, the current proposed budget for Economic and Community Development is $23,051,900 (a near $500,000 decrease from 2019). Our proposed budget for Justice is $66,557,400. I am asking you to stand in solidarity with your community by decreasing the budget for Justice in 2021 and redistributing those funds.

Where could that money go? It could go towards building healthy communities, to the health of our elders and children,to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.

Black communities across the nation are mourning the deaths of George Floyd, tortured to death by Minneapolis police; Ahmaud Arbery, a jogger who was killed while running in a residential neighborhood in Brunswick, Georgia; Breonna Taylor, an EMT killed while asleep in her bed in Louisville, KY; Dreasjon Reed in Indianapolis; and Tony McDade in Tallahassee. Their names are added to a devastatingly long list of Black people who have been killed at the hands of vigilantes or law enforcement. Not to mention the others whose names we don’t yet know, and may never know since they were killed without a camera recording it.

At the same time, the United States leads the world in COVID-19 cases. So far, more than 100,000 people — enough to fill a football stadium– have perished from the virus,with over one million cases confirmed, and those numbers don’t reflect all the people dying from virus-related illnesses. Black people are suffering disproportionately from COVID-19, four times more likely to die than their white neighbors. It is important to state this within the context of the scourge of anti-Black police terror and the resulting uprisings taking place across the U.S.

The COVID-19 deaths and the deaths caused by police terror are connected and consequential to each other. The United States does not have a national healthcare system. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments in the world, too. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, funding for public health decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs.”

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

I join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And I call for the end to police terror.

Sincerely, 
[NAME] 
[PHONE_NUMBER] 
[EMAIL] 
[ADDRESS]

**Comment by rpalakkal** [comment]
on it

**Comment by ahicks11** [comment]
THANK YOU!!!
