### ISSUE TITLE
Add Upland, CA

### ISSUE THREAD

**Issue by jakesundstrom** [defund12/defund12.org#911]
To: dstone@ci.upland.ca.us, jelliott@ci.upland.ca.us, zuniga@ci.upland.ca.us, bvelto@ci.upland.ca.us  

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)
I am a resident of Upland and I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. This, combined with a global pandemic with severe economic consequences, brings the issue of police budgeting to the forefront. 

The 2019-20 Upland budget called for [51 percent of its General Fund Expenditure](https://www.uplandca.gov/uploads/files/Finance/Adopted%20Budget/City%20of%20Upland%20Adopted%20Annual%20Budget%202019-2020%20(Online-Rev2).pdf) ( $41,931,700) to go towards the Upland Police Department. [Page 11] That marked an increase of $1,006,990 with $546,830 coming from personnel services increases. 

From the Maintenance and Operations bulletin: 

“The maintenance and operations budget is $17,464,000, which is an increase of $460,160.
A majority of the increase belongs to the police department. The contract services account
reflects an increase for a new booking service contract.”

The average American state and local government spends $354 per capita per resident [on its police force](https://www.urban.org/policy-centers/cross-center-initiatives/state-and-local-finance-initiative/state-and-local-backgrounders/police-and-corrections-expenditures). Upland spends $287 per capita based on its 78,841 residents. The amount of spending has risen nationwide over the years (same source as before) and Upland, while spending a lower amount per capita, uses a larger amount of its general fund on police than cities like [Oakland](https://www.theatlantic.com/ideas/archive/2020/06/defund-police/612682/), Los Angeles and Houston. 

Crime has decreased both in Upland and nationwide but not [due to increased police spending](https://www.pewresearch.org/fact-tank/2019/10/17/facts-about-crime-in-the-u-s/). If anything, Upland uses its police force as a [revenue generator](https://www.governing.com/topics/finance/fine-fee-revenues-special-report.html). The 2019-20 budget seems to not so subtly suggest as much on page 10 under Miscellaneous Changes.

“Other changes include an increase of $1,155,730 for licenses and permits; increases in fines and forfeitures of $202,650; and increases in charges for services of $139,340.” 

An increase in fines and forfeitures can come from a number of areas: More residents, more visitors to Upland because of the shops and restaurants or the understanding that Upland Police will hand out more tickets. Well-worn cynicism isn’t out of the question. 

We demand the Upland City Council meaningfully defund Upland PD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of its citizens during this trying and uncertain time. 

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by stephbwills** [comment]
:wave: @jakesundstrom - great template! I'm just doing some fact checking using Upland's 2019-2020 approved budget and wanted to clarify some things:

1. Googling Upland's population give me 77,810 and the budget report has 78,481 - this is different than the number in your template. Would you mind confirming?
2. I'm seeing on [page 7 of the budget](https://www.uplandca.gov/uploads/files/Finance/Adopted%20Budget/City%20of%20Upland%20Adopted%20Annual%20Budget%202019-2020%20(Online-Rev2).pdf) that police expenditures hit 54%. Is this accurate (as opposed to the 51% in your template)? It also looks like page 11 deals with surplus/deficits. 

![image](https://user-images.githubusercontent.com/7321362/84217989-58c50a00-aa82-11ea-9233-c1b925f3bfe3.png)

3. My calculation gives me the same per capita spending number as you: $22,643,118*0.54/78841= $287.19 but this should be $289 (rounded up) if we're using the population in the budget report.

Otherwise, I think we should try to trim this message a bit to make it a faster read for folks sending the emails. I'll make some suggested edits for you. In the meantime, let me know if my fact checking is off.

**Comment by jakesundstrom** [comment]
Hey!

1. Like you noted, the budget cites the Upland population as 78,841 (which is what my template says). I think it makes sense to go with their official figure, but if you think the figure on Google is better, that's obviously fine. 

2. The 54 percent number is correct - that was a typo on my part, thanks for catching that! 

3. Shouldn't that be $288 rounded up? Otherwise I think we're good to go! Obviously make whatever edits for clarity/concision you think make sense! Thanks so much!

**Comment by stephbwills** [comment]
Thanks for clarifying! For the edits, I've included two versions, updated per the [style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md). 

Version 1: This one doesn't mention the revenue generation. It's my recommendation. From the perspective of a resident of a different city, I think it might be getting too specific. Folks who are sending the email can customize with the most meaningful issues to them. For example: housing seems to make up only 10% of the budget.

Version 2: Has the revenue generation bit. Because I don't live in Upland, I don't know which issues are most pervasive. Just lmk if you feel like it should be included.

**Version 1**

To: dstone@ci.upland.ca.us, jelliott@ci.upland.ca.us, zuniga@ci.upland.ca.us, bvelto@ci.upland.ca.us

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Dear Upland City Council,

My name is [YOUR NAME], and I am a resident of Upland. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. This, combined with a global pandemic with severe economic consequences, brings the issue of police budgeting to the forefront.

The 2019-20 Upland budget called for 54% of [its General Fund Expenditure](https://www.uplandca.gov/uploads/files/Finance/Adopted%20Budget/City%20of%20Upland%20Adopted%20Annual%20Budget%202019-2020%20(Online-Rev2).pdf) ($22.6 million of $41.9 million) to go towards the Upland Police Department, an even larger proportion than cities like Oakland (41%) and Houston (32%). Furthermore, the majority of the 460K increase to the maintenance and operations budget belonged to the police, even as communities have become more safe in Upland and nationwide.

I demand the Upland City Council meaningfully defund Upland PD. I join the calls of those across the country demanding a budget that adequately and effectively meets the needs of its citizens during this trying and uncertain time.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]


**Version 2**

To: dstone@ci.upland.ca.us, jelliott@ci.upland.ca.us, zuniga@ci.upland.ca.us, bvelto@ci.upland.ca.us

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Dear Upland City Council,

My name is [YOUR NAME], and I am a resident of Upland. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. This, combined with a global pandemic with severe economic consequences, brings the issue of police budgeting to the forefront.

The 2019-20 Upland budget called for 54% of [its General Fund Expenditure](https://www.uplandca.gov/uploads/files/Finance/Adopted%20Budget/City%20of%20Upland%20Adopted%20Annual%20Budget%202019-2020%20(Online-Rev2).pdf) ($22.6 million of $41.9 million) to go towards the Upland Police Department, an even larger proportion than cities like Oakland (41%) and Houston (32%). Furthermore, the majority of the 460K increase to the maintenance and operations budget belonged to the police, even as communities have become more safe in Upland and nationwide.

If anything, Upland uses its police force as a revenue generator. According to the 2019-20 budget, increases in fines and forfeitures brought in an additional $202K. An increase in fines and forfeitures can come from a number of areas: More residents, more visitors to Upland because of the shops and restaurants, or the understanding that Upland Police will hand out more tickets. 

I demand the Upland City Council meaningfully defund Upland PD. I join the calls of those across the country demanding a budget that adequately and effectively meets the needs of its citizens during this trying and uncertain time.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by jakesundstrom** [comment]
Go with the first version if you think that's better! Thanks for taking the time 🤘

**Comment by stephbwills** [comment]
No problem! All right, first version it is: 

To: dstone@ci.upland.ca.us, jelliott@ci.upland.ca.us, zuniga@ci.upland.ca.us, bvelto@ci.upland.ca.us

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

**Message: (Don't forget to replace the [x]'s with your information!)**

Dear Upland City Council,

My name is [YOUR NAME], and I am a resident of Upland. I am writing to demand that the City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. This, combined with a global pandemic with severe economic consequences, brings the issue of police budgeting to the forefront.

The 2019-20 Upland budget called for 54% of [its General Fund Expenditure](https://www.uplandca.gov/uploads/files/Finance/Adopted%20Budget/City%20of%20Upland%20Adopted%20Annual%20Budget%202019-2020%20(Online-Rev2).pdf) ($22.6 million of $41.9 million) to go towards the Upland Police Department, an even larger proportion than cities like Oakland (41%) and Houston (32%). Furthermore, the majority of the 460K increase to the maintenance and operations budget belonged to the police, even as communities have become safer in Upland and nationwide.

I demand the Upland City Council meaningfully defund Upland PD. I join the calls of those across the country demanding a budget that adequately and effectively meets the needs of its citizens during this trying and uncertain time.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]
