### ISSUE TITLE
Add and Defund La Habra PD please

### ISSUE THREAD

**Issue by isaacaraiza** [defund12/defund12.org#913]
Dear Mayor Tom Beamish and the City Council members,
My name is (Insert Name) and i am a concerned resident of La Habra (change to Orange county or LA county if necessary) . I am emailing in support of the nation wide initiative to defund all police departments across the United States in favor of supporting community based public safety measures; that include but are not limited to fighting homelessness. mental health, domestic abuse, sewual assault, and affordable housing. I have seen my communities' pleas for help and change go ignored for far too long. 
For over a week the Nation has been having protests to call an end to the systematic racism and the criminal justice system that has stoked its fire on this country for far too long. I am writing to demand real change in the La Habra criminal justice system.  The La Habra police department's total budget of 20 million dollars makes up 45.5% of the city budget according to the annual budget posted online in your website. So all the overspending you do on the police can go to other public services that reduce the need for police as a whole. I have started a petition in order to let the policy makers in the city know that we demand to stop overfunding the police we can use that money to better our community while providing basic services to every resident in La Habra as well as ensuring their safety both financially and physically. 
Only once is there a mention of mental health in your budget and it happens to be for a childcare consulate with one payment of 1,000 dollars which is less than 1% of the total budget. The Housing authority which "is responsible for managing the City's two mobile home parks, the low/moderate income housing program... and other affordable and homeless housing needs" (La habra city budget vii) actually had 1.2% decrease in 2019 from 2018 while the police actually received a 2.7% increase "mainly due to an increase in unfunded pension liability costs" (v). So while other services were being decreased, the police continues to get an increase on their annual budget. 
I demand immediate reduction of the police force budget, demilitarization of our forces, and the reallocation of funds from the police department to community-led health and safety strategies. A world without police is 100% possible and this is just the first step. Put your trust in the hands of the community and not some strangers with a gun and a body vest. It is your duty to represent the will of the people and i am urging you immediately revise the La habra, CA operating budget to one that doesn’t put an emphasis on the police but rather puts an emphasis on the betterment of the people.
I have seen this city turn their focus away from their citizens and instead put their focus towards big businesses and the police force, so in order to hold you accountable for the years of injustice and the mishandling of funds we must stand up together in solidarity and let La Habra know that this city will NOT control what we want and we must let city hall know just how powerful this new young base of voters really are. MY voice WILL be heard and the defunding of the police will happen.

Sincerely, 
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by isaacaraiza** [comment]
rferrier@lahabraca.gov
bhurt@lahabraca.gov

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
I've cleaned this up a bit, it still needs some more work and fact checking before approval:

SEND TO: rferrier@lahabraca.gov
bhurt@lahabraca.gov
cc@lahabraca.gov

SUBJECT: [INSERT UNIQUE SUBJECT LINE]

Dear Mayor Tom Beamish and La Habra City Council members,

My name is [YOUR NAME] and I am a concerned resident of La Habra. I am emailing in support of the nation wide initiative to defund all police departments across the United States and redistribute funds to community based public safety measures. These include but are not limited to: alleviating homelessness, mental health, domestic abuse, sexual assault, and affordable housing. I have seen my communities' pleas for help and change go ignored for far too long.

For over a week, protests across the nation have called for an end to systematic racism and the criminal justice system that has stoked its fire on this country for far too long. I am writing to demand real change in the La Habra criminal justice system. The La Habra Police Department's total budget of $20 million makes up 45.5% of the city budget, according to the annual budget [YEAR]. This funding should instead go to other public services that better our community while providing basic services to every resident in La Habra and ensuring their physical and financial safety.

Only once is there a mention of mental health in the [YEAR] La Habra budget, and it happens to be for a childcare consulate with one payment of $1,000. This is less than 1% of the total budget. The Housing Authority, which "is responsible for managing the City's two mobile home parks, the low/moderate income housing program... and other affordable and homeless housing needs" (La Habra City Budget VII), actually had a 1.2% decrease from 2018 to 2019, while the police received a 2.7% increase. So while other services were being decreased, the police continues to get an increase on their annual budget.

I demand immediate reduction of the police department budget, demilitarization of our forces, and the reallocation of funds from the police department to community-led health and safety strategies. Put your trust in the hands of the community. It is your duty to represent the will of the people, and I am urging you immediately revise the La Habra operating budget to one that doesn’t put an emphasis on the police, but rather puts an emphasis on the betterment of the people.

I have seen this city turn their focus away from their citizens and instead put their focus towards big businesses and the police department. In order to hold you accountable for the years of injustice and the mishandling of funds we must stand up together in solidarity and let La Habra know just how powerful this new young base of voters really are. My voice will be heard and the defunding of the police will happen.

Sincerely,
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by isaacaraiza** [comment]
What do i need to fact check? And what needs more work?

**Comment by mahrer** [comment]
The La Habra operating budgets can be found here: 
https://www.lahabracity.com/330/City-Budgets 

Other than that, editing for grammar and style guidelines without straying from the submitter's intention too much

**Comment by isaacaraiza** [comment]
SEND TO: rferrier@lahabraca.gov
bhurt@lahabraca.gov
cc@lahabraca.gov

SUBJECT: [INSERT UNIQUE SUBJECT LINE]

Dear Mayor Tom Beamish and La Habra City Council members,

My name is [YOUR NAME] and I am a concerned resident of La Habra. I am emailing in support of the nation wide initiative to defund all police departments across the United States and redistribute funds to community based public safety measures. These include but are not limited to: alleviating homelessness, mental health, domestic abuse, sexual assault, and affordable housing. I have seen my communities' pleas for help and change go ignored for far too long.

For over a week, protests across the nation have called for an end to systematic racism in the criminal justice system that has stoked its fire on this country for far too long. I am writing to demand real change in the La Habra criminal justice system. The La Habra police department's total budget of $20 million makes up 45.5% of the general city budget, according to the annual budget [YEAR]. This funding should instead go to other public services that better our community while providing basic services to every resident in La Habra and ensuring their physical and financial safety.

The Housing Authority, which "is responsible for managing the City's two mobile home parks, the low/moderate income housing program... and other affordable and homeless housing needs" (La Habra City Budget VII), actually had a 1.2% decrease from 2018 to 2019, while the police received a 2.7% increase. So while other services are being decreased, the police continues to get an increase on their annual budget.
 
Then we have the Police Chief who made $172,738 in 2018 (p 3 of the annual salary) while a public teacher in La Habra makes an average of $64,916 their first year and barely reach $114,000 after 25 years of teaching according to the La Habra City School District Salary website. In what world can you justify having a uniformed officer make twice as much as a public school teacher in this city when that teacher is in charge of shaping every minors lives? 

The budget even states, "Considering that over two-thirds of the City's General Fund budget is dedicated to public safety alone the ongoing increases in public safety costs will potentially impact the City's ability to hire and maintain police officers... the City may have few choices before being forced to consider significant cuts to police, fire, and emergency response systems" (4). So I am only asking you to follow through with those statements and actually cut the funds to police and put those funds towards the benefit of the Community. 

I demand immediate reduction of the police department budget, demilitarization of our forces, and the reallocation of funds from the police department to community-led health and safety strategies. Put your trust in the hands of the community. It is your duty to represent the will of the people, and I am urging you to immediately revise the La Habra operating budget to one that doesn’t put an emphasis on the police, but rather puts an emphasis on the betterment of the people.

I have seen this city turn their focus away from their citizens and instead put their focus towards big businesses and the police department. In order to hold you accountable for the years of injustice and the mishandling of funds we must stand up together in solidarity and let La Habra know just how powerful this new young base of voters really are. My voice will be heard and the defunding of the police will happen.

Sincerely,
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by isaacaraiza** [comment]
I hope this reads better

**Comment by mahrer** [comment]
Looks good to me. Some slight edits here and I'll submit for pr:

SEND TO: rferrier@lahabraca.gov
bhurt@lahabraca.gov
cc@lahabraca.gov

SUBJECT: [INSERT UNIQUE SUBJECT LINE]

Dear Mayor Tom Beamish and La Habra City Council members,

My name is [YOUR NAME] and I am a concerned resident of La Habra. I am emailing in support of the nation wide initiative to defund all police departments across the United States and redistribute funds to community based public safety measures. These include but are not limited to: alleviating homelessness, mental health, domestic abuse, sexual assault, and affordable housing. I have seen my communities' pleas for help and change go ignored for far too long.

For over a week, protests across the nation have called for an end to systematic racism in the criminal justice system that has stoked its fire on this country for far too long. I am writing to demand real change in the La Habra criminal justice system. The La Habra police department's total budget of $20 million makes up 45.5% of the general city budget, according to the annual budget of 2019-2020. This funding should instead go to other public services that better our community while providing basic services to every resident in La Habra and ensuring their physical and financial safety.

The Housing Authority, which "is responsible for managing the City's two mobile home parks, the low/moderate income housing program... and other affordable and homeless housing needs" (La Habra City Budget VII), actually had a 1.2% decrease from 2018 to 2019, while the police received a 2.7% increase. So while other services are being decreased, the police continues to get an increase on their annual budget.

Then we have the Police Chief who made $172,738 in 2018 (p 3 of the annual salary) while a public teacher in La Habra makes an average of $64,916 their first year and barely reach $114,000 after 25 years of teaching according to the La Habra City School District Salary website. In what world can you justify having a uniformed officer make twice as much as a public school teacher in this city, when that teacher is in charge of shaping every minor's life?

The budget even states, "Considering that over two-thirds of the City's General Fund budget is dedicated to public safety alone the ongoing increases in public safety costs will potentially impact the City's ability to hire and maintain police officers... the City may have few choices before being forced to consider significant cuts to police, fire, and emergency response systems" (4). So I am only asking you to follow through with those statements and actually cut the funds to police and put those funds towards the benefit of the community.

I demand immediate reduction of the police department budget, demilitarization of our forces, and the reallocation of funds from the police department to community-led health and safety strategies. Put your trust in the hands of the community. It is your duty to represent the will of the people, and I am urging you to immediately revise the La Habra operating budget to one that doesn’t put an emphasis on the police, but rather puts an emphasis on the betterment of the people.

I have seen this city turn their focus away from their citizens and instead put their focus towards big businesses and the police department. In order to hold you accountable for the years of injustice and the mishandling of funds, we must stand together in solidarity and let La Habra know just how powerful this new young base of voters really are. My voice will be heard and the defunding of the police will happen.

Sincerely,
[YOUR NAME]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rpalakkal** [comment]
on it
