### ISSUE TITLE
Wake County NC page

### ISSUE THREAD

**Issue by jakepoysti** [defund12/defund12.org#928]
Letter to County Board of Commissioners and County Manager
Wake County, North Carolina

To: commissioners@wakegov.com
CC: denise.hogan@wakegov.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Wake County Commissioners,

My name is [NAME] and I am a resident of Wake County. I urge you and the rest of the board to amend or deny the proposed budget for 2021. I would like to redirect money away from Wake Sheriff's Department and into social service programs that will benefit public health and our own communities, especially communities of color. The proposed budget for Fiscal Year 2021 (http://www.wakegov.com/budget/fy21/Documents/Recommended%20Budget%20Book.pdf) suggests cutting ambulances but not law enforcement. Fortunately it does not approve the $8 Million the Sheriff requested for even more officers, but it does little to invest in the community. Over 6,000 of my neighbors in Wake County are currently experiencing homelessness and in which nearly 100,000 of our neighbors in Wake County are impoverished and at risk of becoming homeless (www.raleighrescue.org), these are the issues the board needs to address.

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more law enforcement officers and more detention officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don’t need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Baldwin, will you look out for me, and will you look out for us?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
edits in bold:

-----------------------------------------------

To: commissioners@wakegov.com
CC: denise.hogan@wakegov.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Wake County Commissioners,

My name is [NAME] and I am a resident of Wake County. I urge you and the rest of the board to amend or deny the proposed budget for 2021. I would like to redirect money away from Wake Sheriff's Department and into social service programs that will benefit public health and our own communities, especially communities of color. The proposed budget for Fiscal Year 2021 (http://www.wakegov.com/budget/fy21/Documents/Recommended%20Budget%20Book.pdf) suggests cutting ambulances but not law enforcement. Fortunately it does not approve the $8 Million the Sheriff requested for even more officers, but **that is less than 10% of the proposed total expenditures ($97,103,645) and** it does little to invest in the community. Over 6,000 of my neighbors in Wake County are currently experiencing homelessness and in which nearly 100,000 of our neighbors in Wake County are impoverished and at risk of becoming homeless (www.raleighrescue.org) - these are the issues the board needs to address.

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. **In order to really promote community safety**, more law enforcement officers and more detention officers is not the answer - it is more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

**I believe** we don’t need a militarized police force. **Wake County needs** to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Baldwin, will you look out for me, and will you look out for us?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

-------------------------------------------

I confirmed the statistics provided in the links. I also rephrased some sentences to avoid "we" wording.

@mahrer - please update the label to ready for PR

**Comment by mahrer** [comment]
@wendywx can you edit the "Crime is not random" paragraph to take out the policing language per the style guide?

**Comment by jakepoysti** [comment]
Thank you everyone for helping with this!


-Jake

**Comment by jakepoysti** [comment]
Hi..
there is actually one issue that needs to be fixed: At the end it says
"Mayor Baldwin" but should say "Greg Ford and Commissioners,"

It's my fault - I used the Raleigh letter as a starting point and didn't
update that part.


-Jake

**Comment by mahrer** [comment]
Thanks for raising this issue, I'll make sure it gets fixed
