### ISSUE TITLE
Add Letter for Loudoun County, VA

### ISSUE THREAD

**Issue by CarolineRoden1** [defund12/defund12.org#936]
Emails: 
bos@loudoun.gov
Phyllis.Randall@loudoun.gov
Jeanine.Arnett@loudoun.gov
budget@loudoun.gov
Erin.McLellan@loudoun.gov

Dear Members of the Board of Supervisors and Budget Department,

	My name is [YOUR NAME HERE], and I am a resident of Loudoun County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, an end to racism and anti-Blackness, and immediate improvements in how Black people are treated in America.

	Accordingly, it has come to my attention that the budget for FY 2021 was recently revised, and that city officials will soon begin the FY 2022 budget process. In reading the budget for FY 2021 and the predicted budget for FY 2022, a few things jumped out at me. First, I noticed that the Sheriff’s office is predicted to be allocated a massive $109M, an increase in $4.9M from FY 2019. Along with this, an increase by approximately 70 employees was noted. I would like to note that I believe it would behoove Loudoun county to reallocate massive funds from policing to social services and community betterment, which would in turn lessen the need for police in communities as increased community welfare (and by extent, a decrease in overall poverty) has been correlated with decreased criminal activity (see citations below). 
	I understand, however, that in the short term this is a difficult stance to support. I hope that you and your colleagues will continue to monitor the situation in Minneapolis, as they have decided to officially disband the police as it stands and instead establish a community-based safety program. This program will serve as a pilot for the rest of America, and I hope you will consider taking their guidance in the future. I know that the FY 2021 budget has already been approved, so in the meanwhile, I would urge you and your colleagues to consider taking immediate steps such as providing regulations on the “Internal Support” funds to require that those funds are used to acquire, maintain, and monitor body cameras for all members of the sheriff’s department. Additionally, I would urge you to follow up on legislation and regulations requiring said body cameras to be on at all times in the field, with violations to such policies being a serious offense. 
	I believe a better use of the $109M in police funding would be to reallocate the money towards the Mental Health, Substance Abuse, and Developmental Services branch of Loudoun’s government. As you know, the opiate crisis has been very prevalent in Loudoun county. I believe the most efficient way to fight this crisis is not by aggressive policing of residents, but by increasing funding for addiction services. Many people addicted to opioids in Loudoun are average residents who were overprescribed once and hooked forever. The $55M allocated to this department pales in comparison to the funding given to the police. I would urge you to consider this and other departments more highly when drafting your next budget. I believe that the need for increased policing simply indicates a failure of the community to support its residents adequately, and that to truly improve our community we need to focus on supporting residents, not policing them more. 
	I also believe that it is imperative to address the fact that the board has considered placing SROs in elementary schools, when elementary schools in Loudoun do not have a registered nurse on site. If the SRO truly is for student safety, then it seems as if it would be required to have a registered nurse as well, as far more medical emergencies happen than true police emergencies in schools on a daily basis. I urge you to reallocate funds towards hiring at least one registered nurse per school in Loudoun county. 
	In addition, I feel as though the following propositions for what would act in place of police in certain situations must be addressed. Consider, for example, a person having a mental health crisis. Typically, this person would call 911 and emergency services would be dispatched accordingly. However, we have seen the devastating consequences of this system. In Purcellville in 2017, a high school student in the midst of a mental health crisis was unduly shot multiple times by the first responding officer on scene. The officer was not charged, but the family won a lawsuit in court ruling that the shooting was uncalled for. Instead, imagine if a trained mental health professional were the responder. They would have the training and ability to “talk down” the patient and get them the true mental help they need, instead of responding with violence. Many people attempt to commit “suicide by police”, but if they don’t expect someone to respond with a gun, then they won’t be able to follow through with such an idea. Consider another situation, in which someone is sleeping on a park bench. Instead of police responding and arresting the person, imagine if a city employee responded by checking in on them, finding if they need a place to sleep, food, water, or healthcare. Often times, most of the welfare necessities in an area have been delegated to the police, and the police only know to respond with arrests. Instead, we must take action to give these social responsibilities to properly trained people. For this to be done, we must defund the police and reallocate these funds to social welfare initiatives. 
	As you enter the process of developing the FY 2022 budget, I call on you to create a community review board to provide oversight for police in the county. I call on you to protect your Black community members by reallocating the funds of the police force budget to fund what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (including mental healthcare), jobs with livable wages, community centers, treatment, and community-led organizations.

Sincerely,

[YOUR NAME HERE]
[YOUR ADDRESS HERE]
[YOUR PHONE NUMBER HERE]
[YOUR EMAIL HERE]

Published: “Striking at the Roots of Crime: The Impact of Social Welfare Spending on Crime During the Great Depression” (with Price V. Fishback and Ryan S. Johnson). Journal of Law & Economics Vol. 53, No. 4, pp. 715-740. November 2010.

Foley, C. F. Welfare Payments and Crime. 39.
https://law.yale.edu/sites/default/files/documents/pdf/Intellectual_Life/FoleyCrimeFeb08_(2).pdf

**Comment by CarolineRoden1** [comment]
Wasn't 100% sure how to submit best, but let me know if I should export as a pdf and resubmit! Thanks for doing this

**Comment by mahrer** [comment]
Copying and pasting here for ease of editing:

Emails:
bos@loudoun.gov
Phyllis.Randall@loudoun.gov
Jeanine.Arnett@loudoun.gov
budget@loudoun.gov
Erin.McLellan@loudoun.gov

Dear Members of the Board of Supervisors and Budget Department,

My name is [YOUR NAME HERE], and I am a resident of Loudoun County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, an end to racism and anti-Blackness, and immediate improvements in how Black people are treated in America.

Accordingly, it has come to my attention that the budget for FY 2021 was recently revised, and that city officials will soon begin the FY 2022 budget process. In reading the budget for FY 2021 and the predicted budget for FY 2022, a few things jumped out at me. First, I noticed that the Sheriff’s office is predicted to be allocated a massive $109M, an increase in $4.9M from FY 2019.

Along with this, an increase by approximately 70 employees was noted. I would like to note that I believe it would behoove Loudoun county to reallocate massive funds from policing to social services and community betterment, which would in turn lessen the need for police in communities as increased community welfare (and by extent, a decrease in overall poverty) has been correlated with decreased criminal activity (see citations below). I understand, however, that in the short term this is a difficult stance to support. I hope that you and your colleagues will continue to monitor the situation in Minneapolis, as they have decided to officially disband the police as it stands and instead establish a community-based safety program. This program will serve as a pilot for the rest of America, and I hope you will consider taking their guidance in the future. I know that the FY 2021 budget has already been approved, so in the meanwhile, I would urge you and your colleagues to consider taking immediate steps such as providing regulations on the “Internal Support” funds to require that those funds are used to acquire, maintain, and monitor body cameras for all members of the sheriff’s department. Additionally, I would urge you to follow up on legislation and regulations requiring said body cameras to be on at all times in the field, with violations to such policies being a serious offense. 

I believe a better use of the $109M in police funding would be to reallocate the money towards the Mental Health, Substance Abuse, and Developmental Services branch of Loudoun’s government. As you know, the opiate crisis has been very prevalent in Loudoun county. I believe the most efficient way to fight this crisis is not by aggressive policing of citizens, but by increasing funding for addiction services. Many people addicted to opioids are average citizens who were overprescribed once and hooked forever. The $55M allocated to this department pales in comparison to the funding given to the police. I would urge you to consider this and other departments more highly when drafting your next budget. I believe that the need for increased policing simply indicates a failure of the community to support its citizens adequately, and that to truly improve our community we need to focus on supporting citizens, not policing them more. 
I also believe that it is imperative to address the fact that the board has considered placing SROs in elementary schools, when elementary schools in Loudoun do not have a registered nurse on site. If the SRO truly is for student safety, then it seems as if it would be required to have a registered nurse as well, as far more medical emergencies happen than true police emergencies in schools on a daily basis. I urge you to reallocate funds towards hiring at least one registered nurse per school in Loudoun county. 

In addition, I feel as though the following propositions for what would act in place of police in certain situations must be addressed. Consider, for example, a person having a mental health crisis. Typically, this person would call 911 and emergency services would be dispatched accordingly. However, we have seen the devastating consequences of this system. In Purcellville in 2017, a high school student in the midst of a mental health crisis was unduly shot multiple times by the first responding officer on scene. The officer was not charged, but the family won a lawsuit in court ruling that the shooting was uncalled for. Instead, imagine if a trained mental health professional were the responder. They would have the training and ability to “talk down” the patient and get them the true mental help they need, instead of responding with violence. Many people attempt to commit “suicide by police”, but if they don’t expect someone to respond with a gun, then they won’t be able to follow through with such an idea. Consider another situation, in which someone is sleeping on a park bench. Instead of police responding and arresting the person, imagine if a city employee responded by checking in on them, finding if they need a place to sleep, food, water, or healthcare. Often times, most of the welfare necessities in an area have been delegated to the police, and the police only know to respond with arrests. Instead, we must take action to give these social responsibilities to properly trained people. For this to be done, we must defund the police and reallocate these funds to social welfare initiatives. 

As you enter the process of developing the FY 2022 budget, I call on you to create a community review board to provide oversight for police in the county. I call on you to protect your Black community members by reallocating the funds of the police force budget to fund what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (including mental healthcare), jobs with livable wages, community centers, treatment, and community-led organizations.

Sincerely,

[YOUR NAME HERE]
[YOUR ADDRESS HERE]
[YOUR EMAIL HERE]

Published: “Striking at the Roots of Crime: The Impact of Social Welfare Spending on Crime During the Great Depression” (with Price V. Fishback and Ryan S. Johnson). Journal of Law & Economics Vol. 53, No. 4, pp. 715-740. November 2010.

Foley, C. F. Welfare Payments and Crime. 39.
https://law.yale.edu/sites/default/files/documents/pdf/Intellectual_Life/FoleyCrimeFeb08_(2).pdf
