### ISSUE TITLE
Letter to Omaha's City Council and Mayor 

### ISSUE THREAD

**Issue by sophiagustafson** [defund12/defund12.org#938]
SEND TO: 
Pete.Festersen@cityofomaha.org, Ben.Gray@cityofomaha.org, Chris.Jerram@cityofomaha.org, Vinny.Palermo@cityofomaha.org, Rich.Pahls@cityofomaha.org, Brinker.Harding@cityofomaha.org, Aimee.Melton@cityofomaha.org, carrie.murphy@cityofomaha.org, hotline@cityofomaha.org, 

[UNIQUE SUBJECT LINE] 

Dear Mayor Jean Stothert and Members of City Council, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. First, I demand justice for James Scurlock who was killed by Jake Gardner on June 30th, 2020. Jake Gardner has been released from police custody and has not been charged and this case must become officially reopened. Second, I write this letter to urge you to begin defunding and demilitarizing the ¬¬¬¬¬Omaha Police Department. 

The 2020 budget for OPD is outrageously high and unwarranted. Omaha’s general budget for 2020 was $419.6 million and the OPD currently takes up nearly 40% of that budget or $159.5 million. Since 2016, the OPD’s budget has increased 22% but the city’s clearance rates still remain relatively stagnant. 

In 2019, OPD’s portion of the budget was at 38% while Public Works, Parks, and Libraries made up just 5.7%, 5.5%, and 3.3% of the budget respectively. The underfunding schools, infrastructure, parks, and libraries is causing much of Omaha’s suffering. The aforementioned underfunding of public services paired with the overfunding the police shows me as your constituent that you are merely putting Band-Aids over bullet holes. 

As Omaha residents, we therefore demand that you take immediate action to ensure the following:

1. Reduce Omaha’s allocation from the General Fund by 50% (roughly $80 million)
2. Disallow unauthorized overtime by OPD
3. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
4. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
5. Invest in community development initiatives and programs.
6. An official charge against Jake Gardner. 

Omaha cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund OPD. 

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by sophiagustafson** [comment]
All sources came from the City of Omaha Finance Department.

**Comment by todd-m** [comment]
Thanks @sophiagustafson -- and appreciate the sources! Looks good, just made a few edits below.

SEND TO:
Pete.Festersen@cityofomaha.org, Ben.Gray@cityofomaha.org, Chris.Jerram@cityofomaha.org, Vinny.Palermo@cityofomaha.org, Rich.Pahls@cityofomaha.org, Brinker.Harding@cityofomaha.org, Aimee.Melton@cityofomaha.org, carrie.murphy@cityofomaha.org, hotline@cityofomaha.org,

[UNIQUE SUBJECT LINE]

Dear Mayor Jean Stothert and Members of City Council,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. First, I demand justice for James Scurlock who was killed by Jake Gardner on May 30th, 2020. Jake Gardner has been released from police custody and has not been charged. This case must be officially reopened. Second, I urge you to begin defunding and demilitarizing the Omaha Police Department.

The 2020 budget for OPD is outrageously high and unwarranted. Omaha’s general budget for 2020 was $419.6 million and the OPD currently takes up nearly 40% of that budget, or $159.5 million. Since 2016, the OPD’s budget has increased 22% but the city’s clearance rates still remain relatively stagnant.

In 2019, OPD’s portion of the budget was at 38% while Public Works, Parks, and Libraries made up just 5.7%, 5.5%, and 3.3% of the budget respectively. The underfunding of schools, infrastructure, parks, and libraries is causing much of Omaha’s suffering. The aforementioned underfunding of public services paired with the overfunding the police shows me as your constituent that you are merely putting Band-Aids over bullet holes.

As Omaha residents, I therefore demand that you take immediate action to do the following:

* Reduce Omaha’s allocation from the General Fund by 50% (roughly $80 million)
* Disallow unauthorized overtime by OPD
* Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
* Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe
* Invest in community development initiatives and programs
* Officially charge Jake Gardner

Omaha cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund OPD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Ceshion** [comment]
I'm on it!
