### ISSUE TITLE
Please add El Cerrito, CA

### ISSUE THREAD

**Issue by nmobaid** [defund12/defund12.org#951]
To:
glyman@ci.el-cerrito.ca.us, pfadelli@ci.el-cerrito.ca.us, jabelson@ci.el-cerrito.ca.us, gquinto@ci.el-cerrito.ca.us, rpardueokimoto@ci.el-cerrito.ca.us 

Subject: [***INSERT UNIQUE SUBJECT LINE***]

Message (Don’t forget to replace the [x]’s with your information!)

Dear Mayor Lyman, Mayor Pro Tem Fadelli, and El Cerrito Council Members:

My name is [NAME HERE] and I am an El Cerrito resident from [YOUR DISTRICT].

ECPD uses a huge share of our city’s total expenditures, taking away greatly needed resources from essential city services. 24% of the fiscal year 2019-’20 budget goes to police, while only 5% goes toward Community Development. That’s $12.5 million being used at the expense of vital public services like housing and healthcare.

The investment in policing has not made us safer - rather, it poses a lethal threat to Black and Brown communities, as well as those who are unhoused and suffering from mental illness. As shown in this Washington Post story from June 7, there is no correlation between police spending and community safety.

Furthermore, as you know, El Cerrito faces a $4 million deficit in fiscal year 2020-’21. With the city’s finances in dire jeopardy, it is clear that now is the time to defund the police.

As an El Cerrito resident, I demand that you take immediate action to ensure the following:
Reduce ECPD’s allocation from the general fund by 50%.
Enact a democratically-elected civilian police accountability council to oversee the ECPD.
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to improve community safety.

El Cerrito cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the ECPD.

Respectfully,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE #]

**Comment by swallan** [comment]
Dear Mayor Lyman, Mayor Pro Tem Fadelli, and El Cerrito Council Members:

My name is [NAME HERE] and I am an El Cerrito resident from [YOUR DISTRICT].

ECPD uses a huge share of our city’s total expenditures, taking away greatly needed resources from essential city services. 24% of the fiscal year 2019-’20 budget goes to police, while only 5% goes toward Community Development. That’s $12.5 million being used at the expense of vital public services like housing and healthcare.

The investment in policing has not made us safer - rather, it poses a lethal threat to Black and Brown communities, as well as those who are unhoused and suffering from mental illness. As shown in several reports, there is no correlation between police spending and community safety.

Furthermore, as you know, El Cerrito faces a $4 million deficit in fiscal year 2020-’21. With the city’s finances in dire jeopardy, it is clear that now is the time to defund the police.

As an El Cerrito resident, I demand that you take immediate action to ensure the following:
Reduce ECPD’s allocation from the general fund by 50%.
Enact a democratically-elected civilian police accountability council to oversee the ECPD.
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to improve community safety.

El Cerrito cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the ECPD.

Respectfully,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE #]

**Comment by nmobaid** [comment]
Thanks for the edits! What is the next step?

**Comment by swallan** [comment]
@nmasharani It is marked ready for pr, so it is now in the queue to have its file created and then merged

**Comment by nmobaid** [comment]
great, thank you

**Comment by todd-m** [comment]
on it
