### ISSUE TITLE
Letter to Anchorage Alaska's City Council 

### ISSUE THREAD

**Issue by sophiagustafson** [defund12/defund12.org#963]
SEND TO: Christopher.Constant@AnchorageAK.gov, Crystal.Kennedy@AnchorageAK.gov, Jamie.Allard@AnchorageAK.gov, Austin.Quinn-Davidson@AnchorageAK.gov, Kameron.Perez-Verdia@AnchorageAK.gov, Felix.Rivera@AnchorageAK.gov,  Meg.Zaletel@AnchorageAK.gov,  Forrest.Dunbar@AnchorageAK.gov,  Pete.Petersen@AnchorageAK.gov, Suzanne.LaFrance@AnchorageAK.gov, John.Weddleton@AnchorageAK.gov 

[UNIQUE SUBJECT LINE] 

Dear Members of City Council, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. I write this letter to urge you to begin defunding and demilitarizing the ¬¬¬¬¬Anchorage Police Department. The budget approved for 2020 prioritizes policing at the expense of other, vital departments. APD 22.4% of the budget, outranking all other expenditures and costing the city $121,039. Other vital industries like parks and recreation (3.8%), health (2.4%), development services (2.2%), and libraries (1.7%) take up less than half of the police budget when **_combined_**. (Source: 2020 Approved General Government Operating Budget.) Right now, there is a clear disjunction between what the people of Anchorage want and where our tax dollars are going.

As Anchorage residents, we therefore demand that you take immediate action to ensure the following:

1. Reduce Anchorage’s allocation from the General Fund by 50% (roughly $60 million)
2. Disallow unauthorized overtime by ¬APD
3. Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
4. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
5. Invest in community development initiatives and programs.

Anchorage cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund APD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by NickCrews** [comment]
I'm on it as an AK local! I'll make a PR.

**Comment by NickCrews** [comment]
PR #1009 ready to be reviewed and submitted. Thanks a ton neighbor @sophiagustafson! I live in Girdwood :)

**Comment by NickCrews** [comment]
Whoops, I messed the process up, forgot about the review stage. Below is the slightly edited letter. Upon approval I can do a new PR. The changes I made were
- fix typo of $121 million
- remove weird `¬` characters
- use "I" instead of "we"
- added some periods to the list

SEND TO: Christopher.Constant@AnchorageAK.gov, Crystal.Kennedy@AnchorageAK.gov, Jamie.Allard@AnchorageAK.gov, Austin.Quinn-Davidson@AnchorageAK.gov, Kameron.Perez-Verdia@AnchorageAK.gov, Felix.Rivera@AnchorageAK.gov, Meg.Zaletel@AnchorageAK.gov, Forrest.Dunbar@AnchorageAK.gov, Pete.Petersen@AnchorageAK.gov, Suzanne.LaFrance@AnchorageAK.gov, John.Weddleton@AnchorageAK.gov

[UNIQUE SUBJECT LINE]

Dear Members of City Council,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. I write this letter to urge you to defund and demilitarize the Anchorage Police Department. The budget approved for 2020 prioritizes policing at the expense of other, vital departments. APD uses 22.4% of the budget, outranking all other expenditures and costing the city $121 million. Other vital industries like parks and recreation (3.8%), health (2.4%), development services (2.2%), and libraries (1.7%) take up less than half of the police budget when combined. (Source: 2020 Approved General Government Operating Budget.) Right now, there is a clear disjunction between what the people of Anchorage want and where our tax dollars are going.

As an Anchorage resident, I therefore demand that you take immediate action to ensure the following:

- Reduce Anchorage’s allocation from the General Fund by 50% (roughly $60 million).
- Disallow unauthorized overtime by APD.
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
- Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
- Invest in community development initiatives and programs.

Anchorage cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund APD.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
